### ISSUE TITLE
dnSpy compile issue...

### ISSUE THREAD

**Issue by XPownage** [SubnauticaNitrox/Nitrox#100]
Every time I try editing Assembly-CSharp and I compile what I add it doesn't save.

**Comment by Alberto247** [comment]
Save the compiled assembly from the menu, closing the editor is not enough to save it to disk.

**Comment by XPownage** [comment]
The only way it even allows me to edit the code is to right click on the file "Assembly-Charp" and click on Edit Assembly Attributes. After I do that and compile it and nothing changes on the file what so ever.

**Comment by Measurity** [comment]
Closing dnSpy should prompt you to save your changes. If it doesn't then you didn't make any changes.

**Comment by XPownage** [comment]
Yup I fixed it thanks guys.
