### ISSUE TITLE
Interesting Issue with "taking over simulating"?

### ISSUE THREAD

**Issue by Cudler** [SubnauticaNitrox/Nitrox#1001]
So I was playing with a friend when this error came up. [https://i.imgur.com/7TpKbkG.png](url) The picture here shows what happened before and highlighted is the error. 

My friend got disconnected. We are using hamachi.

**Comment by NekoDm** [comment]
I have did Issues too, it only dicoved when some other joining first

**Comment by Sunrunner37** [comment]
Info and debug messages can be ignored.  Taking over simulation is a normal part of play.

**Comment by Pangi790927** [comment]
Me and my friend also get desynced while driving and I see that error a lot.: "Player X has taken over simulating".
