### ISSUE TITLE
base deformation after leaving server

### ISSUE THREAD

**Issue by dikho11** [SubnauticaNitrox/Nitrox#1010]
so I and my friend finally got the mod to work and we were very impressed by the mod and were playing for a few hours now, my friend had some issues like not loading textures so he left and rejoined it seemed to be okay but then while i was building our base he saw it deformed and i still saw it normally when i tried restarting the server and joining back i saw it too. any idea on how to resolve this problem?

**Comment by Sunrunner37** [comment]
Tracked in https://github.com/SubnauticaNitrox/Nitrox/issues/951
