### ISSUE TITLE
few questions about the server program:

### ISSUE THREAD

**Issue by Aaronstar-McClure** [SubnauticaNitrox/Nitrox#102]
1. I have everything setup client side, but on the server there are multiple Nitroxserver.exe, should I run the one in NitroxServer\bin\Debug, or NitroxServer\obj\Debug
2. once the server is running, what is the proper command to shut it down gracefully? or should I just close the program?
3. where is the server's copy of the world saved? or does it not keep a copy after closing.

**Comment by Aaronstar-McClure** [comment]
also, while i can connect to the server i am running, someone else cannot...

**Comment by Measuring** [comment]
Did you port forward 11000 TCP? That's the default port the server runs on.

**Comment by Aaronstar-McClure** [comment]
o, nice to know...

**Comment by Aaronstar-McClure** [comment]
ok, he was connected for a while, the server knew he picked up a fire extinguisher, but we could not see each other... then he randomly got disconnected...

**Comment by Measuring** [comment]
Without knowing the errors you get it's hard for me to provide feedback. Could you upload the Steam\steamapps\common\Subnautica\Subnautica_Data\output_log.txt file? Preferably also from your co-op partner.

**Comment by Aaronstar-McClure** [comment]
https://hastebin.com/ofenaqegit.js (partner)
mine is too big, one moment...

**Comment by Aaronstar-McClure** [comment]
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/1679541/output_log.txt)

**Comment by Aaronstar-McClure** [comment]
also, which copy of the server should i be running?

**Comment by Measuring** [comment]
The .exes in bin/* folders are the ones you should run (at least, that's convention). That's either bin/Debug or bin/Release depending on how you built the files with Visual Studio. I'm checking the output logs now.. a sec.

**Comment by Aaronstar-McClure** [comment]
i also noticed, if i use the day command or explode ship, it does not effect him

**Comment by eldarne** [comment]
Hey there, if I may, I was reading this issue, because like Aaronstar-McClure, I've got everything set up on the client side, but I got some troubles with the server.exe.

I was also wondering which .exe i should use, but you got that covered minutes ago.

My problem now is when I run the server, the console give me this : input string was not in a correct format.

Any idea on what could cause that ?

Sorry to intefere like that, but as the issues is about server problems, I thought I could post here. Tell me if it's any trouble, I'll open a new issue.

**Comment by MarijnS95** [comment]
@eldarne See https://github.com/SubnauticaNitrox/Nitrox/issues/98 and https://github.com/SubnauticaNitrox/Nitrox/issues/84 . It's a known issue and simple to fix, though no-one has (had the the time to) file(d) a pull request with the fix yet.

**Comment by eldarne** [comment]
Thank you very much. I'm checking it right now. 

Actually I felt a bit dumb because I found the issues a minute after posting. I should have checked better before.

Happy to see that this project is very alive =)

**Comment by Aaronstar-McClure** [comment]
if there is some sort of server log i could try to get that for you...

**Comment by Measuring** [comment]
@Aaronstar-McClure Not everything is synchronized yet so it's to be expected. This mod is in development. I've checked the logs and there are some errors popping up like:

    [Nitrox] D: Found deferred packet... adding it back with high priority.
    No filename for prefab 8fd0ce6c-9f88-4d4d-867a-4beab0728000 in database containing 3316 entries
 
    (Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

    Error: Failed to load prefab (CreateEmptyObject=False, IsActive=True, Layer=0, Tag=Untagged, Id=f5e9b51c-60b5-46e5-84c6-a16fdddf0ba3, ClassId=8fd0ce6c-9f88-4d4d-867a-4beab0728000, Parent=aa8f6171-53c8-4363-8ad3-ef0027578e90, OverridePrefab=True, MergeObject=False)

    UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    UnityEngine.Logger:LogException(Exception, Object)
    UnityEngine.Debug:LogException(Exception, Object)
    UWE.Utils:LogReport(String, Object)
    UWE.Utils:LogReportFormat(Object, String, Object[])
    <InstantiatePrefabAsync>c__Iterator4:MoveNext()
    CoroutineTask`1:MoveNext()
    SystemExtensions:SafeMoveNext(IEnumerator)
    SystemExtensions:SafeMoveNext(IEnumerator, String)
    UWE.PumpCoroutineStateMachine:MoveNext()
    PooledStateMachine`1:MoveNext()
    <Start>c__Iterator2:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Looks like ownership of certain items aren't properly handled yet which might cause the server to hang on this error and kick your friend out. Don't think there's something you can do this fix this and we'll have to patch it.

**Comment by Aaronstar-McClure** [comment]
well, even when we are both connected, we still dont see each other...

**Comment by Measuring** [comment]
That's very odd because we have an internal ClientTester and with that I do see another player model pop up (though I admit, it sometimes doesn't seem to spawn). I'm sorry that I cannot provide an intimidate solution. All I can say is this mod is still in the works.

**Comment by hsiayuchih** [comment]
@Measuring Hello, trouble to tell you how much progress in the completion of MOD development yet? May be formally launched in months?

**Comment by CarbonNeuron** [comment]
Anyone have answers on 2-3

**Comment by Sunrunner37** [comment]
2) Just close the server for now.
3) Server persistence is not yet implemented.

**Comment by GuzioMG** [comment]
Wa... Wai... wait...... WHaaaaaaaAATt????

> Server persistence is not yet implemented.

So does it mean, efter closing server, I'll lost our PDAs data (inventory, screenshots, databank, etx.), bases, vechicles, world, EVERYTHING?! SO DOES IT MEAN I MUST ALWAYS KEEP MY COMPUTER ON TO KEEP EVERYTHING (on mysubnautica world) ALIVE?!?!?!?!?

noooooooooooooooooooooooooooooooooooooooooooooooo

Ps. Thanks to @MarijnS95 with my issue. The same day, I posted

> Oh, yes, I didn't saw that :-).

comment, parcel with my new computer finally came, so I didn't checked, is everything working, but thanks.

**Comment by whenofficial** [comment]
> Server persistence is not _yet_ implemented.
Not yet.

**Comment by GuzioMG** [comment]
Well, I hope it'll be implemented soon...

**Comment by Ivick5124** [comment]
My Friend cant join my server I port forwarded it and everything but when he tries to join it just says multiplayer client loaded then fades away can you help me with that?
