### ISSUE TITLE
Abandoned Bases not Appearing

### ISSUE THREAD

**Issue by trizmorrow** [SubnauticaNitrox/Nitrox#1021]
Abandoned Bases are not appearing, on islands.

**Comment by Mrcurlywurly** [comment]
I have the same issue, the middle base doesnt spawn in. I have tried this on my computer and my friends.

**Comment by Mrcurlywurly** [comment]
> 
> 
> Abandoned Bases are not appearing, on islands.

OK I found the fix.

 Use 'Warpme' to go back to your starting base and then use command 'goto base1'

Hopefully this works for you!

**Comment by tomi1206** [comment]
i'll try and leave a post to say if it worked

**Comment by tomi1206** [comment]
OK, it worked for the flotting-island base. But for the mushroom-cave base (goto base2) it's not working, the base still invisible.

**Comment by tomi1206** [comment]
erratum : after a shut down and launching again the server, when i make the command "goto base2", the base appeared.
Let's see for the degasi see base at 500 meters in the grand reef.

**Comment by Coding-Hen** [comment]
@tomi1206 @trizmorrow Can you please verify this issue with the latest version

**Comment by dartasen** [comment]
This is an old issue, no update on it and unable to reproduce those bugs with the current version, I'm closing it for now.
