### ISSUE TITLE
Ion cube issue

### ISSUE THREAD

**Issue by KuragariGin** [SubnauticaNitrox/Nitrox#1025]
Both myself and a friend were unable to find ion cubes at their normal spots, for some reason I can't unlock the alien portals but my friend can.

**Comment by EugeneScully** [comment]
This also happens for me on Alpha 1.3.0.0_RC2

I have never found an ion cube, although I see their stands activate

**Comment by SliceThePi** [comment]
I tried going into freecam; it looks like the cubes spawn but are not raised up with their pedestals when the player approaches.

**Comment by Exso12Ecesis** [comment]
I can not confirm this behavior. I tried on Alpha 1.4.0.0, both clients saw the Alien pedestal behave correctly. Although both could mine it, which is a separate issue already being handled in another ticket. Both clients were able to see random Ion cubes in the world, too.

**Comment by EnchantedBread** [comment]
me and my friend also can't see any ion cubes

**Comment by dartasen** [comment]
Moved to #1463
