### ISSUE TITLE
World Syncing

### ISSUE THREAD

**Issue by SeeFights** [SubnauticaNitrox/Nitrox#1028]
I have the game installed on Epic

My friend has it on steam 

Our locations are: England and Netherlands

We have noticed that after a long play time the server becomes unstable and sync issues arrise, one we found today was that on his screen a ladder was there and on mine there wasnt and another was that there was a multi-room still there and for me it wasnt.

I placed out locations for people to see if someone with a bigger knowlesge could explain , i know this mod is in beta but hey I'm happy to help with bug reports in anyway :)

**Comment by Measurity** [comment]
Thanks for the bug report. Since this is related to base sync issues I'm gonna close this and refer to  #951

If you have a unqiue and detailed bug report about an issue that's not related to base syncing then we're happy keep it.
