### ISSUE TITLE
world got reset but have the old world files

### ISSUE THREAD

**Issue by mvinandarsa** [SubnauticaNitrox/Nitrox#1036]
I played the game normally 2 days ago and when I tried to play again today, somehow it's starting a new world. And because it overwrites the world file, I tried to recover it back to the previous version but no luck, it always overwriting the world files with the new world. Any hope to load the old world files?

**Comment by EcorceToaster** [comment]
Same problem

**Comment by mvinandarsa** [comment]
> Same problem

I just gave up lol, tried everything I could but no luck

**Comment by Jannify** [comment]
Will look into it. See https://github.com/SubnauticaNitrox/Nitrox/issues/1104 for future information. But loading an old (version of nitrox) save will most likely not be supported in the future with the current system. I am working on a new system for experienced users (https://github.com/SubnauticaNitrox/Nitrox/pull/1075) which should be upgradable to new Nitrox versions. However old save files are excluded from this system, sorry for that.
