### ISSUE TITLE
We Need a Road Map and a List of Current Priorities

### ISSUE THREAD

**Issue by MadMaxOfYore** [SubnauticaNitrox/Nitrox#104]
Hey - mind adding me to Trello now that I'm officially a contributor? I'd be happy to keep my status updated there.

**Comment by MarijnS95** [comment]
Hey!

I was about to respond to your comment in Discord: I've been pushing to use github projects which is basically Trello++:

- Tightly integrated with GitHub: we can organise our issues and pullrequests there
- Automation of cards
- Does not require a separate account

**Comment by MadMaxOfYore** [comment]
I'm actually at work so can't get to Discord =)

I'm fine with either solution personally. I would just like to be able to see where we are at as well as get an idea for what our current priorities are. There are a million things that I could jump in to address but it is hard to make the call on which to tackle without know what our road map looks like.

Do we have any plans to make a decision one way or another?

**Comment by MarijnS95** [comment]
Most of the contributers agreed to migrate, but they are still all updating things on Trello 🤷‍♂️ .

**Comment by MadMaxOfYore** [comment]
I'm going to keep this issue open to prod the group into making a commitment one way or the other. I am willing to start working in either space and would even be happy to help get everything up to date in whichever platform we roll with.

Just need a final decision and the required information =)

**Comment by MadMaxOfYore** [comment]
Great work!
