### ISSUE TITLE
Few bugs with 568cc0c9 version

### ISSUE THREAD

**Issue by kornfleks** [SubnauticaNitrox/Nitrox#1041]
I have cloned and compiled the latest version available: [commit 568cc0c9](https://github.com/SubnauticaNitrox/Nitrox/commit/568cc0c995152369867c03614f27aabf72abc9db)

Everything was working great until I started building a hatch on our base (we were 2 players) far away from my friend.

- He was not seing the hatch. The only way for him to see (have) the hatch was that I built it in front of him.
- The second bug was that we were not abled to use a fabricator built from the other player (state: unpowered)

Thanks for the mod, it is really fun. I hope you will be able to fix all the issues that make the game unfinishable (or hard to finish) in multiplayer. It still a great work and really easy to compile.

**Comment by Measurity** [comment]
Base issues are tracked here: #951
