### ISSUE TITLE
compile error CS1061 and CS1503

### ISSUE THREAD

**Issue by tsilipe** [SubnauticaNitrox/Nitrox#105]
Hello, i have build the project and i have this errors.

Error	CS1503	Argument 1: cannot convert from 'void' to 'Harmony.PatchProcessor'	NitroxPatcher	E:\Donwload\Nitrox-master\Nitrox-master\NitroxPatcher\Patches\NitroxPatch.cs	Line 50	

Error	CS1061	'PatchProcessor' does not contain a definition for 'Restore' and no extension method 'Restore' accepting a first argument of type 'PatchProcessor' could be found (are you missing a using directive or an assembly reference?)	NitroxPatcher	E:\Donwload\Nitrox-master\Nitrox-master\NitroxPatcher\Patches\NitroxPatch.cs	Line 58

and

Error	CS1503	Argument 1: cannot convert from 'NitroxModel.DataStructures.Util.Optional<string>' to 'string'	NitroxServer	E:\Donwload\Nitrox-master\Nitrox-master\NitroxServer\Serialization\BatchCellsParser.cs	Line 83

thanks

**Comment by MarijnS95** [comment]
I assume you've manually downloaded and installed the Harmony dependency. We use a modified version, for which you have to init the `submodule` as described in the wiki, and compile the mod with that.
