### ISSUE TITLE
hello. guys i have an issue when i click on play multiplayer this happens

### ISSUE THREAD

**Issue by mskstanmay** [SubnauticaNitrox/Nitrox#1050]
![image](https://user-images.githubusercontent.com/64010302/79825156-ddb27200-83b5-11ea-869a-f6e88e423855.png)

**Comment by mskstanmay** [comment]
can somebody tell me what the issue is ?

**Comment by Measurity** [comment]
Your installation is broken. Reinstall Nitrox by:

1. Removing its files from the game. 
2. Reverify the integrity of the game's files
3. Install Nitrox.

Go to our discord for support so that we can keep GitHub issues on bugs.
