### ISSUE TITLE
Radio not giving any message

### ISSUE THREAD

**Issue by somakiller** [SubnauticaNitrox/Nitrox#1057]
Hello 
I recently started playing this mod with a friend. 
The radio sometimes bleep and we can click on it to have a message but it doesn't appear. 
We sometimes hear the survivor capsules and we have their locations but if the message isn't displayed, we doesn't get any location points.
We can't get the sunbeam to contact us either.

**Comment by filipemartinho** [comment]
same happens to me

**Comment by dartasen** [comment]
Fixed in #1225
