### ISSUE TITLE
Patch 1.2.1.0 - Bugs of items and in building a base

### ISSUE THREAD

**Issue by lucasnog186** [SubnauticaNitrox/Nitrox#1058]
The purple tablets could not be taken by more than one player. Also, the doors that they open were only open to the player that has the purple tablet.
Another issue was in building a base. Some parts of the base that I built was not 100% done for other players. The fabricator that I built could only work for me. 
For me, this mod gives an amazing perspective of playing the game with friends, but these bugs really discourage playing with friends.

**Comment by Measurity** [comment]
Know issues. Story events aren't synced yet and is a work in progress. See: #1032
