### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Skyterix1991** [SubnauticaNitrox/Nitrox#106]
`Error	CS1503	Argument 1: cannot convert from 'NitroxModel.DataStructures.Util.Optional<string>' to 'string'	NitroxServer	C:\Users\Skyte\Desktop\Nitrox\NitroxServer\Serialization\BatchCellsParser.cs	83`

**Comment by Redbyte1** [comment]
Line 83 should be

>string path = Path.Combine(SteamFinder.FindSteamGamePath(264710, "Subnautica").ToString(), "SNUnmanagedData/Build18") + "/";

**Comment by Sunrunner37** [comment]
Issue was fixed with latest commit.
