### ISSUE TITLE
Enable Nitrox to run without copying DLLs over to Subnautica

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#1061]
**Option 1: Virtual File System (VFS)**
Something like what mod organizer 2 does for skyrim could be useful https://wiki.step-project.com/Guide:Mod_Organizer_Advanced
It tells a process, during runtime, how it should access files (where they are and what they look like) without modifying the installation of the game itself.
So it's fast even with many files because no copying :weSmart: 

**Option 2: Assembly resolve event that resolves DLL references dynamically**
https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyresolve?view=netframework-4.8
There's that assembly resolve event with appdomains though I don't know how well Unity works with that. This might require a new "bootloader" dll that loads Nitrox Patcher and all other dlls required to run Nitrox, dynamically. Then the launcher has to inject a call to this new dll instead.

**Comment by Jannify** [comment]
https://github.com/SubnauticaNitrox/Nitrox/pull/1098
