### ISSUE TITLE
Seamoth explodes instantly after docking to Cyclops

### ISSUE THREAD

**Issue by LifetimeMistake** [SubnauticaNitrox/Nitrox#1062]
After exploding, the upgrade console inside the Cyclops still says that the Seamoth is docked (until rejoining the game. After doing that it just says "no vehicle docked" and the Seamoth fragments disappear from the docking bay.).

This happens on Alpha 1.2.0.1 and on the newest build as well (commit 728a405)
I tried looking into the issue but couldn't pin point the problem. Here are the client logs and server logs, hopefully this helps.

[server_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/4530744/server_log.txt)
[client_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/4530745/client_log.txt)
[world.zip](https://github.com/SubnauticaNitrox/Nitrox/files/4530762/world.zip)

**Comment by LifetimeMistake** [comment]
This does not happen when I'm alone on the server. Could this be caused by my friend's internet connection or something? I'm the server host by the way.

**Comment by EugeneScully** [comment]
This happens for me on Alpha 1.3.0.0_RC2 when there are two players

Single player is fine. I don't think that its the connection, because we're on a local LAN

**Comment by dartasen** [comment]
Duplicate #1223 , we're working on it
