### ISSUE TITLE
Syncing problem, documentation request

### ISSUE THREAD

**Issue by Suhdaj** [SubnauticaNitrox/Nitrox#1078]
I've done some extensive tests on april build version of nitrox and i've stumbled across several bugs and problems.

Firstly, the main issue i had is radio msg's, and story nav points are not stored on server side. They are somewhere in the client, but every reconnect, forces you to sync with server, and that makes you completely lost every story nav point (the messages are still in PDA tho). Server on every restart, starts timers of events from point zero. Every audiolog has to come again, and beacuse you cannot get the  audiologs you've got earlier, the radio bugs out (hence some problems on the issue board, that when you recieve radio message, nothing happens [my solution to this is to force already obtained msgs by building and rebuilding the radio, consequentionaly clicking it to the point where the light stops blinking]).

The problem with fabricators, and any other interactable object in the base is beacuse forced syncing. Don't get me wrong, that forced sync repaired bugged base building, but beacuse server has problems with storing energy values, everything bugs out. 

Every client has different value of energy. Thats why the only generator that works semi-properly is thermal reactor. Its power is based purely by place, that it is put on. Works the same as solar panels. Bioreactors, and nuclear reactors are bugging the game to the point of breaking. That happens beacuse the server cannot resolve the problem of energy. You see, solar panels and thermal reactors will work forever, they dont need any fuel, hence there is no reason for the game to calculate for how long they will work. Any other generator has a problem now. Beacuse server is not storing any structure that can calculate on its own the energy values, its starting to desyncing. Every generator built, takes place on server, but it will work only for the client, that put this generator in place. And only for a short period of time, to the point of reconnecting. Thus it's state starts to bug out completely, duplicating resources, creating ghost objects etc.

Same thing with energy of seaglide, seamoth, prawn. Every client reconnect, makes values of HP, and energy taken to the 100%. Thats a huge problem. I think most of the problems that are braking the game expierience is purely based on desync, and server not storing enough data. 

resources are not syncing too. That being said, you cant get to alien facility with somebody, beacuse server does not sync interactions with force fields. Portals (dont) work like this too. 

Ion Cubes are not spawning in the world. I dunno why, and if it is aplicable to every alien base, but the quarantine one does not have any of the cubes.

One of the reasons why Cyclops is desyncing is beacuse the fishes are not synced. One stupid stalker pushes your cyclop by inch, and server desynchronizes entire object. The most stupid thing about it is that every client that gets into the cyclops, he is in this entity. No matter where it is. That creates strange glitches, when you get out from cyclops, your character stretches out to the point where exit from cyclops is, on that one particular client. Every object that has been put on cyclops WORKS. Fabricators, and every other interactable thing. But if you want to put something, on desynced cyclops, those things appear only in cyclops of that one client. On every other client it appears in a place, where that desynced cyclop is, which means floating fabricators in water. (jesus its hard to explain)

oof. That was a really carefull deduction on how it works in my opinion. That being said i would love to work on that, but i am not familiar with that form of programming (with unity framework, mainly) can i ask for some in-depth code documentation?? That would helped a lot, and i think every next person that could contribute to this mod, will have more willingness to work on this, having something to catch into. 

Best regards, and stay safe people

**Comment by dartasen** [comment]
Hi @Suhdaj !

Thank you for your interest in the mod, however the mod is still in alpha and still has a lot of bugs that require the project to mature a bit. However if you wish to contribute to this beautiful community project, I invite you to join our ([https://discordapp.com/invite/E8B4X9s](discord)) and ask in the general chat to join the 'Jr-Alterra' to familiarize yourself with both our team and the code base 😄 

Best regards

**Comment by Jannify** [comment]
Will look into it

**Comment by Jannify** [comment]
I have read and split up all the issues. Here is a list:
https://github.com/SubnauticaNitrox/Nitrox/issues/685
https://github.com/SubnauticaNitrox/Nitrox/issues/1113
https://github.com/SubnauticaNitrox/Nitrox/issues/1114

**Comment by krolik1591** [comment]
how to fix the bug that several messages disappeared after restarting the server?

is it possible to restart all messages on the radio again, or synchronize the info?

**Comment by Jannify** [comment]
They should be synced with version 1.7.1.0, are you on this version? If so what exactly did you do to encounter this bug?

**Comment by krolik1591** [comment]
version is current

I hosted the server. while I was building the base, my friend was researching the pods on the PDA.

during the game, 2 new messages appeared on the radio -> 2 new coordinates on the PDA. we did not investigate them and I closed the server

neither he nor I had new coordinates for the next game session
