### ISSUE TITLE
Server and Discord Questions

### ISSUE THREAD

**Issue by Oceride** [SubnauticaNitrox/Nitrox#108]
First off it said that they had a discord however they didn't leave a link to it if anyone has it pleas post it also if any of the developers are reading this and need a dedicated server i can hook you up with a test dedicated server that you would have access to 24/7 if i can get a discord and you want to talk about it i am not using my servers for anything so its up

**Comment by Sunrunner37** [comment]
Thanks for the offer but we already have a CI server.

Discord link is here: https://discord.gg/GJk7Mw
