### ISSUE TITLE
Exception while processing event with param Story_AuroraWarning

### ISSUE THREAD

**Issue by Alberto247** [SubnauticaNitrox/Nitrox#111]
![immagine](https://user-images.githubusercontent.com/9718334/35769719-a386a038-090f-11e8-997a-2b290909ae89.png)

I've never learned C# so I can't fix this myself. Every time the server processes an event of type PDA and with parameter Story_AuroraWarning(In the image the number 2, but it happened with number 1 too) it returns an exception. The exception translates to "ECall methods must be packed in a system module".
The server doesn't crash however and it keeps handling data between clients after resuming it.
Does it happens to others?

**Comment by Sunrunner37** [comment]
Fixed in latest commit.
