### ISSUE TITLE
Virus detected when download the ZIP

### ISSUE THREAD

**Issue by PikeTemplar** [SubnauticaNitrox/Nitrox#1116]
Hi guys,

I have a virus alert when I download the ZIP package : 
Virus : Win32/Wacatac.D!ml
file: D:\Téléchargements\Nitrox-master.zip->Nitrox-master/.github/depotDownloader/QXCTF.exe
webfile: D:\Téléchargements\Nitrox-master.zip|https://codeload.github.com/SubnauticaNitrox/Nitrox/zip/master|pid:17468,ProcessStart:132349593814332502

Any issue ?

**Comment by Coding-Hen** [comment]
> Hi guys,
> 
> I have a virus alert when I download the ZIP package :
> Virus : Win32/Wacatac.D!ml
> file: D:\Téléchargements\Nitrox-master.zip->Nitrox-master/.github/depotDownloader/QXCTF.exe
> webfile: D:\Téléchargements\Nitrox-master.zip|[https://codeload.github.com/SubnauticaNitrox/Nitrox/zip/master|pid:17468,ProcessStart:132349593814332502](https://codeload.github.com/SubnauticaNitrox/Nitrox/zip/master%7Cpid:17468,ProcessStart:132349593814332502)
> 
> Any issue ?

No it's not a issue, a false positive detected by your antivirus.
