### ISSUE TITLE
Progress disappearing after exiting and restarting.

### ISSUE THREAD

**Issue by dborosev** [SubnauticaNitrox/Nitrox#1119]
Friend and I have been playing, and we exited the game, came back the next day to play, and all of our progress from the last session was gone.  Seaglide was gone, as was all the blueprints we found (4 or 5 of them).  Our storage lockers were gone.   Pretty much everything we built or did was gone.

**Comment by EinLuigi** [comment]
you shouldnt stop your server before you dont type in save

**Comment by dborosev** [comment]
Thats not it.   It auto saves every 2 min.   This wiped out hours of progress.

**Comment by anth888ya** [comment]
This just happened to us. This was a catastrophic fail for the mod aka the most broken bug in the mod by FAR!. We were so far ahead and boom all progress is gone. Me and my friend are even super unmotivated to do this again.

**Comment by 0verdark** [comment]
**Stop** the auto save in-game and use the save in the **Nitrox Launcher** by typing "save" in the server Console without the " " quotes.

**Comment by Coding-Hen** [comment]
@dborosev Please can you reverify with the latest release.

**Comment by dartasen** [comment]
This is an old issue, I'm closing it for now.
Nitrox still in Alpha and is quite unstable, not a really a proper "issue", more a convergence due to a lack of fully functional synchronization
