### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sosalker** [SubnauticaNitrox/Nitrox#1123]
![image](https://user-images.githubusercontent.com/63967221/83324107-4f66c100-a27c-11ea-9468-fbaba8a1b4bf.png)
![image](https://user-images.githubusercontent.com/63967221/83324110-57befc00-a27c-11ea-8f17-ac9f7f9ea01f.png)
![image](https://user-images.githubusercontent.com/63967221/83324114-61486400-a27c-11ea-8ce8-fede287cd5cb.png) After saving and reconnecting, we were near Aurora and then teleported to the previous position, but without water

**Comment by Jannify** [comment]
Does this persist after reconnecting again?

**Comment by sosalker** [comment]
> Does this persist after reconnecting again?

Yes

**Comment by Potatosayno** [comment]
Happened to me too, it can happen with the Aurora as well. For some reason it seems as if 1 player can see everything fine and walk on the floor but for the other he falls through the floor and can't see it. 
This can be fixed on server restarts or reconnects though. But it's extremely annoying, it happens online sometimes.

**Comment by dartasen** [comment]
New version of Nitrox is available, we shipped some fix for this. I'm closing it !
