### ISSUE TITLE
Alien Containment missing/invisible on rejoin

### ISSUE THREAD

**Issue by RedSpid3r** [SubnauticaNitrox/Nitrox#1129]
After rejoining server, Alien Containment is missing/invisible. There was a fish floating in mid air but the structire itself was gone but somehow blocking me from placing a new one in the same room and also blocks me from deconstructing the room.

![image](https://user-images.githubusercontent.com/12657277/83934982-f089d600-a7ac-11ea-9c9f-d520a34614fe.png)

![image](https://user-images.githubusercontent.com/12657277/83934191-b0bff000-a7a6-11ea-8e13-37629cba6b90.png)

**Comment by dartasen** [comment]
Fixed in the next release
