### ISSUE TITLE
Error while starting in multiplayer mode

### ISSUE THREAD

**Issue by xdGlace** [SubnauticaNitrox/Nitrox#1131]
I wanted to play with my friend again this day and then this error came up. The day before everything worked fine and I changed no settings. 
![multiplayer error](https://user-images.githubusercontent.com/66675534/84139721-acb6fb00-aa50-11ea-9872-d8cf0e842d7b.png)

**Comment by Measurity** [comment]
This is an error while copying/patching the assembly (presumably some other IO operation was acting on the same file). We changed how this works so next release it should be fixed.
