### ISSUE TITLE
Non-responsive Creatures

### ISSUE THREAD

**Issue by Jerakin** [SubnauticaNitrox/Nitrox#1132]
- [ ] Skyray (Sample size: in the 20s)
- [ ] Reaper Leviathan (Sample size: 1)

I found the following creatures not moving, I presume their behavior have not been implemented but thought I would make a note of it.

Version: 1.2.2.0

**Comment by it-rec** [comment]
For me its larger than this. Mostly all fish are eigther in a statis or move. It feels like the trigger to make them move after the spawn isn't executed.

**Comment by EinLuigi** [comment]
same for me

**Comment by dartasen** [comment]
???

**Comment by it-rec** [comment]
> 
> 
> ???

What do you inted to say with `???`. Do you imply that this does not happen any more?

**Comment by dartasen** [comment]
> > ???
> 
> What do you inted to say with `???`. Do you imply that this does not happen any more?

An issue is already opened for creature sync, it's more complicated than just trigger a moving script, but we're working on it

**Comment by it-rec** [comment]
Thank you for clarifying!
