### ISSUE TITLE
Geometry issue in Aurora

### ISSUE THREAD

**Issue by Jerakin** [SubnauticaNitrox/Nitrox#1133]
Found a huge hole in the geometry in Aurora, the collision didn't work there either so I could swim around in it.
![2020-06-10 22_05_50-Subnautica](https://user-images.githubusercontent.com/5273682/84314742-dbc09000-ab68-11ea-84c4-c3501da4c710.png)

Version: 1.2.2.0

**Comment by Coding-Hen** [comment]
Can you verify that this is still an issue? Please test with the latest release

**Comment by EugeneScully** [comment]
I also had this issue in Alpha 1.3.0.0_RC2

I couldn't move from the locker room to the cargo bay corridor

**Comment by dartasen** [comment]
New version of Nitrox is available, we shipped some fix for this. I'm closing it !
