### ISSUE TITLE
[Cyclops] Player position issue with Cyclops & Seamoth

### ISSUE THREAD

**Issue by Potatosayno** [SubnauticaNitrox/Nitrox#1145]
Hello!
When using the Seamoth, the position of the player might bug out for the other user, meaning they would stay in place in the Seamoth. The bugs are extremely noticeable when you have 2 players using 2 Seamoths.
The position of the player is only fixed once the player leaves the seamoth.

Regarding an issue with the Cyclops and Seamoth together, their positions can be desynced between the users, and when one user goes into a cyclops or a seamoth that another user has controlled before, the seamoth or cyclops can teleport to where the user who just got in is. Meaning the person who was with the seamoth or cyclops would get it "stolen" even miles away.

These bugs with placement are really annoying as they can both cause invisible players & accidental  deaths because one guy accidentally used a bugged out seamoth that on their screen was empty but it was actually miles away for the other player.

**Comment by Jannify** [comment]
@killzoms is working on a fix with implementing our own Transform and GameObject class.

**Comment by devedse** [comment]
This issue happens all the time for me and my friends as well. Every time you undock from a seamoth in a moon pool the location gets completely screwed up. You have to reload the game for all and then it works again.

**Comment by Jannify** [comment]
Closing as I think it's fixed, at least we (the dev team) didn't encountered this again. If not I will reopen this issue again.

**Comment by tgm4883** [comment]
I'm still having this issue on Nitrox 1.7.1.0 in a 3 person server with 2 Seamoths.
