### ISSUE TITLE
Issue with hatch & fabricator 

### ISSUE THREAD

**Issue by Potatosayno** [SubnauticaNitrox/Nitrox#1146]
Hatch & fabricators are desynced.
BOTH users need to place a hatch on a base in the same spot even for them to be able to get in, as when one player places a hatch it does not appear for the other user.

Regarding fabricators, they do show up for both players, but only the ones placed down by the user are usable, as the other ones not placed by the player are "unpowered" apparently. This unpowered state will show up on all manually made fabricators though on a server restart, and both players will have to replace their fabricators.

https://i.imgur.com/0ezgPkT.png

**Comment by Jannify** [comment]
Duplicate https://github.com/SubnauticaNitrox/Nitrox/issues/1160
