### ISSUE TITLE
Laser & Wired door issue

### ISSUE THREAD

**Issue by Potatosayno** [SubnauticaNitrox/Nitrox#1148]
In the Aurora, the lasered doors will be desynced between the users, and will stay forever at "100%" for the other user. 
Regarding the wired doors which need their wires repaired, they will reset on a server restart for an odd reason.

**Comment by Jannify** [comment]
Yes Nitrox is saving the world. However they reset with each new version. Overall Nitrox is in alpha and not suitable for a serious play throughs.

**Comment by it-rec** [comment]
Had this issue today as well.
