### ISSUE TITLE
[Entity] Implement AI

### ISSUE THREAD

**Issue by killzoms** [SubnauticaNitrox/Nitrox#1153]
[Class](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxClient/GameLogic/AI.cs)

- [ ] Decide model to register new Actions
- [ ] Register all Actions
- [ ] Finish Implementation

**Comment by Dessix** [comment]
Is there any more information on requirements for the model, what registration should entail, if deregistration should be supported, etcetera?

**Comment by WestOnfOrD** [comment]
Any additional information available for this? What kind of challenges exist in expanding the existing creature behavior to accommodate multiple players? What, if anything, already exists to facilitate the necessary changes?

**Comment by NinjaPedroX** [comment]
AFAIK (not as a Developer but as a Discord Server Support Staff member), creature AI was written to deal with only one player/target. With multiplayer, the AI will need to be rewritten to react to multiple players. I'd imagine that this would include choosing which player to target (for hostile/hypnotical creatures) and how often to switch the target depending on distance, time, etc.

**Comment by Jannify** [comment]
Moving to #113
