### ISSUE TITLE
Problem with connection

### ISSUE THREAD

**Issue by Roman-Dzerkal** [SubnauticaNitrox/Nitrox#1156]
Hello there! I have an issue with starting server in SubnauticaLauncher. After click "Start Server" its close immediately (see the video by link). UDP port is 11000. The game and the launcher are in firewall exception (see the screenshots). What did I wrong?

Link: https://youtu.be/5R5eUsVZwdk
Screenshot 1: https://cdn1.savepice.ru/uploads/2020/6/26/1ff8b21b59c40bf08d53dd2b4b1a29e4-full.png
Screenshot 2: https://cdn1.savepice.ru/uploads/2020/6/26/f059931a9757b5a6f8c23297e1b07126-full.png

**Comment by Jannify** [comment]
Pls go to our discord (https://discord.gg/E8B4X9s) first for help with connection issues.
