### ISSUE TITLE
Multiplayer won’t load

### ISSUE THREAD

**Issue by laysboii** [SubnauticaNitrox/Nitrox#1157]
When I hit play multiplayer it has a error and I can’t play
![image](https://user-images.githubusercontent.com/67615236/86071592-aadbc880-ba4d-11ea-9a83-2d49988ccce1.jpg)

**Comment by Measurity** [comment]
Open task manager and kill the Subnautica process, then try again.

**Comment by Measurity** [comment]
Closing this, post here if you still have the issue.
