### ISSUE TITLE
PROBLEM SOLVED : Nitrox.exe just doesn't launch

### ISSUE THREAD

**Issue by Macdevis** [SubnauticaNitrox/Nitrox#1158]
Hi, I installed Nitrox yesterday to play in local with my gf, and everything was working well, except Nitrox launcher that needed to be launched in administrator mode about 3 or 4 times before working. 

And today, when we were finally ready to play, Nitrox.exe didn't launch on my PC and on my gf's PC neither. 

I tried to look at tutos, forums, but nobody seems to have this issue. 

I tried to look at my files, my task manager, nothing at all. Nitrox died during the night... RIP in peace Subnautica Multi :'(

**Comment by Coding-Hen** [comment]
Have you checked your anti virus is not blocking it? Also feel free to check out the discord help channel, friendly staff should be able to help you out.

**Comment by Macdevis** [comment]
I don't have any anti virus :x And ok, I'll go to Discord to try to find a solution. 

If you find something, feel free to leave a message here :)

**Comment by Macdevis** [comment]
PROBLEM SOLVED : I placed the Nitrox folder INSIDE the game's folder. You should place it somewhere else (like desktop, or Steam/Epic folder, but NOT the game's folder). 

It now works well, thanks to the Discord's team.

**Comment by Nhaerfuipro** [comment]
пизда я гей хуй член ах
