### ISSUE TITLE
[BASE] Most furniture is disconnected after restart resulting in (power) issues

### ISSUE THREAD

**Issue by Jannify** [SubnauticaNitrox/Nitrox#1160]
For example: Battery charger, locker, fabricator and even hatches.

**Comment by shambles1812** [comment]
Just had this any updates on this? Any ideas what part of the code is responsible?

**Comment by Jannify** [comment]
Killzoms is working on a few improvements to parenting and entity management, Acid has left us as far as I know and sun will look into building (issues) and acid's code as soon he has time.

**Comment by shambles1812** [comment]
I see, I'd take a look at it for now.
