### ISSUE TITLE
Virus in files

### ISSUE THREAD

**Issue by Trachinusdragon** [SubnauticaNitrox/Nitrox#1164]
Nitrox/.github/depotDownloader/QXCTF.exe 

it is Trojan:Win32/Fuery.B!cl

**Comment by Coding-Hen** [comment]
What anti-virus are you using for this? As per virus total nothing within this repository gets flagged: https://www.virustotal.com/gui/url/890951d79abca6606084f737edfaeea1bb9bcbcc6c118429cd460b71fcfca026/detection

**Comment by Trachinusdragon** [comment]
just check Nitrox/.github/depotDownloader/QXCTF.exe contains Trojan:Win32/Fuery.B!cl
Basic windows defender

**Comment by dartasen** [comment]
Hi @Trachinusdragon, we are aware that QXCTF.exe is detected by Windows defender as a virus and of course it is not.
We are using it to build our test versions before public release. Just to say that it's a tool used for developement purposes and the public will never see it in the zip of the mod.

If you are annoyed by this windows notifications, you can still put a filter on it.

Best regards
