### ISSUE TITLE
Any way to change where you spawn in for the first time 

### ISSUE THREAD

**Issue by KGwinter** [SubnauticaNitrox/Nitrox#1166]
My brother and I want to play subnautica multiplayer and we didn't really like the spawn so he deleted the world folder in the alpha folder to reset the world but we keep spawning in the same place is there a set spawn?

**Comment by killzoms** [comment]
Yea at this current point in time the spawn point is fixed

**Comment by Coding-Hen** [comment]
Linked with #891
