### ISSUE TITLE
If one player docks to the moonpool and the other is in the pool, this player dies.

### ISSUE THREAD

**Issue by it-rec** [SubnauticaNitrox/Nitrox#1172]
**Version:** 
1.2.2.0

**Bug:**
When a player swims in the pool of the moonpool, or tries to climb the ladder he/she dies as another tries to dock to the moonpool.

**Expected:**
The player that blocks the moonpool gets pushed aside and eventually gets hurt a bit (worse the harder the push is).

**Comment by dartasen** [comment]
More likely that this is a Subnautica bug than a nitrox one
