### ISSUE TITLE
Seamoth with MK2 depth module suddently explodes under 200 meter

### ISSUE THREAD

**Issue by it-rec** [SubnauticaNitrox/Nitrox#1174]
**Version:**
1.2.2.0

**Bug:**
One player was on an Island, other was using the seamoth with a MK2 module that allows the seamoth going up to 500 meters deep. However, when going under 200 a sound was suddently played for both players that the moth is going to take damge because it is too deep. When looking at the UI it indidated: 500 meter. I went out of the moth and checked the upgrade: It was there. Suddently the moth went to heaven....

**Expected:**
The Modules on a Vehicle function correctly, also  with two players at total differnt positions and also upon reload.

**Comment by Coding-Hen** [comment]
@it-rec Could you check this on the latest version? We checked this for the current release and were unable to reproduce it.

**Comment by EugeneScully** [comment]
This happens for me on Alpha 1.3.0.0_RC2

It occurs when player 1 is playing on the server and has placed their depth upgrade modules in their seamoth and has been playing for a while (Maybe logged on and off a few times)

Then when player 2 joins, the depth for the seamoth is reset (as if no upgrades)

This also happens for the cyclops depth upgrade modules

A work around is to have player 1 stand next to the upgrade module station, and as soon as player 2 joins, player one removes the module and adds it back again. This re-applies the depth upgrade

**Comment by dartasen** [comment]
Duplicate #1223
