### ISSUE TITLE
Cant Start

### ISSUE THREAD

**Issue by SubnauticaBoi** [SubnauticaNitrox/Nitrox#1180]
When i launch the launcher, it works perfectly but when i hit **PLAY MULTIPLAYER** it pops up with this error message:
![2020-07-26 17_11_40-Error while starting in multiplayer mode](https://user-images.githubusercontent.com/68819589/88483965-23f21100-cf63-11ea-9698-c72bb3ab4739.png)

Please can someone do anything to tell me what to do? I havent been able to play and my friends are getting bored. Any help would be great!

**Comment by dartasen** [comment]
Hi @SubnauticaBoi, could you please head to our [discord ](https://discord.gg/E8B4X9s), so our support team will be able to help you

Best regards

**Comment by Coding-Hen** [comment]
@SubnauticaBoi Were you able to resolve this issue? If so please close this issue

**Comment by 0verdark** [comment]
@SubnauticaBoi Just restart the **Nitrox Launcher**
