### ISSUE TITLE
[UI] Remote Player Colors

### ISSUE THREAD

**Issue by Sunrunner37** [SubnauticaNitrox/Nitrox#119]
- [ ] Equipment coloring 
- [x] Chat coloring 
- [x] Ping Coloring
- [x] Color picker in settings
- [x] Persist picked color
- [x] Begin with a randomly selected color

**Comment by MadMaxOfYore** [comment]
I'm working on this - but can't claim at this time.

**Comment by Jannify** [comment]
#56 Covers all exclusive equipment and random color.
Have to talk to @MadMaxOfYore for cleaning and implementing...
