### ISSUE TITLE
Custom Server and Client Port

### ISSUE THREAD

**Issue by 0x110** [SubnauticaNitrox/Nitrox#1190]
Hey there,

will you add a custom server and client port soon?
I took a look at the source and found port references. But I honestly don't want to fork it and do code hacking, since it should be standard for other people too.

I think a custom port would be awesome regarding host multiple servers under one IP and bringing people better together, than using Hamachi and co. I could also code a server browser tool then and host a few servers on one of my many dedicated servers. I think others would love that too.

Keep up the great work.

Thank you.

**Comment by Coding-Hen** [comment]
A custom port can already be set within the server config

**Comment by killzoms** [comment]
Custom Port can be set [here](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxServer-Subnautica/App.config#L5)  on the server and can be attached at the end of the IP when adding a server to the client

**Comment by Measurity** [comment]
And you can set a port by adding a `:portnumber` after the IP address for a server. Example: `127.0.0.1:11000`. This will use port `11000` to connect which is the default port.

Closing the issue. Reopen it if it doesn't work.

**Comment by 0x110** [comment]
Thank you, guys. I must be blind. :-)
