### ISSUE TITLE
No infection and radio messages don't read anything when clicked on.

### ISSUE THREAD

**Issue by RotisserieMan** [SubnauticaNitrox/Nitrox#1191]
I have over 20 hours of game play with a friend and radio messages make sounds but don't play a message. We have built the Neptune rocket, but we can't leave because the alien gun is up and we can't power down the gun without being infected first. Also the rescue ship still hasn't arrived because of...... NO RADIO MESSAGES.

**Comment by dartasen** [comment]
Fixed in the next release
