### ISSUE TITLE
[Vehicle] Sync Remaining Cyclops Actions

### ISSUE THREAD

**Issue by Sunrunner37** [SubnauticaNitrox/Nitrox#120]
- [x] Decoy Launcher
- [x] Module Statuses
- [x] Sonar (check execution position for remote player)
- [x] Horn
- [x] Smoke Screen

**Comment by Jannify** [comment]
Horn is fixed with https://github.com/SubnauticaNitrox/Nitrox/pull/883

**Comment by tornac1234** [comment]
Sonar is fixed with #1679

**Comment by tornac1234** [comment]
Smoke screen seems to be synced correctly (related to the fire sync) and also the module statuses

**Comment by tornac1234** [comment]
Decoy launcher is synced but I'll make a small PR to fix a smol issue
