### ISSUE TITLE
Sync player's Subroot on connection

### ISSUE THREAD

**Issue by killzoms** [SubnauticaNitrox/Nitrox#1207]
On reconnect as of this moment we do not sync the player's Subroot, this can cause issues such as swimming inside a base

Note:
Likely requires the player to be synced after everything else, bases and vehicles must exist for the players Subroot to be properly set to the relevant objects, something along the lines of locating the Subroot gameObject via the NitroxId and accessing the Subroot monobehaviour to pass into Player.SetCurrentSubroot()

[Source](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs)

**Comment by Untar1** [comment]
Just a thought - will this work in case the player is in a vehicle?
Explanation: as a vehicle is mobile, if a player (A) disconnects when they are in, let's say, cyclops. Then another player (B) moves the cyclops far enough that when the first player (A) reconnects, they would be in space that is outside the cyclops.
As I see, there are two possible solutions:
1. verify if the player is still within the premises
2. attach a player to a vehicle/base on disconnect, then reattach them on reconnect (may rise a ton of issues such as destroyed vehicle/deconstructed base part)

**Comment by dartasen** [comment]
Fixed in #1273
