### ISSUE TITLE
Game state - saving & inventories.

### ISSUE THREAD

**Issue by JackeryJoo** [SubnauticaNitrox/Nitrox#121]
Hello, not sure if this problem is with my current setup, or if you are aware or not, but some elements demonstrated within the videos do not work in the currently available master project.

The following are the issues that I am receiving:

- Having a second player in a cyclops sometimes causes them to teleport 100+ meters away from the cyclops upon moving or in some cases causes death when moving.
- Inventories of objects are not being shared (when another player opens it, the inventory is empty)
- When a player was building a base, nothing would appear on the other clients
- When a player disconnects (has to relaunch game to properly disconnect), the server console says that they are a new client, same goes with running the test client twice. In this process they are also given different reservation keys each time they join, even though they have the same playerID. This results in starting afresh each time, having to go through the crash sequence and loss of inventory. However, if the player saves while on the server, it creates a new game save in single player?

Apologies for bothering you guys. What you are working on is something amazing, and I tip my hat towards you fellas for the work that is being put into this.

**Comment by Alberto247** [comment]
Inventories are synced except from the "special ones", like the one inside the lifepod, floating containers, and the ones inside the cyclops.
Base building works, the only problem i have found is about rotation wich is not always the same for all clients. I have yet to try with the latest updates.

**Comment by MadMaxOfYore** [comment]
1. Having a second player in a cyclops sometimes causes them to teleport 100+ meters away from the cyclops upon moving or in some cases causes death when moving.

Thanks for the heads up - I don't think we have noticed this one on our own.

2. Inventories of objects are not being shared (when another player opens it, the inventory is empty)

This is something that we have not even gotten around to yet. Stay tuned ;)

3. When a player was building a base, nothing would appear on the other clients

This is working in the current build to my knowledge. We'll double check though.

4. When a player disconnects...

This is going to take a few more iterations to resolve. We are still grappling with how we want to handle authentication. Once that is worked out, we'll be able to allow for player reconnects. The reservations you see now are the groundwork for the effort though. Again, stay tuned!

Heads up - I'll be closing this issue once we've verified that all of the report issues have been captured in our backlog.

Thanks!
-MadMax

**Comment by MarijnS95** [comment]
1. All issues regarding Cyclops positioning and movement are known. I know the root cause, though a proper, neat solution is still being formed in my head.

3. This is also a known 'issue'. Packet data revolving building is culled by our 'deferred packet' mechanism, that prevents dealing with with events too far away for the player to see, or for the game itself to care about. While in fact, bases persist in the world even if you are a few kilometers away. Added to that, there are a few issues in the current deferring code, causing bases built closely to not appear under certain circumstances. This has also been fixed on a feature branch of mine, but requires some slight alterations before being mainlined.

**Comment by MadMaxOfYore** [comment]
Thanks for piping in @MarijnS95!

@JackeryJoo - Would you mind closing this issue if you feel that your questions have been answered satisfactorily?

Thanks,
-MadMax

**Comment by JackeryJoo** [comment]
Cheers for the feedback. I'm looking forward to these elements being fixed, along with #145  .

Thank you for your work and dedication to the project!
