### ISSUE TITLE
Nitrox Launcher not booting up, Path Issue?

### ISSUE THREAD

**Issue by plasmapea60** [SubnauticaNitrox/Nitrox#1213]
I also tried creating a folder in Subnautica called AssetBundles and it said something about objects not in the folder or something?
Please help. Screenshot below.

![2020-08-09](https://user-images.githubusercontent.com/69435876/89741129-a2b77580-da5c-11ea-837b-ac2a716a1382.png)

**Comment by jorgegomzar** [comment]
The problem disappears if you copy "AssetBundles" folder into the game folder.
You most likely won't be able to play multiplayer though, in August 6th there was an update and the devs are still trying to patch it up.

**Comment by Measurity** [comment]
This should be fixed next release because we no longer copy these files over to the game dir. Closing this now, reopen if the issue still exists when alpha 1.3.0.0 is released.
