### ISSUE TITLE
[Base] Power cell charger is not synced

### ISSUE THREAD

**Issue by CodingPfeffer** [SubnauticaNitrox/Nitrox#1216]
The following has been identified with Subnautica version Okt. 2020-65786 and Nitrox version Alpha 1.3.0.0-159-alpha-1-3-0-0-1597165443.

We were 2 players in a session. Player 1 has put a power cell into a power cell charger he had build himself. (We know that interior modules only receive power for the building player. Seems that power is not synchronized as well.) Player 2 couldn't see the power cell in the power cell charger. The powercell charger was also shown as not having any power for player 1.

**Comment by EinLuigi** [comment]
I have the same bug

CodingPfeffer <notifications@github.com> schrieb am Sa., 15. Aug. 2020,
22:55:

**Comment by Jannify** [comment]
Merged into issue about base power bugs.
