### ISSUE TITLE
[Misc] Disable lifepod exit cinematics / creature spawns

### ISSUE THREAD

**Issue by Sunrunner37** [SubnauticaNitrox/Nitrox#122]

**Comment by MadMaxOfYore** [comment]
Note: you can disable the intro screen with a call to Utils.SetContinueMode(true)

Can probably do this in Multiplayer.StartSession()

Leaving this open as I have bigger fish to fry and this seems like a good story to leave for any potential new-comers looking to get their feet wet. Will pick it up if it is still lingering around near our first alpha release.

**Comment by Coding-Hen** [comment]
I assume that this be closed as its been marked as complete?
