### ISSUE TITLE
Cyclops launches passengers outside

### ISSUE THREAD

**Issue by CobaltWarrior9** [SubnauticaNitrox/Nitrox#1222]
When one player pilots a cyclops and makes a turn, it seems like passenger players that are not seated tend to be thrown out of it. This can throw players anywhere from around 50 meters away to over 7000 meters away from the cyclops. It seems to only be drastic in distance if the passengers are jumping and moving against the turn that the cyclops is making, but even if they're not purposefully moving around it can launch passengers pretty far.
Sometimes even when the cyclops isn't moving, if a player simply tries to pilot the cyclops, it will eject a passenger if they were moving. As long as the passengers are seated there are no problems.

**Comment by Gangsteri** [comment]
I dont know if this helps at all but sitting in a chair fixes the problem

**Comment by dartasen** [comment]
Yes, people can sit on a chair to stay in the cyclops without glitching !
We can't really do something for that, i'm closing it
