### ISSUE TITLE
UNIQUE_PLAYER_NAME_CONSTRAINT_VIOLATED

### ISSUE THREAD

**Issue by forestpas3** [SubnauticaNitrox/Nitrox#1228]
_ReservationState: REJECTED, UNIQUE_PLAYER_NAME_CONSTRAINT_VIOLATED_
I have this message when my friend tries to connect to the server
Every time he tries to connect to continue to play he needs to create a new character because of this 
We don't use VPNs so that should not be the problem 
Any advice how to fix it ?

**Comment by Coding-Hen** [comment]
you will probably find its because your friend has left erroneously without properly disconnecting. You need to kick the player name so that the name can be connect in again

**Comment by forestpas3** [comment]
(just to be sure)
I need to 
`kick <name> [reason]` even if they don't show up in  `list` ?

**Comment by diabolical17** [comment]
Could someone assign me this?
