### ISSUE TITLE
How to compile and run Nitrox on mac?

### ISSUE THREAD

**Issue by PPetka** [SubnauticaNitrox/Nitrox#1233]
Hi
I've seen last Issue (https://github.com/SubnauticaNitrox/Nitrox/issues/715) asking about Mac support was about a year ago. I can notice some code relating to Mac being present in the codebase.
e.g. 
`macRetinaSupport: 1`

Is this feature already enabled? If so, any doc how do I compile and run that?

If no, what has to be done?

**Comment by Jannify** [comment]
The `macRetinaSupport: 1` is probably from our Unity project for asset bundles and has nothing to do with the Nitrox code. Mac as well as Linux support lack the **cross-platform launcher back-end** which needs to be implemented. Besides that everything is nearly ready for mac/linux suport.

**Comment by Coding-Hen** [comment]
Better to follow this progress: #988
