### ISSUE TITLE
Seamoth Depth Module is not initialized properly on joining a multiplayer session

### ISSUE THREAD

**Issue by CodingPfeffer** [SubnauticaNitrox/Nitrox#1234]
The following has been identified with Subnautica version Okt. 2020-65786 and Nitrox version Alpha 1.3.0.0-159-alpha-1-3-0-0-1597165443.

When joining a game with an existing Seamoth and an equiped Seamoth Depth Module MK1. The game will recognise the module partially. It will warn about the depth limit, but will not apply any visible damage to the Seamoth. After some seconds, the Seamoth will still be destroyed. 

We tested identified this issue with a game with 2 players.

**Comment by EugeneScully** [comment]
This is the same bug as #1174 and it also happens with the cyclops depth upgrades

A workaround is to have player 1 stand next to the upgrade modules, and as soon as player 2 joins, player one removes the module and adds it back again. This re-applies the depth upgrade and prevents the explosion

**Comment by Coding-Hen** [comment]
Should be fixed with #1415
