### ISSUE TITLE
Epic Game Version No Menu in Multiplayer

### ISSUE THREAD

**Issue by Sporeut** [SubnauticaNitrox/Nitrox#1238]
Preexisting issue that was closed but never fixed
No menu when selecting multiplayer

**Comment by Measurity** [comment]
Cannot reproduce this issue myself so if you want us to fix it then we need to know how this error is happening. Most likely Nitrox is missing files or has insufficient permissions to access files.

Can you upload your player.log file? It can be found here: `%AppData%\..\LocalLow\Unknown Worlds\Subnautica\Player.log`

**Comment by epsrrior** [comment]
Hello, I have the same error but with steam version (Im replying here snce I guess it has to be the same bug). I tried reinstalling subnautica and nitrox. I used to play with the multiplayer mod around a year ago and it worked fine but now I can't, even with the old version. Here's the player.log
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/5215418/Player.log)

**Comment by Marcuse7** [comment]
Hi, I have the same issue with the Steam version. I own the MS Store version, too, but it is not installed. In Multi Player mode the menu does not appear. I have attached the log files.
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/5366215/Player.log)
[Player-prev.log](https://github.com/SubnauticaNitrox/Nitrox/files/5366216/Player-prev.log)
I use a Microsoft Modern keyboard (w/ Fingerprint ID) attached via USB.

**Comment by FreshR1997** [comment]
I found a solution: You have to delete all data of subnautica after deinstalling the game. Go to the file Subnautica and delete all data in this Folder. Then install the game again and the mod works.

**Comment by dartasen** [comment]
Easy steps to fix this issue :

1. Go to your Subnautica installation (example is for Steam but Epic is similar). Example:
C:\Steam Games\steamapps\common\Subnautica\Subnautica_Data
Delete the "Managed" folder.

2. Verify game files: Steam steps below (For Epic see link)
Right click game in steam
Click Properties
Click Local Files
Click "Verify Integrity of game files"

For epic version : 
![Epic](https://cdn.discordapp.com/attachments/525438387105038346/742818096993009685/unknown.png)
