### ISSUE TITLE
Main Menu not loading when launching Epic games multiplayer

### ISSUE THREAD

**Issue by Hyp3rSqu1d** [SubnauticaNitrox/Nitrox#1243]
When i launch multiplayer on Epic games the 
Menu icons dont load. I dont know why i linked a screenshot below
![Capture](https://user-images.githubusercontent.com/71411657/93396934-c75df480-f835-11ea-8840-f40650624298.PNG)

**Comment by BlitzCentral** [comment]
Just a thought, I ran into this issue with Oculus open in the background. Worth checking if you have VR.

**Comment by JanssensBart** [comment]
did you ran it as an admin ?

**Comment by SoggyPotato** [comment]
I am having this exact problem, but I'm on steam.  It's stuck on that screen, no audio, no other mods, and I have reinstalled both Nitrox and Subnautica multiple time.  If you found a fix I would appreciate knowing how.

**Comment by SoggyPotato** [comment]
I had this same problem, but on steam.  At least for me, I had to delete and reinstall the game.  When you delete it, make sure you manually go into the files and completely delete anything that is left.  Particularly, I think, Subnautica_data.

**Comment by Coding-Hen** [comment]
Thanks for reporting but this has already been reported. If you are using steam then head to the discord server where you can find a pinned tab in the help channel for resolving this issue with a downgrade.
Duplicate of #859
