### ISSUE TITLE
Bug - Power cannot be synchronized (help me, dear developers)

### ISSUE THREAD

**Issue by SuperHaoHaoHao** [SubnauticaNitrox/Nitrox#1244]
Hello, dear developers, I am a friend from China. I really like this online Mod, but I encountered the problem that the power cannot be synchronized, and the indoor glass became red after making things and hung in the air, making it impossible for me and my friends to proceed. I see that #1003 has become closed. I want to know when a Tag version will be launched. I can update it quickly. The version I currently use is 1.3.0.0, which is problematic.

Chinese (for Chinese friends to understand):
上面我翻译出说的话，原版中文（让中国朋友能看懂）：

你好，亲好的开发者，我是来自中国的朋友。特别喜欢这个联机Mod，但是遇到的这个电力无法同步的问题，和制造东西后室内玻璃变成红色悬在空中，让我和我的小伙伴没法进行下去了。我看到 ＃1003 的那个变成了已关闭状态，我想知道什么时候会打一个Tag版本，我可以迅速的去更新一下。我当前用的版本是1.3.0.0是有问题的。

![WechatIMG62](https://user-images.githubusercontent.com/25069877/93456684-9dc5cb80-f910-11ea-9fb6-53d66e3e187f.jpeg)

![WechatIMG642222](https://user-images.githubusercontent.com/25069877/93456933-ebdacf00-f910-11ea-99a8-37de33798ad0.jpeg)

**Comment by SuperHaoHaoHao** [comment]
If possible, can you reply and tell me when to fix it? Hope, anxiously waiting for me and my friends to continue playing

如果可以的话，能回复下告诉我什么时候修复吗？盼望，焦急等待我和小伙伴继续玩耍

**Comment by dartasen** [comment]
Hi @SuperHaoHaoHao,

We fixed this bug for the next release, thank's for the report.

Best regards
