### ISSUE TITLE
Multiplayer Client Loaded

### ISSUE THREAD

**Issue by Jaxnps** [SubnauticaNitrox/Nitrox#1246]
My friend and I are trying to use Nitrox with Hamachi. He is able to join his own server but when I try to join his or my own server I get a message that says "Multiplayer Client Loaded...". The message eventually disappears and nothing happens. We don't think that this is an issue with Hamachi. We don't know what else to do. Advice?

**Comment by dartasen** [comment]
Sorry, but we do not provide any support here, please join our discord so our support can help you !

Best regards
