### ISSUE TITLE
Start Menu is of Singleplayer, even though started as Multiplayer

### ISSUE THREAD

**Issue by HoWol76** [SubnauticaNitrox/Nitrox#1247]
I don't know exactly what caused this. My son and I want to play Subnautica together, so we downloaded and installed the Nitrox Program. It works fine on my computer, but on my son's computer, even though he clicks on the 'Multiplayer' button, the game starts and he sees the normal, single player interface.

There are several possible causes that I could think of:

1. He is not administrator on his computer. When he launches the NitroxLauncher.exe as administrator, he needs *my* credentials.
2. Only after we had both installed Nitrox did we realise that he didn't own Subnautica on his own Steam account, and had been playing from my library. So I bought him his own copy *while Nitrox was running*, so it is possible that Steam at this point overwrote some configuration file of Subnautica that Nitrox had changed. (We have since reinstalled Subnautica again, but as expected this didn't change the outcome. 

Any ideas on what causes this and how to fix it would be greatly appreciated.
Holger

**Comment by ICDevelopments** [comment]
I had exactly the same problem, and found a simple workaround:
1) I logged into windows with my admin account
2) I logged into steam with my account (with which this mod had worked in my main computer before), and run the game as a baseline. The multiplayer menu had shown.
3) I exited modded game, kept the launcher open, logged out of steam, and than logged into steam again with my second account which has subnautica.
4) launched the modded game again, in multiplayer mode. Now it works.

My guess is that step 2 is not necessary, but I wanted to make sure. Hope this helps someone.

**Comment by UmbreTwins** [comment]
I found a solution:
1. Go to this file adress: C:/Program Files (x86)/Steam/steamapps/common/subnautica
2. Open nitrox server, so it starts
3. Run NitroxLauncher as administrator
4. Launch as multiplayer

You HAVE to launch nitrox from the adress on step 1, otherwise it will not work. I had this before.

**Comment by Jannify** [comment]
@HoWol76 Did this fixed your problem?

**Comment by Coding-Hen** [comment]
Closing as believed to be fixed, reopen if mthis is not the case and you have additional information
