### ISSUE TITLE
What are the networking requirements?

### ISSUE THREAD

**Issue by jar349** [SubnauticaNitrox/Nitrox#1248]
Hello!

I'm pretty well versed in networking and would rather setup something up myself instead of using Hamachi.  What are your network requirements?  Are you using broadcast to find games?

**Comment by jar349** [comment]
I've traced through the code and found that it's using LiteNetLib (a UDP server library) on port 1100:
- port config: https://github.com/SubnauticaNitrox/Nitrox/blob/a4b3c339b1acfc87d149ad7516d0fd6566334b5a/NitroxModel/Server/ServerConfig.cs#L18
- https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxServer/Communication/NetworkingLayer/LiteNetLib/LiteNetLibServer.cs

**Comment by Measurity** [comment]
That's actually a typo in the code. Port is 11000 UDP by default as seen in App.config file in the NitroxServer-Subnautica project.

**Comment by jar349** [comment]
@Measurity if I open port 11000 for UDP traffic and forward it to my son's computer while he's running a Nitrox-powered Subnautica multiplayer game, friends with the IP address of my router should be able to join, right?

I'll definitely join discord for any future questions since that's your preferred comms method.

**Comment by Measurity** [comment]
Yep that's how it works. To recap:

1. Add a port mapping to your router (using the IP for gateway from `ipconfig` command on windows in browser to login)
2. Set IP to LAN IP of the computer that is running the Nitrox server (LAN IP format is usually 192.168.x.x)
3. Set protocol to UDP and port range to 11000 and 11000 ("start" and "end" fields as usually displayed in router UIs)

Then anyone with your external IPv4 (you can get it from a site like this https://whatismyipaddress.com/) should be able to connect as long as the firewall on the server PC isn't blocking incoming connections and your ISP allows this (some ISPs in, say, USA might not like customers hosting servers from their own network).
