### ISSUE TITLE
[Lifepod] Fire extinguisher & smoke respawns on reconnect

### ISSUE THREAD

**Issue by Untar1** [SubnauticaNitrox/Nitrox#1251]
As the title says - I tried launching a fresh server (Alpha v.1.3.0.0) locally (using only localhost for connection).
The fire extinguisher that the player gets in Lifepod 5 is respawned on every subsequent relog onto the local server.

Version: 1.3.0.0 Alpha
Connection type: localhost only
World saves tested: 2

![image](https://user-images.githubusercontent.com/1339172/94207306-06441800-fed0-11ea-89b7-b1c6952f9fe2.png)

**Comment by diabolical17** [comment]
I can work on this.

**Comment by Jannify** [comment]
Also smoke in life pod shows even though no fires are present (Can be removed by spraying the fire extinguisher)
