### ISSUE TITLE
Mobile Vehicle Bay progress resetting on reconnect

### ISSUE THREAD

**Issue by Untar1** [SubnauticaNitrox/Nitrox#1252]
When researching mobile vehicle bay fragments, I paused the progress on 2/3. After closing the client and reconnecting (server was still running), scanning the last fragment showed "1/3" progress. Tested it multiple times on the same server, last attempts were using console commands.

Version: 1.3.0.0 Alpha
Connection type: localhost
World saves tested: 2

Testing process (spawned 3 instances of mobile vehicle bay fragments
![image](https://user-images.githubusercontent.com/1339172/94207672-ccbfdc80-fed0-11ea-87e6-d78c8bffceaa.png)
![image](https://user-images.githubusercontent.com/1339172/94207707-e103d980-fed0-11ea-8103-32559d18d27b.png)
after relogging: the scanned console-spawned fragment respawned, scanned the middle one.
![image](https://user-images.githubusercontent.com/1339172/94207812-16102c00-fed1-11ea-88c9-434750abf91c.png)

**Comment by dartasen** [comment]
Fixed with #1624
