### ISSUE TITLE
Lifepod 5 fabricator animation not ending

### ISSUE THREAD

**Issue by Untar1** [SubnauticaNitrox/Nitrox#1253]
When crafting items in Lifepod 5, the animation+SFX for crafting would persist even after the item is finished crafting and the UI is closed. Additionally, items crafted are not immediately transferred to the player's inventory.
Tested out on 2 world saves.

Version: 1.3.0.0 Alpha
Connection type: localhost
World saves tested: 2

**Comment by Untar1** [comment]
Okay, thanks for the fix. Though does sound as an extreme one... Will try. What is the programfolder? .../Steam apps/common/Subnautica?

**Comment by tommyrsk** [comment]
Yes. That's correct. It solved the issue for me.

**Comment by EinLuigi** [comment]
Same Problem in Alpha 1.4.0.0 but when i rejoin it was fixed

**Comment by Jannify** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fabricator animation looping forever](https://trello.com/c/30w75LZd/6-fabricator-animation-looping-forever)

**Comment by dartasen** [comment]
Fixed in 1.5
