### ISSUE TITLE
Subnautica missions not popping up

### ISSUE THREAD

**Issue by nelrick** [SubnauticaNitrox/Nitrox#1259]
Version
Alpha 1.3.0.0

 Bug
 missions are not popping up after we rejoined the server

 Expected
 unable to progress through the game  

Steps to reproduce

Other details:

**Comment by Coding-Hen** [comment]
Should be fixed as of 6f9c6314f8521a22ba8516d89f41d7d0ec8231a2

**Comment by Bassuest** [comment]
We had to restart the server and now the missions are gone

**Comment by dartasen** [comment]
@Bassuest Yes, we're aware of this bug. This bug will be fixed for the next Nitrox version
