### ISSUE TITLE
Friend Cant Do Any Command Such As /Back

### ISSUE THREAD

**Issue by Ohimark12** [SubnauticaNitrox/Nitrox#1261]

**Comment by Ohimark12** [comment]
### Version


### Bug


### Expected


### Steps to reproduce


### Other details:

**Comment by Ohimark12** [comment]
Wait Why Doesnt It Show What I Wrote?

**Comment by Coding-Hen** [comment]
@Ohimark12 Please fill out the issue template so we can assess the issue

**Comment by Ohimark12** [comment]
It Wont let Me

**Comment by Ohimark12** [comment]
Bug

**Comment by Ohimark12** [comment]
I Put A File Of The Thing Cause It Wont Let me Type Stuff In The Preview

**Comment by Coding-Hen** [comment]
You write text within the write box not within the preview pane. There is one tab for writing he issue and the other for viewing what it will be displayed as

**Comment by Ohimark12** [comment]
There We Go

**Comment by Coding-Hen** [comment]
To give him permission write op <name> in the server console

**Comment by Ohimark12** [comment]
Thank You So Helpful It Took Us For Ever To Get Back But This is Handy Thx!
