### ISSUE TITLE
Server says im outdated, but i am on last version

### ISSUE THREAD

**Issue by RadiantUwU** [SubnauticaNitrox/Nitrox#1263]
### Version

1.3.0.0 Alpha
Subnautica version:oct-2020 65786

### Bug

Joining a 1.3 server, getting greeted with an error saying that im on 1.2

### Expected

Error appearing telling me im out of date

### Steps to reproduce

Have an previously subnautica on 1.2
Update launcher to 1.3
Create a server on localhost
Join it and you get the error

**Comment by dartasen** [comment]
To update Nitrox from 1.2 to 1.3
1. Go to your Subnautica installation (example is for Steam but Epic is similar). Example:
C:\Steam Games\steamapps\common\Subnautica\Subnautica_Data 
Delete the "Managed" folder.
2. Verify game files (for Steam see image below. For Epic see link https://discordapp.com/channels/525437013403631617/525438387105038346/742818099086229514)
3. Download and install Nitrox: https://nitrox.rux.gg/ or see download links in #📢announcements  (do not use old installation, remove it instead)
4. Extract the Nitrox zip somewhere you like and run the launcher.
