### ISSUE TITLE
Most furniture placed in a cyclops has wrong position and appears outside of it, with a hitbox

### ISSUE THREAD

**Issue by grichka** [SubnauticaNitrox/Nitrox#1268]
### Version
Alpha 1.3.0.0_RC2

### Bug

![20201028224119_1](https://user-images.githubusercontent.com/1225647/97631129-d0470600-1a30-11eb-9a16-055e1a27675d.jpg)

![20201029212814_1](https://user-images.githubusercontent.com/1225647/97631072-ba394580-1a30-11eb-9b6a-29cbd815ec62.jpg)

As you can see on the screenshots, furniture that was built inside a cyclops actually appears outside of the cyclops, partially for player 2 just after building and almost all furniture for all players after server restart.

These items outside have their hitbox and make the game very difficult to play...

However, it works fine with coffee machines ;) 

![20201029213046_1](https://user-images.githubusercontent.com/1225647/97631435-4481a980-1a31-11eb-9df1-ba1c9e10cf9a.jpg)

### Expected

Furniture should stay inside.

### Steps to reproduce

Build a Cyclops, place furniture inside. Eventually restart the server.

**Comment by dartasen** [comment]
Hi, thank's for the report !
We're aware of this issue and we're still working on it !

**Comment by Sunrunner37** [comment]
Resolved in ea7efff2475233ffa393c3c638acdb0da9534101

**Comment by grichka** [comment]
Great! This bug made my friend and I stop playing the game ^^
Maybe we'll reconsider :)
