### ISSUE TITLE
Scanner Room upgrades disappear after reconnect

### ISSUE THREAD

**Issue by neverke1** [SubnauticaNitrox/Nitrox#1275]
### Version
Version: 1.3.0.0 Alpha
Connection type: localhost

### Bug
Upgrade modules disappear from the Scanner Room after each reconnect. I'm also not exactly sure if these are synced between clients either. 

### Expected
I expect them to stay where they belong and not having to recraft them after each reconnect. :D

### Steps to reproduce
quit and reconnect

**Comment by dartasen** [comment]
Hi @neverke1, thank's for the report

We fixed this bug in [b9f58b4](https://github.com/SubnauticaNitrox/Nitrox/commit/b9f58b4498327f63ce46f12a148dd4c0ad63a327). So it will be included in the next release !
