### ISSUE TITLE
Placing habitat internal items are offset for different players

### ISSUE THREAD

**Issue by Sharky72** [SubnauticaNitrox/Nitrox#1278]
### Version
ALPHA 1.3.0.0

### Bug
When placing items like the fabricator or the storage containers, noticed that for one player it was set correctly, but for another player it was offset by a couple meters, making items like the fabricator and storage containers not inside the base but just outside. ![Container Outside](https://user-images.githubusercontent.com/70308137/98875652-e34ad480-2439-11eb-9264-a326e68668f3.png)

### Expected
When one player places an object inside of a habitat building, for all other players it is in the correct place. 

### Steps to reproduce
Requires at least 2 players. 

1. Build a multipurpose room
2. Player 1 builds an internal item inside of the room
3. Player 2 sees that the built item is not in the same place that Player 1 built the item

### Other details:

- I tried being the last player in the game, the other player being the last one in the game, connecting to localhost and connecting to the LAN IP address. No changes. 

Player Log - [Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/5527355/Player.log)

**Comment by UmbreTwins** [comment]
For me not this but another issue happened... I built a good cyclops layout, it worked fine. But when I quit the server, and rejoined the next day, everything was placed a few inches below, making deconstructing the modification station impossible. I could deconstruct everything else (Even the chairs that were LITERRALLY IN THE FLOOR), but that... Plus, the bed completely vanished. So if any of you know how this happened, please send me some ideas of how to correct this... I'll gladly appreciate it.

**Comment by EinLuigi** [comment]
pls fix this!!

**Comment by Jannify** [comment]
Should be fixed with current and/or next release
