### ISSUE TITLE
Seamoths stack in a moonpool after rejoin

### ISSUE THREAD

**Issue by Ghaarg** [SubnauticaNitrox/Nitrox#1282]
### Version

Master branch

### Bug
After rejoining the server with two seamoth docked into separate moonpools, both seamoths are docked in the same moonpool.

### Expected
Both seamoths are in their respective moonpools

### Steps to reproduce
Just park two seamoths into a base with two moonpools

### Additional notes
Building more than one moonpool seems bugged after rejoin in any way (i guess the gameObject is not set right or something)

**Comment by Sunrunner37** [comment]
Fixed 4e08011759a63b152088f7167e1bc5abb3e4e971
