### ISSUE TITLE
not possible to join server over a virtual LAN using zerotier

### ISSUE THREAD

**Issue by magnuszetterberg** [SubnauticaNitrox/Nitrox#1296]
### Bug

Installed subnautica through steam.
Unpacked and started a nitrox server
Joined the server locally(127.0.0.1)
Had zerotier installed since before and connected to our friends gaming virtual LAN through zerotier.
Friend tries to connect to my server through zerotiers IP address(the virtual LAN ip) but to no avail)
*could not connect to "**********:11000" error.
I could read in the server console:

> If playing on LAN, use this IP: "192.168.2.xxx"
> If playing on LAN, use this IP: "192.168.196.xxx"
> If using portforward, use this IP: "my external IP"

So, the server seems to find the correct IP's on my computer running the server, but It does seem to bind to the correct NIC on my computer, thus the zerotier IP which is what I want.

I tried turning of my firewall completely or just opening the 11000 port but it made no difference.

* FYI - zerotier is a alternative to lets say hamachi, it's a little bit more technical, and not really aimed against gaming per see, but it works on a hypotetical same level. You get a new virtual network card installed, it gets a IP through zerotier when joining a zerotier network, and then you have a virtual LAN between each computer. Thus there is no need to do any portforwarding etc on the router etc which is nice...  and it would be SUPER good if it would be possible to run Nitrox through this also...  =)

### Expected

My friend who is on the same virtual network can connect to my server without a problem

### Steps to reproduce

Install zero tier, and join a network on 2 different machines.
Start the server on one of the machines
Try to join from the other machine against the zerotier IP(where the server is hosted) which you have got from joining the virtual network provided by zerotier.

**Comment by Measurity** [comment]
Make sure you're using the IP given by the VPN. 

We only provide support for Hamachi right now. However this should mean that *any* VPN works. If other servers (ex: Minecraft server) do work but Nitrox does not then we'll look into fixing where needed. Closing this issue until we know for sure it isn't a user error.
