### ISSUE TITLE
No menu interface

### ISSUE THREAD

**Issue by kylarpp5** [SubnauticaNitrox/Nitrox#1311]
### Version
Alpha
1.3.0.0-159

### Bug
There is no menu on Nitrox Subnautica

### Expected

I did everything what instruction saids but i dont see menu in Epic store version
### Steps to reproduce

ust open game 
### Other details:
![122040499_643642633001056_5344263379109080433_n](https://user-images.githubusercontent.com/75836371/101891661-a2fa8580-3ba2-11eb-8b47-7836d150b1fb.jpg)

[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/5678532/Player.log)

**Comment by TheLxkas** [comment]
did you ask for help on the discord server?

**Comment by kylarpp5** [comment]
Noo.. i didn't used discord before 
okay i will try there then 
thanks 👍

**Comment by dartasen** [comment]
Those are the steps to fix it in case you didn't came on our discord, I'm closing it.

1. Go to your Subnautica installation (example is for Steam but Epic is similar). Example:
C:\Steam Games\steamapps\common\Subnautica\Subnautica_Data 
Delete the "Managed" folder.

2. Verify game files: Steam steps below (For Epic see link)
Right click game in steam
Click Properties
Click Local Files
Click "Verify Integrity of game files"

**Comment by Measurity** [comment]
https://cdn.discordapp.com/attachments/525438387105038346/742818096993009685/unknown.png <-- Epic verify

**Comment by kylarpp5** [comment]
I did it and problem still exist 
if i choose single player its okay but if multi is like You've seen

**Comment by jodo1** [comment]
This problem really solved. I delete the "Managed" folder, and verify files. The game menu works now.
