### ISSUE TITLE
Ported correctly but friend is unable to join.

### ISSUE THREAD

**Issue by AmeliaTheHusky** [SubnauticaNitrox/Nitrox#1314]
A friend and I got the launcher installed today, Port Forwarded and he is unable to join my server. I'm wondering is perhaps it's because private range is incorrect but I can't find any answer to this anywhere. I did see that the port needed to be TCP and UDP on a steam forum and tried that along with just UDP but still not working.

Port info:
![Config](https://user-images.githubusercontent.com/48843446/102003109-1b5f6480-3cd1-11eb-90a4-b5d19a15b0ab.PNG)

Error on my friends end:
![unknown](https://user-images.githubusercontent.com/48843446/102003120-5792c500-3cd1-11eb-8e1f-18ba161d39cd.png)

I should note that I am able to connect and play on the server but I assume that's because I'm the host and whatnot.

**Comment by killzoms** [comment]
did you try with the correct private range? Nitrox ports are also configurable in the NitroxServer-Subnautica.exe.config file

**Comment by AmeliaTheHusky** [comment]
> did you try with the correct private range? Nitrox ports are also configurable in the NitroxServer-Subnautica.exe.config file

What exactly is the correct private range? I couldn't find this information myself.

**Comment by Measurity** [comment]
Just to give the same information as I said on discord. Port ranges should be `11000-11000` and `11000-11000`.
Why?

This tells your router that incoming data for port 11000 UDP should not be dropped and instead forwarded to the internal network (LAN) with the same port number, 11000.
