### ISSUE TITLE
Flying blueprints

### ISSUE THREAD

**Issue by Etound** [SubnauticaNitrox/Nitrox#1328]
### Version
Alpha 1.4.0.0 

### Bug
 flying hatch or door schematic appears  https://user-images.githubusercontent.com/76262344/102696792-40a02580-4231-11eb-9947-07b1f826558c.png And i can't destroy that section

### Expected
It should never appear  

### Steps to reproduce
I don't really know i was just building

**Comment by EinLuigi** [comment]
same problem

**Comment by Jannify** [comment]
Duplicate of https://github.com/SubnauticaNitrox/Nitrox/issues/1400
