### ISSUE TITLE
[Base] Sync Locker Names

### ISSUE THREAD

**Issue by Sunrunner37** [SubnauticaNitrox/Nitrox#133]

**Comment by Agent77326** [comment]
I may have overseen it and I am sorry for that, but could it be that the locker names are actually not saved and synched? Personally in-game I was also unable to change signs to for the other player and vice versa.

**Comment by acidscorch** [comment]
Currently locker ids are not synced correctly. This will be taken in accound for the upcoming base building pr. If base and locker Ids are asynced and reloaded correctly this needs to be reviewed.

**Comment by Sunrunner37** [comment]
This is resolved.
