### ISSUE TITLE
Vehicle upgrade console disappears

### ISSUE THREAD

**Issue by simgre** [SubnauticaNitrox/Nitrox#1330]
### Version

1.4.0.0

### Bug

When reconnecting to server vehicle upgrade console disappears clientside, but remains serverside. Meaning I can't see it when I reconnect after building it, but others who are online can see and use it.

When swimming outside I can see a red blueprint of it offset by 1 "tile" in a direction.

### Expected

That the vehicle upgrade console remains where it's placed and is usable.

### Steps to reproduce

Build a moonpool, build a vehicle upgrade console in it, disconnect from the server and then reconnect.

### Other details:

I'm getting a couple of NullReferenceExceptions in the player.log, but couldn't tell you what they mean or if they are related to the issue, so I'm attaching the file if you want to take a look.
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/5721109/Player.log)

**Comment by mpocius** [comment]
I can confirm this as well in 1.4.0.0. Console is gone after exiting the game and remains so after a server restart, but you're able to construct a new one in the previous location.
