### ISSUE TITLE
All of the leviathans and Warpers aren't moving

### ISSUE THREAD

**Issue by AgentFlex** [SubnauticaNitrox/Nitrox#1332]
### Version
1.4.0.0

### Bug
I am playing with my friend on Nitrox, and none of the reapers, seadragons, or any of the big leviathans and warpers move, they all go through their animations but they do not attack or move.

### Steps to reproduce
Load up a world, go to any place like the dunes or kelp zone, no leviathans or warpers are moving.

Or you can try spawning them.
### Other details:
I have tried multiple different world files to see if its corruption, and it still happens.
and there is no errors in the logs.

**Comment by neutrinos4all** [comment]
@AgentFlex does this occur with other creatures, or just leviathans? I have observed similar behavior with ampeels, crabsquids, bonesharks, and stalkers (animations in place, but no movement around). However, I have noted that approaching each of those creatures to "touch" them or get sufficiently close results in an immediate attack and normal behavior after that. It seems like getting close forces those resources to be properly simulated.

**Comment by daufinsyd** [comment]
I seems thats créatures are not synced. As a result, the player who a took the "lead" see créatures moving whereas other players see the créatures stucked.

**Comment by Exso12Ecesis** [comment]
I have confirmed this behavior in 1.4.0.0. I had a scenario occur, where a client was seeing a leviathan push the Cyclops around, but another client saw nothing but the Cyclops moving for no reason.

**Comment by neutrinos4all** [comment]
Is this potentially related to #1132?

**Comment by Exso12Ecesis** [comment]
> Is this potentially related to #1132?
To me, the two tickets look exactly the same, I'd say this a duplicate.

**Comment by romgerman** [comment]
Can confirm about warpers. They are not moving. Leviathans kidna work but only for one player (when i was in a vehicle it was ramming into me but others saw it as leviathan just stood in place).

**Comment by Iltotore** [comment]
Idk if this repo has label for high priority issues but this should be prioritised as Leviathans and warpers are really importants for the gameplay

**Comment by Coding-Hen** [comment]
Related and tracked by #113
