### ISSUE TITLE
No main menu (Steam)

### ISSUE THREAD

**Issue by matthias-luger** [SubnauticaNitrox/Nitrox#1339]
### Version

1.4.0.0

### Bug
The menu buttons at the title screen at the beginning of the game don't show up. After starting the game with the launcher I cant do anything. This only occurs with the multiplayer version.

### Expected
The menu buttons are shown and functional.

### Steps to reproduce
- Install the Nitrox Launcher
- Specify the path to Subnautica (Steam Version)
- Start the multiplayer game ("Play Multiplayer" in the Launcher)
- See no buttons, only the Subnautica text over the ocean

### Other details:
Same bug was already fixed some time ago: https://github.com/SubnauticaNitrox/Nitrox/issues/859

Platform: Steam
Screen: 4k 144hz, also tried on WQHD 144hz

**Player.log: (important, there is an exception)**
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/5738225/Player.log)

Image:
![subnautica](https://user-images.githubusercontent.com/58751503/103062870-d6c8a880-45af-11eb-8e92-a39a084a60ff.JPG)

**Comment by Jannify** [comment]
Have you tried the common fixes for this? If not head over to our discord server, they will help you to get it starting.

**Comment by matthias-luger** [comment]
Thanks, the following steps from the discord solved it for me:

- Go to your Subnautica file installation (example is for Steam but Epic is similar) Example: C:\Steam Games\steamapps\common\Subnautica\Subnautica_Data and delete the "Managed" folder.
- Go to the Steam/Epic Game library, go into the properties of Subnautica, and then search and click “Verify Game files” (or similar).
- Redownload and reextract Nitrox to your desktop, and try joining the server again.
