### ISSUE TITLE
Can't charge vehicles in moonpool

### ISSUE THREAD

**Issue by Iltotore** [SubnauticaNitrox/Nitrox#1340]
### Version
Latest (1.4.0.0)

### Bug
The seamoth/prawn doesn't charge when docked in a alimented moonpool. (The battery gain a point of energy and lose it immediately)

### Expected
They should charge when docked to alimented moonpool.

### Steps to reproduce
Dock a seamoth or a prawn in a moonpool.

### Other details:
-

**Comment by Jannify** [comment]
Will close this now as https://github.com/SubnauticaNitrox/Nitrox/issues/1376 is the collective thread of all these issues.
