### ISSUE TITLE
Ladders disappear

### ISSUE THREAD

**Issue by daufinsyd** [SubnauticaNitrox/Nitrox#1346]
### Version
1.4.0.0

### Bug
Ladders constructed in bases are removes after server exit.

### Expected
Ladders, like other objects, are saved and present on reconnect.

### Steps to reproduce
- construct a ladder
- exit/shutdown the server
- start the server.
The ladder is missing.

### Other details:
As far as I know it's the only build component which disappears. You're surely aware of the bug but I didn't found any issue mentioning it.

Thank you all for your hard work !

**Comment by Measurity** [comment]
Rejoining server also causes the bug.
