### ISSUE TITLE
Base Build is not 100% finished

### ISSUE THREAD

**Issue by EinLuigi** [SubnauticaNitrox/Nitrox#1355]
### Bug
i played with my friend an he build someting and it was not finished

### Expected
That building is finished

### Steps to reproduce
Create a Server let build your friend something than it happens

**Comment by Coding-Hen** [comment]
Please can you update this with the version

**Comment by Measurity** [comment]
We know base building isn't completed yet. Gonna close this until you provide more information about steps to reproduce. If you don't give details, we can't fix.
