### ISSUE TITLE
Seamoth will not charge in moonpool built by different player

### ISSUE THREAD

**Issue by neutrinos4all** [SubnauticaNitrox/Nitrox#1376]
### Version:

Nitrox 1.4.0.0

### Bug

A Seamoth built by Player A will not charge when docked in moonpool built by Player B.

### Expected

Seamoths should charge interchangeably with moonpools. In other words, I expect to be able to build one moonpool to support/charge multiple Seamoths.

### Steps to reproduce

1. Players A and B each build a Seamoth.
2. Player A builds a moonpool.
3. Players A and B dock their Seamoths in Player A's moonpool in series, waiting to observe charge rates for those vehicles.
4. If bug is present, Player A's Seamoth should charge, while Player B's Seamoth should not.

### Other details:

Could be related to #1340 ("Can't charge vehicles in moonpool"), but additional testing or detail is needed on that issue to determine similarity/difference. 
No related log details identified.

**Comment by Jannify** [comment]
Seems like the cyclops is experiencing the same problem: https://github.com/SubnauticaNitrox/Nitrox/issues/1377

**Comment by Iltotore** [comment]
I wanted to confirm that the bug also happen on same-owner moonpools.

**Comment by Jannify** [comment]
With recent changes to LiveMixIn and EnergyMixIn this needs to be reverified.

**Comment by NZVengeance** [comment]
Can confirm this issue for Seamoths and Moonpools built by any players (checked all combinations)

**Comment by tornac1234** [comment]
Tested with a moonpool and two seamoths, they both charged on both players POV
