### ISSUE TITLE
Seamoth and prawn suit won't charge in the cyclops

### ISSUE THREAD

**Issue by Fraah** [SubnauticaNitrox/Nitrox#1377]
### Version
1.4.0.0

### Bug
Seamoth and prawn suit won't charge in the cyclops

### Expected
If I dock the seamoth or the prawn suit in the cyclops they will not recharge, but the cyclops battery will be consumed anyway

**Comment by Jannify** [comment]
Will close this now because it's the same problem as in the referenced issue.
