### ISSUE TITLE
CS1061 and CS1501 compiling/building errors

### ISSUE THREAD

**Issue by Etherthedragon** [SubnauticaNitrox/Nitrox#1380]
Help an amateur coder out? Trying to build the latest source code (solution) - without using Git, via desktop with Visual Studio 2019 (free) - but I'm getting 4 errors. I have not edited the two files that are causing these errors in any way - that code was left as is.

### Version

Current source-code (Jan 6th)

### Bug

Cannot build the solution file, getting 4 errors (attachments included):

The error messages are as follows:

CS1061	'GameObject' does not contain a definition for 'TryGetComponent' and no accessible extension method 'TryGetComponent' accepting a first argument of type 'GameObject' could be found (are you missing a using directive or an assembly reference?)

(This one repeats 3 times, in one file: RemotePlayerSyncProcessor.cs - Lines 49, 77, and 108)

and

CS1501 No overload for method 'UpdateGhostModel' takes 5 arguments

(the other file, MultiplayerBuilder.cs - Line 189)

### Expected Behavior:
Compiling without throwing errors my way.

### Steps to reproduce
Download the latest source code + LiteNetLib.
Open in Visual Studio.
Click "Build Solution"
Wait until done.
Hopefully see the 4 errors. (if it's not my problem alone)

![rsz_5ffb26cbb4e44](https://user-images.githubusercontent.com/49726810/104128826-d3d50280-537a-11eb-8cd0-752812cc2443.png)
![rsz_5ffb2726aac2b](https://user-images.githubusercontent.com/49726810/104128828-d5062f80-537a-11eb-93bb-0a5b8c441d34.png)
![rsz_5ffb266a39689](https://user-images.githubusercontent.com/49726810/104128829-d5062f80-537a-11eb-9b8b-cd4879a1c43c.png)

**Comment by Jannify** [comment]
This seems like a error on your side. Nobody else from the dev team is experiencing this. Please check if you linked VS to your subnautica folder correctly and delete the cache. Also ensure all Nuget packages are installed. After that restart VS and check if the error is still there. If so I am sorry to say that I cannot help you furthermore.

**Comment by Measurity** [comment]
See: https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox for steps as well.
