### ISSUE TITLE
Planted objects not keeping their "age" when server restart

### ISSUE THREAD

**Issue by JacopoSciampi** [SubnauticaNitrox/Nitrox#1381]
### Version
Alpha 1.4.0.0

### Bug
I made a base with some plants in it. They were full grown. Closed the server for a bit. Re-opened it and the plants are not fully grown, but they start growing like if I have just planted them

**Comment by Jannify** [comment]
https://github.com/SubnauticaNitrox/Nitrox/pull/1341

**Comment by AntalaFilip** [comment]
# I think this was fixed in #1341
