### ISSUE TITLE
items vanishing

### ISSUE THREAD

**Issue by LeaderbotX400** [SubnauticaNitrox/Nitrox#1385]
### Version
Alpha 1.4.0.0

### Bug
item vanishing from inventory's when a player rejoins or after a server restart

### Expected
the players inventory should still be there but sometimes one plays inventory will be wiped

### Steps to reproduce

- Start a server
- get items
- restart server
- join server

that is what I do for this bug to be made it might not work every time

**Comment by Measurity** [comment]
Can you be more specific when this happens and to which inventory (player? locker? water storage? only inside bases?)? Can you send the player.log file when the issue happens again? Note: The log is cleared every time you start the game so it has to be after you get the issue.

**Comment by LeaderbotX400** [comment]
> Can you be more specific when this happens and to which inventory (player? locker? water storage? only inside bases?)? Can you send the player.log file when the issue happens again? Note: The log is cleared every time you start the game so it has to be after you get the issue.

the items disappear from player inventory's and it does not happen every time, furthermore it seems to happen more often when you have three or more players, and it might be due to the way that players load and/or the way that nitrox saved the player data.

**Comment by MrSpudd** [comment]
Yes, I can confirm this is a rather big issue, specifically in our experience with titanium. It can occasionally happen in the middle of a session with opening up your PDA Inventory and finding items vanishing before one's eye.

**Comment by NinjaPedroX** [comment]
Try this: Have someone look at their inventory when it has titanium then have a different player build a base piece that's made out of titanium. If the titanium disappears from the first person's inventory, that's your reason why.

**Comment by LeaderbotX400** [comment]
> Try this: Have someone look at their inventory when it has titanium then have a different player build a base piece that's made out of titanium. If the titanium disappears from the first person's inventory, that's your reason why.

that has also happened but I have also seen that sometimes a players full inventory will be wiped or swapped with a different players inventory the latter has only happened once so it might have been a one off bug

**Comment by NinjaPedroX** [comment]
> > Try this: Have someone look at their inventory when it has titanium then have a different player build a base piece that's made out of titanium. If the titanium disappears from the first person's inventory, that's your reason why.
> 
> that has also happened but I have also seen that sometimes a players full inventory will be wiped or swapped with a different players inventory the latter has only happened once so it might have been a one off bug

Swapped with another player's inventory? That's a new one...

One thing to keep in mind, though, is that inventories are currently tied to your playername, so changing that or using someone else's will result in losing/switching of inventory
