### ISSUE TITLE
QuickSlots are not persisted between reloads.

### ISSUE THREAD

**Issue by Exso12Ecesis** [SubnauticaNitrox/Nitrox#1393]
### Version
1.4.0.0 ALPHA

### Bug
The user's hotkeys are completely ignored between server reloads.

### Expected
The user's hotkeys should be persisted in to the save files.

### Steps to reproduce
1. Assign equipment to a hotkey.
2. Type /save in chat.
3. Restart the server.
4. Reconnect to the server.
5. Unexpected result occurs.

**Comment by Exso12Ecesis** [comment]
Since I'll probably be taking this bug next, since it's the next in line, I'll need to prepare the tools necessary to gather the information required to store this in the first place. More specifically, something like SetHotkey or something, I need a way to start parsing out the metadata in the C# binary to get the function names and stuff, but il2cppdumper (the tool I use to hack C# games with) requires a file called global-metadata.dat. I haven't done this Unity hacking crap since Rust came out, so it's been a while. Any better decent tools out there that can dump the instruction metadata or will Ghidra or something work against Unity? I tried looking at Subnautica in IDA, but it's not really meant for .NET analysis, it's meant more for x86 and RISC.

**Comment by Sunrunner37** [comment]
We use dnspy:
https://github.com/dnSpy/dnSpy

**Comment by Exso12Ecesis** [comment]
> We use dnspy:
> https://github.com/dnSpy/dnSpy

I'll tell you what, you C# guys and your open source, I'm really digging it so far. It takes me minutes to scan the program for vulnerabilities and problems, because I'm so used to dealing with obfuscation and virtualization and captured live binaries that have been dumped from raw memory. It's actually super nice to be able to read documentation on what these things do, and what name of fields are the developer gave them, and see change history. It's very refreshing, it almost feels too easy in a sense.  I used to be a die hard Microsoft fan in the early 2000s, but as IBM and HP and Oracle (At the time Sun Microsystems) kind of moved away from Microsoft towards Java, I had to follow with them if I wanted to stay relevant in the hacking space, as that's what my clients moved to. I have always preferred Windows as my OS of choice, but unfortunately require an Open Source OS for the work I do, for obvious reasons. But ironically, all my clients have always been on Windows based platforms and have been for years. Kind of weird they went for the open source cheaper version of Java, which was based on a lie that Sun would make these stupid JVM chips that would power the world, which is that stupid meme you see Java powering 6 million devices when you install the JDK. Awful. What a scam that was, I don't know how the SCE didn't sanction Sun for what they did. Oracle has become a lot better of a company in the recent years though, so has Microsoft. I was severely against ejecting Bill Gates, he did nothing wrong but be a super smart dude and amazing businessman, but Satya has taken the company in the right direction, I do believe open source to be the future, the problem is so does everyone else, and people are just slow to adopt, because they don't want to take the time to learn something new or some nonsense. Most of my clients ask me for Java work because it's what I have experience with on my resume, but I tell them I can do C# work, but nobody has ever taken me up on it. So I finally took the initiative myself and took a peak at how the other side is living. I have to say, the grass really is greener over here.

**Comment by Jannify** [comment]
Killzoms implemented a config file structure (like . properities or minecraft config file) on the server side which could be also used client side for something like this.

**Comment by Exso12Ecesis** [comment]
> Killzoms implemented a config file structure (like . properities or minecraft config file) on the server side which could be also used client side for something like this.

I thought about that before while working out a solution for #1401, but that would require connecting to the server PRIOR to handling the at rest file, which would occur after LoadSavedServers() is already called. If that is something we want to do going forward for client data, I think we should decide if we just want to use the flat file for storing IP/port/token combo, and then use the config file that's piped to the server for stuff that actually matters and will be used for active development/integration.

**Comment by Measurity** [comment]
@Exso12Ecesis You don't need to communicate with the server. The config API is in NitroxModel which is shared code, containing the config (de)serializer: `NitroxConfig`. Just need to define a type and let the serializer do its thing. You can take `ServerConfig` as an example but you don't need to communicate with the server *at all*.

**Comment by Exso12Ecesis** [comment]
> @Exso12Ecesis You don't need to communicate with the server. The config API is in NitroxModel which is shared code, containing the config (de)serializer: `NitroxConfig`. Just need to define a type and let the serializer do its thing. You can take `ServerConfig` as an example but you don't need to communicate with the server _at all_.

That is what I planned to do, I was going to duplicate the behavior in PersistedPlayerData to just work on the client side. I don't know how well known ProtoBuf is in the C# world, but in Java it's not in the systems I work with. TF2 used to use Google Prototype Buffers to communicate with the Steam API, which was actually very secure I found. But I didn't really mess with them very much. Is the format well understood? I think using that for the at-rest data will at least stop nosy teenagers from reading the file, they would have to actually put the effort in to parsing out a ProtoBuf file and then reading the GUID token, even if they can see our system. It wouldn't be very hard, but it fits with the security through obscurity model the team wishes to adopt.

**Comment by Measurity** [comment]
> Assign equipment to a hotkey.

I overlooked the steps, thought this was about hotkeys you can set in the game's settings. Recommend renaming this issue: "QuickSlots are not persisted between reloads." as that's what the game calls those equipment hotkeys.

> That is what I planned to do, I was going to duplicate the behavior in PersistedPlayerData to just work on the client side. I don't know how well known ProtoBuf is in the C# world, but in Java it's not in the systems I work with.

It's just a binary format. Java can be used too: https://developers.google.com/protocol-buffers/docs/javatutorial
Anyway, it should be saved on the server instead because server should know the inventory of players anyway. It would allow server admins predefining the quickslots before they join. And it prevents clients from messing around with what they have on quickslots that can impact gameplay on server.

**Comment by Exso12Ecesis** [comment]
Is this already handled by [https://github.com/SubnauticaNitrox/Nitrox/blob/0baaddb1e0a3596ad43da0390554ba819aa2a797/NitroxModel/DataStructures/GameLogic/ItemEquipment.cs](EquippedItemData)?

**Comment by Exso12Ecesis** [comment]
My friend stopped playing Nitrox, so my interest in the project is dwindling, I probably won't be taking this ticket next. For now, assume I'm not working on it.
