### ISSUE TITLE
Water purifier percentage completed not being persisted

### ISSUE THREAD

**Issue by Exso12Ecesis** [SubnauticaNitrox/Nitrox#1394]
### Version
1.4.0.0 ALPHA

### Bug
The percentage completion of the water purifier does not save between server reloads. 

### Expected
the percentage should be persisted. 

### Steps to reproduce
1. Build a water purifier. 
2. Wait for a discernible percentage to be displayed on the purifier’s tooltip. 
3. Type /save in to the chat
4. Restart the server. 
5. Reconnect to the server. 
6. Observe the percentages are now 0% for both water and salt.

**Comment by dartasen** [comment]
Duplicated of #129
