### ISSUE TITLE
Players cannot see other players inside seamoths when departing from a moonpool

### ISSUE THREAD

**Issue by RazzyFFA** [SubnauticaNitrox/Nitrox#1398]
### Version
 Nitrox ALPHA 1.4.0.0

### Bug
 Moonpools glitch Seamoths for multiplayer.

### Expected
 Seamoths in moonpools should be able to leave the moonpool normally, however, when playing multiplayer, and having multiple moonpools (2+) people won't see other people leave with the seamoth, leaving the player stuck inside the seamoth in the moonpool for other players. The player in the seamoth will be able to drive it however everybody else will only be able to see them inside the seamoth parked in the moonpool. This also causes another bug that kills players when they go around the moonpool (inside) when the user is in the seamoth.

See included screenshot:

![1](https://user-images.githubusercontent.com/77472878/104824872-c1971f00-58ba-11eb-9944-15f8ac85e6ee.png)

### Steps to reproduce
 
1. Start a multiplayer server
2. Build two moonpools
3. Get two seamoths, park them both in both moonpools.
4. Get a 2nd player to get inside a parked seamoth.
5. It will glitch out.

### Other details:
 
 
 No extra details for this glitch, screenshots provided above

**Comment by Exso12Ecesis** [comment]
I have confirmed this behavior on 1.4.0.0 ALPHA.

**Comment by romgerman** [comment]
Also sometimes seamoth dissapears with a player inside and when the player somes out you can't see seamoth anymore.

**Comment by Dayflare** [comment]
i can confirm this bug. Sometimes one player can't steer a seamoth, one time i tested one player couldn't enter a seamoth, another time a player could enter but couldn't control or steer the seamoth.

**Comment by mmccall0813** [comment]
any progress on this?

**Comment by Astar007** [comment]
Please fix it.
