### ISSUE TITLE
nitrox wont launch when I press multiplayer

### ISSUE THREAD

**Issue by Zaptron7** [SubnauticaNitrox/Nitrox#1399]
1.4.0.0
system 32 is blocking me from being able to change my subnautica route

was working just fine yesterday, i didn't restart or shut down my computer, tried it today and wouldn't
 launch

i open the launcher and the multiplayer button doesn't open the game

![Screenshot (7)](https://user-images.githubusercontent.com/77588529/104857252-bead2600-58dc-11eb-94d6-b752be2c2a7e.png)
This is the error i recieve if  i try to luanch the game

![Screenshot (10)](https://user-images.githubusercontent.com/77588529/104857254-c10f8000-58dc-11eb-84e4-0f4fb7e3ff99.png)
 this is the one if i try to change the file location, and after i get tht error the launcher crashes

**Comment by Exso12Ecesis** [comment]
Have you tried simply just running it as administrator? This error is complaining that it can't access a file, a simple privilege escalation should fix this,

**Comment by Zaptron7** [comment]
> Have you tried simply just running it as administrator? This error is c

that worked........ thank you, im upset at myself for not even trying it
