### ISSUE TITLE
Bioreactor Problems

### ISSUE THREAD

**Issue by EinLuigi** [SubnauticaNitrox/Nitrox#1404]
### Bug

let your friend build a Bioreactor than you see it. It is not 100% finished with constructing

### Expected

That it is constructed

### Other details:
![notfinished-bioreactor-problem-subnautica-nitrox](https://user-images.githubusercontent.com/62796561/105152372-5ee69300-5b07-11eb-9dcb-457d4ab86eee.PNG)

**Comment by Exso12Ecesis** [comment]
This is a duplicate of #1400.
