### ISSUE TITLE
Coffee machine can be used a second time while the first cup is still being brewed.

### ISSUE THREAD

**Issue by Exso12Ecesis** [SubnauticaNitrox/Nitrox#1405]
### Version
Latest master revision as of 1-20-2021 in JSON persistence mode.

### Bug
A user can acquire two cups of coffee with only a single brew period, by double clicking the coffee machine interface.

### Expected
The user should only be allowed to brew one cup of coffee at a time.

### Steps to reproduce
Build a coffee machine and double click the interface.

### Other details:
Sometimes this bug did not occur when first restarting the server, it sometimes requires waiting until a subsequent attempt is made for this bug to show itself.

**Comment by daufinsyd** [comment]
That's no bug, is it ? You can simply order two cups by pressing the button two times in a row, work same in reality (well I'm kind of a coffee amateur and didn't find any coffee machine not providing this king of feature :) ).

**Comment by NinjaPedroX** [comment]
I thought this was a feature in the base game. I remember being able to brew two cups at the same time when I played singleplayer.
Unless this was also a big that was fixed after that in the base game

**Comment by Jannify** [comment]
Yeah, it a game feature, I stumbled open it while working with sound-components (the coffee machine is the only one who has two of then...)
