### ISSUE TITLE
Nitrox simply wont work

### ISSUE THREAD

**Issue by BangBang1029** [SubnauticaNitrox/Nitrox#1408]
My friend and I are trying to play subnautica together, but when he lauches nitrox, and selects the multiplayer selection, the game just launches in normal singleplayer mode. he is running in administrator, and his account is the admin account. any ideas?

**Comment by Exso12Ecesis** [comment]
What platform are you playing on?

**Comment by AntalaFilip** [comment]
Did you try running it without administrator? That worked for my friend...

**Comment by Jannify** [comment]
This is not a help page it's an issue board. Just write something if you know it a common bug. Pls visit our discord for future help with your problem.
