### ISSUE TITLE
Bugged ladders

### ISSUE THREAD

**Issue by TheStyxo** [SubnauticaNitrox/Nitrox#1409]
### Version
Alpha 1.4.0.0

### Bug
The ladders look all weird when another player climbs them...

### Expected
The ladders should look normal

### Steps to reproduce
Climb up the ladder I assume

### Other details:
![image](https://user-images.githubusercontent.com/63962807/105470534-ae6fbf00-5cbf-11eb-83b2-c96d3a5447c2.png)

![image](https://user-images.githubusercontent.com/63962807/105470613-c8a99d00-5cbf-11eb-9d50-ed000720c1f9.png)

Edit: He was using a version that was not purchased... But is there a fix for players who have purchased? I have purchased the game but it still appears on my side...

Sooo this bug occurs whenever a player(that has not purchased the game) climbs up any ladders... Also you can't deconstruct anything that is attached to the red thing...

**Comment by TheStyxo** [comment]
![image](https://user-images.githubusercontent.com/63962807/105474575-643d0c80-5cc4-11eb-9deb-79560c9f8d18.png)

**Comment by Exso12Ecesis** [comment]
This is a duplicate of #1400.

**Comment by TheStyxo** [comment]
https://github.com/SubnauticaNitrox/Nitrox/issues/1400
