### ISSUE TITLE
Compile error, retarded question what am I doing wrong?

### ISSUE THREAD

**Issue by jonasuouo** [SubnauticaNitrox/Nitrox#141]
1>------ Build started: Project: NitroxReloader, Configuration: Debug Any CPU ------
1>C:\Users\Jonas\Desktop\Nitrox\NitroxReloader\Reloader.cs(49,41,49,45): error CS0117: 'ReloaderSettings' does not contain a definition for 'PATH'
1>C:\Users\Jonas\Desktop\Nitrox\NitroxReloader\Reloader.cs(69,87,69,91): error CS0117: 'ReloaderSettings' does not contain a definition for 'PATH'
2>------ Build started: Project: NitroxClient, Configuration: Debug Any CPU ------
3>------ Build started: Project: NitroxServer, Configuration: Debug Any CPU ------
4>------ Build started: Project: NitroxPatcher, Configuration: Debug Any CPU ------
5>------ Build started: Project: ClientTester, Configuration: Debug Any CPU ------
6>------ Build started: Project: NitroxTest, Configuration: Debug Any CPU ------
========== Build: 0 succeeded, 6 failed, 2 up-to-date, 0 skipped ==========

**Comment by MarijnS95** [comment]
It looks like for some reason the autogenerator job hasn't fired.

**Comment by MarijnS95** [comment]
Never mind - I found a different issue.

Your error is showing that it can't find a field named `PATH`, but the field is actually called `Path`. Make sure you have checked out the master branch (and pull for the most recent commits) with a clean working tree.

**Comment by MarijnS95** [comment]
Looks like this issue hasn't had any comments in the past 6 days, I assume it's resolved. You can always reopen it if need be.
