### ISSUE TITLE
Freeze every 15 sec

### ISSUE THREAD

**Issue by Oryx84** [SubnauticaNitrox/Nitrox#1412]

**Comment by Coding-Hen** [comment]
Having some information here would be useful to understand what you are doing that is facing this. However I suspect it is when you first time you go into a new area and it has to generate which is just normal nitric behaviour and not a bug. I'm going to close this, reopen if this is not the case and you have more information.

**Comment by Oryx84** [comment]
there are no more details i play nitrox normally but every 15 seconds i have a little freeze and it's really annoying whereas when i play subnautica there is no freeze and the game is smooth
