### ISSUE TITLE
[Command] /warp is bugged in cyclops

### ISSUE THREAD

**Issue by dogdie233** [SubnauticaNitrox/Nitrox#1414]
### Version
Alpha 1.4.0.0

### Bug
When I enter the Cyclops, the position becomes relative to the Cyclops.
This will affect /warp

### Expected
After entering the Cyclops, the position is still relative to the world.

### Steps to reproduce
1. Enter Cyclops, use /whois to get position. (Now relative to the Cyclops)
2. Drive Cyclops, use /whois to get position. (now relative to the world)

### Other details:
![Position before drive Cyclops](https://user-images.githubusercontent.com/42267840/106345633-9c5bd500-62ec-11eb-8dc0-e74d71121861.png)
![Position before drive Cyclops](https://user-images.githubusercontent.com/42267840/106345635-9e259880-62ec-11eb-9b1c-d1d86deae95c.png)

**Comment by Jannify** [comment]
Position being relative to the cyclops is from UWE. So just `/warp` can't handle it when a player is steering a cyclops.

**Comment by dogdie233** [comment]
> Position being relative to the cyclops is from UWE. So just `/warp` can't handle it when a player is steering a cyclops.

But the expected behavior is that playerA is in the cyclop (non-driving state), and playerB using "/warp playerA" should be teleported to the Cyclops instead of near (0,0,0)

Maybe you should use transform.position to get the coordinates instead of transform.localPosition

**Comment by Jannify** [comment]
Yeah that would be the expected result. Just wanted to clarify what the root of the problem is.

**Comment by Coding-Hen** [comment]
Maybe we need to add a check to the /warp to check if the player is inside a vehicle
