### ISSUE TITLE
Check installation path based on "libraryfolders.vdf"

### ISSUE THREAD

**Issue by Moerty** [SubnauticaNitrox/Nitrox#142]
Check all Steam library folders based on the file "libraryfolders.vdf".
Defaultpath: C:\Program Files (x86)\steamapps\libraryfolders.vdf

File content:
```
"LibraryFolders"
{
	"TimeNextStatsReport"		"123456"
	"ContentStatsID"		"123456"
	"1"		"G:\\SteamLibrary"
	"2"		"A:\\SteamLibrary"
}
```

**Comment by nesrak1** [comment]
Steam finder already checks library folders.vdf, not sure what the issue is here
