### ISSUE TITLE
Problem saving world (Using Windows 10 Subnautica)

### ISSUE THREAD

**Issue by damien1406** [SubnauticaNitrox/Nitrox#1422]
### Version

Latest Version

### Expected
I expected a save since autosave is on.
### Steps to reproduce
Run this using the windows 10 application and let it autosave then restart the server, telling you an error. "Could Not Load World, creating a new one."

### Platform
Windows 10 Subnautica
### Error
![image](https://user-images.githubusercontent.com/78812751/107442129-591f1480-6aeb-11eb-8649-a55bef6d7cdd.png)

### Attempts to fix issue
I tried to get the world I backed up into the worlds folder. I deleted the worlds folder, set my new one in there. After I have done that, I launch the server, and it ignores my new placed world and continues the same issue.

**Comment by Coding-Hen** [comment]
Did you login to the server or was this just start, save, close?

**Comment by damien1406** [comment]
Yeah, I login in to the server, played for around 20-45 minutes, then I leave, then I stop the server.

**Comment by damien1406** [comment]
It takes a while for you to dump Subnautica if you have it.

**Comment by damien1406** [comment]
Are you their?

**Comment by TheLxkas** [comment]
I recommend heading to the discord server and asking for support there
https://discord.gg/E8B4X9s

**Comment by dartasen** [comment]
No new informations about this, I'm closing it for now
