### ISSUE TITLE
my friend can't see any entities

### ISSUE THREAD

**Issue by nonolapatato** [SubnauticaNitrox/Nitrox#1423]
### Version
1.4.0.0

### Bug
my friend can't see any entities when i host a server and I can't see any entities when he host the server (we use hamachi )

### Steps to reproduce
i just create my hamachi nitrox server and this hapen

### Other details:
we use hamachi for the server and i found this in log
Player nono has taken over simulating 338d8937-32a7-2a07-4de3-85339cb6cd32
18:32:09.855 [Server][INF] World state saved.
18:32:17.375 [Server][INF] Spawning 304 entities from 88 spawn points in batch [NitroxInt3 - 10, 18, 10]
18:32:17.440 [Server][INF] Spawning 850 entities from 109 spawn points in batch [NitroxInt3 - 10, 18, 11]
18:32:32.527 [Server][INF] Spawning 472 entities from 105 spawn points in batch [NitroxInt3 - 10, 18, 9]
18:32:32.598 [Server][INF] Spawning 889 entities from 151 spawn points in batch [NitroxInt3 - 10, 17, 11]
18:32:49.570 [Server][INF] Player JObe has taken over simulating 6b59e9e8-a5e7-b84e-07b1-9c91e41bfbba
18:32:49.570 [Server][INF] Player JObe has taken over simulating ef30572e-35af-530d-6f7b-abb8c21ee731

**Comment by TheLxkas** [comment]
I recommend heading to the discord server and asking for support there
https://discord.gg/E8B4X9s
