### ISSUE TITLE
Multiplayer button is missing

### ISSUE THREAD

**Issue by Nobowolf** [SubnauticaNitrox/Nitrox#1424]
### Version

 alpha 1.4.0.0 

### Bug
Start the game and i don't have a multiplayer button 

### Expected
 I expect the button to be there.

**Comment by Nobowolf** [comment]
I have reinstalled the launcher mutiple times, donwloaded int multiple times, and nother works.

**Comment by Measurity** [comment]
Cannot reproduce this issue. Possibly anti virus causing issues. Check Player.log file at `%appdata%\..\LocalLow\Unknown Worlds\Subnautica` and/or upload it here for errors.

**Comment by noctdark** [comment]
Go to your Subnautica install location, open the folder "Subnautica Data" and delete the folder named "Managed".

Go to the Steam Library, find Subnautica then right click Properties, then go to LOCAL FILES and VERIFY INTEGRITY OF GAME FILES

TRY THIS. 
https://nitrox.rux.gg/wizard/steam/update/step-2

**Comment by Chrinsieboy** [comment]
Still does not work

**Comment by Jannify** [comment]
For assistance in problem regarding Nitrox pls visit our discord https://discord.gg/E8B4X9s
