### ISSUE TITLE
Grav Trap bug

### ISSUE THREAD

**Issue by Nikos2k** [SubnauticaNitrox/Nitrox#1426]
My friend became a grav trap after throwing away one, no it fixed after 2 restart's but it was cumbersome![unknown-1.png](https://user-images.githubusercontent.com/59316298/108641743-4d473100-74a1-11eb-9ea9-94d61a735bd1.png)![unknown.png](https://user-images.githubusercontent.com/59316298/108641756-5801c600-74a1-11eb-9c0c-b6b63c5da0b4.png)

**Comment by Gangsteri** [comment]
Dude thats not a bug its more of like a "feature".

**Comment by Nikos2k** [comment]
> Dude thats not a bug its more of like a "feature".

Unless the robo-spiders from aurora are attacking you or leeches or even stalkers

**Comment by Measurity** [comment]
Closing as there are no reproducible steps in this issue so we can't fix it.
