### ISSUE TITLE
Seamoth can go as deep as you want

### ISSUE THREAD

**Issue by LightForerunner** [SubnauticaNitrox/Nitrox#1427]
### Version
1.4.0.0

### Bug
The Seamoth doesn't suffer from depth damage (max is 200m, I can go as deep as I want (the deeper I went was 1100m I think) without suffering any damage.

### Expected
The Seamoth has to lose HP when I go deeper than its limit.

### Steps to reproduce
Just take the Seamoth and go wherever you want, I always have this bug.

**Comment by TheClockTwister** [comment]
Can confirm this with v1.4.0, weather you spawn a seamoth or construct it by yourself, it's invulnerable to depth damage.

**Comment by TheClockTwister** [comment]
This bug has been fixed in eee5183832bb7270d98fa1e92d6287033d4c2770  and I can confirm that it works with the latest commit (27118286ae5f7db695394508c5ce2248ea405b65). Just wait for the next release  :)
