### ISSUE TITLE
The exe NitroxLauncher is not running and nothing is happened

### ISSUE THREAD

**Issue by vcordonnier** [SubnauticaNitrox/Nitrox#1429]
Hello

After unzipped the Alpha 1.4.0.0.zip file (for my windows environnement), I click on the file "NitroxLauncher.exe" with the administrator rights. But, Nothing is coming. I cannot go to the step 4 : "Click Options, click Change and then choose the folder you have Subnautica installed into" 

When I open the file "NitroxServer-Subnautica.exe" I guess this is the launcher log, there is an error inside, see the screenshot below:

![exelog](https://user-images.githubusercontent.com/79966455/109773831-ee4f8d80-7bff-11eb-9374-4696853f31a1.jpg)
Could you please help me to resolve this issue ?
Thanks

Regards
Veronique

**Comment by TheLxkas** [comment]
If you wouldn't mind I think it would be easier to sort your issue out on our support discord.
https://discord.gg/E8B4X9s

**Comment by Measurity** [comment]
Are you using a third party anti virus (Windows Defender is OK)? Add an exclusion to it for Subnautica then launch Nitrox again. If you know of any other software that might interrupt Nitrox doing its thing then disable that too.
