### ISSUE TITLE
saving

### ISSUE THREAD

**Issue by jannesvh2** [SubnauticaNitrox/Nitrox#143]
Hi.  Every time I join I start over with the intro followed by a fresh spawn with empty inv on the pod.  Am I missing something or is saving from the server not implemented yet?

Based on this issue it might be working (partly) https://github.com/SubnauticaNitrox/Nitrox/issues/121

and also based on the trello card: https://trello.com/c/eNxkjVZM/3-save-file-sending it should atleast be working partly.

So any idea why it doesnt work for me at all, its as if I join as a complete new user every time.

Thanks

**Comment by MarijnS95** [comment]
Not yet, it's on our list though: https://github.com/SubnauticaNitrox/Nitrox/issues/112
