### ISSUE TITLE
Nitrox Alpha 1.4.0.0 "None" Construction Piece

### ISSUE THREAD

**Issue by Soniczac7-Games** [SubnauticaNitrox/Nitrox#1431]
### Version
Nitrox Alpha 1.4.0.0

### Bug
Me and a friend was building a base in the inactive lava zone and we had already built 2 moonpools and 3 multipurpose rooms and a bioreactor and then I was heading out of my moonpool when I noticed that the wall was partially deconstructed so I got out my builder tool and it said "None" so I tried to construct it but it kept reappearing. Then I tried to deconstruct it and then it disappeared instantly.

### Expected
The construction of "None" shouldn't appear

### Steps to reproduce
I actually have no clue how it happened

### Other details:
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/6083654/Player.log)
![unknown](https://user-images.githubusercontent.com/70811525/109965204-8f187880-7ce6-11eb-87f9-fe402a32d07c.png)

**Comment by TheClockTwister** [comment]
I've observed many cases in which a base was fine, until you add a bioreactor to it. Most of the time, the reactor is partially constructed and often floats outside the base. Sometimes this state of partial construction spreads to other components.
Like in #1404 (or #1400 in general).

@Soniczac7-Games What's the status now after you "removed" it? Has the issue resolved after restarting/re-logging or does it persist with the new piece?
