### ISSUE TITLE
Seamoth colors not synced

### ISSUE THREAD

**Issue by Blinkle1** [SubnauticaNitrox/Nitrox#1434]
Seamoth colors are just not synced

**Comment by Jannify** [comment]
Could you provide more details (take a look on the issue template)? As far as I know colors and names should be synced.

**Comment by Exso12Ecesis** [comment]
I have confirmed the behavior. If you build a new Seamoth then edit its colors, nobody else but the player who made the change can see it. However, if you save and restart the server, everyone else will see the color change.

**Comment by dartasen** [comment]
Moved to #1470
