### ISSUE TITLE
How to save - load multiplayer game

### ISSUE THREAD

**Issue by JulianKraiz** [SubnauticaNitrox/Nitrox#144]
Hello,

I'm sorry if this has already been answered out, but I just can't find m way around it.

When I start the the  game ,after the Nitrox server, I can join, but I can't find how to make the server instance load a savegame.
From what I've read, this is possible, but I can't find how.
If you have an idiot proof guide on how to do that I'd take it.

Any help will be greatly appreciated.

**Comment by MarijnS95** [comment]
The same question has just been asked and answered here: https://github.com/SubnauticaNitrox/Nitrox/issues/143.
