### ISSUE TITLE
restart command deletes world

### ISSUE THREAD

**Issue by ChildishGiant** [SubnauticaNitrox/Nitrox#1448]
### Version

1.4.0.0

### Bug
Just lost a 15 hour save because apparently `restart` doesn't restart the server, it deletes the entire save.

### Expected
Restart to restart the server.

### Steps to reproduce
run `restart` on the server.

**Comment by Measurity** [comment]
It should not have done that, did you get anything from the server when you restarted it that indicated this?
If you still have the save file, that would be useful to know what kind of data is/was there.

**Comment by Measurity** [comment]
Fixed next release.
