### ISSUE TITLE
[MS-Store] No creatures in the world

### ISSUE THREAD

**Issue by Yanzzzx** [SubnauticaNitrox/Nitrox#1449]
### Version
1.4.0.0

### Bug
after installing the nitrox mod, no creatures were spawned and there isnt a cutscene after opening the world

### Expected
have all fishes and leviathans in game

### Steps to reproduce
start the server > start subnautica > start multiplayer

### Other details:
 i'm using the Microsoft Store subnautica 
I think is important to say: the singleplayer has all the creatures

[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/6446827/Player.log) -->

**Comment by Jannify** [comment]
Can you go to our discord and ask there for help? Maybe out support stuff can fix it for you.

**Comment by Yanzzzx** [comment]
> Can you go to our discord and ask there for help? Maybe out support stuff can fix it for you.

I asked in the discord, one guy said about the firewall, I disabled and nothing changed

**Comment by isnew62** [comment]
Same here no creatures and nothing to loot

**Comment by Yanzzzx** [comment]
> Same here no creatures and nothing to loot

they helped me in discord, the solution is:

8. If you wanna host AssetBundles and SNUnmanagedData copy these folders and paste them into StreamingAssets folder
keep them where they are at but make copies in the StreamingAssets folder

copy the folder, not the files in

**Comment by isnew62** [comment]
Thank you man you made my day :)
