### ISSUE TITLE
[Client] "NullReferenceException: routine is null" in IngameMenu_QuitSubscreen_Patch.Prefix

### ISSUE THREAD

**Issue by Jannify** [SubnauticaNitrox/Nitrox#1455]
### Version
master branch

### Steps to reproduce
Start a game of Nitrox and close it with the ingame button or the window "x".

### Other details:
`IngameMenu_QuitSubscreen_Patch.Prefix` is trowing a `NullReferenceException: routine is null` error when closing the game. Keep in mind that it's an unity error and so properly just be found in `Player.log`.

**Comment by Measurity** [comment]
I think we should ignore this until we can remove the quit patch and allow people to go back to main menu again. For this to happen we need to properly cleanup any Nitrox data/monobehaviours when disconnecting on client.
