### ISSUE TITLE
Cyclops: other players fly away if not seated.

### ISSUE THREAD

**Issue by psychogmg** [SubnauticaNitrox/Nitrox#1456]
### Version
ALPHA 1.4.0.0

### Bug
 In multiplayer mode, my character flies off the map if we are both in the cyclops. Once, while I was waiting for my partner, I suddenly flew off the map with the boat. The other player, on the other hand, saw that I was still there.

### Steps to reproduce
 You have to travel together in the cyclops.

**Comment by Measurity** [comment]
Known issue, has to do with game physics not needing to handle multiple players until Nitrox. Make a chair for other people in the cyclops, let them site down, then control cyclops.
