### ISSUE TITLE
What i am suposed to do?

### ISSUE THREAD

**Issue by Catupiry** [SubnauticaNitrox/Nitrox#146]
I was compiling in visual studio, first problem, directory not correct in DevVars.Target, OK, Fixed, now HARMONY DON'T LOAD FOR ME, 1. Taked the github, 2. Added the harmony project and left only the harmony.csproj, OK, Too good for me now, but when i try to compile, BAM, 119 errors each named : 

The name of the type or of namespace "Harmony" can't be encountered (is missing a directive using or a reference of assembly?)	 

or HarmonyInstance, I don't know what to do from now, lack of youtubers that actually help with the install with the mod or give a compiled link; can someone help me?

**Comment by Catupiry** [comment]
I am sorry, but yeah, i can make some things in Visual studio like compiling, BUT, i cant know what to do, it's a problem for me, because me and my friends whould go play, and i am the only that makes efforts to try to make the mod work, if i fix this error i would like to ask to release the fixed version on youtube to people play while it isn't released

**Comment by Sunrunner37** [comment]
The mod is not released yet and is only meant for developers.  It is constantly in a broken state that is not ready for public use.  Please wait for a public release.
