### ISSUE TITLE
[Player] Spawning far away when relogging

### ISSUE THREAD

**Issue by dartasen** [SubnauticaNitrox/Nitrox#1465]

**Comment by Measurity** [comment]
Afaik we assume this is physics pushing the player away because it presumably spawns partly inside the escape pod. Might be enough to set player rigidbody to isKinematic/freeze while world is loading in. Correct me if I'm wrong.

**Comment by dartasen** [comment]
> 
> 
> Afaik we assume this is physics pushing the player away because it presumably spawns partly inside the escape pod. Might be enough to set player rigidbody to isKinematic/freeze while world is loading in. Correct me if I'm wrong.

Can be the first we might need to look into indeed, but might be also related to weird vehicles position broadcasting (cyclops ?)

**Comment by Jannify** [comment]
Fixed with #1679
