### ISSUE TITLE
[World] Add sync for blueprint progress

### ISSUE THREAD

**Issue by dartasen** [SubnauticaNitrox/Nitrox#1467]
### Steps to reproduce
- Start scanning some blueprints without completing it
- Relog
- Try to scan the same blueprint
- The progress will be lost

**Comment by tornac1234** [comment]
Can someone assign this issue to me ? (I already made the fix but I need more time to improve it)

**Comment by dartasen** [comment]
@tornac1234 Sure, thank's for working on it ! 😄 
PS : you can join also join our discord so we can give you access to dev channels

**Comment by Measurity** [comment]
Fixed with PR #1624
