### ISSUE TITLE
wreck's not spawning, or partially spawning

### ISSUE THREAD

**Issue by pkTux** [SubnauticaNitrox/Nitrox#1468]
### Version

1.4.0.0
### Bug
wrecks sometimes fail to spawn  & can be swam thru, other times partially spawn

### Expected
wreck exists

### Steps to reproduce
[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/6462611/Player.log)

sometimes happens when you travel great distances, from reconnect point.

### Other details:
windows 10.

**Comment by 1Kr0noZ1** [comment]
Can confirm this one. Sometimes wrecks are stretched out vertically over significant depths. Where it should be on the sea floor, some parts may actually be there with the rest of the wreck being in pieces and floating above in a disconnected mess (meaning if it's one of the wrecks you are supposed to get into, sometimes the doors are just free floating and the actual interior bits are present in the vicinity but blocked by invisible walls, loot also doesn't spawn in properly). It mostly seems to happen to wrecks far away from the initial spawn location (making it hard to notice at first) but can persist through server restarts regardless of players being in the area on spawn or not.

**Comment by Mephisto090** [comment]
I can confirm that too. Makes it almost impossible to play as it is difficult to unlock new things

**Comment by AwesomenessZ** [comment]
I've found that using the cheat freecam, moving a little, and typing freecam again to deactivate fixes the position of the wrecks
