### ISSUE TITLE
Pipes that were connected are lose when rejoining server

### ISSUE THREAD

**Issue by Tactical-Shrubbery** [SubnauticaNitrox/Nitrox#1482]
Me and a friend had made a pipe network the day before, the world state was saved multiple times during the process. When we loaded up today, all the pipes were gone. It's not a huge deal for us, thought I would just let the team know

**Comment by killzoms** [comment]
Technically not gone, they were turned into items.

**Comment by Tactical-Shrubbery** [comment]
If the items were dropped into the world, we didn't see them
