### ISSUE TITLE
Seamoth/Prawn/(Maybe others?) sounds playing for all players

### ISSUE THREAD

**Issue by MFuell2** [SubnauticaNitrox/Nitrox#1483]
### Version
Alpha V1.4.0.0

### Bug
Seamoth sounds such as the turbines, the lights, and the Prawn Suit sounds such as walking, and the jump jet are shared among all players

### Expected
The expectation is for the sounds to be localized on each player

**Comment by Jannify** [comment]
Thank you for taking the time to look if this issue was already created or is already done (hint it is) :D
