### ISSUE TITLE
cannot start subnautica from the xbox app on pc

### ISSUE THREAD

**Issue by sfggg** [SubnauticaNitrox/Nitrox#1485]
### Version
latest
1.4.0.0

### Bug
cannot start gamepass subnautica on pc

### Expected
cannot start multiplayer and singleplayer

### Steps to reproduce
download subnautica from the xbox app on pc

**Comment by TheLxkas** [comment]
this is not a bug, the gamepass version needs extra setup steps. If you need help with it, I recommend you ask for it on our discord server.

**Comment by Coding-Hen** [comment]
Beat me to it. Check it out here: https://discord.com/invite/E8B4X9s
