### ISSUE TITLE
Ctrl + C is closing the server

### ISSUE THREAD

**Issue by Jannify** [SubnauticaNitrox/Nitrox#1489]
### Bug
When pressing `Ctrl+C` in the server console it stops the server

### Expected
It should clear the line with possible entered commands like in normal command-line-interfaces

### Steps to reproduce
Start the server, type something and press `Ctrl+C`

**Comment by Measurity** [comment]
Good catch, should be `CTRL+D` instead. `CTRL+C` should cancel command.

**Comment by Xaekai** [comment]
FYI: CTRL-C typically sends `SIGTERM` from most console emulators on Linux, which I would _expect_ to generally terminate whatever is running. Only bring this up because you mentioned "Linux systems".

**Comment by pavlukivan** [comment]
Ctrl+C isn't intended for clearing the line at all. That said, some REPLs handle SIGTERM by stopping the currently running code instead of exiting the REPL (which has the side effect of just cancelling the command if you didn't enter it yet). That does make sense for REPLs, but I'm not sure it makes sense in this case, as there's no user-inputted code to cancel.

**Comment by Measurity** [comment]
What do you guys think of using these hotkeys?

```
CTRL+C: Cancel command/clear unsubmitted command text
CTRL+D: Close server
Escape (windows only): Same as CTRL+C.
```

**Comment by killzoms** [comment]
So used to using Ctrl+C to exit any running code, I would say at least make it Ctrl+T, however thats just me speaking from using that shortcut in Minecraft for Computercraft

**Comment by Measurity** [comment]
We'll probably should make it configurable but just discussing defaults for now.

**Comment by dartasen** [comment]
> 
> 
> What do you guys think of using these hotkeys?
> 
> ```
> CTRL+C: Cancel command/clear unsubmitted command text
> CTRL+D: Close server
> Escape (windows only): Same as CTRL+C.
> ```

Sounds good

**Comment by Xaekai** [comment]
CTRL-D typically sends EOF, making it a logical sane default to exit a REPL.

I would also suggest, if feasible, CTRL-C twice should as well. In other words CTRL-C, when the readline is already empty, should terminate.

**Comment by Squall-Leonhart** [comment]
the default should be CTRL-C in line with every other server console ever.

control C has never cleared a line anywhere.

**Comment by pavlukivan** [comment]
> control C has never cleared a line anywhere.

it clears the line in posix-compatible shells, as well as stuff like python, and probably cmd.exe, which probably confused the author

**Comment by Squall-Leonhart** [comment]
not even in cmd.exe

**Comment by Measurity** [comment]
![Qk4eq1WB95](https://user-images.githubusercontent.com/1107063/131325199-24444afa-53c3-4331-8ee2-16b5b5163b4d.gif)

@Squall-Leonhart Used CTRL+C on windows.

**Comment by Squall-Leonhart** [comment]
Thats not doing what you think its doing.
