### ISSUE TITLE
Cannot Start Nitrox Server

### ISSUE THREAD

**Issue by TheMysticle** [SubnauticaNitrox/Nitrox#149]
Hello and thank you for working on this amazing mod. I have installed it successfully and I have the multiplayer button in my game, but when I try to start the nitrox server it gives me this error.
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
Anything I can do?
Here is the entire CMD window:
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.
   at NitroxServer.GameLogic.EntitySpawner.GetDataFiles(String& lootDistributions, Dictionary`2& worldEntityData) in C:\Users\olikr\Nitrox\NitroxServer\GameLogic\Spawning\EntitySpawner.cs:line 166
   at NitroxServer.GameLogic.EntitySpawner..ctor() in C:\Users\olikr\Nitrox\NitroxServer\GameLogic\Spawning\EntitySpawner.cs:line 31
   at NitroxServer.Communication.Packets.PacketHandler..ctor(PlayerManager playerManager, TimeKeeper timeKeeper, SimulationOwnership simulationOwnership) in C:\Users\olikr\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs:line 26
   at NitroxServer.Server..ctor() in C:\Users\olikr\Nitrox\NitroxServer\Server.cs:line 17
   at NitroxServer.Program.Main(String[] args) in C:\Users\olikr\Nitrox\NitroxServer\Program.cs:line 14
Thanks in advance

**Comment by MarijnS95** [comment]
The error message tells you what to do:

> ```[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.```

**Comment by TheMysticle** [comment]
> 
The error message tells you what to do:

**Comment by TheMysticle** [comment]
Sorry about that so do I just copy resources.assets into server folder?
Also the error before that tells me my game isn't installed
Thanks

**Comment by TheMysticle** [comment]
When I copy resources.assets into the subnautica folder I get this error: 
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Loading batch data...
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] E: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Could not locate subnautica root

**Comment by MarijnS95** [comment]
We had a little discussion and looked into the code, and it turns out that the fallback path for when Steam can't be found (which is a legitimate usecase when running the server application on a separate machine that doesn't have the game installed) causes incorrect log messages to be printed. More importantly, this fallback only applies to `resources.assets`, the mandatory `batch` files are not provided with such a fallback and prevent the server from starting.

For now, you can only use the server application on a machine with Subnautica installed through Steam, until we get to fixing this.

**Comment by MadMaxOfYore** [comment]
Closing this issue as the desired functionality is way out of scope for any iterations in the foreseeable future. We need to get focus on a stable server before we try and deal with the logistics of running the server app on a separate, dedicated machine.

**Comment by MarijnS95** [comment]
@MadMaxOfYore I do think that this is in the scope of the foreseeable future, as running a server on a separate machine is a very real usecase. The only limiting factor is a tiny bug, which can be fixed simultaneously with the settings-file. That feature is required for our first alpha release anyway.
