### ISSUE TITLE
Disable server pause when no players connected?

### ISSUE THREAD

**Issue by Joe-Capewell** [SubnauticaNitrox/Nitrox#1495]

**Comment by Coding-Hen** [comment]
What would be the advantage of doing this?

**Comment by Joe-Capewell** [comment]
I have problems with plant growth resetting after leaving the server. Seems to be caused by the automatic pausing.

**Comment by Coding-Hen** [comment]
This is not the case it's due to the plants not being persistently saved, see #1341 it will be fixed next release
