### ISSUE TITLE
No creatures/fish for other (non-host) players

### ISSUE THREAD

**Issue by ScottDylan22** [SubnauticaNitrox/Nitrox#1500]
Well, I'm using version 1.4.0.0 of Nitrox. The problem is this, I don't know if more People are facing it or have already or have, I use Hamachi, Me and my Friend connected in the same room and everything worked out so far, then after hours of trying we managed to log into the server together from (subnautica) we entered was stabilized and it worked, But, the problem started when we jumped into the sea, It was kind of okay for me but for him, he didn't see any creatures in the sea, there was only an empty ocean, then we tested him as the host of the server, then I suffered the same problem as his, I couldn't see any creatures in the Ocean. If anyone who has been through this can help or know how to resolve this issue, please help me resolve this, I really appreciate it.

**Comment by dartasen** [comment]
This is related to Hamachi setup, we can't really do anything about it, if you still have that issue, you can ask help on our discord.
I'm closing this one
