### ISSUE TITLE
Missing ladder, and plants become un-grown every time by going back into server.

### ISSUE THREAD

**Issue by HymenSlayer69** [SubnauticaNitrox/Nitrox#1501]
### Version
1.4.0.0

### Bug
1. The ladder keeps disappearing every time I return to the server, even after saving multiple times before going offline.
2. My full-grown plants (e.g. lantern tree, creepvines, and etc.) keep returning back to their growing stage every time I return to the server as well. 

### Expected
1. ladder is supposed to stay in the exact position without disappearing
2. Full-grown plants are supposed to remain fully grown

### Steps to reproduce
By saving, shutting down the server, and then returning back to the server

### Other details:
I am using hamachi 
Don't seem to have any errors in the player log

**Comment by Coding-Hen** [comment]
Thanks for the report. I do think these are covered already though. The ladder bug is within #1400 and the plants sync has already been merged and will be in the next release #1341
