### ISSUE TITLE
Cannot enter empty seamoth, "another player is using it".

### ISSUE THREAD

**Issue by itsmeow** [SubnauticaNitrox/Nitrox#1504]
### Version
Master branch build of bdf39f8895b0dc17f451f8ff88536a43851f1343 (latest at time of creation)

### Bug
An empty seamoth on the server, neither of the only two players can enter it as "Another player is interacting with this object". Moving away does not fix it. One player logging out seems to fix it, but as soon as they log in it stops working again.

### Expected
Should be able to enter an empty seamoth

### Steps to reproduce
1. Build seamoth while two players are on
2. ???
3. Try entering seamoth while other player is online

**Comment by dartasen** [comment]
You should try to clarify the steps to reproduce this bug first

**Comment by itsmeow** [comment]
The steps don't really exist, plus I'll be fixing this myself. It just seemed to happen.

**Comment by itsmeow** [comment]
Can't seem to reproduce this, even on the original server, original versions. Not sure what was happening then.
