### ISSUE TITLE
Scanable items

### ISSUE THREAD

**Issue by KBTKraft** [SubnauticaNitrox/Nitrox#151]
None of the randomly spawning items are there is this a known issue or is it just my game

**Comment by al-darwish** [comment]
U mean blueprints?

**Comment by KBTKraft** [comment]
Yeah the items for the blueprints

**Comment by Alberto247** [comment]
Just your game, are you sure that there are no errors while launching the server?

**Comment by KBTKraft** [comment]
Yeah I am sure i have cheeked all the places i can think of Where else should i be looking

**Comment by MarijnS95** [comment]
From the top of my head I can't remember seeing code that explicitly disables these elements. I do know for sure though that these items are not synced through the server yet. You could say it's a `known missing feature`, not a bug.

**Comment by MadMaxOfYore** [comment]
Hey @MarijnS95, do we have a story in the backlog to address this? I just took a peak and didn't see it anywhere, but it may be implicitly captured in one of the other cards. I'll create a card and close this issue if that needs to happen.

**Comment by MarijnS95** [comment]
@MadMaxOfYore I can't find it either, and like I mentioned I can't remember explictly disabling these from spawning - work must've been done on it in some way, or other patches affect the spawning of said items. Feel free to create a new card.

**Comment by MadMaxOfYore** [comment]
We've capture this work item. Feel free to check in on progress periodically at #161 

Thanks,
-MadMax
