### ISSUE TITLE
Reduce VehicleColorChange packets while selecting color

### ISSUE THREAD

**Issue by Jannify** [SubnauticaNitrox/Nitrox#1524]
We are currently sending a `VehicleColorChange` packet each time the cursor moves a pixel (at least for the vehicle upgrade console). To reduce bandwidth we should use the "Done" button and/or leaving the upgrade console.

**Comment by Coding-Hen** [comment]
It does cause a lot of unnecessary packets but does it not give a little bit of an engaging player experience if they can see other players changing the colours rather than it just snapping to another colour?

**Comment by dartasen** [comment]
Yeah, I think it will reduce the player experience but we are also hammering the server with those packets, so maybe we should just add a treshold like for player stats and player movements
