### ISSUE TITLE
Multiplayer not launching

### ISSUE THREAD

**Issue by DaveWasAlsoThere** [SubnauticaNitrox/Nitrox#1525]
### Version
1.4.0.0

### Bug
Multiplayer not launching
https://imgur.com/a/8o2jGdJ

### Expected
Game launches

### Steps to reproduce
Downloaded and extracted the .zip file, opened NitroxLauncher.exe, pressed "play multiplayer" button

**Comment by Measurity** [comment]
Is the path correct in nitrox launcher? Here's mine (yours will be different but should also point to where you have Subnautica).
![image](https://user-images.githubusercontent.com/1107063/125869789-be02a8ee-ec3d-43ee-924f-49f9af389532.png)

**Comment by DaveWasAlsoThere** [comment]
Hi @Measurity !
Mine doesnt seem to point anywhere, and I cant find the Subnautica files
![image](https://user-images.githubusercontent.com/87504211/125871052-26da04bf-e9d8-4952-8614-5ffa03d38bb9.png)

**Comment by Measurity** [comment]
Where subnautica is depends on where you got it and where you put it. 

- If Steam it's in steam apps (similar to as seen in my image, where you have Steam)
- If ms store you need to run this tool: https://github.com/Measurity/AddModSupportMSStoreSubnautica/releases/latest/download/Add.Mod.Support.To.MS.Store.Subnautica.zip
- If Epic Games Store it's where you have Epic Games installed in a sub folder.
- If you cracked Subnautica then we don't support it and that's why Nitrox couldn't find it.

**Comment by DaveWasAlsoThere** [comment]
Thank you very much it works!

**Comment by DaveWasAlsoThere** [comment]
Hi! I was using MS store and ran the tool, and I set the path, but it still doesn't work
![image](https://user-images.githubusercontent.com/87504211/125924537-fe5c24c9-fa09-4916-9497-ae583aab892f.png)

**Comment by Measurity** [comment]
Ok, a few things:
- Did you extract the files from the zip before running the tool?
- You're running it from MS Store, not where it's extracted to (tool asks for the path where you want Subnautica to be). So this means the tool didn't replace MS Store Subnautica aka: it failed somehow.

**Comment by DaveWasAlsoThere** [comment]
Yes, I did fully extract it
and I know it is in WindowsApps, that's the path I put in
![image](https://user-images.githubusercontent.com/87504211/125925387-9406595b-7b92-4608-892a-2c618668aa60.png)

**Comment by Measurity** [comment]
This tool you need to run. Which path did you choose *here*?:
![image](https://user-images.githubusercontent.com/1107063/125925680-978b3a4c-76cc-4f8c-852b-dc4b1dddfd50.png)

**Comment by DaveWasAlsoThere** [comment]
C:\Subnautica

**Comment by Measurity** [comment]
Then Subnautica should be there, use that directory in Nitrox Launcher. If it's NOT there, something went wrong with the tool and it should have shown an error.

Rerun tool if Subnautica is not there.

**Comment by DaveWasAlsoThere** [comment]
Ive rerun it twice now, the only error I get is when I add it to Nitrox as the file path
![image](https://user-images.githubusercontent.com/87504211/125926427-46fdae97-2759-48a4-84c8-3fafbdff377b.png)

**Comment by Measurity** [comment]
Did the tool not do this when you ran it?
![image](https://user-images.githubusercontent.com/1107063/125926624-42eb08e6-66b9-4faf-a35c-278399b5a176.png)

This means it's extracting files and should be where you entered it (this is how it looks for me):
![image](https://user-images.githubusercontent.com/1107063/125926730-561a0817-3ddb-4c1f-aad9-7f229323c97d.png)
Not fully extracted yet:
![image](https://user-images.githubusercontent.com/1107063/125926761-41944961-9c0c-4cbd-9d4d-effa11ef6513.png)

Wait for the tool to finish. Then set path in Nitrox Launcher. Do not close tool before it's done.

**Comment by Measurity** [comment]
It should say these things when done:
![image](https://user-images.githubusercontent.com/1107063/125927589-ca72af16-1714-4208-9a8a-c5235d120b7c.png)

**Comment by DaveWasAlsoThere** [comment]
Then I think maybe its my computer being bad cuz it usually just crashed and I just assumed that it was done, looks like this could be the problem, Ill close Chrome to make sure its not just too many things open at once making it crash

**Comment by Measurity** [comment]
Make sure there's enough space left on your PC for 3 subnautica's at a time. There's one from MS Store, one in temp state and one dumped in the path you give. It will uninstall the former 2 soon after.

**Comment by DaveWasAlsoThere** [comment]
I have 21 gigs free (before I ran the program) is that enough?

**Comment by Measurity** [comment]
![image](https://user-images.githubusercontent.com/1107063/125929456-d9154585-d888-4fa0-8d15-7a147a6a93ab.png)
This is what Steam says so I think it's not enough and causes the tool to crash.

**Comment by DaveWasAlsoThere** [comment]
Alright Ill try and quickly delete some unnecessary things

**Comment by DaveWasAlsoThere** [comment]
It stopped at 1950 downloaded

**Comment by DaveWasAlsoThere** [comment]
![image](https://user-images.githubusercontent.com/87504211/125937974-71b2b6be-4117-49ad-a87b-26132ad92033.png)
@Measurity I started it again, I put in the path, but I got this error

**Comment by Measurity** [comment]
... that's still the WindowsApps path.

**Comment by DaveWasAlsoThere** [comment]
Oh, whoops
But if I use C:\Subnautica it shows this
![image](https://user-images.githubusercontent.com/87504211/125938449-cb92b230-cc28-40e0-ad59-00cbbb2ffa2c.png)

**Comment by Measurity** [comment]
Try run Nitrox Launcher as admin.

**Comment by DaveWasAlsoThere** [comment]
It works, thank you very much for your time and effort! :)
