### ISSUE TITLE
Multiplayer Button not appearing

### ISSUE THREAD

**Issue by XiominTSS** [SubnauticaNitrox/Nitrox#1530]
Multiplayer button replaced with Play button.
Joined the discord, tried to search the #🚩bugs-and-issues-list but found nothing.
can someone please help?

**Comment by Coding-Hen** [comment]
Have a look in the mod-fixes there is one for No Menu/Logo which should help you

**Comment by Measurity** [comment]
When you start Subnautica through Nitrox the play button is disabled. Might come back some day but if you want to play SP just start Subnautica normally.

**Comment by XiominTSS** [comment]
> Have a look in the #mod-fixes there is one for No Menu/Logo which should help you

I already did all of this. Five times at least. Yet nothing happened.
