### ISSUE TITLE
Creating / Joining a server

### ISSUE THREAD

**Issue by TheKaenguru** [SubnauticaNitrox/Nitrox#154]
Me and my friend managed to install the mod but we just cant manage to join each other.
Maybe we cant even start the server correctly?
Need some help pls ^^
Edit: top left corner "Multiplayer Client Loaded...
                                 Negotiating session..."
Then it stops

**Comment by AndrosHD** [comment]
I got the same problem

**Comment by Jannify** [comment]
You probably have to enable **Port Forwarding**. So not a Nitrox issue...
@Sunrunner37 Pls delete this issue if I am right...

**Comment by MadMaxOfYore** [comment]
We're sorry, but we are not setup to provided technical assistance at this point in time as the mod is still in pre-alpha development. We are happy to hear feedback concerning any error messages that you receive, but getting the mod configured to run in your local environment is well beyond the level of support that we can offer for the immediate future. 

We thank you sincerely for you interest in our work and we encourage you to continue to follow our progress as we continue to push towards a stable release. While this may seem harsh, please trust that we are just as vested in getting to play SN with out friends as all of you are - we wouldn't be doing this for free if we didn't share that goal with our audience.

I'll be closing this ticket at this time and ask that we all refrain from opening issues in this same vein moving forward. 

Thanks Again!
-MadMax
