### ISSUE TITLE
1.5 failed to load the world from 1.4, I want to download 1.4

### ISSUE THREAD

**Issue by karikera** [SubnauticaNitrox/Nitrox#1540]
### Version

1.5.0.0

### Bug
Failed to load world from 1.4.0.0

### Steps to reproduce
[worldBackup_tt.zip](https://github.com/SubnauticaNitrox/Nitrox/files/6873412/worldBackup_tt.zip)
try to load 1.4.0.0 world with 1.5.0.0

**Comment by Jannify** [comment]
Did the server log something in the console or what exactly happened?

**Comment by Coding-Hen** [comment]
This is due to you using protobuf rather than json for the save files (Which can be changed in the config). Unfortunately updating from 1.4 to 1.5 with protobuf is not possible

**Comment by karikera** [comment]
Could you keep the old download links?

**Comment by Measurity** [comment]
You can always build from source. We will keep the old releases on GitHub going forward.

**Comment by Measurity** [comment]
You can now download 1.4.0.0 again here: 
https://github.com/SubnauticaNitrox/Nitrox/releases/tag/1.4.0.0

**Comment by karikera** [comment]
Thanks for your help
