### ISSUE TITLE
A little help getting started 

### ISSUE THREAD

**Issue by lolsheeplol** [SubnauticaNitrox/Nitrox#155]
Not sure if this is the right place to ask this, but I'm looking to help contribute to this project in some capacity.  I've developed primarily in Java so C# is new to me, but I'm hoping to use this repo to read some good code and get serious with the language, and I have a few questions that weren't fully answered in the wiki or contributing guide.  

- Is there a recommended IDE (seems like Visual Studio Community)?
- What are the recommended workloads needed to compile this mod? The VS installer asks for these and they install several gb of libraries so I'd like to narrow it down.  
- Is there a list of basic/easy tasks that I can begin with?  
- Once the mod is installed for development, is there a way to also uninstall if I get stuck in a non-compiling state?

I apologize if this is the wrong place to ask, but any help would be appreciated!

**Comment by MarijnS95** [comment]
- Visual Studio is basically mandatory. Community should work fine, afaik it's what most people use. Latest version (2017) is recommended.
- Sorry, can't pull up the VS installer now to check (and I have many more things installed for other projects), but you should be able to get away with .NET 3.5, and probably some of the testing features though I don't know which ones exactly. Start off with just .NET 3.5, start the project and check what's missing: you can always install that after the fact by opening the `Visual Studio Installer`.
- You should be able to view the [url=https://github.com/orgs/SubnauticaNitrox/projects/1]projects board[/url] where most of our backlog is listed (we are not sure about the access rights yet, you might get a 404). It's not really sorted on simplicity but you should be able to figure that out.
- The mod itself doesn't change **any** game files, all you have to do is manually add **a single line of code** to a game library as mentioned in the wiki guide. Simply removing this line from the library (or restoring a previous backup) removes the mod. If it doesn't compile you can always use git to go back to a compiling state; guessing from your github history that shouldn't be a problem.

**Comment by lolsheeplol** [comment]
This is very helpful, thanks.  If I have more specific questions I'll ask but until then I'm gonna try and figure out what this mod is doing and follow the wiki and Trello closely.  :D

**Comment by MarijnS95** [comment]
We're phasing out Trello in favor of GitHub projects, which connects with the repository much more naturally.

You can also join the Subnautica Modding discord: https://discord.gg/9MfKs2s, here we do most of our discussion :wink:
