### ISSUE TITLE
Convert save from 1.4 to JSON and upgrade

### ISSUE THREAD

**Issue by vahrennd** [SubnauticaNitrox/Nitrox#1554]
Reading up on the 1.5.0.0 release it sounds like users of 1.4.0.0 are out of luck as far as migrating an existing save to 1.5.0.0? From my understanding 1.4.0.0 has saves in a ProtoBuf format with no way to convert them to JSON and 1.5.0.0 has significant enough changes that it can't read in 1.4.0.0 ProtoBuf saves.

It looks like the conversion commands were added in https://github.com/SubnauticaNitrox/Nitrox/pull/1370, not too long after the 1.4.0.0 release but well before the 1.5.0.0 release. Could we get a tag of that commit as something like 1.4.0.1, then use that version to convert an existing 1.4.0.0 save to JSON and from there upgrade to 1.5.0.0, or is it more complicated than that?

**Comment by Jannify** [comment]
You are free to try this but we decided internally to not make a V1.4.1.0 and therefor not support it. We are still in ALPHA and the upgrade function is not very stable so we are trying to learn from the few reports we get from people who used JSON in V1.4.0.0 while not spamming our support team with everyone if a problem appears with this newly introduced feature.
