### ISSUE TITLE
Lockers' label disappear

### ISSUE THREAD

**Issue by nathnet** [SubnauticaNitrox/Nitrox#1568]
### Bug
The locker label disappears every time the server is closed and reopened. Having to re-label each time we start the server.

### Expected
Lockers are all labeled "locked" instead of the name we gave them.

### Steps to reproduce
1. Name the lockers
2. Quit the game and close the server
3. Reopen the server and join
4. Bam! Lockers' labels are gone

**Comment by tornac1234** [comment]
Fixed with #1693
