### ISSUE TITLE
[Clean Up] Manually check all patches and verify sanity

### ISSUE THREAD

**Issue by killzoms** [SubnauticaNitrox/Nitrox#1576]
Some patches such as [BuilderTool_HandleInput_Patch](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Patches/Dynamic/BuilderTool_HandleInput_Patch.cs#L34) have silently broken over the years. We should manually check all of the current patches and verify that the sanity behind them checks out.

In the case of BuilderTool_HandleInput_Patch We pass a GameObject as a NitroxId, Which I doubt we have any implicit casts implemented for this conversion.

**Comment by dartasen** [comment]
Some transpilers are implemented like this and should help keeping the sanity of those black magic c# code
```csharp
public static IEnumerable<CodeInstruction> Transpiler(MethodBase original, IEnumerable<CodeInstruction> instructions)
{
    foreach (CodeInstruction instruction in instructions)
    {
          yield return instruction;
          
          if (instruction.opcode == INJECTION_CODE)
          {
               //Load up variables needed from the code
               yield return new CodeInstruction(OpCodes.Call, typeof(ThisClassPatch).GetMethod("Callback", BindingFlags.Static | BindingFlags.NonPublic));
          }
    }
}

private static void Callback(AllMyVariablesNeededToDoMyStuff)
{
      DoMyStuffIwannaDoSoTheCompilerWillYellIfItsNotValid
}
```

**Comment by Measurity** [comment]
Patches are now statically typed and not in immediate need for verification.
