### ISSUE TITLE
Continuing a save after closing the server?

### ISSUE THREAD

**Issue by Jonezzy** [SubnauticaNitrox/Nitrox#158]
Is it possible to continue on the same save after closing the server or do you have to start again every time?

**Comment by Alberto247** [comment]
I have yet to try but I think it's possible if you save it in singleplayer and then you join using the command line

**Comment by TheMysticle** [comment]
How do you join using command line?

**Comment by Alberto247** [comment]
mplayer username ip

**Comment by Jannify** [comment]
Yes it is possible. So delete this issue pls @Jonezzy.

**Comment by MadMaxOfYore** [comment]
The ability to join via the command console was hosed in our last build (my bad...)

We have a PR on-deck ( #159 ) that will fix this issue, but it will be a week or two before it is approved and subsequently lands on the master branch. Apologies for any inconvenience this causes in the iterim.

Would you be willing to close the issue at this point-in-time? 

Thanks,
-MadMax

**Comment by Laero00000** [comment]
how connect? My friend write in conosle in game and no connect =( Why me do?

**Comment by MadMaxOfYore** [comment]
@Laero00000 - Did you bother to read my last comment? 

The ability to log into the server via console command is currently broken and will be resolved as soon as we can update the current build. The only thing that you can now do is wait.

Thank you for your patience.

**Comment by Laero00000** [comment]
ok. How long it will?

**Comment by MadMaxOfYore** [comment]
> The ability to join via the command console was hosed in our last build (my bad...)
>
> We have a PR on-deck ( #159 ) that will fix this issue, but it will be a week or two before it is approved and subsequently lands on the master branch. Apologies for any inconvenience this causes in the iterim.
>
>Thanks,
>-MadMax

**Comment by MarijnS95** [comment]
1. The ability to save the server world is not implemented yet, but is definitely on our `major features` list in the backlog.
2. As @MadMaxOfYore correctly stated, joining through the cli is currently broken, and will be fixed soon enough.
