### ISSUE TITLE
Flung into the Void

### ISSUE THREAD

**Issue by Mrjman9991** [SubnauticaNitrox/Nitrox#1589]
### Version
1.5.0.1

### Bug
When exploring the mountain island with my friend, we were walking through the caves when we experienced a small lag spike. When I swung my thermoblade at a cave crawler during the lag spike, it damaged me and I was projectile launched at max speed though the walls of the cave and diagonally up into the air. After 10-15 seconds of flying at full speed up this way, I could no longer see the island and quit the game mid-flight. When I loaded back into the game, I had lost all my momentum and fell for 20-30 seconds straight down into the water well past the crater edge. I had to warp to my friend who was still on the island, and barely made it away before the ghost leviathans had converged on me. 

### Expected
Random cave crawler launches you into space like a NASA rocket if player is hit in a certain way on land.

### Steps to reproduce
Despite my best efforts, I am unable to reproduce this issue and have no idea how it happened in the first place.

**Comment by dartasen** [comment]
External factor bug
