### ISSUE TITLE
MS Store Subnautica does not work

### ISSUE THREAD

**Issue by luqueequee** [SubnauticaNitrox/Nitrox#1590]
### Version
1.5.0.1

### Bug
When I click the multiplayer tab nothing happens. The dot beside it becomes yellow but the interface doesn't pop up.

### Expected
It should pop up right?

### Other details:
I am using the nitrox on Microsoft Store Subnautica, so I watched A video in which the person did not have this bug on how to do it.

**Comment by Measurity** [comment]
MS Store is a different version of Subnautica (got updated recently unlike Steam/Epic version) that's why it does not work. We rely on other open source tools like UWPDumper to make Subnautica moddable as well and that also seems to have issues with current MS Store Subnautica.

**Comment by luqueequee** [comment]
I used all of these things when I watched the video, but when I use nitrox, the play button works but the multiplayer button does nothing.

**Comment by luqueequee** [comment]
I also tried reinstalling both subnautica and nitrox.

**Comment by Measurity** [comment]
Yes, we know. Doesn't matter what you try, it won't work. It's missing files that UWPDumper can't write to disk and we still need to update Nitrox to match the version of Subnautica provided by MS Store.

**Comment by Jannify** [comment]
As MS Store is still an update ahead we can't really do anything, sry.
