### ISSUE TITLE
Simplified Chinese is not supported

### ISSUE THREAD

**Issue by 2293745032** [SubnauticaNitrox/Nitrox#1593]
I tried to write the a Chinese (Simplified)language file,but It couldn't be read.
The language file is here:
[Chinese (Simplified).zip](https://github.com/SubnauticaNitrox/Nitrox/files/7149088/Chinese.Simplified.zip)
Is my format wrong?
Please make Simplified Chinese be supported.

**Comment by Jannify** [comment]
![grafik](https://user-images.githubusercontent.com/23176718/132978302-5a0aa23d-a2a5-4d08-8a0f-92c3a6a727d1.png)
As you can see here Subnautica uses the Unicode representation of the Chinese character. I am sure it will work if you do it this way.
