### ISSUE TITLE
Bio Reactor MissBehaving

### ISSUE THREAD

**Issue by TheFirstEqualcrazy** [SubnauticaNitrox/Nitrox#1596]
### Version

 1.5.0.1 -->

### Bug
 After saving and leaving the game for an unknown reason the bioreactor changed orientation, and became a static model, lost all power, and was no longer interactable in any way shape or form, but still playing the animated interaction when players are near. (could not be manually deleted through the console, or with the builder tool, creative, etc) after this bug occurs there seems to be a major desync in the two different players world when it comes to using the habitat builder -->

### Expected
 BioReactor to behave as intended, remembering power levels and inventory, as well as orientation between saves -->

### Steps to reproduce
 build bioreactor in nondefault
[game-20210914.log](https://github.com/SubnauticaNitrox/Nitrox/files/7166016/game-20210914.log)
 rotation, save and close server, relog (Does not happen every time, sometimes the bioreactor does behave as normal between saves) -->

### Other details:
 No errors found -->

**Comment by chatrat12** [comment]
Having the same issue

**Comment by Cryptic96** [comment]
Same with me. The major de-sync resulted in a unplayable world and did not fix itself after removing the generator and reloading the game/server.

**Comment by lLordShadowl** [comment]
The same problem happens with Nuclear Reactor. It changes rotation to "default" (I guess). Bio Reactor also changes this same "default" rotation. Reactor Rods are lost. When deleted it returned after server restart as unfinished blueprint, slightly moved away from where it was before and now it cant be interacted with and whole area is impossible to be changed (no construction or deconstruction).

**Comment by xSimone** [comment]
Confirm, also seems to revert back to 99% built and must finish again.
