### ISSUE TITLE
Scanner room not syncing

### ISSUE THREAD

**Issue by lucafont2** [SubnauticaNitrox/Nitrox#1602]
### Version
Alpha 1.5.0.1

### Bug
In the scanner room, the status of the modules and whether the search for an item is in progress is on, is not synchronized between the players.

### Other details:
[LOGFILE](https://cdn.lucaservers.com/SUB/09-17-02.log)
[LOGFILE_PRE](https://cdn.lucaservers.com/SUB/09-17-02-prev.log)

**Comment by Measurity** [comment]
Duplicate of #1425
