### ISSUE TITLE
Seamoth breaking sound issue

### ISSUE THREAD

**Issue by lucafont2** [SubnauticaNitrox/Nitrox#1605]
### Version
Alpha 1.5.0.1

### Bug
If you go more than 200m down, when you have modules installed, sometimes the pda will notice you about breaking height, and the sound of breaking Seamoth will start.

The sound will be bugged every time you enter the Seamoth until you restart the game

### Other details:
[LOGFILE](https://cdn.lucaservers.com/SUB/09-17-02.log)
[LOGFILE_PRE](https://cdn.lucaservers.com/SUB/09-17-02-prev.log)

**Comment by Measurity** [comment]
Fixed on master. See: #1537
