### ISSUE TITLE
Objects disappear from vehicles 

### ISSUE THREAD

**Issue by lucafont2** [SubnauticaNitrox/Nitrox#1606]
### Version
Alpha 1.5.0.1

### Bug
After rebooting any objects inside the Seamoth or Prown suit disappear completely. Many times the storage module disappears with him 

### Other details:
[LOGFILE](https://cdn.lucaservers.com/SUB/09-18.log)
[LOGFILE_PRE](https://cdn.lucaservers.com/SUB/09-18-prev.log)
[SCREENSHOT After Restart](https://cdn.lucaservers.com/SUB/2021-09-18_00006.jpg)

**Comment by Measurity** [comment]
This is fixed on master branch but not yet released. 
See: https://github.com/SubnauticaNitrox/Nitrox/pull/1551
