### ISSUE TITLE
Bug on structures not completed 

### ISSUE THREAD

**Issue by lucafont2** [SubnauticaNitrox/Nitrox#1607]
### Version
Alpha 1.5.0.1

### Bug
Unbuilt structures sometimes shift after rejoin, resulting in floating shapes that are impossible to break. Furthermore, it is impossible to build anything near them.
This bug wont fix even with a server restart

### Other details:
[LOGFILE](https://cdn.lucaservers.com/SUB/09-18.log)
[LOGFILE_PRE](https://cdn.lucaservers.com/SUB/09-18-prev.log)
[SCREENSHOT](https://cdn.lucaservers.com/SUB/2021-09-18_00004.jpg)
[SCREENSHOT](https://cdn.lucaservers.com/SUB/2021-09-18_00005.jpg)

**Comment by Measurity** [comment]
Duplicate issue, please do not mass create issues without verifying it isn't already reported. See #1400

**Comment by lucafont2** [comment]
> 
> 
> Duplicate issue, please do not mass create issues without verifying it isn't already reported. See #1400

Sorry, my bad. I always do but sometimes i miss / bad search. Apologies
