### ISSUE TITLE
Prawn Suit Drill Arm Noise

### ISSUE THREAD

**Issue by DayLittwin** [SubnauticaNitrox/Nitrox#1612]
Version
Alpha 1.5.0.1

Bug
The drill arm on the prawn suit continuously makes the drilling noise. The noise continues no matter how far the player is, or if you remove the drill arm upgrade module.

Expected
Drill arm noise will persist regardless of location of prawn suit or removal of drill arm module. 

Steps to reproduce
Use the drill arm on the prawn suit. Afterwards, the drilling noise will continue.

**Comment by Jannify** [comment]
The referenced pull request is still open (not merged) so yes, it is in fact still broken in 1.6.0.0

**Comment by Merdis01** [comment]
still in the game
