### ISSUE TITLE
Equipped vehicle upgrades are deleted on login.

### ISSUE THREAD

**Issue by fosley** [SubnauticaNitrox/Nitrox#1616]
### Version

1.5.0.1

### Bug

Affects the Seamoth and Cyclops vehicles for sure. Don't have prawn suit upgrades to test.

When rejoining a game, all but one equipped vehicle upgrade is deleted from the vehicle. I'm not sure if it's the same slot each time, or if it depends on what order you equip them.

This does not require a second player to ever join the game, so isn't the same as the bug where different players see different upgrade modules on the vehicle (though they may be related).

### Expected

Upgrades should stay in vehicle on reloading the game.

### Steps to reproduce

1. Create a vehicle.
2. Create multiple upgrades for that vehicle.
3. Install those upgrades.
4. Quit and rejoin the game.
5. Only one upgrade remains.

**Comment by Measurity** [comment]
This is fixed next release
