### ISSUE TITLE
Nitrox Build Problems path.txt

### ISSUE THREAD

**Issue by OctonalXX** [SubnauticaNitrox/Nitrox#1625]
When I'm building the mod, where do I put path.txt?

**Comment by Measurity** [comment]
We use Nitrox.BuildTool project now. It goes like this:
1. Run `git clean -xdf` command on your cloned Nitrox folder (this cleans all files in Nitrox folder).
2. Run `dotnet restore` to install NuGet dependencies that Nitrox needs.
3. Run *only* the Nitrox.BuildTool project to fetch the Subnautica code and install it into Nitrox for building.
4. Build or run any or all other projects in Nitrox you want.
