### ISSUE TITLE
restart the game, Aurora explodes again

### ISSUE THREAD

**Issue by ise6990** [SubnauticaNitrox/Nitrox#1628]
### Version
[The version of Nitrox you are using]
--1.5.0.1

### Bug
[Explain the bug that you have encountered]
--Every time you restart the game, Aurora explodes again.
Radiation leaked, and the engine compartment had to be repaired again.

Is this normal? I'm a beginner in subnautica so I don't know

**Comment by fridomelone** [comment]
Same here :(
