### ISSUE TITLE
Lots of stuff is missing

### ISSUE THREAD

**Issue by JimmyTDM** [SubnauticaNitrox/Nitrox#1647]
Hi, for some reason, fish and all types of plants are just gone, like the entire kelp forest has not a single piece of creepvine. Is there any way of fixing this without restarting the world? Thanks

**Comment by TheLxkas** [comment]
we help with these kinds of issues on our support discord. Might want ask there as it's easier for everyone to communicate.
https://discord.gg/E8B4X9s
