### ISSUE TITLE
Other players character not showing the right color

### ISSUE THREAD

**Issue by Bricklou** [SubnauticaNitrox/Nitrox#1649]
### Version
1.5.0.1

### Bug
All players choose a color before connecting on the server. You others body charater color in the color you choosed and not the color they choosed.

### Expected
Other player character should be coloring in the color they choosed for us.

### Steps to reproduce
- Have 2 games instance and a server
- Choose 2 different color while connecting
- Compare your own color between both instances.

Player A screen
![image](https://user-images.githubusercontent.com/15181236/141648538-f59ca0b1-1035-400f-b760-f6cd6531d317.png)

Player B screen
![image](https://user-images.githubusercontent.com/15181236/141648563-8fd5052b-5bf3-4e74-9f10-2586c659a0d1.png)

**Comment by dartasen** [comment]
Fixed with #1867
