### ISSUE TITLE
Fails to find optional game directory

### ISSUE THREAD

**Issue by jazzmadrazz** [SubnauticaNitrox/Nitrox#165]
Got Subnautica installed in an optional game library ("d:\something") which is set as default in Steam.  

Could be wrong about this, but it appears never to get to the libraryfolders.vdf file (see else statement below) as the acf file exists, even though the Optional game library is set as Default as should overrun the acf file test (I think...)

```
string appsPath = Path.Combine((string)ReadRegistrySafe("Software\\Valve\\Steam", "SteamPath"), "steamapps");

            if (File.Exists(Path.Combine(appsPath, $"appmanifest_{appid.ToString()}.acf")))
            {
                return Optional<string>.Of(Path.Combine(Path.Combine(appsPath, "common"), gameName));
            }
            else
            {
                string path = SearchAllInstallations(Path.Combine(appsPath, "libraryfolders.vdf"), appid, gameName);
                if (path == null)
                {
                    Log.Info($"It appears you don't have {gameName} installed anywhere. The game files are needed to run the server.");
                }
                else
                {
                    return Optional<string>.Of(path);
                }
            }
            return Optional<string>.Empty();
```

**Comment by nesrak1** [comment]
What does the registry value for steam say in Software\Valve\Steam\SteamPath ? Some users have reported incorrect values in the registry there

**Comment by jazzmadrazz** [comment]
Registry value for SteamPath is c:/program files (x86)/steam
I don't see any mention of the optional path in the registry under Steam in registry.

(I temporarily deleted the Subnautica.acf file in C:\Program Files (x86)\Steam\steamapps so that the code  would search for the vdf file.  This works fine.)

**Comment by MadMaxOfYore** [comment]
@nesrak1 

Do we need to keep this issue open?
