### ISSUE TITLE
Add fallback URIs for getting public IP

### ISSUE THREAD

**Issue by TwinBuilderOne** [SubnauticaNitrox/Nitrox#1652]
Sometimes the request to [https://ipv4bot.whatismyipaddress.com/](https://ipv4bot.whatismyipaddress.com/) fails or returns an error, which produces this unhelpful message:
> Could not get your external IP. You are on your own...

I propose that additional IP checking sites be supported in case this check fails. Some candidates are:
- https://checkip.amazonaws.com/
- https://ipv4.icanhazip.com/

**Comment by Measurity** [comment]
You can ask the router which external IP it has through UPnP. We should use this as the first option before falling back to sites.
