### ISSUE TITLE
errors connecting (I'm new to this)

### ISSUE THREAD

**Issue by bobatrisha** [SubnauticaNitrox/Nitrox#1654]
Hi I'm new to all this and I'm just wondering if somebody can help me through the basics on how to start this up.  I have already launched the mod but I cannot connect to the server.  It loads but then I cannot connect to the server.  I don't know if I am breaking any rules in this, but I just need help to get into the mod.  I would appreciate any help necessary.  Thanks.

**Comment by Jannify** [comment]
We help with these kinds of issues on our support discord. Might want ask there as it's easier for everyone to communicate.
https://discord.gg/E8B4X9s
