### ISSUE TITLE
Add platform select page to the launcher with support for custom launch arguments

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#1657]
Arguments are hard coded right now:
https://github.com/SubnauticaNitrox/Nitrox/pull/1656/files#diff-7a0366e5e7853fb5655bfffb8b97f72dbeb6b2f583d1f61d22f9b34b784bbb1dR79

_Originally posted by @dartasen in https://github.com/SubnauticaNitrox/Nitrox/pull/1656#r757887923_

**Comment by dartasen** [comment]
![image](https://user-images.githubusercontent.com/10561268/145247909-4a8eaf45-9bf1-4f71-85d4-7f91a3d96474.png)
