### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by mlebjerg** [SubnauticaNitrox/Nitrox#166]
Cave sulfur can't be found, so you have to spawn it in.
You can dupe stuff if you are both in the fabricator.
You Storage inventory doesn't sync. 
Time doesn't sync.
It would nice if could share blueprints, since fragments are a finite resource.

Other than that, this is an amazing mod! Great job!

**Comment by Sunrunner37** [comment]
- Crash fish should now be working for simulating player
- Time should be fixed now that we removed the ability for players to pause
- Storage inventory and duping are known bugs.

Thanks for reporting items, let us know if you find anything else.
