### ISSUE TITLE
resources not spawning

### ISSUE THREAD

**Issue by wakkytabbaky** [SubnauticaNitrox/Nitrox#168]
unsure if its nitrox or just a bugged save file , but has anyone else ran into the issue of not having any resources spawning inside the ILZ or lava lakes, not a single piece of kyanite or sulphur has spawned. using latest build of nitrox and latest subnautica update also

**Comment by Kosiak** [comment]
I think it's a bug with this build. Because it's was already reported that some resources not spawning. Hope they already fixed this on their local branch.

**Comment by wakkytabbaky** [comment]
also noticed while watching another playthrough that lots of rays spawn near the big ghost tree, none spawn while using nitrox also

**Comment by Sunrunner37** [comment]
Can you please verify again with the newest changes?  The root cause may be the same as #161.
