### ISSUE TITLE
Items/vehicle mods disapear out of nowhere

### ISSUE THREAD

**Issue by Subnautica4life** [SubnauticaNitrox/Nitrox#1683]
I'm using up to date version alpha 15.0.1 (i this is number if i'm correct)

Today me and my friend Beeking tried out multiplayer subnautica we came across some bugs but not very gamebreaking at all sometimes it was fun to see reefbacks spin around or giant crabsnakes. We used a cyclops to get everywhere we started at the mushrooms near crash zome with prawn suit (we played this mod since 2 days and encounter indeed some loss of things) i drilled multiple salt piles and couldn't find more so we decided to head out. My game decided to duplicate multiple items afterwards (notice when leaving steer of cyclops) and then out of nowhere all my equipment disapeared radiation coming through (even tho we fixed Aurora reactor and it was over 10 days in game so should have stopped) luckly i could build myself fast a radiation suit and head out again remaking my equipment i lost. We got at the alien platform gun island and i saw some lead and other potential things when i boarded the prawn suit i imidiatly knew something was wrong i missed my 2 drill arms :( then i was just done i told my friend this ain't getring much further we are losing more progress than earning so we both stopped. We hope you guys can look in this matter or may have already experienced it we really look out for your beautifull mod.

Thank you
Subnautica4life

**Comment by Measurity** [comment]
This is fixed next release
