### ISSUE TITLE
Vehicle modules missing on connection

### ISSUE THREAD

**Issue by PigguJones** [SubnauticaNitrox/Nitrox#1684]
### Version
Alpha 1.5.0.1

### Bug
It has multiple parts and it's kind of confusing, It's a hamachi connection, the server is hosted on my end, and the issue happens to me as well.

- On player connection: All modules disappear in all vehicles and vehicles behave as if they have 0 modules installed including and mining/grapple/propulsion arms.
- If a player is already in the game and they manually replace the modules the vehicles will work fine FOR THAT PLAYER for the duration of their session until they disconnect.
- Any disconnection and reconnection to the server (game crashes, internet outages) will cause all of the modules to disappear for the player(s) that disconnected and reconnected.
- Shutting down the server with players in the game and everyone reconnecting will cause the modules to disappear for everyone and vehicles will take damage if below base crush depth.
- The vehicles will always take damage from being below the base crush depth for any player who reconnected and will eventually get destroyed unless they replace the modules with new ones.
- If one player fixes the modules in all of the vehicles and another player joins the player who joins will not see any modules in any vehicles and any vehicles below base crush depth will take damage.
- If a vehicle gets destroyed in this way the player who initially fixed the modules will still be able to see any vehicles destroyed for the player who joined as well as any modules that were put into the vehicles.

### Expected
Modules should persist between reconnections like player or locker inventories

### Steps to reproduce
Put a bunch of various modules in the vehicles. It doesn't matter what depth you are or where you are on the map. It doesn't matter what modules you use or what vehicle they're put in.
Disconnect from the local server
Connect to the local server
Most if not all of the modules should just be gone from all vehicles.

### Other details:
We just installed the game and nitrox last week so as far as we can tell we're using what we're supposed to. I apologize if this is a non-issue I couldn't find another thread about it besides one from 2019.

**Comment by NinjaPedroX** [comment]
This is fixed in the next release. I recommend taking modules out before disconnecting from the server.
