### ISSUE TITLE
Battery percent going too fast

### ISSUE THREAD

**Issue by GamerProPlaysYT** [SubnauticaNitrox/Nitrox#1694]
### Version

 1.5.0.1

### Bug
 The battery percent is going from 100% to 0% faster than usual. It once went from 90% to 87% in 1 second

### Expected
 The battery are supposed to go like 2 or 3 times slower.

### Steps to reproduce
 ???

### Other details:
 No.
 Everything looks normal.
 I run the server on a VPS.

**Comment by Jannify** [comment]
Should be fixed with https://github.com/SubnauticaNitrox/Nitrox/pull/1659
