### ISSUE TITLE
Netstandard library is missing when discordrpcontroller attempts to get wanip

### ISSUE THREAD

**Issue by Coding-Hen** [SubnauticaNitrox/Nitrox#1700]
Server is able to use the NetHelper to get the wanip however when the discordrpcontoller tries to get the wanip an error is thrown as shown below:
![image](https://user-images.githubusercontent.com/8798074/147822611-2a522fcd-a4e7-4b10-b6e3-0d71c3f2f718.png)

**Comment by Jannify** [comment]
Once I get to my planed rework of the discord implementation I will investigate an option to get rid of the IP lookup. But possibility of that is still in the stars.
