### ISSUE TITLE
Other Players don't see any entities and containers are not synced

### ISSUE THREAD

**Issue by Powered99** [SubnauticaNitrox/Nitrox#1708]
### Version
1.5.0.1

### Bug
Other Players don't see any entities like fishes, items, plants and other.
Containers are not synced as well.

### Expected
All entities and containers should be synced and visible for all Players on the Server.

### Steps to reproduce
None, it's just an bug, that happens from it self.

### Other details:
Me and my friend are playing a Subnautica copy from Epic Games.
I'm playing on the Server as the host.
The others are joining via LogMeInHamachi.
Other Players, that join don't see any entity.
Containers aren't synced, so if i put an item into them, no one can access it.

There are no errors in the log file.

**Comment by Jannify** [comment]
The bugs you describe sounds like a firewall problem. You can join our discord for getting help with fixing that. For now I close this issue.

**Comment by Powered99** [comment]
Thank you very much. Now it worked with the entities.
