### ISSUE TITLE
Player positions are not synced

### ISSUE THREAD

**Issue by Powered99** [SubnauticaNitrox/Nitrox#1709]
### Version
1.5.0.1

### Bug
Every player on the server sees other players flying around the map and spinning at the same time.
The player positions aren't synced. Even when the players meet the same location, they don't see each other.

### Expected
Players should have the position synced and be able to meet in a location.

### Steps to reproduce
None, it's a bug, that happened from itself.

### Other details:
We are playing Subnautica from Epic Games and our firewalls are disabled.
The server is being hostet via LogMeInHamachi.

**Comment by Jannify** [comment]
Could you provide us the logs of both one client and the server? They are located in the Nitrox Launcher directory.

**Comment by Powered99** [comment]
This are the logs from my computer:
[log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/7877857/log.txt)
.

**Comment by Jannify** [comment]
Mh strange. I don't see any errors in the logs which can result in bugs like described. There is one strange entry about SN failing a web-request but this has nothing to do with Nitrox as far as I can see. I would recommend that you seek help in our discord (https://discord.com/invite/sF8ynqc), maybe our support-staff can help you. I as a developer can neither find the issue in the logs nor reproduce it, so I will close this ticket now.
