### ISSUE TITLE
Exception while processing packet: Dropped Item

### ISSUE THREAD

**Issue by Ryguy92250** [SubnauticaNitrox/Nitrox#1711]
### Version
1.5.0.1

### Bug
 Inventory Duplication / Overfill 
[Example Errors Subnautica Nitrox Github.txt](https://github.com/SubnauticaNitrox/Nitrox/files/7914938/Example.Errors.Subnautica.Nitrox.Github.txt)

### Expected
When playing with the Nitrox multiplayer mod, using the fabricator or mobile vehicle bay to craft items should spend your items, not duplicate or overfill inventory.

### Steps to reproduce
I'm not sure why or how this bug happened. I was playing with 3 other players who were constantly dealing with sync issues, like their seamoth would glitch into terrain and they would have to relog to be able to see it again and enter it, sometimes entering habitats would cause the player to still be swimming / not receive oxygen for a period of time, etc. They were also dropping fish a lot into the open. I was just using the fabricator to turn about 8-10 bladderfish into bottles of water when I received an error in the top left corner:  Exception while processing packet, and then it would say something to the effect of "Due to recent multiplayer updates, your inventory now has overfill (x127 or however many items overfilled). Please clear out your inventory to view the rest."

### Other details:

[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/7914924/Player.log)

**Comment by Jannify** [comment]
Probably fixed with new entity system
