### ISSUE TITLE
Steam features (like Controller mapping) won't load with direct start

### ISSUE THREAD

**Issue by joshuatam** [SubnauticaNitrox/Nitrox#1723]
### Version
master at 9e9382d

### Bug
Controller is not working.

### Expected
It was working in last stable build 1.5.0.1

### Steps to reproduce
Build the project from master branch, open NitroxLauncher.exe after plugging in a controller, after opening the game the cursor will move randomly and clicked buttons.

### Other details:
Windows 10
I have already opened Steam in the background.

**Comment by Jannify** [comment]
Could you upload your game log (it's located inside the launcher folder)?a

**Comment by joshuatam** [comment]
> Could you upload your game log (it's located inside the launcher folder)?

Sure.

[launcher-20220205.log](https://github.com/SubnauticaNitrox/Nitrox/files/8004543/launcher-20220205.log)

[game-20220205.log](https://github.com/SubnauticaNitrox/Nitrox/files/8004541/game-20220205.log)

**Comment by joshuatam** [comment]
Btw, this is the log from 1.5.0.1

[launcher-20220205.log](https://github.com/SubnauticaNitrox/Nitrox/files/8004625/launcher-20220205.log)

[game-20220205.log](https://github.com/SubnauticaNitrox/Nitrox/files/8004629/game-20220205.log)

**Comment by joshuatam** [comment]
I also notice another behavior, when clicking "Play Multiplayer" in v1.5.0.1, it will first open Steam in the background (Steam icon appeared at the Task Bar and disappeared shortly), and then start the game. While using the master branch, it will open the game directly without Steam icon on Task Bar.

**Comment by joshuatam** [comment]
I am not sure whether it is related to https://github.com/SubnauticaNitrox/Nitrox/commit/fbd4229a057b751c26a93d4be51d299d01e2af0c

`NitroxLauncher/LauncherLogic.cs` logic is changed from `"steam://run/264710"` to the real path of the game exe.

**Comment by joshuatam** [comment]
Finally to workaround by reviesing launch method of Steam platform.
Please see if it is a suitable modification. #1724

**Comment by dartasen** [comment]
> I also notice another behavior, when clicking "Play Multiplayer" in v1.5.0.1, it will first open Steam in the background (Steam icon appeared at the Task Bar and disappeared shortly), and then start the game. While using the master branch, it will open the game directly without Steam icon on Task Bar.

Yeah, since 1.5 we reworked the whole logic behind platform management

**Comment by Jannify** [comment]
https://github.com/SubnauticaNitrox/Nitrox/pull/1724#issuecomment-1059330358
