### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Laero00000** [SubnauticaNitrox/Nitrox#173]
Error: Couldn't load serializable attribute for Peeper version
I read the forum, written that it was fixed and the topic is closed, but I still do not spawn fish and scrap metal. What should I do?

**Comment by MadMaxOfYore** [comment]
I believe that @Sunrunner37 is working on this right now.

**Comment by Laero00000** [comment]
when will this error be fixed?

**Comment by nesrak1** [comment]
It's been around ever since it was implemented, it could possibly be due to duplicate fields in both the regular class and in the case class. However, that won't affect anything and is pretty much a warning. If nothing is spawning, that's an entirely different problem.

**Comment by Krum3L** [comment]
Unfortunally, i have the same error when i start a server.... but there are Too many fishes swiming around ~500 in the FoV only...

**Comment by Laero00000** [comment]
When you fix?

**Comment by Lukarius51** [comment]
This post is very old, but for those who were still wondering there is a fix. I do believe others are trying to fix this, but saldy NitroX was made to work for steam. So if you get this error you simply need to get subnautica on steam and download the multiplayer onto it. That is the only up to date solution that I have found so far.
