### ISSUE TITLE
Bug while teleporting to a player inside a multipurpose room

### ISSUE THREAD

**Issue by tornac1234** [SubnauticaNitrox/Nitrox#1733]
### Version

commit 8c5c52c2f027d554133dfd83aac1e27cee869ee4 (Fix for discord game discovery)

### Bug
When using the command warp to a player that's inside a multipurpose room, you're teleported far away.

### Expected
You should be teleported to him

### Steps to reproduce
- Have one player go inside a multipurpose room
- Have another player use the warp command to the first player
- The 2nd player is now far in the water

### Other details:
Probably some issue with the sub detection of the multipurpose room

**Comment by dartasen** [comment]
This is not working inside every base pieces, not only multipurpose room
