### ISSUE TITLE
Server problems (problemas con el servidor) need help (necesito ayuda para resolverlo) 

### ISSUE THREAD

**Issue by TNTCarrasco** [SubnauticaNitrox/Nitrox#174]
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.
   en NitroxServer.GameLogic.EntitySpawner.GetDataFiles(String& lootDistributions, Dictionary`2& worldEntityData) en C:\Users\Ernesto\Documents\Nitrox\NitroxServer\GameLogic\Spawning\EntitySpawner.cs:línea 166
   en NitroxServer.GameLogic.EntitySpawner..ctor() en C:\Users\Ernesto\Documents\Nitrox\NitroxServer\GameLogic\Spawning\EntitySpawner.cs:línea 31
   en NitroxServer.Communication.Packets.PacketHandler..ctor(PlayerManager playerManager, TimeKeeper timeKeeper, SimulationOwnership simulationOwnership) en C:\Users\Ernesto\Documents\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs:línea 26
   en NitroxServer.Server..ctor() en C:\Users\Ernesto\Documents\Nitrox\NitroxServer\Server.cs:línea 17
   en NitroxServer.Program.Main(String[] args) en C:\Users\Ernesto\Documents\Nitrox\NitroxServer\Program.cs:línea 14

nesesito ayuda por favor mandenme las sugerencias a ernestomp7@nauta.cu

**Comment by nesrak1** [comment]
The environment variable is probably wrong. Can you check `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam` and see if the path is there in regedit?
Translate I guess?
La variable de entorno probablemente está equivocada. ¿puede comprobar `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Valve\Steam` y ver si el camino está allí en regedit?

**Comment by TNTCarrasco** [comment]
disculpa la demora en responder pero aun me sigue dando el mismo problema
tengo la version pirata puesto qeu no tengo internet para jugarlo y no se si
funcionara bien con la version pirata

**Comment by Measurity** [comment]
We do not support pirated versions of the game. I hope you consider buying the game when you are able because we cannot support pirated versions.

No admitimos versiones pirateadas del juego. Espero que consideres comprar el juego cuando puedas porque no podemos admitir versiones pirateadas.

**Comment by TNTCarrasco** [comment]
no puedo comprarlo porque n tengo aceeso al servicio debido al pais en donde vivo ojala lo pueda comprara pero spor desgracia no puedo pero de todas formas gracias por la ayuda
