### ISSUE TITLE
Habitat power resetting

### ISSUE THREAD

**Issue by RedW0lfStoneYT** [SubnauticaNitrox/Nitrox#1741]
### Version

1.6.0.0
### Bug

When you join the server (Even if someone was already on) all the habitat things get replaced down meaning any stored power gets cleared 
### Expected

the power should stay at the level it was at
### Steps to reproduce

1. Build a multi purpose room.
2. Place solar panels on it.
3. Wait for it to charge a bit.
4. Rejoin, power is reset but should be where it was before leaving.

**Comment by Measurity** [comment]
Reactors are not synced and will break when rejoin. Use solar power and thermal only for now.

**Comment by RedW0lfStoneYT** [comment]
Just wanna add, this happens with solar too for us so I do not think that is a simple fix at all

**Comment by Jannify** [comment]
Merged into issue about base power bugs.
