### ISSUE TITLE
Moon pool causing seamoth desync 

### ISSUE THREAD

**Issue by RedW0lfStoneYT** [SubnauticaNitrox/Nitrox#1745]
### Version

a 1.6.0.0
### Bug

We cannot find the direct reason but have found out that one of our moon pools seems to cause seamoth desync,
this means unless you drop from one specific moon pool the other user wont see your sea moth (They can also die from just hitting it)
### Expected

They should be synced no matter what moon pool you drop from and you should not die suddenly from stuff that doesn't exist
### Steps to reproduce

Have a layout like outs (unsure if the layout location is the cause) [Attached layout below]
![image](https://user-images.githubusercontent.com/40332881/155619587-192557c7-cdd5-4215-8067-5fcdd55f471f.png)
Bugged moon pool location: 167.1212, -42.06496, 77.18507
Working moon pool location: 163.5879, -42.06496, 97.42337

**Comment by tornac1234** [comment]
Did it happen before you built the second moonpool ?

**Comment by RedW0lfStoneYT** [comment]
we know it is the second moon pool and not the sea moths if we drop from the first moon pool all is synced, if we drop from the second moon pool it doesnt.
nothing to do with connection as the server has restarted several times in attempts to fix.
tried reconstructing the moon pool, nothing happened.
Not a network error, I am the one hosting it and it happens with either user.
