### ISSUE TITLE
Bio reactor dupe (and likely other items)

### ISSUE THREAD

**Issue by RedW0lfStoneYT** [SubnauticaNitrox/Nitrox#1749]
### Version

1.6.0.0
### Bug

So, Bio reactors. when a player places them down it places for all players, but when deconstruct them each player has to do it theirself.
This results in each player getting the materials used to make the reactor thus duping materials.
### Expected

Building should be constructed for all players.
### Steps to reproduce

1, Place bio reactor on a server with 2 or more people
2, players deconstruct the reactor one by one resulting in them all getting the materials

**Comment by Jannify** [comment]
Probably fixed with #1751
