### ISSUE TITLE
Sunbeam events states aren't saved

### ISSUE THREAD

**Issue by tornac1234** [SubnauticaNitrox/Nitrox#1755]
As of 1.6.0.0, Sunbeam events aren't supposed to be synced yet. Tho, because of the StoryEventSend packet, they may be triggered by other clients.
it's probably stuff from StoryGoalCustomEventHandler and it also contains infection and telepathy. PrecursorGunStoryEvents may be a good place to look at also
We need some state recovery of this class for everything that concerns sunbeam. So we'll have the timer reappear when we reconnect. (and the countdown time will be saved on server-side in the EventTriggerer as for aurora's explosion)

**Comment by tornac1234** [comment]
Just sayin but I've been working on that one for a while now, missing some things tho that's why I didn't open a PR yet

**Comment by Jannify** [comment]
Fixed with #1967
