### ISSUE TITLE
Radiation state not synced

### ISSUE THREAD

**Issue by Szczurowsky** [SubnauticaNitrox/Nitrox#1757]
### Version
1.6.0.0 Alpha

### Bug
After sucessfully fixing aurora engines by me and friend (both did it separately) and getting message about fixing it succesfully and relogin radiation still exists. Even when disabled by `radiation` command it's still not disabled after re-login

### Expected
Radiation state is disabled - doesn't affect players

### Steps to reproduce
Fix the Aurora engines by 2 players separatly and try to re-login

**Comment by Joan68** [comment]
Same issue here

**Comment by tornac1234** [comment]
Duplicate of #1454
