### ISSUE TITLE
Destroyed seamoth respawn when restard the server

### ISSUE THREAD

**Issue by Luckipro** [SubnauticaNitrox/Nitrox#1758]
### Version
1.6.0.0

### Bug
When I restart my Nitrox survival server, all destroy seamoth respawn, and everytime I try to redestroy these seamoth, they respawn when I restard my server.

### Expected
I expected nothing

### Steps to reproduce
1. Destroy a seamoth in a multiplayer server
2. Restart the server
3. Connect to the server and see if the seamoth respawn.

### Other details:
This bug only happen in Multiplayer.

[Player.log](https://github.com/SubnauticaNitrox/Nitrox/files/8206427/Player.log)

**Comment by wconner** [comment]
I've also been experiencing this, I've been removing my exploded vehicles from WorldData.json manually as a workaround.

**Comment by RazzyFFA** [comment]
This bug does indeed, happen, however deems to be useful in some situations where seamoths just instantly get destroyed due to positions not being synced with players. I'll be in my seamoth and it'll just destroy instantly from 100% to 0%

**Comment by tornac1234** [comment]
Supposedly fixed by #1893
