### ISSUE TITLE
Port forwarding won't work when router has multiple ISPs assigned (more complicated home network)

### ISSUE THREAD

**Issue by Szczurowsky** [SubnauticaNitrox/Nitrox#1769]
### Version
V1.6.0.0
 ### Network schematic:
![image](https://user-images.githubusercontent.com/70973416/160296416-e3e6da79-5b4f-4913-ac2b-32314adb2d04.png)

### Network logic:
PC and ABR of Area 1 are being OpenVPN client when external server being VPN server.
PC is nitrox server host with disabled every firewall. PC also is connected to VPN as 10.8.0.2 when router (10.8.0.3) forward every traffic from 10.8.0.0/24 network to PC also to port 11000 on both protocols.
ISP 1 / ISP 2 are border routers in Area 0 connected to ISP's (they're not ISP's)
### Bug:
**When trying to connect to nitrox server on 10.8.0.3 getting error:**
```
20:36:39.063] [INF] Initializing MultiplayerSessionManager...
[20:36:39.083] [INF] Klient wieloosobowy wczytany...
[20:36:39.090] [INF] Initializing LiteNetLibClient...
[20:36:41.154] [INF] Nie można połączyć się ze zdalnym serwerem: "**********":11000
```
**Now when scanning 10.8.0.3 host port is discoverable**
![image](https://user-images.githubusercontent.com/70973416/160296652-80fdc822-751f-4552-81f1-99a9891e2001.png)

**Also nitrox is receiving packets because on receiving scan packets console prints error**
![image](https://user-images.githubusercontent.com/70973416/160296689-88eb0b1c-da27-4735-8540-2ec434db9120.png)

Also wireshark shows that packets being delivered corectly and nothing is being sent back to the client.
When connecting directly to 10.8.0.2:11000 everything works as it should.

**Comment by Measurity** [comment]
Since we don't have your network setup it's gonna be difficult for us to test this situation so I'm gonna mark this as "help wanted".

**Comment by Szczurowsky** [comment]
> Since we don't have your network setup it's gonna be difficult for us to test this situation so I'm gonna mark this as "help wanted".

Understandable. I can help in further investigation of this issue. If you want to recreate similar setup you can use Cloud Hosted Router on VM from mikrotik`s site.

**Comment by prodigyrick** [comment]
I turned off AutoPortForward. Then I created my own port open for 11000 and it worked fine on udp.
