### ISSUE TITLE
Intterior items (posters, bags, etc.) fall through the base when joining

### ISSUE THREAD

**Issue by geicorules** [SubnauticaNitrox/Nitrox#1772]
1.6.0.0 Version

### Bug
Some placable items placed in constructed base falls through base upon re-lauch of server. 
Some items disappear from the base ladder every time and unique poster from aurora 
This has happened with bags from the aurora as well as aurora poster. 

### Expected
Place item, save relaunch server items gone. If quick enough you can see them (Bag) fall through the map at least the bags not sure what happened to the poster or ladder.

### Steps to reproduce
Place bag o floor. 
save game 
shut down server.
relaunch server
enter game
try to catch bag before goes through bottom of map. 
if anything in bag good luck. 

### Other details:
none

**Comment by Jannify** [comment]
Merged into #1462
