### ISSUE TITLE
Hamachi cannot connect becuase of port forwarding.

### ISSUE THREAD

**Issue by Nakkung** [SubnauticaNitrox/Nitrox#1774]
### Bug 
We use hamachi but subnautica say "unable to contact remote server "

**Comment by Measurity** [comment]
Right-click your friend in Hamachi, diagnose and verify the summary says 4 OKs. If not, "local" issues are for you, "peer" issues are for your friend to fix.

Check that: 
- Windows firewall is not blocking the connection (neither Hamachi, nor Subnautica.exe/NitroxServer-Subnautica.exe)
- Hamachi is properly installed (no "adapter" issues). Requires Hamachi reinstall to fix.
- As a host, you've given the correct hamachi IP to your friend (shown in Nitrox server console).
