### ISSUE TITLE
Certain progress doesn't save

### ISSUE THREAD

**Issue by panda4k** [SubnauticaNitrox/Nitrox#1778]
### Version

1.6.0.0

### Bug

Certain progress not saving (scans, creature discoveries, story mode mission completions (unlocking new ones does save) and similar).

### Expected

Play, relog, all progress saved.

### Steps to reproduce

Play, relog, check scan progress or other things such as discoveries and notice them not saved.

### Other details:

For example: Pick up a fish, get notified of the new discovery, relog to pick up the same fish and get a notification of the new discovery (along other progress things), that's just one example.

**Comment by Measurity** [comment]
This is fixed on master
