### ISSUE TITLE
Scannable objects do not spawn (probability too low)

### ISSUE THREAD

**Issue by Megumini** [SubnauticaNitrox/Nitrox#1779]
### Version
 1.6.0.0

### Bug
 All scanable objects don't appear on the map. It's a very big issue because we can't have the modication station or other things that we need to progress in the game.

**Comment by andrew-waite** [comment]
+1

This is happening to me as well. Things like the battery charger and other fragments required to progress haven't spawned anywhere on the map.

**Comment by DragonMC233** [comment]
Yeah, I also had this problem. When I went to the room inside the large wreckage, there was nothing inside

**Comment by Arrkhz** [comment]
It is more than just empty rooms in wrecks, if you relog it fixes the empty rooms. What you cannot fix is the fact that no wreck in my game has any prawn arms, no thermal reactor, no nuclear reactor, and the rest of the fragments are bound to wrecks. I am hosting a server for me and my friends and this is getting in the way of progression, thank you, and have a nice day.
