### ISSUE TITLE
CS1061 Errors when trying to compile Nitrox

### ISSUE THREAD

**Issue by Zakkious** [SubnauticaNitrox/Nitrox#1794]
### Version
1.6.0.0 

### Bug
Three CS1061 errors when trying to compile the solution:

Error CS1061 'BaseAddCorridorGhost' does not contain a definition for 'rotation' and no accessible extension method 'rotation' accepting a first argument of type 'BaseAddCorridorGhost' could be found (are you missing a using directive or an assembly reference?) NitroxModel-Subnautica	C:\Users\******\Downloads\Nitrox\Nitrox - Copia\NitroxModel-Subnautica\DataStructures\GameLogic\Buildings\Rotation\SubnauticaRotationMetadataFactory.cs Line 17 

CS1061 'BaseAddMapRoomGhost' does not contain a definition for 'cellType' and no accessible extension method 'cellType' accepting a first argument of type 'BaseAddMapRoomGhost' could be found (are you missing a using directive or an assembly reference?) NitroxModel-Subnautica C:\Users\******\Downloads\Nitrox\Nitrox - Copia\NitroxModel-Subnautica\DataStructures\GameLogic\Buildings\Rotation\SubnauticaRotationMetadataFactory.cs Line 23

Error CS1061 'BaseAddMapRoomGhost' does not contain a definition for 'connectionMask' and no accessible extension method 'connectionMask' accepting a first argument of type 'BaseAddMapRoomGhost' could be found (are you missing a using directive or an assembly reference?) NitroxModel-Subnautica	C:\Users\******\Downloads\Nitrox\Nitrox - Copia\NitroxModel-Subnautica\DataStructures\GameLogic\Buildings\Rotation\SubnauticaRotationMetadataFactory.cs Line 24

### Steps to reproduce
clone the repo with git
use git clean -xdf
run the build.tool 
compile the solution 

### Other details:
It might be worth adding that, while i'm not sure if it's relevant, that BuildTool finishes with code 0. Also, i can't run dotnet restore before BuildTool, for some reason

**Comment by Measurity** [comment]
Build tool is required to run for the errors to disappear. I redid the steps you highlighted here and I cannot reproduce the issue. My hypothesis is that the build tool is unable to find your steam and/or game installation. Note: we do not support pirated copies of Subnautica (if that is the case here).

**Comment by Zakkious** [comment]
Not sure if it's relevant, but i have the Epic Games edition of the game

**Comment by Measurity** [comment]
Yes that's very relevant. This is the part of code that handles EGS game discovery: https://github.com/SubnauticaNitrox/Nitrox/blob/3075e0a5da51c93fd1cd28a77a9f43a67058cd8b/NitroxModel/Discovery/InstallationFinders/EpicGamesInstallationFinder.cs#L14

I commented out the other finders and it still succeeds for me (retraced the steps from your post). So if you could debug this for us we'd appreciate it and would integrate it into the code.

**Comment by Zakkious** [comment]
Sure, i'm not too good messing with C# and Visual Studio, but i'll try

**Comment by Zakkious** [comment]
Welp. A friend of my shared Subnautica with me on Steam (Family Sharing, y'know the deal), so i decided to try uninstalling the Epic Games version for now and try it on the Steam version. Unfortunately, now Nitrox.BuildTool doesn't even find the game (i think)

System.Exception: Game at: '\' is not a Unity game
   em Nitrox.BuildTool.Program.EnsureGame() na Nitrox.BuildTool\Program.cs:linha 72
   em System.Threading.Tasks.Task`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Nitrox.BuildTool.Program.<Main>d__5.MoveNext() na Nitrox.BuildTool\Program.cs:linha 35
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Nitrox.BuildTool.Program.<Main>(String[] args)
   
   It does say that it's not a Unity game, but that doesn't make any sense, so i'm not sure if it is locating my game at all. I'll try to build it right next to the game, maybe this could help

**Comment by Measurity** [comment]
`Game at: '' is not a Unity game`
This error is because the path to the game is empty (i.e. could not be found) and so it errors somewhere else further down that's unrelated.
