### ISSUE TITLE
Not showing multiplayer button

### ISSUE THREAD

**Issue by StiglCZ** [SubnauticaNitrox/Nitrox#1796]
V 1.6
I normally start subnautica with nitrox, but it's starting normally And showing singleplayer

**Comment by RivalsRebels** [comment]
1.Make sure you started Nitrox as Adminstrator
if you already started Nitrox as Adminstrator,start without it.
2.Make sure Nitrox is on the same Drive as Subnautica(if you have more then 1 drives)
3.Delete the "Managed folder" in the Subnautica Folder,and then Verify the Files
If the Problem Persits,Please join our Discord Server for further Troubleshoot.

**Comment by StiglCZ** [comment]
And if i don't have subnautica from Steam but from epic games?

**Comment by Measurity** [comment]
Then the same steps apply, you can verify files in epic games launcher here:
![image](https://user-images.githubusercontent.com/1107063/166682034-c5fe7111-3e1d-4862-a64d-1143815a4327.png)

**Comment by StiglCZ** [comment]
Ok I will do it
