### ISSUE TITLE
Vehicle destruction not syncing

### ISSUE THREAD

**Issue by paj1s** [SubnauticaNitrox/Nitrox#1797]
1.6.0.0

Seamoth of my friend was destroyed (for him) but i could enter it and see it had 3hp left and vice versa when i destroyed mine.

player.log seems fine but game.log in nitrox logs folder is full of errors. ->

https://pastebin.com/7raQMLDX

**Comment by prodigyrick** [comment]
Every vehicle exploded shows up after restart of client. Not all clients can see. I was able to repair one and drive it back after exploding.

**Comment by dartasen** [comment]
> Every vehicle exploded shows up after restart of client. Not all clients can see. I was able to repair one and drive it back after exploding.

This is not already true, only vehicle explosion due to huge desync will have this behaviour

**Comment by tornac1234** [comment]
Supposedly fixed by #1893
