### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [SubnauticaNitrox/Nitrox#1807]
https://hosted.weblate.org/projects/subnauticanitrox/website/#information says GPLv3-only, which people usually select when really wanting the GPLv3-or-later, which allows greater flexibility.

Can be changed in 
https://hosted.weblate.org/settings/subnauticanitrox/ingamesubnautica/
and
https://hosted.weblate.org/settings/subnauticanitrox/website/

Before people start translating would be a good time to do it :)

**Comment by Jannify** [comment]
Could you elaborate what the greater flexibility is?
The repo is licensed with GPLv3. It is where the translation is pushed to and the product distributed. Changing weblate to GPLv3-or-later would result in license inconsistency when GPLv4 comes out, wouldn't it?

**Comment by comradekingu** [comment]
@Jannify The greater flexibility is being able to move to AGPLv3, or A/GPLv4 when that comes out.
When or if the A/GPLv4 is released, there is no requirement to move to it.
The repo doesn't say "or later" or "only".
If the translated strings are GPLv3 or later, it also means more projects can use them, and no restriction is placed on base projects, one of which is Nitrox.
The translation license is set in Weblate, and agreed to by translators.
https://hosted.weblate.org/legal/terms/  3.2 and 6.2

**Comment by Jannify** [comment]
Changed it to GPLv3-or-later
