### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Anti-Apple4life** [SubnauticaNitrox/Nitrox#1809]
I use Linux as my daily driver, and I thought about the possibility of using the Nitrox Launcher without rebooting every time. Would that be possible? I already have QModManager working under Proton Experimental.

**Comment by dartasen** [comment]
> I use Linux as my daily driver, and I thought about the possibility of using Nitrox without rebooting every time. Would that be possible? I already have QModManager working under Proton Experimental.

What do you need exactly to get Nitrox working ?

Maybe you can give more details so we'll be able to help you

**Comment by Jannify** [comment]
You definitely can perma patch Subnautica with dnspy. Just remember that Nitrox needs the launcher path for some files which can be set with environment variables (see https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Main.cs).

**Comment by Anti-Apple4life** [comment]
One thing I did yesterday is extract nitrox files while the game was running, and Nitrox somewhat loaded in. It gave me the Qmod warning, but the normal play button was still there.
