### ISSUE TITLE
Building consumes resources for every player

### ISSUE THREAD

**Issue by Jannify** [SubnauticaNitrox/Nitrox#1812]
### Steps to reproduce

If a user partially breaks a structure it is not always synchronized to the others until the reboot or until the user rebuilds or completely removes it. When two players build at the same time by adding materials to the same structure, the players lose any extra materials from their inventory.

### Further notes - bug is triggered when player DOES NOT HAVE items required to finish building.

- 2x Titanium in inventory, player A
-  20x Titanium in inventory, player B
- Player A attempts to Build X Compartment, requires 3x Titanium
- As soon as Player A reaches build progress to pull third Titanium, Player B's inventory removes one Titanium per tick while Player A attempts to build

**Comment by tornac1234** [comment]
I can't seem to reproduce the bug, can someone else try it ?
