### ISSUE TITLE
Can't see any ui no matter what

### ISSUE THREAD

**Issue by Cloakam** [SubnauticaNitrox/Nitrox#1813]
### Version
1.6.0.0

### Bug
There have been probably thousands of people that encounter this at this point, but there isn't any ui when opening Subnautica through the Nitrox launcher.

### Expected
something

### Steps to reproduce
1. Start Subnautica Multiplayer through the launcher

### Other details:
The title screen map itself loads, and so does mods (I can tell because version checker is visible), and the cursor is visible. Also, before you say the solution everyone hears, I tried it, multiple times, never works. (the one everyone hears: delete managed and review integrity)
![image](https://user-images.githubusercontent.com/81453312/170381199-d8027228-b1d1-41e7-9190-b477e421024f.png)

**Comment by NinjaPedroX** [comment]
Any issues you encounter while using other mods with Nitrox may not be caused by Nitrox itself, as mods are not officially supported yet. I recommend trying to get Nitrox to work first without mods, and if you still have issues, you can seek help in the official Nitrox Discord server.

**Comment by Cloakam** [comment]
> Any issues you encounter while using other mods with Nitrox may not be caused by Nitrox itself, as mods are not officially supported yet. I recommend trying to get Nitrox to work first without mods, and if you still have issues, you can seek help in the official Nitrox Discord server.

oh my god, i cant believe i didnt try that, thanks
