### ISSUE TITLE
Random base parts

### ISSUE THREAD

**Issue by Cloakam** [SubnauticaNitrox/Nitrox#1814]
### Version
1.6.0.0

### Bug
Random base parts are build/removed, as if there was another player 😳 (herobrine in subnautica????)

### Expected
Everything to be as it was yesterday.

### Steps to reproduce
1. Start a server
2. Build things
3. Reload the area (rejoin, leave and come back to the biome, whatever)
4. oh, oh, oh, its maaagic
![image](https://user-images.githubusercontent.com/81453312/170529685-122f0a85-c35f-4565-92b6-33eea05cecdc.png)
![image](https://user-images.githubusercontent.com/81453312/170529959-d246b929-b297-49f7-8715-b87ec90263e8.png)

**Comment by Jannify** [comment]
Many base bugs are fixed in next release, therefore I will close the issue as all mentioned bugs should be solved
