### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Alberto247** [SubnauticaNitrox/Nitrox#182]
After the last update while compiling the code it returns the following error:
"Parameter "SkipNonexistentTargets" is not supported by the activity "MSBuild". Check that the parameter is present for the activity and that it is a public instance for the proprerty".
It's translated so it can be not exactly the same, but that's the meaning.
Can someone check/confirm the issue? It does not happens with the version just before this one.

**Comment by MarijnS95** [comment]
According to @Sunrunner37 the new autofac library refuses to deploy to his install directory as well, which is done by the same MSBuild file. I'll investigate as soon as I get home - maybe something got messed up with the merge.

**Comment by Alberto247** [comment]
After updating visual studio to the latest version the issue is solved, sorry for opening it before checking.

**Comment by MarijnS95** [comment]
Actually it's a good thing, thanks for confirming. Which VS version were you using?

**Comment by Alberto247** [comment]
The last one, version 15.5.7.

2018-03-02 17:26 GMT+01:00 MarijnS95 <notifications@github.com>:

**Comment by MarijnS95** [comment]
@Alberto247 @Sunrunner37 Please check #184 - let me know if this solves the issue in older VS versions.
