### ISSUE TITLE
Base not syncing and saving correctly

### ISSUE THREAD

**Issue by Gorgolyo** [SubnauticaNitrox/Nitrox#1822]
### Version
1.6.0.0

### Bug
Bases are saved and showed different for two players (for example, my base looked perfectly fine for me, while my friend saw it as destroyed, flooded, having extra components i deleted earlier. Quiting and rejoining seems to fix the issue for the current components, but later it reoccures with other ones. Also, sometimes certain components i build do not save, and the resources used to build them dissapear)

### Expected
Bases should look the same for every player, even if multiple have interacting with it and what i build should be saved correctly

### Steps to reproduce
Randomly occured for me while building a base, quitting and rejoining a couple of times for other reasons.

### Other details:
I was not aware of a manual save feature, so i relied on autosave, but i have never made changes to the world after an  autosave before quitting

**Comment by Jannify** [comment]
Most of this should be fixed in the next version
