### ISSUE TITLE
Player not moving and 90M away from lifepod

### ISSUE THREAD

**Issue by beans0256** [SubnauticaNitrox/Nitrox#1827]
### Version
 1.6.0.0

### Bug
 Player is not moving

### Expected
 player will be some distance away from the life pod. they will be in an A pose and will switch items that they are currently holding

### Steps to reproduce
 Play with 3 players on LAN

### Other details:
![e](https://user-images.githubusercontent.com/109005596/178126807-95ba74a1-ecc4-4b5d-8b79-0888883e70e1.jpg)

we are playing 3 players, on LAN, the player that is not moving is on windows 11 and we are on windows 10, me and the other player that could see each other move are on pc, while the other player is on laptop

**Comment by Jannify** [comment]
This looks more like a setup error (probably firewall) and not a real bug. You can seek help to solve this in our discord. Closing the issue for now.
