### ISSUE TITLE
Player cap bug

### ISSUE THREAD

**Issue by Alberto247** [SubnauticaNitrox/Nitrox#183]
Looks like when the fourth player enters the game everyone else's client crashes.

**Comment by Sunrunner37** [comment]
Do you have any stack traces or reason for the crash?  Can anyone else confirm this one?

**Comment by Alberto247** [comment]
I forgot to post them, sorry.
The log is actually very strange: 
-The server says nothing but the common disconnect message
-The client logs the following:
"[Nitrox] I: Error reading data from socket: An existing connection was forcibly closed by the remote host
[Nitrox] I: No data found from socket, disconnecting
[Nitrox] D: Error reading data from server
[Nitrox] I: Error closing socket -- probably already closed"
Then it says:
"========== OUTPUTING STACK TRACE ==================

  ERROR: SymGetSymFromAddr64, GetLastError: 'attempt to access invalid address.' (Address: 00007FF6D2EB3C38)
0x00007FF6D2EB3C38 (Subnautica) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'attempt to access invalid address.' (Address: 00007FF6D2EB43C6)
0x00007FF6D2EB43C6 (Subnautica) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'attempt to access invalid address.' (Address: 00007FF6D2EBCAA2)
0x00007FF6D2EBCAA2 (Subnautica) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'attempt to access invalid address.' (Address: 00007FF6D2EBF6F2)
0x00007FF6D2EBF6F2 (Subnautica) 
  ERROR: SymGetSymFromAddr64, GetLastError: 'attempt to access invalid address.' (Address: 00007FF6D2EF2684)
0x00007FF6D2EF2684 (Subnautica) 
0x000000001F87421C (Mono JIT Code) (wrapper managed-to-native) UnityEngine.TextGenerator:INTERNAL_CALL_Populate_Internal_cpp (UnityEngine.TextGenerator,string,UnityEngine.Font,UnityEngine.Color&,int,single,single,UnityEngine.FontStyle,bool,bool,int,int,int,int,bool,UnityEngine.TextAnchor,single,single,single,single,bool,bool,uint&)
0x000000001F873F3C (Mono JIT Code) [C:\Subnautica\plastic_workspace_unity\artifacts\generated\common\modules\TextRendering\TextRenderingBindings.gen.cs:782] UnityEngine.TextGenerator:Populate_Internal_cpp (string,UnityEngine.Font,UnityEngine.Color,int,single,single,UnityEngine.FontStyle,bool,bool,int,int,int,int,bool,UnityEngine.TextAnchor,single,single,single,single,bool,bool,uint&) 
0x000000001F873C9F (Mono JIT Code) [C:\Subnautica\plastic_workspace_unity\artifacts\generated\common\modules\TextRendering\TextRenderingBindings.gen.cs:761] UnityEngine.TextGenerator:Populate_Internal (string,UnityEngine.Font,UnityEngine.Color,int,single,single,UnityEngine.FontStyle,bool,bool,int,int,UnityEngine.VerticalWrapMode,UnityEngine.HorizontalWrapMode,bool,UnityEngine.TextAnchor,UnityEngine.Vector2,UnityEngine.Vector2,bool,bool,UnityEngine.TextGenerationError&) 
0x000000001F873196 (Mono JIT Code) [C:\Subnautica\plastic_workspace_unity\Runtime\TextRendering\Managed\TextGenerator.cs:266] UnityEngine.TextGenerator:PopulateAlways (string,UnityEngine.TextGenerationSettings) 
0x000000001F872B65 (Mono JIT Code) [C:\Subnautica\plastic_workspace_unity\Runtime\TextRendering\Managed\TextGenerator.cs:250] UnityEngine.TextGenerator:PopulateWithError (string,UnityEngine.TextGenerationSettings) 
0x000000001F8A9876 (Mono JIT Code) [C:\Subnautica\plastic_workspace_unity\Runtime\TextRendering\Managed\TextGenerator.cs:241] UnityEngine.TextGenerator:Populate (string,UnityEngine.TextGenerationSettings) 
0x000000001F90B529 (Mono JIT Code) [C:\Subnautica\plastic_workspace_unity\Runtime\TextRendering\Managed\TextGenerator.cs:213] UnityEngine.TextGenerator:GetPreferredWidth (string,UnityEngine.TextGenerationSettings) 
0x000000001F90B2A3 (Mono JIT Code) UnityEngine.UI.Text:get_preferredWidth ()
0x0000000022E867B7 (Mono JIT Code) ErrorMessage:_AddMessage (string)
0x0000000022E860D4 (Mono JIT Code) ErrorMessage:AddError (string)
0x0000000022E85FDD (Mono JIT Code) ErrorMessage:AddMessage (string)
0x0000000022E85EAC (Mono JIT Code) NitroxModel.Logger.Log:InGame (string)
0x000000000356A755 (Mono JIT Code) NitroxClient.Communication.TcpClient:Stop ()
0x0000000024ADFACC (Mono JIT Code) NitroxClient.Communication.TcpClient:DataReceived (System.IAsyncResult)
0x0000000024AD5B86 (Mono JIT Code) System.Net.Sockets.Socket/SocketAsyncResult:Complete ()
0x0000000024ADF567 (Mono JIT Code) System.Net.Sockets.Socket/Worker:Receive ()
0x0000000007AD5BF2 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFEA7A8AE0C (mono) mono_walk_stack
0x00007FFEA79E8AA5 (mono) mono_runtime_invoke
0x00007FFEA79E8FAC (mono) mono_runtime_invoke_array
0x00007FFEA79E696D (mono) mono_load_remote_field_new
0x00007FFEA7A09E9B (mono) mono_security_set_mode
0x00007FFEA7A09551 (mono) mono_security_set_mode
0x00007FFEA7A0E360 (mono) mono_unity_thread_fast_detach
0x00007FFEA7B181B0 (mono) unity_mono_reflection_method_get_method
0x00007FFEDB851FE4 (KERNEL32) BaseThreadInitThunk
0x00007FFEDD18EFC1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**** Crash! ****
[Nitrox] I: Cannot send packet to a closed connection."


We made sure this happens to everyone, it doesn't matter who is the fourth player.

**Comment by Alberto247** [comment]
It looks like the server was closed, but it wasn't and we were still able to rejoin in without restarting it.
What's more the fourth player can join with no problems on his side.

**Comment by MarijnS95** [comment]
@Alberto247 I have identified the issue.

We are setting an array to a `readonly` field, which does not play nice with the Garbage Collector: the local array gets collected and is thus not entirely available in future calls. The readonly field is not `null`, but the data it points to doesn't really exist anymore either; this causes the entire engine to crash.

I have a fix ready, but have heard that this entire system will be done differently anyway.

Before I forget to mention (FYI): that array modification happens on every client when someone else joins, such that we can have more ping colors. Initially the error happened at that `Log.Ingame` line for me as well, because the internal state got corrupted. Commenting it out revealed the real issue.
