### ISSUE TITLE
Floating Unfinished/Red Blueprints 

### ISSUE THREAD

**Issue by BigFellaRT** [SubnauticaNitrox/Nitrox#1833]
### Version

1.6.0.0
### Bug

It's the floating blueprint bug, but every thread on it references a dead link, issue #1400. I just want to know if they came to any conclusions in that thread that could be a fix.

**Comment by NinjaPedroX** [comment]
This bug has been fixed/improved for the next release. See more here: https://github.com/SubnauticaNitrox/Nitrox/commit/9eaa8eba403444c65f46c19645da1af4fac8953c

**Comment by wowpiglet** [comment]
I have this same bug. Not sure what im supposed to do to it now.

**Comment by TheLxkas** [comment]
https://tornac1234.github.io/
This was made by one of our Programmers.
I know it looks sketchy but it works.
So try that.
