### ISSUE TITLE
Beacon & modification station bug

### ISSUE THREAD

**Issue by Laamy** [SubnauticaNitrox/Nitrox#1835]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you bought Subnautica?

Steam

### Describe the issue.

Beacons dont spawn where they should (Same with the modification station

### Describe the steps you took to encounter the bug.

beacons aren't on the map at all (I searched for hours) and modification stations aren't in wreckages anymore (I could only find 2 on the map in total)

**Comment by Gus887** [comment]
issue is already fixed on master
