### ISSUE TITLE
Please write an informative title describing the bug in a few words

### ISSUE THREAD

**Issue by prodigyrick** [SubnauticaNitrox/Nitrox#1837]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you bought Subnautica?

Steam

### Describe the issue.

Misc. Issues:
Invisible wall/bubble in multipurpose room. Unremovable half deconstructed entryway. Destroyed seamoth now visible and enterable on client reload, permanently. Deconstruction of one build material (ie hatch) can be deconstructed and rebuilt endlessly creating duped materials by both parties endlessly.

### Describe the steps you took to encounter the bug.

Bubble in room developed over time. Other rooms didn't experience this issue.
Unremovable half deconstructed hatch totally random.
Destroyed seamoth always visible and can be entered by myself but now the party that destroyed it.
Duped materials form by having 2 players deconstruct and reconstruct base pieces at the same time. One would build or destroy  and the other did the same and it would be like out of sync collecting materials out of thin air.

**Comment by Jannify** [comment]
The issues you described are already fixed in the next release or have their own separate issues already. Therefore I am closing this.
