### ISSUE TITLE
Gameplay missing components..

### ISSUE THREAD

**Issue by prodigyrick** [SubnauticaNitrox/Nitrox#1838]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you bought Subnautica?

Steam

### Describe the issue.

Pod 3 wont show.
No prawn suit arms spawn even when they will on normal subnautica gameplay in single player mode at same spots.
No battery chargers, nuclear reactor parts, etc.

### Describe the steps you took to encounter the bug.

Verified bugs via single player.  -865 -430 -1420 should have many prawn components for instance and in this build, all are missing. This is just one location among all of them missing components. No mods run when verifying.

**Comment by Jannify** [comment]
The pod spawning bug already has an issue and the rest is fixed on master. Therefore I am closing this issue.
