### ISSUE TITLE
Bioreactor causes Base errors, void access.

### ISSUE THREAD

**Issue by prodigyrick** [SubnauticaNitrox/Nitrox#1840]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you bought Subnautica?

Steam

### Describe the issue.

Standing in a multiroom, I placed a new 4way and a corridor attached to a new multiroom and set down a brand new bio reactor. Other player was in base and I was placing a window. The 4 way, and everything after it disappeared except for the multiroom with the bioreactor. Not sure exactly what caused it but If you step out where the 4 way was at it drops you into the void. I died and went through it again without dying at nearly 4k below the map before typing warpme.

### Describe the steps you took to encounter the bug.

I'm not entirely sure but most likely the old bug that causes a duplicate offset base part after trying to deconstruct any random part.

### Relevant log output

Game[Player]: http://improdigy.com/files/game[Prodigy]-20220809.log
Game: http://improdigy.com/files/game-20220809.log
Server: http://improdigy.com/files/server-20220809.log

**Comment by tornac1234** [comment]
Same as in https://github.com/SubnauticaNitrox/Nitrox/issues/1844#issuecomment-1229457826
