### ISSUE TITLE
Duplicate items on /back

### ISSUE THREAD

**Issue by prodigyrick** [SubnauticaNitrox/Nitrox#1841]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you bought Subnautica?

Steam

### Describe the issue.

Type /back after death.

### Describe the steps you took to encounter the bug.

Friend typed /back after dying. Ended up with duped items.

### Relevant log output

Game: http://improdigy.com/files/game-20220809.log
Server: http://improdigy.com/files/server-20220809.log

**Comment by tornac1234** [comment]
I can confirm that bug

**Comment by dartasen** [comment]
@ywgATustcbbs we did not adress this issue yet
