### ISSUE TITLE
The baseupgradeconsole vanishes on exiting game.

### ISSUE THREAD

**Issue by prodigyrick** [SubnauticaNitrox/Nitrox#1844]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Placing baseupgradeconsole works great until leaving the server for the one who placed it. Soon after it vanishes upon rejoining.

### Describe the steps you took to encounter the bug.

Placed the baseupgradeconsole, left and rejoined.

**Comment by tornac1234** [comment]
Tested it with #1819 and it seems to work. Would you mind testing it yourself with the same steps ?

**Comment by wheeler7** [comment]
Hi,
I have the same issue with disapearing baseupgradeconsole after rejoining server which was not stopped meanwhile.

OS: Windows
Platform: Steam
Nitrox version: 1.6.0 and 1.6.1
