### ISSUE TITLE
Buildings in base disappeared

### ISSUE THREAD

**Issue by ywgATustcbbs** [SubnauticaNitrox/Nitrox#1846]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

No need to describe, just see the screen shot.

![1](https://user-images.githubusercontent.com/11514506/184811005-be69fd81-1b20-4487-9a2f-e9002dfe7c51.png)

### Describe the steps you took to encounter the bug.

No idea how to repeat. But here is what i did before the bug.

Base was OK before I built the scanner room. Then I built a second door to the scanner room.

When building second door, it stucked at 90%. Then I canceled building. Bug occured.

**Comment by ywgATustcbbs** [comment]
![1](https://user-images.githubusercontent.com/11514506/184811100-1efe6ae9-06d4-43a6-9921-813056180fc2.png)

**Comment by tornac1234** [comment]
Please look at #1823

**Comment by Jannify** [comment]
Duplicate #1823
