### ISSUE TITLE
Scanning blueprint still not persistent?

### ISSUE THREAD

**Issue by dohay2314** [SubnauticaNitrox/Nitrox#1849]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Whenever I have a partially unlocked blueprint on my account and restart the server, I loose the progress on the blueprint and have to start again but the fragments are still gone, this can make progressing in difficult blueprints a bit difficult.

### Describe the steps you took to encounter the bug.

Have a partially unlocked blueprint and then restart the server.

**Comment by Crapy** [comment]
This also happens to me, very annoying

**Comment by Jannify** [comment]
This should be fixed long ago by #1624. Are you sure this is not caused by something else? Did you encounter that bug in a fresh save?
