### ISSUE TITLE
Modification Station Fragments are no where to be found 1.6.0.0

### ISSUE THREAD

**Issue by Corbino31** [SubnauticaNitrox/Nitrox#1852]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Modification Station Fragment can’t be found anywhere

### Describe the steps you took to encounter the bug.

Me and my friend started a server got as far as raiding the aurora and couldn’t find any fragments. We even started a new server.

**Comment by Crapy** [comment]
Can confirm that this https://github.com/SubnauticaNitrox/Nitrox/pull/1819 fixes the issue

**Comment by Jannify** [comment]
Duplicate

**Comment by Corbino31** [comment]
How do we duplicate

**Comment by Corbino31** [comment]
> Duplicate

How do we duplicate

**Comment by NinjaPedroX** [comment]
> > Duplicate
> 
> How do we duplicate 

That means that your issue is a duplicate of another issue, so yours was closed. Please join the official Nitrox server for help on this: https://discord.gg/E8B4X9s
