### ISSUE TITLE
Random floating indestructible blueprints

### ISSUE THREAD

**Issue by Memphisros** [SubnauticaNitrox/Nitrox#1854]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Whenever I rejoin the server these random indestructible building pieces appear that I cannot finish building them or deconstruct them.
![2022-09-04_00024](https://user-images.githubusercontent.com/112842913/188491848-069a15f7-cdae-4e76-924f-ccd6694d14ec.jpg)
![2022-09-04_00025](https://user-images.githubusercontent.com/112842913/188491851-a8b0d742-0272-430c-b838-01d5a4aad9bd.jpg)
![2022-09-04_00026](https://user-images.githubusercontent.com/112842913/188491853-ff7f12af-35fd-4e19-8f65-3759df46e72c.jpg)

### Describe the steps you took to encounter the bug.

No clue how they appeared.

**Comment by Gus887** [comment]
https://tornac1234.github.io/redpieces_removing.html
try using this fix to remove them
if you have any trouble with this, please join our discord server

**Comment by Memphisros** [comment]
> https://tornac1234.github.io/redpieces_removing.html try using this fix to remove them if you have any trouble with this, please join our discord server

Thank you so much
