### ISSUE TITLE
mplayer command doesn't work

### ISSUE THREAD

**Issue by ghost** [SubnauticaNitrox/Nitrox#186]
I know the mplayer command was broken, but it started working a few commits ago. But with the f/clean disconnect commit it stopped working again... should i change something? My output log gives these errors: 
[Nitrox] I: Behaviours applied.
InvalidOperationException: You must begin a new lifetime scope before resolving dependencies.
  at NitroxModel.Core.NitroxServiceLocator.CheckServiceResolutionViability () [0x00000] in <filename unknown>:0 
  at NitroxModel.Core.NitroxServiceLocator.LocateService[IMultiplayerSession] () [0x00000] in <filename unknown>:0 
  at NitroxClient.MonoBehaviours.Gui.Chat.PlayerChatEntry.Awake () [0x00000] in <filename unknown>:0 

Are these supposed to happen?

**Comment by MarijnS95** [comment]
Pinging @MadMaxOfYore:

AFAIK this doesn't have much to do with the chat, but the class that initializes these commands seems to do the same: asking the IoC for an object before a new lifetime scope is started.

I'm wondering why it did work though; console commands get removed when a game session is started, according to a previous assessment. As far as I can see we're still instantiating these commands when the game starts, rather than when it switches to the actual playing scene.

**Comment by yenzgamingyt** [comment]
Well the command worked in the main menu, and now it wont work at all.. just nothing and these errors....

**Comment by yenzgamingyt** [comment]
I noticed i also get these as well:
[Nitrox] I: Applying Nitrox behaviours..
InvalidOperationException: You must begin a new lifetime scope before resolving dependencies.
  at NitroxModel.Core.NitroxServiceLocator.CheckServiceResolutionViability () [0x00000] in <filename unknown>:0 
  at NitroxModel.Core.NitroxServiceLocator.LocateService[IMultiplayerSession] () [0x00000] in <filename unknown>:0 
  at NitroxClient.MonoBehaviours.Gui.MainMenu.ConsoleJoinServer.Awake () [0x00000] in <filename unknown>:0

**Comment by yenzgamingyt** [comment]
Any news on this?
Still haven't figured it out, I did look into it a lot more and saw that the "lifetime scope" part is the origin of the  error's. is this a new thing? I compiled the whole project a few times after and saw that some had issues with "Autofac" And the lifetime scope thingy..... Please help.

**Comment by Measurity** [comment]
Hi yenzgamingyt,

I'm working on fixing this issue. Though in order to do it properly I'll need some time. I try to submit a PR today.

**Comment by yenzgamingyt** [comment]
Hi Measurity,

Thanks, I am really looking forward to the PR! Can't seem to figure this out myself XD

**Comment by MadMaxOfYore** [comment]
@Measurity 

We should only need a couple of things.

1. Spin the `ConsoleJoinServer` behavior up with a `GameObject` that does not get destroyed when a scene changes.

2. Call `NitroxServiceLocator.BeginNewLifetimeScope()` from the `mplayer` command handler.

**Comment by Measurity** [comment]
@MadMaxOfYore 

I wanted to begin a new lifetimescope when the server starts so I refactored the JoinServer/ConsoleJoinServer code and moved it into Multiplayer (excluding the UI parts). Though there are some exceptions that probably have to do with the order in which things are initialized (packets, terrain, crash fish spawning and the like).

It's almost ready but I still need to do testing.

**Comment by MadMaxOfYore** [comment]
It should also be noted, for posterity if nothing else, that the current plan is to deprecate the mplayer command entirely once we get to a prod-ready state. It is not extensible and creates a undo burden on the dev team to maintain. 

My next PR introduces persistent player preferences. The mplayer command *will not* be retrofitted to take advantage of that feature (at least not by me - I have much better things to do with my time honestly...) I would expect the list of things that you lose out on by using the command line vector to grow as we get closer to an official release. 

The one reason that it is still there for the time being is that it is the only way for anyone to spin up a session with a prior save. This command will absolutely be on the chopping block once that changes. I would strongly urge the community to not rely on this mechanism in the long-run.

**Comment by MadMaxOfYore** [comment]
@Measurity 

The lifetime scope needs to begin before the session starts, not afterwards. You will not be able to resolve the reference to the multiplayer session object otherwise.
