### ISSUE TITLE
Player is displayed half transparent 

### ISSUE THREAD

**Issue by JannesStroehlein** [SubnauticaNitrox/Nitrox#1860]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

![image](https://user-images.githubusercontent.com/48127946/189521076-5ac051ce-42d9-4406-82ac-8029e5bb79a8.png)

A player is half transparent. 

### Describe the steps you took to encounter the bug.

We both restarted Nitrox and the server and joined.

**Comment by Jannify** [comment]
Could you upload you log? That way we can identify what is going wrong.

**Comment by JannesStroehlein** [comment]
Sorry, but I don't have the specific log file anymore.

**Comment by Jannify** [comment]
Then I will close this issue for now. If we or some other players encounter it I will reopen this issue accordingly.
