### ISSUE TITLE
Im trying to build Nitrox in Visual Studio with unity, but I'm getting a Error

### ISSUE THREAD

**Issue by sajddrhndhj** [SubnauticaNitrox/Nitrox#1861]
### Describe the issue

Everytime I get an Error Message when I try to build
`'Error	CS0246	The type or namespace name 'LiteNetLib' could not be found (are you missing a using directive or an assembly reference?)' `
i think it has to do with the folder being empty... plz help

**Comment by sarayuuki** [comment]
Ping me in the discord server, @Garuda Yazumi#0001

**Comment by dartasen** [comment]
Please don't use github issues for problems that are not related to nitrox directly, we do not offer support for that.
