### ISSUE TITLE
Nitrox not working with the new update on linux

### ISSUE THREAD

**Issue by chicco-carone** [SubnauticaNitrox/Nitrox#1864]
### Describe the issue

i tried to run nitrox on linux using wine/proton/and steam and it gave me the same error, that it couldn't read this file "system.windows.controls.ribbon" but when i tried 1.5 it worked flawlessly

**Comment by Jannify** [comment]
"system.windows.controls.ribbon" doesn't sound like anything from the Nitrox code base, so maybe it has something to do with your setup/start method.
Unfortunately we can't really help with the unofficial linux support. Once the Subnautica update lands we will certainly work on full linux support (see #988)
