### ISSUE TITLE
When a base is removed by an other player and you are inside, your inventory is lost

### ISSUE THREAD

**Issue by RedRelay** [SubnauticaNitrox/Nitrox#1865]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

My friend Mayline was inside a base I've just built.
When inside, I removed the base with the building tool

Mayline does not died but lost every items in her inventory except equipped items.
Leave then join does not fix it 

### Describe the steps you took to encounter the bug.

* Player A build a base
* Player B go inside
* Player A destroy base using tool

### Relevant log output

Game : https://pastebin.com/kZp0yx4B

**Comment by tornac1234** [comment]
I assumed it was ridiculous at first but after testing it, I can confirm this bug is real
