### ISSUE TITLE
Server dir error

### ISSUE THREAD

**Issue by DuduMedtler** [SubnauticaNitrox/Nitrox#187]
When I start the server this error occurs indicating that I can not find the game directory.
I have the non-original game :/
The game is installed under Program Files.

> [Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game fi
les are needed to run the server.
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in cu
rrent or parent directory and readable.
   em NitroxServer.Serialization.ResourceAssetsParser.findPath() na C:\Users\duz
zy\Documents\Nitrox\NitroxServer\Serialization\ResourceAssetsParser.cs:linha 95
   em NitroxServer.Serialization.ResourceAssetsParser.parse() na C:\Users\duzzy\
Documents\Nitrox\NitroxServer\Serialization\ResourceAssetsParser.cs:linha 18
   em NitroxServer.Communication.Packets.PacketHandler..ctor(PlayerManager playe
rManager, TimeKeeper timeKeeper, SimulationOwnership simulationOwnership) na C:\
Users\duzzy\Documents\Nitrox\NitroxServer\Communication\Packets\PacketHandler.cs
:linha 28
   em NitroxServer.Server..ctor() na C:\Users\duzzy\Documents\Nitrox\NitroxServe
r\Server.cs:linha 17
   em NitroxServer.Program.Main(String[] args) na C:\Users\duzzy\Documents\Nitro
x\NitroxServer\Program.cs:linha 14 

> 

>

**Comment by Alberto247** [comment]
We don't support pirated copies of the game. Please consider buying it if you want to use this mod.
