### ISSUE TITLE
my friend cant joint the server 

### ISSUE THREAD

**Issue by kokito741** [SubnauticaNitrox/Nitrox#1882]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

i have port forward it rand both me and my friend have reinstalled bot the game and nitrox. We know its not the antivirus.
[game-20221026.log](https://github.com/SubnauticaNitrox/Nitrox/files/9873060/game-20221026.log)
[server-20221026.log](https://github.com/SubnauticaNitrox/Nitrox/files/9873073/server-20221026.log)
here are both logs

**Comment by Measurity** [comment]
A few things to note:
 - Did you friend use your public IP to connect? It's shown when the server starts in this line: 
 `x.x.x.x - Friends on another internet network (Port Forwarding)`
 - Did you host other servers before (e.g. Minecraft)? If you didn't, then you might need to use a VPN like Hamachi to play Nitrox together.
 
If you need further assistance then it'd be faster to join our Discord server and contact our support team directly in **#help-channel**: https://discord.gg/E8B4X9s
