### ISSUE TITLE
Subnautica is not launching

### ISSUE THREAD

**Issue by itmeyes** [SubnauticaNitrox/Nitrox#1887]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Hello, ive installed everything as normal. now wehn i want to stard the Multiplayer nothing happens, it showes up in the taskbar for a sec. and then dissapears.

### Describe the steps you took to encounter the bug.

ive dienstalled it and reinstalled it like 20 times, watch every vidio i could find, nothing worked

### Relevant log output

[6XgvnGPZ (1).txt](https://github.com/SubnauticaNitrox/Nitrox/files/9890280/6XgvnGPZ.1.txt)

**Comment by RivalsRebels** [comment]
Have you runned Nitrox as administrator, if you did try without it.
Keep in mind that we only offer support in our discord server. This issue will be closed

**Comment by Jannify** [comment]
I would like to promote our discord for common issues regarding Nitrox. Our staff can help you with them and can easily identify if it's a real bug or some issue with your setup/PC. GitHub should ideally be a place were reproducible and verified issues are posted.
