### ISSUE TITLE
Chat keybind keep resetting

### ISSUE THREAD

**Issue by Zanzancomms** [SubnauticaNitrox/Nitrox#1897]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Epic

### Describe the issue.

Chat key bind(default is Y) doesn't save when you change it to another key, it always reset to the default key whenever you open the game again, asked a couple other people and they said it also happened to them too.

### Describe the steps you took to encounter the bug.

-Opening the game
-Change chat keybind from Y to any other key in keyboard options (in-game or just main menu)
![image](https://user-images.githubusercontent.com/68141931/200155890-2b2ed4de-8860-4c88-922c-8b57d055663d.png)

-Restart game at any time(after being in-game or just main menu)
-Keybind resets to the default one when opening the game again

![image](https://user-images.githubusercontent.com/68141931/200155914-b56ed0f7-1867-4a04-9ba2-53177e56718f.png)

**Comment by Ironwally** [comment]
This bug also seems to apply to "Focus Discord (Alt +)"

**Comment by Ironwally** [comment]
A little more new information on the issue:
The file, where the information is saved, is updated when the options menu is closed. This happens, when your in Game and when your in the main Menu. 
But, while you are in the main Menu, eventhough the file is updated, changed keybinds are not saved/changed in the file.
While in game, keybinds are indeed saved to the file, when closing the options menu.

After Restart:
The Keybinds defaults are show in the options directly after restart, though are not jet changed in the file. Only after oppening options and closing them again, the file is updated. Changing the keybinds now, will as mentioned before NOT change the keybinds saved in the file. This will only happen when closing options while in game.

This only applies to the two nitrox keybinds. SN keybinds are updated correctly while in the main menu.
