### ISSUE TITLE
Issue while building the solution 

### ISSUE THREAD

**Issue by MixaMega** [SubnauticaNitrox/Nitrox#1900]
### Describe the issue

I followed the instructions for setting up the development environment for nitrox, but ran into an issue while building it
![image](https://user-images.githubusercontent.com/93724648/200973385-c52d7919-ff85-432a-ad52-0c0a36590edb.png)

**Comment by Jannify** [comment]
Pls reach out to me in our Discord server. You are allowed to mention/tag me in the help channel (Jannify#2211)

**Comment by Measurity** [comment]
Discord: https://discord.gg/E8B4X9s

In the meantime try:

1. Restarting Visual Studio
2. Building with `dotnet build Nitrox.BuildTool` and then `dotnet build`.

See the "setting up a dev environment" wiki on this repository.
