### ISSUE TITLE
Please write an informative title describing the bug in a few words

### ISSUE THREAD

**Issue by Ayosm** [SubnauticaNitrox/Nitrox#1901]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Bioreactor is unfinished upon rejoining

### Describe the steps you took to encounter the bug.

Built the bioreactor, closed server, restarted and bioreactor was not finished being built.

**Comment by Jannify** [comment]
Is fixed with #1819 in next release
