### ISSUE TITLE
Unlimited titanium since 2nd player crashed and reconnected

### ISSUE THREAD

**Issue by thecrazy** [SubnauticaNitrox/Nitrox#1909]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

I was transferring titanium from storage to my inventory. It was no longer being removed from the storage and I can fill my inventory with it.

### Describe the steps you took to encounter the bug.

2nd player crashed and reconnected while I was transferring titanium between storage and inventory

**Comment by Jannify** [comment]
Moving to #2047
