### ISSUE TITLE
whenever a client connects to the server a new game starts

### ISSUE THREAD

**Issue by daromero2** [SubnauticaNitrox/Nitrox#191]
the server starts a new game when you enter the game and does not load the saved data. Anyone knows how to solve this?

**Comment by MarijnS95** [comment]
This question has been asked a bunch of times already: https://github.com/SubnauticaNitrox/Nitrox/issues?=is%3Aissue+save.

In short: solve it in code and contribute that to the repo. We haven't had the time to look into this yet.
