### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by Reflexistaken** [SubnauticaNitrox/Nitrox#1911]
### Describe the issue

Hi, is there any way that you would be able to make mac support in the future or compile the file in any way? I suck at coding btw

Thanks

**Comment by ikir83** [comment]
Any official update?

**Comment by dartasen** [comment]
@ikir83 We're still working on it as a background task, most of the team is focused on releasing 1.8 first, we'll communicate on our networks once the POSIX support is available.

**Comment by ikir83** [comment]
Thanks for the update
