### ISSUE TITLE
entities missing with recent subnautica update

### ISSUE THREAD

**Issue by ywgATustcbbs** [SubnauticaNitrox/Nitrox#1921]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Nitrox isn't fully compatible with subanutica's Dec 14, 2022 update, all enties including fishes and resources will disappear.

### Describe the steps you took to encounter the bug.

n/a

**Comment by Jannify** [comment]
https://twitter.com/ModNitrox/status/1602812078733017088
