### ISSUE TITLE
Nitrox on linux

### ISSUE THREAD

**Issue by chicco-carone** [SubnauticaNitrox/Nitrox#1922]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Linux (currently not supported, don't file any reports if your are using this)

### On which platform did you buy Subnautica?

Epic

### Describe the issue.

I read in the changelog that there was improvements and platform detection on linux system, so obviously i tried to play the game and it just gives me the same error that it gave me with the precedent version (could not load the file 'system.windows.controls.ribbon') the latest version that used to work was 1.5.1.0

**Comment by Jannify** [comment]
Duplicate #988
