### ISSUE TITLE
i cant connect any server

### ISSUE THREAD

**Issue by GoodNlCE** [SubnauticaNitrox/Nitrox#194]
When i try connect any server, nothing happen, but i should see the window where i enter my username.
![hdgjghhgjfdgdfgdfgd](https://user-images.githubusercontent.com/37265955/37256080-fb8585e2-2566-11e8-9c52-f2ddb1b9bfe5.PNG)

**Comment by minerprosk** [comment]
me too

**Comment by Banan1447** [comment]
The same problem
![image](https://user-images.githubusercontent.com/37272362/37256372-c930811a-256a-11e8-867f-ac59704a8ff8.png)

**Comment by Banan1447** [comment]
"Вызвано исключение по адресу 0x000000002A539B3D в Subnautica.exe: 0xC0000005: нарушение прав доступа при чтении по адресу 0x0000000000000000."

**Comment by GoodNlCE** [comment]
Now, its work, thanks!
