### ISSUE TITLE
Blueprint progress lost when restarting client and rejoining.

### ISSUE THREAD

**Issue by Grainen** [SubnauticaNitrox/Nitrox#1955]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When i restart Subnautica and join back in. If i scan a fragment that i already made progress on, the progression gets reset to one.
I have to unlock the whole blueprint in one session, if i dont want to lose progress on it.
It seems that when joining the server and scanning something that already has progress on it, overwrites it.

### Describe the steps you took to encounter the bug.

1. Scanned a fragment of something i haven't unlocked yet.
2. Closed Subnautica (Only the client).
3. Rejoined.
4. Scanned the same fragment.
5. Ta da! Blueprint progress reset for everyone.

**Comment by QuintonWhited** [comment]
Same issue, +1

**Comment by vakkanslj** [comment]
+1

Have the same issue ! (we are 3 players)

What we did, is, we knew we had found enough fragments, we just spawned with commands subject fragments.

**Comment by Rjomik** [comment]
+1

**Comment by Jannify** [comment]
Should be fixed with #1967
