### ISSUE TITLE
cyclops power running out very quick

### ISSUE THREAD

**Issue by Lt0Tactical** [SubnauticaNitrox/Nitrox#1976]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

cyclops power seems to be running out incredibly quickly, barely lasting 2-3 minutes. also I think it was exponentially getting worse?

### Describe the steps you took to encounter the bug.

play the game while using cyclops a lot with a 2nd player using another vehicle

**Comment by JKX-Jakubix** [comment]
Same issue here.

**Comment by The-Great-Sephiroth** [comment]
Are you guys running on silent or max speed? I played with a friend for HOURS yesterday on our server. I built the cyclops and we travelled al over in it, carrying around a prawn suit and using it also. Battery drain in both vehicles was normal. Do we both need to by in cyclops subs to trigger this?

**Comment by Jannify** [comment]
Duplicate of #1293
