### ISSUE TITLE
how i can save my progress in game?

### ISSUE THREAD

**Issue by Menenn** [SubnauticaNitrox/Nitrox#198]
I recently installed the mod, but the world is not saved and the features are generated 2x, is this a bug or do I need to configure something?

**Comment by yenzgamingyt** [comment]
From what i know i can say that saving is not implemented yet. Atleast not in a usable way. We had a way of connecting after closing the server via the mplayer command but i think the mod makers are deprecating that.. So yeah no saving progress for now...

**Comment by Sunrunner37** [comment]
Closing as this is now implemented
