### ISSUE TITLE
Deconstructing a base part that requires enameled glass instead returns normal glass.

### ISSUE THREAD

**Issue by QuintonWhited** [SubnauticaNitrox/Nitrox#1980]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Deconstructing a base part that requires enameled glass instead returns normal glass. Example base piece is Observatory.

### Describe the steps you took to encounter the bug.

1. Build an observatory using enameled glass.
2. Deconstruct Observatory.
3. Instead of getting enameled glass, you get regular glass.

**Comment by tornac1234** [comment]
Couldn't reproduce issue with #1952
