### ISSUE TITLE
Game Crash on lan discovery 

### ISSUE THREAD

**Issue by bud3699** [SubnauticaNitrox/Nitrox#1983]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Being in the Multiplayer tab while a server is discovered crashes the game. 

### Describe the steps you took to encounter the bug.

Head into the multiplayer tab 
Start the server and wait
The game then crashes

### Relevant log output

Game: https://pastebin.com/sWgx6R2F
You don't even get to do anything on the server aha

**Comment by dartasen** [comment]
Will be closed by #2055
