### ISSUE TITLE
Water purification machines vanish on reconnect or restart...

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [SubnauticaNitrox/Nitrox#1988]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Upon building a base with a water purification machine and leaving, then rejoining the server, the purification machines are all gone. You can create new ones, but the old ones are completely gone, even if you don't turn off the server and simply exit and then join the server again.

### Describe the steps you took to encounter the bug.

Built a base with two purification machines. Exited the game. Came back a while later and upon joining, noted that they were gone. They are gone every time players exit and rejoin.

**Comment by vakkanslj** [comment]
+1

Have the same issue ! (we are 3 players)

**Comment by owanvik** [comment]
+1

Same issue with 2 playeres

**Comment by JeffS2Duda** [comment]
+1

Reactor too for me.

**Comment by linuxchr** [comment]
+1

2 Players

**Comment by MassaHex** [comment]
Same
