### ISSUE TITLE
Items in Seamoth inventory are lost on rejoining a server

### ISSUE THREAD

**Issue by The-Great-Sephiroth** [SubnauticaNitrox/Nitrox#1989]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

After building my first Seamoth, I added the storage module and stored the items from the Aurora in it. This included posters, the plushie, the model Aurora, and eight batteries. Upon exiting the game and rejoining the server, everything in the inventory of the Seamoth was gone.

### Describe the steps you took to encounter the bug.

Build a Seamoth. Install the storage module. Put items in the storage module. Exit the server. Join the server. Everything is gone from the storage module.

**Comment by linuxchr** [comment]
Same bug for me.

**Comment by Jannify** [comment]
Fixed with #1971

**Comment by JasonHoku** [comment]
Hello, I downloaded NitroX from the site and I am experiencing this issue consistently. Do I need to use the latest GitHub version to fix this issue and is there any problem with upgrading from the website downloaded version?

Thank you.

**Comment by oliver408i** [comment]
Looks like this PR came after 1.7.1.0, meaning that its on the github and to be released in 1.8

**Comment by JasonHoku** [comment]
> Looks like this PR came after 1.7.1.0, meaning that its on the github and to be released in 1.8

Do you know if building the latest master from source to upgrade from 1.7.1.0 release allows continuity from a previous world?

**Comment by oliver408i** [comment]
It does not. You should wait for the official release for all 1.8 features to be implemented
