### ISSUE TITLE
Creating a tutorial on building nitrox for the inexperienced audience

### ISSUE THREAD

**Issue by sarayuuki** [SubnauticaNitrox/Nitrox#1993]
### Describe the issue

Hey there, since updates take awhile to develop. I wanted to ask if it be ok to make a YouTube video on building the mod from scratch. Of course adding in the disclaimer of, Nitrox staff will not support help or issues with nitrox GitHub builds.

**Comment by tornac1234** [comment]
We don't want people to build the mod by themselves for other reasons than helping work on the project or testing it and giving feedback (which is not always necessary depending on the current state of master). Therefore, inexperienced users have no reason to know how to build the mod; if they want to play normally, they should only be playing on the latest stable release.
