### ISSUE TITLE
Base components aren't consistent for each player

### ISSUE THREAD

**Issue by Gyroplex** [SubnauticaNitrox/Nitrox#2010]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

On my side, positions of base components are placed correctly, and the base works fine. On the other player's side, pieces aren't connected, and are positioned the wrong way around (see photos).
![Snapchat-1685496653](https://user-images.githubusercontent.com/80266101/226169697-c0785f90-3219-4262-8fc2-e68ad8455fd5.jpg)
![PXL_20230319_103035807](https://user-images.githubusercontent.com/80266101/226169707-1bc07542-74e6-435e-89bb-59a3ba8ab3a0.jpg)

### Describe the steps you took to encounter the bug.

We just placed the parts down where we each saw was correct, but they were not consistent with each other. This happens every time, including after both leaving the game, restarting the server, and removing and replacing the pieces repeatedly.

### Relevant log output

N/A

**Comment by ChiefMcClane** [comment]
Yes I can absolutely confirm this. In my savegame the rotations don't match with other players either.

**Comment by VELD-Dev** [comment]
this problem is already known by us, @tornac1234 is giving his soul to make bases at least stable
