### ISSUE TITLE
Add languages to the Nitrox Launcher

### ISSUE THREAD

**Issue by DarkWolfK** [SubnauticaNitrox/Nitrox#2019]
### Describe the issue

You should add an option to change the language in the Nitrox Launcher. I'm willing to translate the Launcher in Italian, if you want you can start a new translation on Weblate. Sorry if I'm in the wrong place to make these requests but I don't use GitHub very often.

**Comment by Jannify** [comment]
This is technically the right place ;)
But we have not implemented translations into the launcher yet bc we are dedicating all our "front-end" resources into a new launcher (just the programming side of things, not how it looks), which will probably have translations enabled right at release or shortly after. Therefor I am closing this issue for now.
