### ISSUE TITLE
Many creatures doesn't spawn

### ISSUE THREAD

**Issue by AlexALX** [SubnauticaNitrox/Nitrox#202]
I'm not sure if there is already such issue or not (if its duplicate then close), but there is still issue with creatures spawn. Many of them doesn't spawn at all, and i have a lot of this messages on server:

```
[Nitrox] D: Batch 11,15,11 not parsed yet; parsing...
[Nitrox] D: Loaded 0 entity-spawn-points for batch 11,15,11
[Nitrox] D: Batch 11,15,12 not parsed yet; parsing...
[Nitrox] D: Loaded 0 entity-spawn-points for batch 11,15,12
[Nitrox] D: Batch 11,15,10 not parsed yet; parsing...
[Nitrox] D: Loaded 0 entity-spawn-points for batch 11,15,10
[Nitrox] D: Batch 11,15,9 not parsed yet; parsing...
[Nitrox] D: Loaded 0 entity-spawn-points for batch 11,15,9
```

So i assume that batch parser work incorrect or i'm doing something wrong. There is some animals in some locations but still not much.

**Comment by MarijnS95** [comment]
Can you check if there's any batch with more than zero entity spawn points? If not, is there any error message displayed at the start of the application, just above the first `Batch x,y,z not parsed yet; parsing...`?

**Comment by Alberto247** [comment]
I'm guessing the ones with 0 spawn points loaded are the ones where there is nothing at all, like the ones under the ground but with no empty spaces.

**Comment by AlexALX** [comment]
@MarijnS95 yes there is some batches with more than zero, but what about creatures not spawning in locations where they should be for sure? For example i have no stalkers at all and a lot of different creatures.

**Comment by MarijnS95** [comment]
@AlexALX I checked the batches from your log-paste and they are indeed empty. However, there should also be a bunch of batches with a few thousand spawn-points each. There are some stalkers in the kelp forest next to the spawn point, and there should be tons of fauna below the escape pod. Make sure you've compiled the latest commit on the master branch, and have your game files verified. This was tested on the Subnautica "Steam" main branch; I have yet to check experimental.

**Comment by AlexALX** [comment]
I have almost no fauna near escape pod, and yes i have spawn points more than 0 with 100+ so it should work, but its not. So i'll recheck everything again and report back.

**Comment by AlexALX** [comment]
Hello again, sorry for so long delay, finally got some free time to again look into this problem.

So here is steps what i did:
1. Checked Subnautica in steam, its 100% valid.
2. Downloaded once again nitrox, and configured DevVars.targets.
3. Compiled project.
4. Again patched subnautica using dnSpy.
5. Start subnautica and nitrox server and connect to it.

And got exactly same result as it was before. But i have some ideas why this might happens:

1. I have not default location of subnautica and steam itself, yes i did setup DevVars.targets properly, but maybe this is one of reasons?
2. When i'm compiling whole project NitroxTest part are failing to compile due to:

`Error CS0433	Type "Action" exists in "System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", and in "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".	NitroxTest	\Nitrox\NitroxTest\Client\Communication\MultiplayerSessionTests\ConnectionStateTests\ConnectionNegotiatedStateTests\SessionReservationRejectedStateTests.cs	21`

In many places (translated to english from russian).

But everything else (including server) compiling without problems and works. For what this module is needed?

3. I did looked into output log and found a lot of errors and i think there is problem somewhere. So here is part of errors (i can sent full log but basically its same error in all 22mb log file)

`
[Nitrox] I: Applying NitroxPatcher.Patches.TelemetryReporting_SendPlayerDeathEvent_Patch
[Nitrox] I: Applying NitroxPatcher.Patches.ToggleLights_SetLightsActive_Patch
[Nitrox] I: Applying NitroxPatcher.Patches.uGUI_OptionsPanel_AddBindings_Patch
WARNING: PrefabSpawn (body(Clone)/player_view/export_skeleton/head_rig/neck/chest/clav_L/clav_L_aim/shoulder_L/elbow_L/hand_L/attachL/SpawnPDA) already spawned its object! Object = body(Clone)/player_view/export_skeleton/head_rig/neck/chest/clav_L/clav_L_aim/shoulder_L/elbow_L/hand_L/attachL/SpawnPDA/PlayerPDA(Clone)
 
(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[Nitrox] D: Freezing escape pod rigidbody
IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00249>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>

 
(Filename:  Line: -1)

LightmappedPrefabs all loaded, maybe starting intro vignette frame 4976
 
(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 7 Unused Serialized files (Serialized files now loaded: 1)

Unloading 4198 unused Assets to reduce memory usage. Loaded Objects now: 103258.
Total: 556.289917 ms (FindLiveObjects: 17.604801 ms CreateObjectMapping: 8.070056 ms MarkObjects: 527.299316 ms  DeleteObjects: 3.314786 ms)

--- PerformGarbageAndAssetCollectionAsync: GC Time 95.8272 Asset GC Time 648.6699
 
(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00249>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>

 
(Filename:  Line: -1)

IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00249>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>

 
(Filename:  Line: -1)

IndexOutOfRangeException: Array index is out of range.
  at Array3`1[System.Int32].Get (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at Array3`1[System.Int32].get_Item (Int32 x, Int32 y, Int32 z) [0x00000] in <filename unknown>:0 
  at GameInput.GetBindingInternal (Device device, Button button, BindingSet bindingSet) [0x00000] in <filename unknown>:0 
  at GameInput.GetInputStateForButton (Button button) [0x00000] in <filename unknown>:0 
  at GameInput.GetButtonDown (Button button) [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0022d>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x0002f>
at NitroxModel.Helper.ReflectionHelper.ReflectionCall<GameInput> (GameInput,string,System.Type[],bool,bool,object[]) <0x000be>
at NitroxPatcher.Patches.Player_Update_Patch.Postfix (Player) <0x00249>
at (wrapper dynamic-method) Player.Update_Patch1 (object) <0x0041c>
`

And also having this:

`
[Nitrox] E: Expected to simulate an unknown entity: bd540176-b962-4e45-acef-888c008c90d0
[Nitrox] E: Expected to simulate an unknown entity: 42c846f9-2df7-48bd-905b-1304fbf7f65f
[Nitrox] E: Expected to simulate an unknown entity: 670eb2de-169d-4a0a-a06e-735c3bff3103
[Nitrox] E: Expected to simulate an unknown entity: 2311f3b2-19ee-4cd1-909f-00c3a34c0a98
[Nitrox] E: Expected to simulate an unknown entity: ad18d3ae-cddf-4386-971e-1ad950470e37
[Nitrox] E: Expected to simulate an unknown entity: 3aae89aa-ec54-49f1-8058-b4f0de6364ef
[Nitrox] E: Expected to simulate an unknown entity: 8b1b2418-05d6-4b01-980a-2bd75edcb9c2
[Nitrox] E: Expected to simulate an unknown entity: cb358d77-ec37-4ce2-98d4-8c4b83078d78
[Nitrox] E: Expected to simulate an unknown entity: 1a8de1f4-3bcf-480a-a8f9-f343d22063dd
[Nitrox] E: Expected to simulate an unknown entity: 5675904e-6293-4b82-a62b-38010bf52455
[Nitrox] E: Expected to simulate an unknown entity: d95263cb-fa82-420a-b95b-bd44e637e084
[Nitrox] E: Expected to simulate an unknown entity: aa4b48be-8f24-4dac-9673-2f15b44df49d
[Nitrox] E: Expected to simulate an unknown entity: 36b1c6f8-3da6-4fa6-bb32-1351c0fef7a7
[Nitrox] E: Expected to simulate an unknown entity: 7d550c06-4b41-4019-8301-b9dd9cf94bc2
[Nitrox] E: Expected to simulate an unknown entity: 72639dde-8864-4567-9f36-2306de947782
[Nitrox] E: Expected to simulate an unknown entity: 99210cd5-ed89-4c37-a52e-72509a5092a9
[Nitrox] E: Expected to simulate an unknown entity: 8bab0882-c9c7-4a7d-99f6-4675cc10653d
[Nitrox] E: Expected to simulate an unknown entity: 9b63a948-3aa4-4010-9dbf-194ee2f7d974
[Nitrox] E: Expected to simulate an unknown entity: 873c2ea0-e93f-406b-9d66-e3ab751255f7
[Nitrox] E: Expected to simulate an unknown entity: 01073165-dff1-4f47-81d0-ce433e2dfc11
[Nitrox] E: Expected to simulate an unknown entity: f794dcfc-5fe4-4cd8-b3dc-8a69f0667799
[Nitrox] E: Expected to simulate an unknown entity: 89675dab-fb12-470e-a6af-9cef599761c5
[Nitrox] E: Expected to simulate an unknown entity: 2f34d6c4-8022-4cd9-ad6f-e52ca4d0e1e1
[Nitrox] E: Expected to simulate an unknown entity: 092efc9e-a7c1-453f-bb54-49d75ca23b25
`

So why it happens and what i'm doing wrong?

**Comment by MarijnS95** [comment]
@AlexALX See if you can find other reported issues with exactly the same exception.

If I may ask, did you follow the incorrect youtube tutorial?

**Comment by AlexALX** [comment]
Ok i did search now and indeed there is some issues with this problem. But i'm not sure - is there actually solution for this? 

As for question - no, i'm doing everything on my own, also i have steam version of subnautica and its completely legit.

Also for example on one issue you saw:

`This is a known issue. For the time being, the server cannot properly run on a machine without Steam installed. This'll be fixed in the future, once we introduce config files for the server.`

But i do have steam installed so i'm not sure what wrong then.

**Comment by MarijnS95** [comment]
I'm talking about the `IndexOutOfRangeException`. If you get rid of that one, it should be easier to figure out what's wrong with the rest. (I can't remember if it actually prevented the mod from running properly in it's entirety).

We had some issues with Steam path detection, but that happens on the server, and as you mentioned there are no errors there so that should be fine.

**Comment by AlexALX** [comment]
Ah then on server i'm getting this as well, i didn't noticed that until you said about server so..
`[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version`

As for steam path.. How it actually detect it? Do i need specify it separately for server? Basically it is possible that it not detecting my steam properly as i have steam on another hdd with completely non usual path.

**Comment by MarijnS95** [comment]
It is detected correctly, otherwise you'll get an error.

The peeper thingy is just a warning, it doesn't interfere with any spawns (even peepers themselves spawn).

**Comment by AlexALX** [comment]
Ok, so then what i need to do? How i can fix that error? I did look into code and actually didn't get why exactly this happens (not error itself - i know what it mean, but why).

Basically i think it happens here https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxPatcher/Patches/Player_Update_Patch.cs#L27

This means it goes through the keyBindingManager.KeyboardKeyBindings and it have invalid keys or so, not sure.

**Comment by MarijnS95** [comment]
https://github.com/SubnauticaNitrox/Nitrox/issues?utf8=%E2%9C%93&q=is%3Aissue+IndexOutOfRangeException

**Comment by AlexALX** [comment]
Ok i did read issues again and fixed it. But this does not solve problem with creatures spawning. Here is full output log: https://pastebin.com/wNK7kLRY

There is still many of "Expected to simulate an unknown entity", and i didn't saw errors on server. So what i can try next?

**Comment by MarijnS95** [comment]
Thanks. Like I said, getting rid of that error doesn't fix the issue, but at least allows to read the log without vast amounts of irrelevant errors.

Anyway, those errors show that at least the server has a bunch of entities spawned. I can't remember if spawn commands were logged locally, but AFAIK there shouldn't be that many unknown entities. At least that's what an earlier pull request fixed.

There might be a chance that I boot into Windows and check this myself, but don't count on it; anyone else able to check the code and/or their logs? As far as I'm aware there hasn't been a Subnautica update since I last worked on this project.

**Comment by AlexALX** [comment]
Ok then as i understand i just need to wait until someone will have same error and will able to look code)

Also i had this problem from beginning even few months ago (when path was hardcoded and i changed it manually) so i'm not sure why this happens on my system. I still think that this may be because of not default path of steam or so.

**Comment by Alberto247** [comment]
About the "Expected to simulate an unknown entity" error I think is caused when the server sends data to move an entity which the client has already unregistered. However, I have no idea if the entity got unregistered due to a command from the server or due to a bug in the client code.
This is just an idea, I'm not totally sure.
What I did was to log all registered and unregistered entities on the client side, and this is what looks like it's happening.

**Comment by MarijnS95** [comment]
I assume this is some sort of concurrency issue, as these messages are triggered by a piece of code that deals with receiving (re)distributions of entity simulation ownership. Basically as soon as a client has a change in visible entity cells, it notifies the server which in turn redisitributes simulation ownership. I can see multiple reasons for this message to be caused, as obviously entities move, and may have just despawned on a client. The cell may have also gotten unloaded again, for example when swimming "past it", where it's barely in range for a split-second.
At this point the entity will stay floating still on the server until another player loads the cell, or if the "owning" player unloads the cell.

Though this shouldn't really influence spawning of entities in the first place. If you stay in an area for a while (for example the starting area), there should be an abundance of peepers, gelsacks and rabbit rays.

**Comment by birdcpe25** [comment]
I'm quite newbie with unity and game modding but have look through some code and not sure if this one cause the problem?

NitroxServer.GameLogic.Entities.Spawning.BatchEntitySpawner
```
 private IEnumerable<Entity> SpawnEntitiesUsingRandomDistribution(EntitySpawnPoint entitySpawnPoint, DstData dstData)
        {
            float rollingProbabilityDensity = dstData.prefabs.Sum(prefab => prefab.probability / entitySpawnPoint.Density);

            if (rollingProbabilityDensity <= 0)
            {
                yield break;
            }

            double randomNumber = random.NextDouble();
            if (rollingProbabilityDensity > 1f)
            {
                randomNumber *= rollingProbabilityDensity;
            }

            double rollingProbability = 0;
            PrefabData selectedPrefab = dstData.prefabs.FirstOrDefault(prefab =>
            {
                if(prefab.probability == 0)
                {
                    return false;
                }

                float probabilityDensity = prefab.probability / entitySpawnPoint.Density;
                rollingProbability += probabilityDensity;
                bool isValidSpawn = IsValidSpawnType(prefab.classId, entitySpawnPoint.CanSpawnCreature);
                return rollingProbability >= randomNumber && isValidSpawn;
            });

            WorldEntityInfo worldEntityInfo;
            if (!ReferenceEquals(selectedPrefab, null) && worldEntitiesByClassId.TryGetValue(selectedPrefab.classId, out worldEntityInfo))
            {
                for (int i = 0; i < selectedPrefab.count; i++)
                {
                    IEnumerable<Entity> entities = CreateEntityWithChildren(entitySpawnPoint, 
                                                                            worldEntityInfo.techType, 
                                                                            worldEntityInfo.cellLevel, 
                                                                            selectedPrefab.classId);
                    foreach (Entity entity in entities)
                    {
                        yield return entity;
                    }
                }
            }
        }
```

Should filter invalid before doing distribution?

```
        private IEnumerable<Entity> SpawnEntitiesUsingRandomDistribution(EntitySpawnPoint entitySpawnPoint, DstData dstData)
        {

            // Filter out all unused prefabs type at entityspawnpoint
            IEnumerable<PrefabData> prefabs = dstData.prefabs.Where(prefab =>
            {
                return IsValidSpawnType(prefab.classId, entitySpawnPoint.CanSpawnCreature);
            });
            
            float rollingProbabilityDensity = prefabs.Sum(prefab => prefab.probability / entitySpawnPoint.Density);

            if (rollingProbabilityDensity <= 0)
            {
                yield break;
            }

            double randomNumber = random.NextDouble();
            if (rollingProbabilityDensity > 1f)
            {
                randomNumber *= rollingProbabilityDensity;
            }

            double rollingProbability = 0;

            PrefabData selectedPrefab = prefabs.FirstOrDefault(prefab =>
            {
                if(prefab.probability == 0)
                {
                    return false;
                }

                float probabilityDensity = prefab.probability / entitySpawnPoint.Density;
                rollingProbability += probabilityDensity;
                return rollingProbability >= randomNumber;
            });

            WorldEntityInfo worldEntityInfo;
            if (!ReferenceEquals(selectedPrefab, null) && worldEntitiesByClassId.TryGetValue(selectedPrefab.classId, out worldEntityInfo))
            {
                for (int i = 0; i < selectedPrefab.count; i++)
                {
                    IEnumerable<Entity> entities = CreateEntityWithChildren(entitySpawnPoint, 
                                                                            worldEntityInfo.techType, 
                                                                            worldEntityInfo.cellLevel, 
                                                                            selectedPrefab.classId);
                    foreach (Entity entity in entities)
                    {
                        yield return entity;
                    }
                }
            }
        }
```

**Comment by AlexALX** [comment]
This was fixed?

**Comment by alexanderheuts** [comment]
This issue is 6 months old with quite an overhaul in spawning. Check the changelogs. Join discord if you have further issues.

**Comment by AlexALX** [comment]
Even if its 6 months old it doesn't meant it was fixed, last time when i checked it still was here (it was 2-3 months ago). But ok i'll recheck later.
