### ISSUE TITLE
Add an "Access to Folder" or move it to the world manager page of launcher

### ISSUE THREAD

**Issue by VELD-Dev** [SubnauticaNitrox/Nitrox#2020]
As explained in the title, add a button to access the folder of the save directly from the launcher, for example into the save settings. I think it would greatly improve navigation to save files, and above this, it would be much better if it's a button on each server/save in the manager, it would automatically open *this* save. Maybe an idea for the next launcher ? I think this would be an interesting improvement for users and for interface simplicity

**Comment by Measurity** [comment]
Implemented in new launcher. See #1848
