### ISSUE TITLE
Can't build NitroxClient

### ISSUE THREAD

**Issue by Pvpgamerr** [SubnauticaNitrox/Nitrox#2024]
### Describe the issue

I'm trying to build the NitroxClient porject but every time i get the error

"The type or namespace name 'Atlas' could not be found"

I did every step from the wiki but still the same error

**Comment by Measurity** [comment]
Are you on the latest subnautica code (i.e. not legacy)?

**Comment by Pvpgamerr** [comment]
i am

**Comment by Measurity** [comment]
Can't help your further with the limited information you've given me. 
I can tell you if you follow the steps correctly without skipping any, that it has worked for everyone on our team.
