### ISSUE TITLE
Duplicated waterproof storage lockers

### ISSUE THREAD

**Issue by sarayuuki** [SubnauticaNitrox/Nitrox#2048]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

waterproof lockers are being duplicated,

### Describe the steps you took to encounter the bug.

both me and my friend went 800 meters away or so when we come back theres a second storage locker.

**Comment by gussandst** [comment]
Could not replicate.
