### ISSUE TITLE
Can't get Nitrox Server to Build properly with Microsoft Visual Studio 2017 ('TranslationLiveUpdate' could not be found) 

### ISSUE THREAD

**Issue by Darrenrclk** [SubnauticaNitrox/Nitrox#205]
Hey guys, im new here and i havent ever used Visual studio or coded in anything other than Delphi.
I've been trying to Build successfully build the Nitrox server but i can't get it to work. i keep getting the same 4 errors.

1>------ Build started: Project: NitroxModel, Configuration: Debug Any CPU ------
2>------ Build started: Project: NitroxReloader, Configuration: Debug Any CPU ------
3>------ Build started: Project: Harmony, Configuration: Debug Any CPU ------
1>  NitroxModel -> C:\Users\Darre\Documents\Nitrox-master\bin\Debug\NitroxModel.dll
3>  Harmony -> C:\Users\Darre\Documents\Nitrox-master\Harmony\Harmony\bin\Debug\0Harmony.dll
2>  NitroxReloader -> C:\Users\Darre\Documents\Nitrox-master\bin\Debug\NitroxReloader.dll
4>------ Build started: Project: NitroxClient, Configuration: Debug Any CPU ------
5>------ Build started: Project: NitroxServer, Configuration: Debug Any CPU ------
4>C:\Users\Darre\Documents\Nitrox-master\NitroxClient\GameLogic\Spawning\DefaultEntitySpawner.cs(15,47,15,113): warning CS0618: 'PrefabDatabase.TryGetPrefab(string, out GameObject)' is obsolete: 'Prefer using GetPrefabAsync'
4>C:\Users\Darre\Documents\Nitrox-master\NitroxClient\MonoBehaviours\Gui\MainMenu\MainMenuMods.cs(35,45,35,66): error CS0246: The type or namespace name 'TranslationLiveUpdate' could not be found (are you missing a using directive or an assembly reference?)
4>C:\Users\Darre\Documents\Nitrox-master\NitroxClient\MonoBehaviours\Gui\MainMenu\MainMenuMultiplayerPanel.cs(59,44,59,65): error CS0246: The type or namespace name 'TranslationLiveUpdate' could not be found (are you missing a using directive or an assembly reference?)
4>C:\Users\Darre\Documents\Nitrox-master\NitroxClient\MonoBehaviours\Gui\MainMenu\MainMenuMultiplayerPanel.cs(72,44,72,65): error CS0246: The type or namespace name 'TranslationLiveUpdate' could not be found (are you missing a using directive or an assembly reference?)
6>------ Build started: Project: NitroxPatcher, Configuration: Debug Any CPU ------
7>------ Build started: Project: ClientTester, Configuration: Debug Any CPU ------
5>  NitroxServer -> C:\Users\Darre\Documents\Nitrox-master\NitroxServer\bin\Debug\NitroxServer.exe
8>------ Build started: Project: NitroxTest, Configuration: Debug Any CPU ------
========== Build: 4 succeeded, 4 failed, 0 up-to-date, 0 skipped ==========
 
That's the output i keep receiving when i try build the solution and i haven't found a way to fix it online. Any suggestions or solutions?

**Comment by killzoms** [comment]
after pulling a fresh Nitrox source from github and attempting to build from it I successfully built the solution. This brings me to the conclusion you have files that have been edited locally or from another fork. If the files were edited locally please attach them to supply the much needed information

**Comment by Darrenrclk** [comment]
I managed to fix the error, the subnautica build i used was the January build. updated it and tried again, works perfectly now.
Thank you for the response and sorry for any and all wasted time and effort.
