### ISSUE TITLE
How do you use an existing singleplayer world as a multiplayer server world

### ISSUE THREAD

**Issue by syn7ax-3rr0r** [SubnauticaNitrox/Nitrox#2054]
### Describe the issue

like for example using `C:\Program Files (x86)\Steam\steamapps\common\Subnautica\SNApppData\SavedGames\slot0000` as a server world

**Comment by RivalsRebels** [comment]
Nitrox does not support Singleplayer Worlds. Also, please refrain from using issues to seek help.

**Comment by syn7ax-3rr0r** [comment]
sorry
