### ISSUE TITLE
sulfur not spawining

### ISSUE THREAD

**Issue by EpicGamer243** [SubnauticaNitrox/Nitrox#2057]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Sulfur Does not spawn with crashfish

### Describe the steps you took to encounter the bug.

Find Crashfish
No sulfur

### Relevant log output

Server:https://pastebin.com/uGA8KZFj
Game [Player LOg]:https://pastebin.com/S5smpAFk
Game:https://pastebin.com/eejAJttq

**Comment by Kroink** [comment]
> 

Monke132 was using the latest github commit.

**Comment by Monke132** [comment]
i can find it now
