### ISSUE TITLE
Subnautica crashes on start

### ISSUE THREAD

**Issue by ANormalPrussian** [SubnauticaNitrox/Nitrox#2064]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Whenever i try to open Subnautica via the launcher it shows the icon in my toolbar then it dissapears without opening the game

### Describe the steps you took to encounter the bug.

Launch the game

### Relevant log output

[game-20230709.log](https://github.com/SubnauticaNitrox/Nitrox/files/11996888/game-20230709.log)

**Comment by killzoms** [comment]
Are you on the legacy branch of Subnautica while using a github build of Nitrox?

**Comment by ANormalPrussian** [comment]
Using the legacy branch. Not the github version though. Should I be using that version?

**Comment by killzoms** [comment]
Judging by the log your version of Nitrox appears to have been built recently

**Comment by ANormalPrussian** [comment]
V 1.7.10

**Comment by killzoms** [comment]
Recommend grabbing the latest release build of Nitrox from https://nitrox.rux.gg/ and joining the discord https://discord.gg/E8B4X9s
