### ISSUE TITLE
Base pieces do not place in any game mode

### ISSUE THREAD

**Issue by Soniczac7** [SubnauticaNitrox/Nitrox#2067]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When I attempt to place any base pieces they do not place with errors in the game log (attached below).
This happens in any game mode including creative.

### Describe the steps you took to encounter the bug.

1. Create a new creative server
2. Get a builder tool
3. Attempt to place a base piece
4. See issue

### Relevant log output

[Game Log: https://pastebin.com/KjCFY7vT](https://pastebin.com/KjCFY7vT)

**Comment by Jannify** [comment]
Known regression from the Subnautica 2.0 Update. Will be fixed by #1952
