### ISSUE TITLE
Server default ip.

### ISSUE THREAD

**Issue by GaleguinhoCakeHud** [SubnauticaNitrox/Nitrox#207]
How can i change the default ip adress of my server, 'cause it's always executing with the default (127.0.0.1). And i need to put the IPv4 ou the public adress?

**Comment by yenzgamingyt** [comment]
If you run the server and play from the same ip it will work fine but if you use another pc to connect to the server, you need the public ip of the server

**Comment by GaleguinhoCakeHud** [comment]
What i'm doing is: Opening the server normally (i opened the 11000). And i give my friend my public ip (i got it using to diferrent sites, and the ip was  the same in both). And nothing happen, it appears "Unable to connect to remote server <ip:11000>

**Comment by MarijnS95** [comment]
The server doesn't just listen on the local interface, it listens [on all interfaces](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxServer/Communication/TcpServer.cs#L25). You'll have to set up port forwarding or similar.

We might want to make the listening address configurable as to not pollute all interfaces, but this is not needed for connections to work.
