### ISSUE TITLE
How to change the language on Subnautica Legacy, and to make the change persistent on Nitrox Multiplayer Server

### ISSUE THREAD

**Issue by victor-schumann** [SubnauticaNitrox/Nitrox#2070]
### Describe the issue
Edit: Most languages will be switched by simply changing to the target language on the base game. A few have a different ID and simply cannot be processed properly (like Portuguese-BR). To fix those, the below tutorial and issue apply.

Problem: Not a lot of documentation on how to properly switch languages on the Nitrox Multiplayer with Legacy Subnautica. When you try to open Subnautica and choose a language, Nitrox overrides that with English Subnautica language pack.
Solution: Ctrl+c, Ctrl+v.

Hi, guys. I had a lot of dificulties researching how to change the language of the multiplayer experience after the recent updates required us to use the legacy version. So, the goal of this is to try to find a consistent way of changing the language of the game, and to make that change persistent on the Nitrox Server.

Normally, I tried simply copying and pasting the files, then renaming them, but for some reason I found it difficult to make it happen on the server computer (the client computer had no problems). This might have something to do with my Windows 10 build. Regardless, the following approach worked just fine:

1. Go to the Nitrox folder and copy the contents from the target language woth CTRL+A, CTRL+C, and override the contents of the English file (en.json) with CTRL+A, CTRL+V. 
2. Go to the subnautica original instalation files (accessible through Steam) and, just like we did above, copy the contents from the target language file to the English file (English.json).
3. Start the server.
4. Start the Subnautica edition you got on Nitrox.
5. Close the Nitrox Subnautica, start the Steam Subnautica (optional for joystick users).
6. Enjoy!

I hope that someone else finds this and makes the process more reliable and with less steps. Until then, I hope to help someone like me, that just wanted to translate the multiplayer experience for their loved ones.

And, I might have just been remiss or lazy when looking information up, but I found no tutorials or open issues about a way to do this. If that is not the case, I urge the devs to add a tutorial similar to this on the README.md so that other people can properly change their Nitrox/Subnautica languages.

**Comment by dartasen** [comment]
You just need to change Subnautica language and Nitrox will follow up.

**Comment by dartasen** [comment]
Also we don't actually support the latest version of Subnautica

**Comment by victor-schumann** [comment]
> You just need to change Subnautica's language and Nitrox will follow up if the language is supported on our weblate

Like I wrote, I tried that. Changing the language on the Steam Subnautica resulted on a working game in my target language, when launched by steam, without Nitrox. When launched by Nitrox, the menu and logs had a proper Nitrox translation, but the core game had its langauge overriden by English.

**Comment by victor-schumann** [comment]
That is it, friend, you were completely right. For some reason, my Portuguese-BR language was not listed on this "weblate" that you mentioned. I coud not find this list of supported languages, but I did try some popular ones, like Spanish and Italian, and I had no problems switching them by going to the base game, changing it, then going to the server.
I guess it could be a problem with the way Subnautica and Nitrox process the ID of my language or simply because it is not listed there yet. Regardless, this methos works for any languages that are not properly translated or listed there.
Thanks for the help clarifying things!
