### ISSUE TITLE
Me and my friend cant open the launcher

### ISSUE THREAD

**Issue by Doghouse501** [SubnauticaNitrox/Nitrox#2079]
### Describe the issue

![Screenshot (1)](https://github.com/SubnauticaNitrox/Nitrox/assets/145939406/77536360-8858-4e8c-9715-8357e05d0332)

**Comment by LkMNeuY** [comment]
You need to change your subnautica build to legacy (if you bought through Steam)

**Comment by Doghouse501** [comment]
how?

**Comment by Jannify** [comment]
Pleas visit for future help our discord, GitHub is not the place for that. Locking and closing the issue.
