### ISSUE TITLE
waterproof storage lockers disappear on logging back on to the server

### ISSUE THREAD

**Issue by WolfMad** [SubnauticaNitrox/Nitrox#2080]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

waterproof storage lockers disappear on logging back on to the server after some time they reappear

sometimes when I log in I get the Inventory overflow error and need to find waterproof storage lockers that overflow

### Describe the steps you took to encounter the bug.

I have placed waterproof storage lockers that have items near my life pod and quit Subnautica then reconnected to the server before I started getting this error I was getting the Duplicated waterproof storage lockers #2048

**Comment by gussandst** [comment]
Could not replicate.
