### ISSUE TITLE
Way to many fish spawns

### ISSUE THREAD

**Issue by Krum3L** [SubnauticaNitrox/Nitrox#209]
Hello,
I tried this about 2-3 months ago with a friend, we installed everything, almost everything worked EXCEPT that there was about 5000 Fishes only in the FoV, it was very laggy due to the fishes.
Tried:
Reinstalling
Changing hosts (He hosted first, then i hosted)

I dont know if we only had the Problem, or if someone else encountered this to.
-Krum3L
![20180224125710_1](https://user-images.githubusercontent.com/26604063/38638012-28bc92ca-3dcd-11e8-8c0f-1d7cb8c1d6db.jpg)
Thats what it looked like in the Lava zone

**Comment by Alberto247** [comment]
That was happening to me before the release of the 1.0 of the game. After that release the problem got fixed. Are you sure you are running the latest build?

**Comment by Krum3L** [comment]
Hello,
as far as i know, i did everything correct, downloaded the latest files.
I watched this video as a tutorial:
https://www.youtube.com/watch?v=_0IQ4VvTRXc

**Comment by Alberto247** [comment]
Sorry, I wasn't clear. I was talking about the subnautica's version, not the mod's one.

**Comment by Krum3L** [comment]
Oh, yeah, im using the latest version of subnautica

**Comment by Krum3L** [comment]
I could also give you the Logs of the server, maybe theres something wrong with that?

**Comment by Krum3L** [comment]
Wanted to ask, did this got fixed?

**Comment by B-gamer** [comment]
I played it with a friend to and got the same problem we had no higer then 20 fps and sometimes the game crashed. Its a really nice mod but its bairly playable because of this. Is it may possible to just complete disable spawing creatures?
