### ISSUE TITLE
Please write an informative title describing the bug in a few words

### ISSUE THREAD

**Issue by CakeIsAlie1** [SubnauticaNitrox/Nitrox#2094]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

lifepod number 3 didnt spawn

### Describe the steps you took to encounter the bug.

i was playing with my friend

**Comment by NinjaPedroX** [comment]
This bug is normally the result of an issue with your connection. Please seek help for this issue in the help channel of the official Nitrox server.
