### ISSUE TITLE
all lifepods are gone except starting one ,some recipes are reseting on rejoin

### ISSUE THREAD

**Issue by CakeIsAlie1** [SubnauticaNitrox/Nitrox#2095]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

i cant find lifepods, mark just leads me to empty spot.some recepis reseting on rejoin

### Describe the steps you took to encounter the bug.

i was playing game with my friend

### Relevant log output

game:https://pastebin.com/fGK1pgGe
server:https://pastebin.com/4f92D16x

**Comment by NinjaPedroX** [comment]
As I told you before, please visit our Discord server to get support on these issues. You will not get help here.
