### ISSUE TITLE
No hostile leviathans are spawning

### ISSUE THREAD

**Issue by Xolotel** [SubnauticaNitrox/Nitrox#2103]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

No hostile leviathan-class species on the map will spawn. Reefbacks spawn fine, and I assume the Sea Treaders do as well, though I haven't been to the STP. I have been to the Lost River, which had no Ghost Leviathans, the Dunes, which had no Reapers, and the Aurora, which also had no Reapers. Wiping the world save doesn't fix it. 

### Describe the steps you took to encounter the bug.

It's a persistent bug, there's no steps.

**Comment by Xolotel** [comment]
I searched this issue again, forgetting I made this, and accidentally clicked on my own post thinking their would be some answers lol

**Comment by tornac1234** [comment]
This was fixed idk when but it was.
