### ISSUE TITLE
building never goes to 100% on the server side 

### ISSUE THREAD

**Issue by ImaDoor2785** [SubnauticaNitrox/Nitrox#2104]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

i can build something and even if it says 100% on the client after a reload it usualy 60%
![Screenshot (178)](https://github.com/SubnauticaNitrox/Nitrox/assets/74113326/e5ee99d1-032f-4576-bb32-440f1aeb2965)

### Describe the steps you took to encounter the bug.

my brother was building a base and for me it wasnt all 100% so i tried fixing t and it never worked

### Relevant log output

server https://pastebin.com/WUhtD4b7
game log is to big for pastebin so ill upload a txt file
[Uploading game-20240101.log…]()

**Comment by tornac1234** [comment]
Will be fixed by #2099
