### ISSUE TITLE
DnSpy Compiler Errors

### ISSUE THREAD

**Issue by N4rv4s** [SubnauticaNitrox/Nitrox#211]
Hello,
i have a huge Problem with the Installation. I used this guide: https://www.youtube.com/watch?v=_0IQ4VvTRXc
And i did everything he did. Except compiling this NitroxPatcher.Main.Execute(); into the awake method. Because i get Compiler Errors, I'vealready reinstalled and recompiled with Visual Studio but still compiler errors. 
These are the Compiler Errors:
![prolbem sub](https://user-images.githubusercontent.com/38793705/39376803-3b49a5bc-4a53-11e8-9e80-56a107ec6b1c.PNG)

If someone knows how to fix it, please help me.

Thanks a lot.

**Comment by DanX100** [comment]
try to launch DnSpy by Administrator

**Comment by N4rv4s** [comment]
I've already tried that, but still same errors

**Comment by MightySCollins** [comment]
Just comment out the lines which error. A better fix might be needed

**Comment by Dkamps18** [comment]
Left from where you assembly the reference switch from main.cs to main.g.cs and remove line 9 till line 19 and compile again

**Comment by quimnuss** [comment]
@Dkamps18 is correct. You can comment in the error lines without repercussions.
