### ISSUE TITLE
Can't compile, corridorGhost.rotation

### ISSUE THREAD

**Issue by elEthamin** [SubnauticaNitrox/Nitrox#2118]
### Describe the issue

Hello ! 
I'm trying to compile the given source code with nitrox release 1.7.1.0 downloaded on github. Nothing is touched but it doesn't compile. 

The file NitroxModel-Subnautica\DataStructures\GameLogic\Buildings\Rotation\SubnauticaRotationMetadataFactory.cs
contains errors

```
case BaseAddCorridorGhost corridorGhost:
{
    int rotation = corridorGhost.rotation;

    Vector3 position = corridorGhost.GetComponentInParent<ConstructableBase>().transform.position;
    bool hasTargetBase = corridorGhost.targetBase != null;
    Int3 targetCell = hasTargetBase ? corridorGhost.targetBase.WorldToGrid(position): default;
    builderMetadata = new CorridorBuilderMetadata(position.ToDto(), rotation, hasTargetBase, targetCell.ToDto());
    break;
}
case BaseAddMapRoomGhost mapRoomGhost:
{
    Base.CellType cellType = mapRoomGhost.cellType;
    int connectionMask = mapRoomGhost.connectionMask;
    builderMetadata = new MapRoomBuilderMetadata((byte)cellType, connectionMask);
    break;
}
```

```
BaseAddCorridorGhost does not contain a definition for 'rotation'.
BaseAddMapRoomGhost does not contain a definition for 'cellType'.
BaseAddMapRoomGhost does not contain a definition for 'connectionMask'.
```

Do you have any idea what is causing this problem?

Having taken the source code of a release I expected it to compile
Thanks
![Capture](https://github.com/SubnauticaNitrox/Nitrox/assets/100302330/9f51ac6a-a041-4b98-b7de-4a36d8b723c2)

**Comment by NinjaPedroX** [comment]
Why are you trying to compile old code?

**Comment by elEthamin** [comment]
because this is the last stable release

**Comment by Measurity** [comment]
Make sure you have Subnautica in "legacy - Public legacy builds" mode:
![image](https://github.com/SubnauticaNitrox/Nitrox/assets/1107063/6ac732ef-cb4a-4703-8476-e82ea87f40fc)

You might need to clear the Nitrox.BuildTool cache by removing this folder as well:
`Nitrox-1.7.1.0\Nitrox.BuildTool\bin\generated_files`

**Comment by elEthamin** [comment]
maxi chad
