### ISSUE TITLE
Client freeze on old world with fps drop

### ISSUE THREAD

**Issue by RomikB** [SubnauticaNitrox/Nitrox#2123]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Epic

### Describe the issue.

We play with friend more then 10 hours. After login to server client start to freeze, fps drops to about 1. Sometime freeze begin not after start but after leaving the login location.

### Describe the steps you took to encounter the bug.

Play a lot with friends.

### Relevant log output

Game: https://pastebin.com/SndBJuiP Server: https://pastebin.com/QBtn9nDk

**Comment by Jannify** [comment]
Without upgrade scripts for the new version old world files are not compatible with the new release. Unfortunately we can't guarantee right now if we can even provide these scripts as much of the code based changed.

**Comment by RomikB** [comment]
Oh. Old world is not a world from old version. Can you reopen or should I recreate the same bug with the same data?

**Comment by RomikB** [comment]
I upload my world and video of issue to cloud.
world: https://1drv.ms/u/s!ArwOwR-mbwqZgYFPFB5qIxdqtCmM-A?e=SuPjpA
video: https://1drv.ms/v/s!ArwOwR-mbwqZgYFQuSgCV6jBMv_WLA?e=hI6GJ1

**Comment by RomikB** [comment]
The bug reason was a bad save with more than 8900 spawned skyrays. What is the reason of this is unknown.

**Comment by dartasen** [comment]
Don't think we can have any workaround for this, closing it for now.
