### ISSUE TITLE
Water filtration machine keeps disappearing after login

### ISSUE THREAD

**Issue by parsivan** [SubnauticaNitrox/Nitrox#2129]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

After rejoining or after the server restart "Water Filtration machine" disappears from my base.

### Describe the steps you took to encounter the bug.

just quit the server instance and rejoine or restart the server and rejoin.

### Relevant log output

https://pastebin.com/Y1bNjGpu (today after login it disappeared again)
https://pastebin.com/F70hxWSk (when i had the machine)

**Comment by dartasen** [comment]
Fixed by #1952
