### ISSUE TITLE
whenever me or my friend move we start teleporting.

### ISSUE THREAD

**Issue by kamage1** [SubnauticaNitrox/Nitrox#2134]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

so whenever me or my friend move on any server we both play on we start flying and moving insanely fast everywhere we go. for example when my friend moves, its normal on his screen. but on my screen he starts vigorously teleporting everywhere.

https://github.com/SubnauticaNitrox/Nitrox/assets/168560430/8dd8889b-b5aa-4d93-a1df-3b1264ccc0b5

### Describe the steps you took to encounter the bug.

we encountered this bug by just doing the normal steps of making a server, joining it and you know.

**Comment by dartasen** [comment]
Should be improved with 1.8
