### ISSUE TITLE
Question: Cannot Launch "Play Multiplayer" v1.5.0.1 it only worked once for me

### ISSUE THREAD

**Issue by liszca** [SubnauticaNitrox/Nitrox#2135]
I managed to get the Launcher running in Ubuntu Linux.
When starting Multiplayer for the first time it seemed to start the Multiplayer Version. But not ever again, instead I get into the Single Player.
Is there something I can do or is it a dead end under Linux for now?

**Comment by dartasen** [comment]
1.5.0.1 isn't supported anymore
