### ISSUE TITLE
My friends can't connect to my serveur

### ISSUE THREAD

**Issue by Bobnaval** [SubnauticaNitrox/Nitrox#2138]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

everything works fine util my friend tried to join.I search online and it says that my port 11000 is closed.I tried to opened it with windows firewall but it's not working.

**Comment by Measurity** [comment]
You need to port forward too if you aren't using a VPN (like Hamachi). Did the server console window mention that port forwarding succeeded? If not you need to login to your router to do it manually.

**Comment by Bobnaval** [comment]
if you are talking about the Nitrox integrated console then no I have no mention of "this port forwarding was successful". The only line with a port report is Server is listening on port 11000

**Comment by Measurity** [comment]
Alright. So you have 2 options to connect with friends. 
- Either use [Hamachi](https://vpn.net/) (or other VPN). It's easier but everyone needs to install and connect to work.
- Login to your router and add a port forward rule for 11000 UDP. Harder but only you (server owner) need to do this.

Plenty of tutorials on setting up Hamachi online but for port forwarding I will explain a bit:
1. Open command prompt (windows button + R -> then enter cmd -> OK)
2. In the CMD enter `ipconfig`, look for "Default Gateway" and type the 4 part number beside it into your browser (chrome/edge/firefox)
3. You should see your router's login page, find out the default password for your router (check logo on the login and search for the name in google + "default password"
4. Login and navigate to port forwarding rule page (search online for your router model to see where to go)
5. Add the port forward rule, which depends on router model how it looks like. Image below is how I would fill it out based on what's returned by the `ipconfig` command
6. Apply the rule and your friends should be able to connect (unless you didn't configure Windows Firewall)

### CMD "ipconfig" output on my PC
![image](https://github.com/SubnauticaNitrox/Nitrox/assets/1107063/677779db-3bce-408b-898e-cf9006b618ca)
### Port forward rule I would need to add to make Nitrox server work online
![image](https://github.com/SubnauticaNitrox/Nitrox/assets/1107063/66eff801-9b9c-4d4a-b833-68fb61a0a650)

**Comment by Bobnaval** [comment]
After doing everything, my port 11000 remains closed.
![porc](https://github.com/SubnauticaNitrox/Nitrox/assets/112502403/f301b804-7cad-47e6-9672-b7a0cf2ed554)
![port](https://github.com/SubnauticaNitrox/Nitrox/assets/112502403/43108e28-19d6-450c-8760-b942fd4f856f)

**Comment by Measurity** [comment]
Port forward rule looks good. You cannot test Nitrox Server with an online port tester. It only responds to connecting Nitrox clients. So you should test by having a friend try and join by giving them your public IP: https://ipv4.icanhazip.com/

If it doesn't work make sure Windows Firewall on either side isn't blocking the connection. Here's the guide to fix it:
## Allowing Nitrox and Subnautica through Windows Defender

1. Control Panel --> System and Security --> Windows Defender Firewall --> Allow an App or Feature through the Firewall:

2. Click Change Settings then Allow another app...

3. Click Browse... then search for the Nitrox folder(The folder where Nitrox is located).

4. Select nitroxlauncher.exe and click Add.

5. Click Allow another app and Browse.... once again.

6. Select nitroxserver-subnautica.exe and click Add.

7. Click Allow another app and Browse.... again, this time, go into the Subnautica folder(The folder where Subnautica has been installed).

8. Select subnautica.exe  and click Add.

Tick nitroxlauncher.exe, nitroxserver-subnautica.exe and subnautica.exe for both private and public.
**NOTE: If you have multiple copies of these three exceptions, make sure to tick all of them for both private and public.**

9. Click OK.

**Comment by Bobnaval** [comment]
I gave permission to subnautica and nitrox in window firewall but my friend still cannot connect.

**Comment by Measurity** [comment]
Make sure that the friend(s) are using your public IP by first adding a server entry by clicking "Add server" and entering your public IP you gave them. And your friends need to do the firewall steps too.
![image](https://github.com/SubnauticaNitrox/Nitrox/assets/1107063/8bab0621-0733-44f9-b629-360a17f28b6a)
![image](https://github.com/SubnauticaNitrox/Nitrox/assets/1107063/373dde4d-2f82-46ac-96af-429e34200707)

**Comment by Bobnaval** [comment]
MAN, IT WORK THANK YOU SO MUCH (btw I used Radmin VPN) <3
