### ISSUE TITLE
Subnautica closes almost immediately when trying to start it through Nitrox Launcher

### ISSUE THREAD

**Issue by CubiqloYT** [SubnauticaNitrox/Nitrox#2139]
### Describe the issue

Nitrox's version of Subnautica keeps _crashing_, when opening it through steam its fine. I've tryed everything. I've went to reddit for answers, support on your discord Isn't helping, so I've come to here. I need help badly. this has gone from days to weeks, I'm very pissed off that your own discord support team didnt help at all, so can **you** help me? also there was a github post that I saw that said I needed to update my drivers. did that and it didn't work. please help I am begging you not to redirect me to the github or reddit post, because reddit didn't help nor did github.

**Comment by VazarinX** [comment]
?

**Comment by VazarinX** [comment]
Feel free to come back to the help channel. For support.

**Comment by Measurity** [comment]
Is the nitrox launcher crashing or is it crashing while you're playing? The former is likely your anti virus stopping Nitrox from working or Discord SDK crashing. Try stopping Discord and then starting Nitrox and Subnautica. Discord can be started again once playing. 

Can you post the Player.log file? It'll show more info about the crash: 
```
%AppData%\..\LocalLow\Unknown Worlds\Subnautica\Player.log
```
^ Enter in the "address bar" of windows explorer.
