### ISSUE TITLE
Game freezing my pc for a few second every ~20 seconds

### ISSUE THREAD

**Issue by TOBI6HANA** [SubnauticaNitrox/Nitrox#2140]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

When i am playing with nitrox my game freezes, my ram usage is around 80% it doesn't happed to my friend that i play with.
Main game works fine

### Describe the steps you took to encounter the bug.

I joined the server

### Relevant log output

https://pastebin.com/tTWAdgc2

**Comment by dartasen** [comment]
Few things i'm noticing : 
* World save seems somehow corrupted
* You have QMod installed, which can also be a source of bug since it's not compatible with Nitrox
