### ISSUE TITLE
world save don't work

### ISSUE THREAD

**Issue by sheydhql** [SubnauticaNitrox/Nitrox#2142]
### Describe the issue

I played for several days on the same save, but now when I started the server I saw this text :

**Could not load world, creating a new one : System.NullReferenceException Object reference not set to an instance of an object.**

the files of the world, as I understand it, are now in the folder " worldBackups.zip " , but when I pull them back into the " world " folder, I see this error text over and over again, I don't understand what it means, just a couple of hours ago everything was fine.

Windows 10
Sabnautica Legacy
Nitrox 1.7.1.0

I used a translator to write this.

![изображение_2024-05-19_045930693](https://github.com/SubnauticaNitrox/Nitrox/assets/89232506/ed2dd2bf-5b04-4025-9491-d44c6dd19367)

**Comment by NinjaPedroX** [comment]
Looks like your save files are corrupted. Please join our [Discord server](https://discord.gg/subnautica-nitrox-official-525437013403631617), where we can help you further.

**Comment by sheydhql** [comment]
> Looks like your save files are corrupted. Please join our [Discord server](https://discord.gg/subnautica-nitrox-official-525437013403631617), where we can help you further.

this help channel? 

![изображение_2024-05-19_051717632](https://github.com/SubnauticaNitrox/Nitrox/assets/89232506/206720ad-2599-45cb-9ddf-a91a5ccfb3e5)
