### ISSUE TITLE
bz-experimental branch launches subnautica not below zero

### ISSUE THREAD

**Issue by Art3mis2980** [SubnauticaNitrox/Nitrox#2144]
### Describe the issue

bz-experimental branch launches subnautica not below zero and when i try to change the game folder it says that it needs to be subnautica

**Comment by Coding-Hen** [comment]
This branch is still being worked on and as such doesn't have all the kinks ironed out. It can be used to launch bz however it is not stable and is not currently supported by our team. 

Many changes is the last update to bz caused breaking changes with compatibility. I would currently not advise trying to use this branch unless you have experience in c# and with to manually edit some code first
