### ISSUE TITLE
Nitrox cannot start Subnautica (Discord shutting down client?)

### ISSUE THREAD

**Issue by natrius** [SubnauticaNitrox/Nitrox#2152]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

I downloaded Nitrox to my download folder, started the launcher as administrator, checked the path `C:\Program Files (x86)\Steam\steamapps\common\Subnautica` and then through "Play game" with "Play Multiplayer" it tries to start the game (the little icon in the taskbar appears) and then the icon disappears again and nothing happened. Logs below.

Discord is started and running, if that is somehow needed as well?

Unfortunately I am not able to post on discord due to no phone-number in discord. 

### Relevant log output

```
[11:05:50.366] [INF] Using Nitrox Alpha V1.7.1.0 built on 26.07.2024 09:00:25
[11:05:50.517] [INF] Registering dependencies
[11:05:50.597] [INF] Patching Subnautica...
[11:05:50.926] [INF] Completed patching
[11:05:50.926] [INF] Applying Nitrox behaviours..
[11:05:50.929] [INF] [Discord] Starting Discord client
[11:05:50.939] [INF] Behaviours applied.
[11:05:52.812] [INF] [Discord] Shutdown client
```

**Comment by Measurity** [comment]
Could you upload the Player.log file as well? It's location is here:
`%appdata%\..\LocalLow\Unknown Worlds\Subnautica\Player.log`

(my guess on the issue atm is that your anti virus is blocking Nitrox from starting, but would like to confirm the issue)

**Comment by natrius** [comment]
Sure thing, its simply the Windows Defender, not something else. Additionally, i forgot to mention, in Steam i chose 
"Betas" - "legacy - Public legacy builds" with "none" i get an error that the game is not found. (Plus, the others are playing with this currently :D )

```
Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Subnautica/Subnautica_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Subnautica/MonoBleedingEdge/etc'
Initialize engine version: 2019.2.17f1 (441)
[XR] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Subnautica/Subnautica_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA Quadro T2000 with Max-Q Design (ID=0x1fb8)
    Vendor:   
    VRAM:     3949 MB
    Driver:   31.0.15.3818
Begin MonoManager ReloadAssembly
- Completed reload, in  0.105 seconds
OnLevelWasLoaded was found on OVRScreenFade
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
 
(Filename: C:\plastic_workspace_unity\Runtime/Mono/MonoScriptCache.cpp Line: 355)

<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.651000 ms
Initializing Steam services
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Nitrox will not load because launcher path was not provided.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
 
(Filename: C:\plastic_workspace_unity\Runtime/SceneManager/SceneManager.cpp Line: 566)

Object reference not set to an instance of an object
Material doesn't have a texture property '_MainTex'
 
(Filename: C:\plastic_workspace_unity\Runtime/Shaders/Material.cpp Line: 1371)

Material doesn't have a texture property '_MainTex'
 
(Filename: C:\plastic_workspace_unity\Runtime/Shaders/Material.cpp Line: 1371)

Loading game settings
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Unloading asset bundle 'waterdisplacement' because it is no longer referenced
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Material doesn't have a texture property '_MainTex'
 
(Filename: C:\plastic_workspace_unity\Runtime/Shaders/Material.cpp Line: 1371)

Process name: Subnautica
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

changeset 68598, QualityLevel = 2
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

OK Running Win64
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Application version: 68598
 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

SystemInfo: 
 deviceModel = MODEL
 deviceName = DEVICENAME
 deviceType = Desktop
 deviceUniqueIdentifier = STRING
 graphicsDeviceID = 8120
 graphicsDeviceName = NVIDIA Quadro T2000 with Max-Q Design
 graphicsDeviceType = Direct3D11
 graphicsDeviceVendor = NVIDIA
 graphicsDeviceVendorID = 4318
 graphicsDeviceVersion = Direct3D 11.0 [level 11.1]
 graphicsMemorySize = 3949
 graphicsShaderLevel = 50
 npotSupport = Full
 maxTextureSize = 16384
 operatingSystem = Windows 10  (10.0.0) 64bit
 processorCount = 12
 processorFrequency = 2592
 processorType = Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
 supportedRenderTargetCount = 8
 supports3DTextures = True
 supportsAccelerometer = False
 supportsComputeShaders = True
 supportsGyroscope = False
 supportsImageEffects = True
 supportsInstancing = True
 supportsLocationService = False
 supportsRawShadowDepthSampling = True
 supportsRenderTextures = True
 supportsRenderToCubemap = True
 supportsShadows = True
 supportsSparseTextures = True
 supportsStencil = 1
 supportsVibration = False
 systemMemorySize = 32595

 
(Filename: C:\plastic_workspace_unity\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Setting up 6 worker threads for Enlighten.
  Thread -> id: 56f0 -> priority: 1 
  Thread -> id: 43ec -> priority: 1 
  Thread -> id: 6240 -> priority: 1 
  Thread -> id: 56c8 -> priority: 1 
  Thread -> id: 4de8 -> priority: 1 
  Thread -> id: 3e9c -> priority: 1 

 
(Filename:  Line: -1)


```

**Comment by Measurity** [comment]
Here's a guide that we use on Discord when this issue comes up.

>Make sure to open Nitrox as Administrator.
>
> If step 1 didn't work, Open Nitrox without Administrator.
>
> This is arguably the best fix for this issue. If that somehow still does not work, try each of the other fixes below:
> Make sure the Nitrox Folder and Subnautica Folder are on the same drive( Note: Do NOT place the Nitrox folder in the same folder as Subnautica), Just place it in the Local Drive. If you only have one drive, simply place the Nitrox folder on desktop.
>
> Verify the game integrity in case of corrupted files: (see below)
>
> If you have an Antivirus like (AVG, Avast, Kaspersky or Eset Internet Security), Either try disabling it, or add an exception for nitroxlauncher.exe and nitroxserver-subnautica.exe
>
> If you are using an Windows Administrator Account, try logging out of it. If you are not using it right now, try using it, it might fix the issue.

### Verify game files
> 1. Go to your Subnautica installation (example is for Steam but Epic is similar). Example:
> C:\Steam Games\steamapps\common\Subnautica\Subnautica_Data 
> Delete the "Managed" folder.
>
> 2. Verify game files: Steam steps below (For Epic see image)
> Right click game in steam
> Click Properties
> Click Local Files
> Click "Verify Integrity of game files"
>
> 3. Run the launcher as admin and press play
>
> ![image](https://github.com/user-attachments/assets/3c48fc6d-7833-4fb1-803c-571402c615ea)

(Usually if it's a file permission issue an error should pop up or something should be written in `Player.log`. But if it's a security program that's killing Subnautica, running/not-running as admin can help.)

**Comment by natrius** [comment]
Thanks for your help! 

1. Start Nitrox without admin: asks to open with admin, then same problem
2. Start Nitrox as admin: same problem
3. Subnautica is in steam default, nitrox in "Downloads". Copied nitrox-folder to "Desktop" and tried again. Same Problem. 
4. Verify gamefiles: 1 file needed redownload, started nitrox from desktop without admin: same problem
5. Added nitroxlauncher.exe and nitroxserver-subnautica.exe to Windows Defender Exception: startet from downloadsfolder again: same problem
6. Not using the admin-account as one should not, but using an additional admin accnut to install stuff as admin and so on. 

I bet at home on my computer it works instantly :D

**Comment by SavageJayGatsby** [comment]
Regarding Step 1 - It asks to open with admin but you can safely ignore that and try to move forward without admin to see if the problem still occurs.

**Comment by natrius** [comment]
I completely missed that one. Starting without admin actually worked. 🤦  Thanks for your help! :)

**Comment by natrius** [comment]
So, this would be my little rework from your steps: 

1. Make sure to open Nitrox as Administrator.
2. If step 1 didn't work, Open Nitrox without Administrator. (If you abort the Admin-Popup when starting Nitrox, it will start without Admin)
This is arguably the best fix for this issue. If that somehow still does not work, try each of the other fixes below:
3. Make sure the Nitrox Folder and Subnautica Folder are on the same drive (Note: Do NOT place the Nitrox folder in the same folder as Subnautica), Just place it in the Local Drive. If you only have one drive, simply place the Nitrox folder on desktop.
4. Verify the game integrity in Steam in case of corrupted files.
5. If you have an Antivirus like (AVG, Avast, Kaspersky or Eset Internet Security), either try disabling it, or add an exception for nitroxlauncher.exe and nitroxserver-subnautica.exe
6. If you are using an Windows Administrator Account, try logging out of it. If you are not using it right now, try using it, it might fix the issue.
