### ISSUE TITLE
Fix player not being shown disconnection panel

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#2157]
### Describe the issue

Fix player not being shown the disconnection panel when server stops or kicks the player [see Modal.cs](https://github.com/SubnauticaNitrox/Nitrox/blob/cfc08f3cc1174e551bddfb2dabaec1f6f34cc1a3/NitroxClient/MonoBehaviours/Gui/Modals/Modal.cs#L14)

Investigate `NetManager.DisconnectOnUnreachable`, `NetManager.MaxAttempts`, etc..

Suggested by @tornac1234

**Comment by OhmV-IR** [comment]
I have a fix(seems to be at least) for this, but I need to test & review code myself before I open up the PR
