### ISSUE TITLE
Defocus chat input field on enter and refocus on 'Y' press

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#2159]
### Describe the issue

Chat doesn't defocus when you press enter (if you hold enter and type you'll immediately submit the letter).
Make it so that:
- [x] `Enter` defocuses the input

This makes it more inline with other games like Counter Strike 2 or Deep Rock Galactic.

## Related code
https://github.com/SubnauticaNitrox/Nitrox/blob/cfc08f3cc1174e551bddfb2dabaec1f6f34cc1a3/NitroxClient/MonoBehaviours/Gui/Chat/PlayerChatInputField.cs#L101-L115

**Comment by dartasen** [comment]
#2182 Did fullfill the first point

**Comment by Risusama** [comment]
Just to clarify, what are the situations counted as "in-game cursor active" in which we would like the chat to refocus?
 - ESC menu?
 - Tab-menu (inventory, databank etc.)?
 - something else?
