### ISSUE TITLE
leviathans not moving

### ISSUE THREAD

**Issue by dominusballdemon** [SubnauticaNitrox/Nitrox#2170]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

i was trying to hunt for leviathans but when we got there the leviathans werent moving for me but my friend could see them moving

**Comment by Measurity** [comment]
Duplicate of #1153
