### ISSUE TITLE
Can't build the solution in visual studio. The "DiscoverGame" task was not found.

### ISSUE THREAD

**Issue by RomikB** [SubnauticaNitrox/Nitrox#2171]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Other

### Describe the issue.

Current solution do not depend from new package (Nitrox.Discovery.MSBuild). Solution can not be build from IDE.

### Describe the steps you took to encounter the bug.

Open the solution. Run Build Solution.

### Relevant log output

Nitrox\Directory.Build.targets(4,9): error MSB4036: The "DiscoverGame" task was not found.

**Comment by Measurity** [comment]
Does the issue persist after you restore the nuget packages?

**Comment by RomikB** [comment]
Sorry, click wrong button.

**Comment by Measurity** [comment]
Thanks. Could you try changing msbuild package to version 0.0.4? I've deprecated the 0.0.3 and older versions on Nuget which might have caused Visual Studio to ignore those.

**Comment by RomikB** [comment]
I change to '<PackageReference Include="Nitrox.Discovery.MSBuild" Version="0.0.4">' in 'Nitrox\Directory.Build.props'. Reload Solution. Do clean, restore packages, build. Nothing changed.

**Comment by Measurity** [comment]
Thanks for waiting and for creating this issue.
Found a fix for this which will be available when this PR is merged #2173

Cause is explained in the PR if you're interested.
