### ISSUE TITLE
How do I get Nitrox on Mac?

### ISSUE THREAD

**Issue by ProProgramer123** [SubnauticaNitrox/Nitrox#2176]
### Describe the issue

I am on a mac and I do not know how to get Nitrox on my mac.

**Comment by oliver408i** [comment]
Because you can't. Ask in the discord first before opening an issue.

**Comment by Measurity** [comment]
Improvements for Mac are on the way but no promises that it will be fully supported. Have (more) testers on Mac would be a big help.

#1848
