### ISSUE TITLE
Base Power Desync

### ISSUE THREAD

**Issue by ctrLd147** [SubnauticaNitrox/Nitrox#2179]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest release of Nitrox.

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

Power supply desync, issue is already opened somewhere, causes some people to see reactors etc, but some cant

**Comment by Jannify** [comment]
Duplicate of fixed base building (on master) or already existing #1811
