### ISSUE TITLE
NitroxPatcher fails to build

### ISSUE THREAD

**Issue by ZiotecH** [SubnauticaNitrox/Nitrox#219]
I've been trying to build Nitrox a few times now, and every time I get the same build-error.

`1>------ Build started: Project: NitroxPatcher, Configuration: Debug Any CPU ------
1>V:\tempo\Nitrox-master\Documents\Nitrox\NitroxPatcher\Patches\TelemetryReporting_SendPlayerDeathEvent_Patch.cs(12,59,12,77): error CS0246: The type or namespace name 'TelemetryReporting' could not be found (are you missing a using directive or an assembly reference?)
2>------ Build started: Project: NitroxTest, Configuration: Debug Any CPU ------
========== Build: 0 succeeded, 2 failed, 6 up-to-date, 0 skipped ==========`

And sure enough, the thing that holds it back is indeed the reference to TelemetryReporting, which it claims doesn't exist.

This has been done with the newest repo pulled.

Error specifically found in "TelemetryReporting_SendPlayerDeathEvent_Patch.cs" on line 12.

Any assistance would be deeply appreciated.

**Comment by derbartman** [comment]
I also have this same issue with a new clone and new download of studio..

**Comment by magus1972** [comment]
Same problem...

**Comment by magus1972** [comment]
Hey, I've just found the solution on The Mysticle's Discord. Here is the quote by Ormarr: 

"To elaborate for other peeps: Search for "Telemetry" using the solution explorer (Top right, usually), click on "TelemetryReporting_SendPlayerDeathEvent_Patch.cs" and replace "TelemetryReporting" with "TelemetryReporting_SendPlayerDeathEvent_Patch". Build and enjoy! Thanks a bunch Silv3r"

So you basically need to replace "TelemetryReporting" with "TelemetryReporting_SendPlayerDeathEvent_Patch" and it works!

**Comment by magus1972** [comment]
You need to replace TelemetryReporting with "TelemetryReporting_SendPlayerDeathEvent_Patch" ;)

**Comment by ZiotecH** [comment]
Wow.. Why didn't that even cross my mind?
I blame the warpers.

**Comment by ahk1221** [comment]
@magus1972 @ZiotecH All that does is make sure that the project compiles. Basically, all you're doing is changing what class is being patched. It's really very stupid to just change it so that you're patching the actual patcher class.. I've made a PR that fixes this issue, should be accepted if everything is fine.
