### ISSUE TITLE
Fixed status of escape pod doesn't save/load and still plays the alarm sound

### ISSUE THREAD

**Issue by Czekoloczek** [SubnauticaNitrox/Nitrox#2200]
### Are you on the latest version of Nitrox?

Yes, I'm on the latest commit of the repo (only for experts).

### Which OS are you playing on?

Windows

### On which platform did you buy Subnautica?

Steam

### Describe the issue.

https://youtu.be/8k0j7f8lWW4

### Describe the steps you took to encounter the bug.

\> Repair the esacpe pod
\> Stop the server
\> Start the server
\> Join the server

### Relevant log output

https://pastebin.com/phRr9CGv
https://pastebin.com/xzErFVyJ

**Comment by Czekoloczek** [comment]
also, the alarm plays globally, it probably should only play when inside the escape pod

**Comment by Tevtongermany** [comment]
still happening?

**Comment by Measurity** [comment]
> still happening?

Yes. Last commit on master caused it but no one had time to fix this yet. This issue will be closed when it's fixed.

**Comment by Tevtongermany** [comment]
aight

**Comment by Jannify** [comment]
Ok the sound  issue only manifest when the intro is skipped (when building in DEBUG configuration or when joining in creative). Will investigate a fix for it
