### ISSUE TITLE
does anyone have any servers?

### ISSUE THREAD

**Issue by jeremiah0** [SubnauticaNitrox/Nitrox#223]

**Comment by Neimoh** [comment]
I just joined the Subnautica Modding community and am very intrigued and wishful for this project. I own a private Dedicated server that is kinda just idling here now waiting for something to run. If it would assist in developing this mod I can make it available.

Win 10 Ultimate
Water Cooled I7-6800k o/c 4.3ghz
32g DDR4 2666
Samsung 960pro 256g nvme m.2 ssd split for o/s and server files, 2nd 250g mechanical drive for storage.
I'm on cable internet 250ds / 12us

**Comment by AlexejheroYTB** [comment]
@jeremiah0 I don't think this is topic is fit for an issue report, this is usually something that you would see on a forum
