### ISSUE TITLE
dnSpy does not edit Assembly-CSharp.dll

### ISSUE THREAD

**Issue by Egor179** [SubnauticaNitrox/Nitrox#227]
At compilation produces a lot of errors, did everything the same as always.
https://c.radikal.ru/c35/1806/5e/96497e52d84f.png

**Comment by quimnuss** [comment]
There's the exact same issue like 6 issues below this one. Please read what's there before posting.

https://github.com/SubnauticaNitrox/Nitrox/issues/211

**Comment by AlexejheroYTB** [comment]
Duplicate of #221

**Comment by AlexejheroYTB** [comment]
(Added comment because `Duplicate of #` is a GitHub keyword)

**Comment by quimnuss** [comment]
I guess you meant 211 ?

Duplicate of #211

**Comment by quimnuss** [comment]
Duplicate of #211
