### ISSUE TITLE
Air Pump Pipes not Syncing to Client

### ISSUE THREAD

**Issue by Neimoh** [SubnauticaNitrox/Nitrox#244]
Survival 2 player Local LAN. I can set a surface air pump which player 2 can see but every air pipe I connect he only sees as if the pipes are dropped in the line I place them in but are not connected on his side and he can't draw air from them.

**Comment by Frappa123** [comment]
Also having the same issue

**Comment by Praevalens** [comment]
As an potential easy fix, I'm picking this up to learn the Nitrox code. Will keep this issue updated.

**Comment by Coding-Hen** [comment]
Brilliant good luck. Glad to have another developer onboard

**Comment by Praevalens** [comment]
@Coding-Hen Quick question, how do you test multiplayer features do you have to buy the game twice? (I'm thinking once on steam and once on Epic Launcher) since steam doesn't let me launch it twice.

**Comment by Coding-Hen** [comment]
That's one way of doing it, if you have a second computer you can do it
with a trick of family sharing on Steam. Easiest way though other than
buying another version is to go on the discord and ask for someone to join

**Comment by Praevalens** [comment]
Oh my god, I never knew steam had that functionality. Well guess I'll spin up a VM and get debugging. You my friend just saved me all the money I would have spent on buying games for my girlfriend so we can play together 😲

**Comment by acidscorch** [comment]
I don't know if this is really Base related, but i will test it and take into account.

**Comment by acidscorch** [comment]
I have tested this. The base attached air pump is base related. 

The swimming air pump and the air pipes are standalone objects and need to be handled separatly.

**Comment by Jannify** [comment]
Moved it to https://github.com/SubnauticaNitrox/Nitrox/issues/1450
