### ISSUE TITLE
All inventories and blueprints cleared themselves

### ISSUE THREAD

**Issue by Neimoh** [SubnauticaNitrox/Nitrox#245]
Survival 2 player Local LAN. My son and I were playing locally and had a bunch of inventory between 2 wall lockers and 2 large lockers in a base. He logged out for the night and I was away from the base located in shallows while I was in jelly shrooms. He logged back in to see if his inventory stayed which it did and everything else was still there. Then he logged out for real after running a local save on his machine. When I got back to base All inventories were empty, all the growing planters and pots were empty. Everything was wiped. I logged off and loaded us both back in and same issue. This time though, All the voice recordings played the point where Aurora exploded back to back. Our base was still there but the mounting posts into the ground were gone and it was loaded with swimming fish and scrap metal. Lockers and pots were present but still empty and all of our scanned blueprints were also cleared

**Comment by garsia0** [comment]
im working on blueprint save if you want to test https://github.com/garsia0/Nitrox

**Comment by rakete** [comment]
I have just tested your build garsia0. As long as I kept the server running the blueprint were saved and would be added to my PDA after quitting and re-joining the server.

As soon as I restarted the server however, all blueprints were missing from my PDA again.

So I use saving the blueprint works, but loading them back from save.nitrox file does not.

**Comment by garsia0** [comment]
acado de realizar unos fix actualiza y prueva de nuevo gracias por reportar

**Comment by rakete** [comment]
I just tried it and it works. Blueprints (at least the few I got while testing from beginning) are saved and added back to the player after restarting the server.

**Comment by Neimoh** [comment]
This makes it so much easier as each player can contribute to progress, anyone that's scans a fragment or picks up a PDA is shared by everyone. My son and I have verified that the scanned items are retained on this build as long as the server is running. However a bug seems to have been created, we no longer can drop inventory and the other can pick it up. Our only means of transfer is via lockers, even the waterproof locker is not visible to anyone but the owner. This used to work on the master branch.

**Comment by Coding-Hen** [comment]
@garsia0 did you make any progress on implementing this is still an outstanding issue?

**Comment by Measurity** [comment]
Inventory sync issues are being tracked here: #1003

Thank you for providing detailed steps on what happend at which time. This will help us fix this bug. If you have more information regarding this bug, please post it in the referenced issue.
