### ISSUE TITLE
[question] linux server

### ISSUE THREAD

**Issue by Aaronstar-McClure** [SubnauticaNitrox/Nitrox#249]
Would the server program work on a normal linux server? Or would i need to push it through mono?

**Comment by Sunrunner37** [comment]
I don't think the server will work on linux as we build against microsoft binaries and not mono binaries.  However, I'm not entirely sure as I haven't tried.

**Comment by adamryczkowski** [comment]
What is the status now? I contemplate to buy the game for my whole family, but only if I would be able to play on linux with this mod.
