### ISSUE TITLE
Fish not spawning

### ISSUE THREAD

**Issue by UberPsyX** [SubnauticaNitrox/Nitrox#254]
Hey, I am using latest build of the mod, from today, and the latest steam version, wehn I am in game the ocean seems to be dead, I cannot see any fish, etc. Is it okay?

**Comment by quimnuss** [comment]
When this happens to me I usually delete the nitrox.save, ensure that I've compiled the NitroxServer and relaunch.

Of course you lose the save, but this is a mod not yet meant to be used to play yet, so that will happen often. Saves aren't intended to be forward compatible.

**Comment by quimnuss** [comment]
It does.

The mod is not close to release at this point

**Comment by UberPsyX** [comment]
I got you, thanks for the answer.
