### ISSUE TITLE
No fish, minerals or other players visible for a client.

### ISSUE THREAD

**Issue by samsunix** [SubnauticaNitrox/Nitrox#258]
Computer 1, host, client 
Computer 2, client

connected by via Hamachi. 

On the host computer 1. player is able to see everything, even other players.
On the client computer 2. player is not able to see other player, fish, minerals.

Both computers have fresh subnautica (legit steam) install and Nitrox installed with this as**ole: 
https://www.youtube.com/watch?v=_0IQ4VvTRXc

**Comment by garsia0** [comment]
that instalation guide is wrong

put path method like that remember add using NitroxPatcher;

private void Awake()
	{
		Main.Execute(); 
		if (GameInput.instance != null)
		{
			UnityEngine.Object.Destroy(base.gameObject);
			return;
		}
		GameInput.instance = this;
		GameInput.instance.Initialize();
		for (int i = 0; i < GameInput.numDevices; i++)
		{
			GameInput.SetupDefaultBindings((GameInput.Device)i);
		}
	}

**Comment by quimnuss** [comment]
He does it correctly at the end of the video.

**Comment by samsunix** [comment]
Chancing that on line position did not resolve anything :(

**Comment by trjflash** [comment]
Hi folks! Could you tell me the problem with the respawn of scrap metal, and drawing still there or am I missing something?
