### ISSUE TITLE
Cave Crawler deprecated spawn type

### ISSUE THREAD

**Issue by killzoms** [SubnauticaNitrox/Nitrox#271]
Aurora old spawn type
![screenshot 23](https://user-images.githubusercontent.com/13115936/43310486-b0a1b144-9155-11e8-8b82-9ca2272e02eb.png)

Island proper spawn on left old spawn type on right
![screenshot 24](https://user-images.githubusercontent.com/13115936/43310487-b0b7f12a-9155-11e8-902d-9efa9d691d76.png)

**Comment by Coding-Hen** [comment]
Has this been changed over now?
