### ISSUE TITLE
Warpers duplicated and not working.

### ISSUE THREAD

**Issue by DevoutRelic** [SubnauticaNitrox/Nitrox#272]
Two warpers teleport in on each spawn point, and neither of them move. They won't throw teleport orbs at me either. They will claw me if I get close enough, but afterwards they still won't chase me. I'm assuming this issue is related to the very similar leviathan bug. Only difference is that none of the warpers work, whereas one of the leviathans usually works.

**Comment by killzoms** [comment]
Will try getting the classId for the warpers and adding them to blacklist

**Comment by killzoms** [comment]
Added to blacklist bore no fruit
