### ISSUE TITLE
There are no Peepers

### ISSUE THREAD

**Issue by F1R3H4WK** [SubnauticaNitrox/Nitrox#273]
I know, that there are already an issue with this error:
`[Nitrox] W: Couldn't load serializable attribute for Peeper version`
But there was an answer. The reason why it is not working is that your subnautica wasn't installed from Steam.
So after reading Nitrox source code(mainly Helper namespace) I found, how Nitrox is searching Subnautica location. So I "simulated" Subnautica installation:
1. I've installed steam
2. In steamapps folder, I've created appmanifest_264710.acf file.
3. I've copied Subnautica folder to the common folder.
But nothing happened [http://tinypic.com/r/22zyqb/9](url)
And after playing about an hour, there weren't stalkers also. But a lot of bubblefishes.
Can you help?

**Comment by AlexejheroYTB** [comment]
Duplicate of #173
