### ISSUE TITLE
Multiplayer Interface not showing up

### ISSUE THREAD

**Issue by SkidFlashys** [SubnauticaNitrox/Nitrox#274]
When I click on the "Multiplayer" Tab, nothing happens

**Comment by SkidFlashys** [comment]
Also, when I click on "Options", the game crashes

**Comment by Measurity** [comment]
Could you upload the output log? It's located here: `..\steamapps\common\Subnautica\Subnautica_Data\output_log.txt`.

Also, make sure the injected `NitroxPatcher.Main.Execute()` is in the right location:
https://i.imgur.com/mUachvA.png

**Comment by Gumby37** [comment]
Right in this part prior to compiling. 
https://i.imgur.com/Si08Hgp.png

**Comment by Measurity** [comment]
@Gumby37 That's the wrong location. You'll get keybinding exceptions because Nitrox hooks `GameInput.bindings` which shouldn't be changed after `GameInput.Initialize()`.

**Comment by AlexejheroYTB** [comment]
Duplicate of #196
