### ISSUE TITLE
Items disappearing from inventory

### ISSUE THREAD

**Issue by fleeting-aardvark** [SubnauticaNitrox/Nitrox#280]
On a most recent download of the server {8/11/2018}, items seem to disappear from inventory.
Specifically in this case, it was the lead resource.  Even after locating and collecting more, it was removed from inventory not long afterwards.

Another item that disappeared from inventory was a storage upgrade to the Seamoth.  It also was removed from inventory.

Removed from inventory does not mean dropped either.  The items disappeared and became no longer view able or available in game.

**Comment by garsia0** [comment]
the current status of mod no support savegams from old vercion

**Comment by crashfly** [comment]
the save game was from a current version.  it was not previously used prior to this update

**Comment by crashfly** [comment]
yes, client version is 60072 and the nitrox server files have all be recompiled very recently.  yet i still get inventory syncing problems.

**Comment by Measurity** [comment]
This issue is being tracked here: #1003
