### ISSUE TITLE
Base Built Not Loading Correctly On Server Reload

### ISSUE THREAD

**Issue by Frappa123** [SubnauticaNitrox/Nitrox#282]
Built a base in a new game, (couple of multipurpose rooms); when loaded the server back up it would load certain parts but others would be missing.

**Comment by M3dicCookie** [comment]
Well with mine it slowly loads everything and I never log out on my base because I run out of oxygen. I'm thinking maybe other pieces your friends builds don't sync until server reloads at least for me.
