### ISSUE TITLE
Bug in compile code 

### ISSUE THREAD

**Issue by minhdung321** [SubnauticaNitrox/Nitrox#285]
I have many bug in compiling code with NitroxPatcher in dnSpy. 
![image](https://user-images.githubusercontent.com/39442146/44300150-5b45f500-a32c-11e8-83f1-fbf071d495d5.png)

**Comment by quimnuss** [comment]
Duplicate #211

El 16:20 ds. 18/08/2018, minhdung321 <notifications@github.com> va escriure:

**Comment by Measurity** [comment]
@minhdung321 This problem is also explained in the wiki ["Setting-up-a-development-environment-for-Nitrox"](https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox). I hope others will read that first before posting the issue again.

**Comment by minhdung321** [comment]
Yes I have seen it. And I deleted lines 9 through 19 and it worked out as I wanted. Sorry about forgetting to close my post.
