### ISSUE TITLE
Renaming wiki title "Setting up a development environment for Nitrox"

### ISSUE THREAD

**Issue by q4z1** [SubnauticaNitrox/Nitrox#287]
As the wiki post is not only about the setup for a dev-env, can you rename it into something more user friendly for hobby c#coders like "HowTo Build the mod with Visual Studio" or kinda?

**Comment by crashfly** [comment]
I have created an Installation and Testing page with full instructions.   This should resolve your issue.

**Comment by q4z1** [comment]
Thank you very much.
