### ISSUE TITLE
more details for wiki part "Inject NitroxPatcher into Assembly-CSharp"

### ISSUE THREAD

**Issue by q4z1** [SubnauticaNitrox/Nitrox#288]
Can you provide a few more details about how to do this in a best way?

I saw a youtube video from a guy, explaining how to do this. But he obviously did a minor mistake ... Injecting dircectly inside a for-loop.

**Comment by crashfly** [comment]
A more complete installation and testing page has been created.  This should resolve your problem.

**Comment by q4z1** [comment]
Thank you very much.
