### ISSUE TITLE
No oxygen loss with tank.

### ISSUE THREAD

**Issue by fleeting-aardvark** [SubnauticaNitrox/Nitrox#290]
Updated and compiled a few of hours ago {Wed, 22 Aug 18 @ 5pm CST} on a client version of 60072.

When wearing an oxygen tank or high capacity oxygen tank, there is no oxygen loss for the player.
This occurs for the host {myself} and another client computer {a friend}.

----
With the recent changes to player positioning, I do not believe this is an intended side effect.

**Comment by crashfly** [comment]
Further play on the new save seems to limit this bug on initial startup of the server.  Disconnecting and reconnecting later has corrected the problem.

Still, it was kind of nice to not have to go up for air.

**Comment by tprussak** [comment]
I've also experienced this issue. Another fix for it is to manually remove and reequip the tank. It seems to be related to the tank being put into the player's equipment automatically when crafted.

**Comment by TroelsL** [comment]
We've also experienced this bug. Exiting and restarting the clients did not resolve it. As soon as any tank is equipped, unlimited O2.

**Comment by Kurgol** [comment]
It's only when the oxygen tank (and advanced oxygen tank) are auto-equipped by the crafting station. If you immediate unequip and requip either tank it starts working correctly. Hope that helps!

**Comment by GW-GhostWolf** [comment]
We have found that the bug is related to equipping any tank at or above the surface. We have a fix that is being committed and PR'd shortly.
