### ISSUE TITLE
Fabricator items going to wrong person.

### ISSUE THREAD

**Issue by fleeting-aardvark** [SubnauticaNitrox/Nitrox#291]
Updated and compiled a few of hours ago {Wed, 22 Aug 18 @ 5pm CST} on a client version of 60072.

When in the vicinity of a fabricator {in a base, or the starting life pod}, the fabricator will give the items just created to the most recent person that came near the fabricator.  This happens for both the host and client computer.

**Comment by Measurity** [comment]
Doesn't seem to happen anymore. Gonna close this, please create a new issue if it is still the case.
