### ISSUE TITLE
Crashes on Launch

### ISSUE THREAD

**Issue by veerorith** [SubnauticaNitrox/Nitrox#296]
So I followed this tutorial https://www.youtube.com/watch?v=_0IQ4VvTRXc
And I also did the fix for the compiling error for issue 221 https://github.com/SubnauticaNitrox/Nitrox/issues/211

But. I still crash when I start the game.  I get a glimpse of the game with a black screen and a date/version in the top right May 2018 60072, but then it immediately closes.  I'm not 100% sure what parts of the log are useful so here's the whole thing because why not.  

Also.  When I build the project in Visual Studio instead of getting the 8 completed and nothing else like in the video I get 9 completed 1 skipped. So I wasn't sure if that was because parts were added/updated and something was obsolete or if I just fucked it up.  So if thats the cause here please let me know and maybe how to fix that.  But since there were no errors per say I continued from that point.  

(For reference I have super rudimentary experience using visual studio and blender to mess with 3d models and some experience with html/css and like 1 class in javascript.  I'm not a complete noob at certain things but please be detailed in replies for the sake of my sanity and not needing to google how to find a certain function in a program/syntax for a certain task.  Or at least be willing to help when I inevitably fuck it up by dropping a semicolon >_<  Thanks!

[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2342287/output_log.txt)

**Comment by Measurity** [comment]
The Nitrox solution contains 1 project that's for building the installer, called `NitroxInstaller`. If it skips that project you're fine.

I'm not sure what the error is specifically but I do know that the video asks you to inject Nitrox in the wrong location. `NitroxPatcher.Main.Execute()` should be at the top (first thing that is executed) of the `GameInput.Awake()` method. 

If that doesn't work then make sure Subnautica is updated and make sure all the DLLs from Nitrox are copied over to your game installation.
![afbeelding](https://user-images.githubusercontent.com/1107063/44945663-a4974980-adee-11e8-8d80-387d3e09f18b.png)

You should look for the DLLs from Nitrox here: `...\steamapps\common\Subnautica\Subnautica_Data\Managed`

**Comment by Measurity** [comment]
👍 that's all good at least. Does it work better now or still the same? I hope the output log is more meaningful now.

**Comment by veerorith** [comment]
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2342376/output_log.txt)
It looks like it crashes at the exact same point.  For what its worth I reinstalled subnautica before trying the install of nitrox again and I know it works unmodded.  But yeah.  Same crash.

**Comment by veerorith** [comment]
I actually just did that in this most recent attempt.  Deleted csharp dll and verified the files to let steam install it fresh.  The only code changed is the highlighted line, and the removal of lines 9-19 to deal with the whole #211 compiling issue.

**Comment by veerorith** [comment]
I'm going to uninstall my visual studio install and reinstall it since I basically overrode an older version when I installed it this time around that way there isn't any question of issues caused by that.  As well as redownload and do the whole process from scratch so there isn't any chance of leftover fuckups from the first time around. Will update when done with that.

**Comment by veerorith** [comment]
AHAHAHAHAHAHHHAAHAHAHA I updated my graphics drivers and now it works fine I'm a dummy.  It launches fine and I have the multiplayer list and everthing.  I'll set it up now on my laptop too and make sure it works in an actual game not just the main menu.  Thank you for the help and tolerating my silliness.

**Comment by Measurity** [comment]
Never would have guessed it be a driver issue. Nice work on solving it! Please close the issue if it's solved and thanks for explaining what you did to fix it.
