### ISSUE TITLE
Is importing an existing singleplayer save possible

### ISSUE THREAD

**Issue by veerorith** [SubnauticaNitrox/Nitrox#297]
I mean assuming it isn't I can see that it'd be a lot of work especially considering that if they are far along how do you be sure that the person who played in singleplayer would still have all their inventory/blueprints and stuff on joining.  Maybe is it tied to steam ID rather than the username chosen by the player when joining?  

Sorry if this is super random but I was just wondering.  Also can somebody 'steal' your inventory by using the name you use in game when joining?  I mean I will test that once I have the second machine with nitrox installed running but I was wondering if anybody has already figured that out.  I guess itd depend on the 'entered name' vs steam id question.  Anywho.  If anybody knows let me know.  If I find out on my own I'll update to answer my own random questions.  Hopefully that'll be kinda sorta helpful maybe.

**Comment by killzoms** [comment]
If someone feels like writing code to convert Subnautica saves to nitrox saves I would imagine that it wouldn't know the save owners name unless there is code to include the owners name/steamid in place. So a patch for the current save mechanism in singleplayer would be needed.
