### ISSUE TITLE
Worldspawn Issue Verification

### ISSUE THREAD

**Issue by bradleybooster** [SubnauticaNitrox/Nitrox#300]
I couldn't find any confirmation for my issue so I'll seek it here. When in multiplayer, all fauna and world objects (coral tubes etc.) spawn correctly, however when switching back to singleplayer, nothing apart from the opening cinematic fauna spawn, with the rest of the world being empty. 

A reinstall made no difference, and solutions to fix similar issues on the multiplayer side [such as [this](https://github.com/SubnauticaNitrox/Nitrox/issues/188#issuecomment-370823042)] have no effect. Is this just what happens when Nitrox is installed, or is there deeper issues here?

**Comment by chengtai2** [comment]
Seconded. I'm having the same issue. I'm on latest version of SN and Nitrox. Like you said, fauna spawns just fine but no fish.
As far as I can tell, it also seems like no ores spawn. No limestones, no quartz, etc. And I didn't see any metal salvage spawns either after swimming around for about 10 minutes.
But strangely enough, I DID find some fish swimming around Reefbacks. But nowhere else.

**Comment by chengtai2** [comment]
I might want to add that this happened to me when I began a new singleplayer game. If I save the game from multiplayer and load it as singleplayer, spawns work correctly. On the flipside, new singleplayer games have the stated issues.

**Comment by Sajgoniarz** [comment]
I have similar issue, but at multiplayer. There are just few ores and bladderfishes. Whats surprising when i saw a reefback and i swum to it bunch of fishes fall of the sky including ~1- reefbacks. Is there any place in code, where i can manipulate with spawning rate?
