### ISSUE TITLE
NitroxServer binary.

### ISSUE THREAD

**Issue by gLevaa** [SubnauticaNitrox/Nitrox#302]
I was wondering if someone would be able to provide me with all the files for the NitroxServer and the .exe itself? Thanks.

**Comment by re-polm** [comment]
Check if the installer works. If it doesn't, (or even if it does) then the mod is not yet ready to be used for non-devs or testers.

If you want to be a dev or a tester, then you should be able to compile the server and the patch following the instructions on this project's wiki..

**Comment by kylinator25** [comment]
When you build the project in visual studio, the server .exe will be built with it, inside NitroxServer/bin/debug

**Comment by gLevaa** [comment]
I get millions of errors I honestly cant be bothered fixing, related to missing references and so on.

**Comment by quimnuss** [comment]
This mod is currently under development for modders and testers only.
