### ISSUE TITLE
Instruction "Setting up a development environment for Nitrox" missing some important stuff

### ISSUE THREAD

**Issue by MariuszPL55** [SubnauticaNitrox/Nitrox#304]
Hi everybody,

I want to only mark that instruction [Setting up a development environment for Nitrox](https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox) is missing info that the **Unity** or **Unity dll's** are required to build the solution in **Visual Studio 2017 Community**. You can do it simply by installing **Unity** support from the **Visual Studio Installer** or by installing whole **Unity** environment on your system.

**Comment by MarijnS95** [comment]
You do **not** need the Unity development libraries. All this mod does is link to the generated dll's which are **already bundled with the game**. Following the setup **closely** yields you a development environment with this **properly configured** automatically.

**Comment by MariuszPL55** [comment]
I agree that installing Unity not fully resolved my problems. Unfortunately, I can't get this solution to work, have problems with Vector3, Serializable attribute, event string references problem.

### Problem solved
**Subnautica NO EXPERIMENTAL is required** to make it work, so still I think this is not closed.

**Comment by MariuszPL55** [comment]
I agree that installing Unity not fully resolved my problems. Unfortunately, I can't get this solution to work, have problems with Vector3, Serializable attribute, event string references problem.

Problem solved
Subnautica NO EXPERIMENTAL is required to make it work, so still I think this is not closed.

**Comment by HeronickSK** [comment]
@MarijnS95 hi ... i somehow fixed the problem with **Unity**, but i have problem with **"Assembly-CSharp"** ... when i look in visual studio, then it doesn't even show a path to it

![snimka2](https://user-images.githubusercontent.com/45624854/50043124-06628300-006f-11e9-9106-c3494ee5e348.PNG)
![snimka](https://user-images.githubusercontent.com/45624854/50043125-06628300-006f-11e9-82b2-45fb9cc4d5ae.PNG)

thanks for help :)
