### ISSUE TITLE
A way to redirect port/s or to change IP

### ISSUE THREAD

**Issue by custume** [SubnauticaNitrox/Nitrox#306]
Hello to all,

Got your server running on a VM inside my server but I had a hard time redirecting port because the server don't latch on the external IP, just the internal, so inside my network all good (inside my Vlan) but outside I get port close all the time if I try to connect directly to the server.

It is online, you can connect by domain : custume-server.com on port 11000

But I had to redirect the port 11000 to 5000 inside my DMZ and them from port 5000 to 11000 inside my network, and it works now but was hard to find out the error

can you guys add some way ( if you have time ) to accept other port or IP so that we can config the server better and not running port redirects all over the place 

Thank you all for the mod and best regards

**Comment by MarijnS95** [comment]
It is open source, so anyone is free to contribute a properly working configuration mechanism (https://github.com/orgs/SubnauticaNitrox/projects/1#card-7411616).

As a temporary solution, you could change the ports ([here](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxClient/Communication/UdpClient.cs#L14) and [here](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxServer/Communication/UdpServer.cs#L159)) and recompile. Of course every player needs to have that change locally as well but that shouldn't be an issue given that this software is still pre-alpha (without any release).

**Comment by custume** [comment]
Great reply, thank you for the directions.

I can change the port but the string ipAddress where is the variable located ?? that is what I like to change, that way I can add a static IP and move on.

For the moment is already running with 2 redirects but with the info you give me I can custom tailed the server

I already offer my help to contribute with testing and debug but got no answer, even try on the subnautica forum but nothing, is not like I have to much time but I'm happy to help in any way.

Thx and best regards

**Comment by quimnuss** [comment]
I didn't even know there was a forum. You can put your issues here on the repository or visit the subnautica modding discord for a more interactive experience.

Althought the mp devs are very busy lately, you're welcome. 

El 10 d’octubre de 2018 17:35:40 CEST, Nuno Ribeiro <notifications@github.com> ha escrit:

**Comment by custume** [comment]
there is a discord ?!? , got it

Thx for the reply

**Comment by MarijnS95** [comment]
> I already offer my help to contribute with testing and debug but got no answer, even try on the subnautica forum but nothing, is not like I have to much time but I'm happy to help in any way.

Without any developers working on the project (last contribution has been almost 1.5 month ago) there's not much to test anyway. And even if you did write down a list of missing/broken things, chances are that it is already known. There's just not enough development capacity (read: no capacity at all) as seemingly the SN community is not interested in this mod.

That said, a "static IP" doesn't really apply to sever applications. The most you can do is use addresses to bind the listening port to a specific ethernet adapter on your server (rather than accepting traffic from all interfaces).
The IP address on the client side can (obviously) be changed from the Multiplayer join menu.

**Comment by quimnuss** [comment]
I would encourage people to open an Issue on the repo anyway after checking if one exists. Just for tracking puposes.

**Comment by custume** [comment]
Thank you for the reply MarijnS95,

Well I already have it bind to the (only) adapter on the VM, all the leg work is done by the firewalls.

The strange thing is the server not responding from outside, simply there is no flow to outside network.

The static ip idea was to force it to receive traffic from that ip and not the internal one, but after thinking a bit that don't make sense, no idea why the port don't cross over like all of the other services.

I try several ports and nothing work, I even try adding a service to that port and test it from outside and the service work fine, but not the nitrox server.

Well I will get back to you later on after some play sessions on the server, already have 3 players on it.

Thank you all and best regards 

PS, for the moment the server is working fine and there is no need for Hamachi.

**Comment by MarijnS95** [comment]
Just a quick check; are you forwarding TCP? Since about 2 months or so the project uses UDP.

**Comment by custume** [comment]
UDP, I made a scan to the network and found the only protocol was UDP, I had the TCP open but nothing was coming from that internally, so I scan it.

Thx for the concern

**Comment by custume** [comment]
Hello again to all,

Have play on the server and it looks good, really good, sure it haves some shortcomings but overall works ok, the spawn rate is off the charts and the occasional "flying" riper is all part of the fun hehehehehehh

I had to change the server to 2 cores and add more bandwidth to keep up with the users.

Is working on a dedicated machine inside a server cluster on Hyper-V with win2008R2, is working as stand alone, the only complain from the server is that is missing steam installation, no other error pop up.

The only major things in game that I spot was :

To many warpers, to many anything, the aurora blowup like 3 or 4 times, some story lines don't show up but some work ok, some crazy stuff can happens with the base building like stuff missing and stuff showing up from no where.

For the moment the top users count was 4 people and no problems, I will try to get more people to test

Thank you all and best regards

**Comment by custume** [comment]
Hello to all,
For the moment all is the same, but ...

We have one user having one strange problem, he gets a new ID every time we connects to the server and resets all the stuff that is using.

We already try checking files and the works but all looks ok, and this is the only user complaining about it.

I will keep looking in to it

Best regards

**Comment by Measurity** [comment]
Some ISPs (internet providers) don't assign static IPs to households. So every day you might get a different IP and then Nitrox thinks it's a different user. It's something that's fixable with a username+password per server but that feature doesn't exist yet.

**Comment by quimnuss** [comment]
ISP don't assign static IPs unless you pay for it. What happens is that they often assign long-time leases or assign repeatedly the same dynamic IP.

I am not so sure that is to be the issue, but if that's the issue, can this particular user join via hamachi or you're on a more public thing with dubious users?

**Comment by custume** [comment]
Looks like the version that I was using is old.
Just compile the last version, testing now, lets see if is working better

Best regards to all

**Comment by custume** [comment]
Here is an update ...

The new version is way better, buildings stay synchronized, spawn rates aren't out of whack, and the stuff you put in containers stay there.

There is a problem with the oxygen would sometimes stay full even under water, the oxygen tank don't save also the radiation suit.

Trying to find out how it is happening and I will let you know.

Great work

Best regards to all
