### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by dostapa** [SubnauticaNitrox/Nitrox#308]
When trying to build Nitrox in visual studio I get Error code: CS0246 5 times and it says 4/5 times that
The type or namespace name 'Lidgren' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\use goggle right\Downloads\Nitrox-master\Nitrox-master\NitroxModel\Packets\Packet.cs 
and the other error message says
The type or namespace name 'NetDeliveryMethod' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\use goggle right\Downloads\Nitrox-master\Nitrox-master\NitroxModel\Packets\Packet.cs

Not sure if i'm missing something but im pretty sure i followed most of the steps.

**Comment by Kr3mik** [comment]
Same problem
