### ISSUE TITLE
Connecting problem.

### ISSUE THREAD

**Issue by Kserdes** [SubnauticaNitrox/Nitrox#316]
I have problem with my server on my VM. Each PC when it tries to connect to the server on the VM, it ends with the message "Requesting session policy information". The ports are open. 

Everything works fine if I run the server on my PC, but I need to open the server on VM because my ISP blocks ports. Hamachi does not work either. my friends can connect, but they lose their connection with the server a few seconds after entering the world. Any suggestions for repairing it?

It is strange that VM itself can not connect to its own server. The message when trying to connect is the same.

![screenshot_1](https://user-images.githubusercontent.com/44430426/47854821-10903100-dde3-11e8-880c-10c4fa25c0e6.png)

**Comment by killzoms** [comment]
Do you have Hyper-V enabled?

**Comment by Kserdes** [comment]
No, VM is hosted on Google VPS. Other games work great. Only subnautica have problem with connecting.

**Comment by Sajgoniarz** [comment]
Im currently experiancing same issue on Hyper-V machine, due to sync problems, when i played on same instance from which sever was started.
