### ISSUE TITLE
NITROX SUBNAUTICA

### ISSUE THREAD

**Issue by Kexite123** [SubnauticaNitrox/Nitrox#317]
Hello, I wanted to ask when will finish the mod?uncomfortable to play without animals and without drawings, even in Aurora can not get and wanted to know whether such a network mod on subnautica below zero??

**Comment by FlashOnFire** [comment]
For the DLC, Measurity has already answer to your question in #298. Also, as he said, issues aren't for Q&A.... Also, you should close your issues when they are answered.
