### ISSUE TITLE
error nitrox

### ISSUE THREAD

**Issue by Kexite123** [SubnauticaNitrox/Nitrox#318]
What to do?
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: No previous save file found - creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.
   в NitroxServer.Serialization.ResourceAssetsParser.FindPath() в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Serialization\ResourceAssetsParser.cs:строка 89
   в NitroxServer.Serialization.ResourceAssetsParser.Parse() в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Serialization\ResourceAssetsParser.cs:строка 18
   в NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, BaseData baseData, VehicleData vehicleData, InventoryData inventoryData, PlayerData playerData, GameData gameData, List`1 ParsedBatchCells) в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Serialization\World\WorldPersistence.cs:строка 132
   в NitroxServer.Serialization.World.WorldPersistence.CreateFreshWorld() в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Serialization\World\WorldPersistence.cs:строка 105
   в NitroxServer.Serialization.World.WorldPersistence.Load() в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Serialization\World\WorldPersistence.cs:строка 100
   в NitroxServer.Server..ctor() в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Server.cs:строка 24
   в NitroxServer.Program.Main(String[] args) в C:\Users\nare\Desktop\Nitrox-master\NitroxServer\Program.cs:строка 16

**Comment by Aaronstar-McClure** [comment]
*assuming you are on the network branch*
copy C:\Program Files (x86)\Steam\steamapps\common\Subnautica\Subnautica_Data to 
NitroxServer\bin\Debug
