### ISSUE TITLE
Error Compiling

### ISSUE THREAD

**Issue by overspin99** [SubnauticaNitrox/Nitrox#319]
Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0246	The type or namespace name 'TranslationLiveUpdate' could not be found (are you missing a using directive or an assembly reference?)	NitroxClient	C:\Users\Matteo\Documents\Nitrox\NitroxClient\MonoBehaviours\Gui\MainMenu\MainMenuMods.cs	35	Active
> Error	CS0246	The type or namespace name 'TranslationLiveUpdate' could not be found (are you missing a using directive or an assembly reference?)	NitroxClient	C:\Users\Matteo\Documents\Nitrox\NitroxClient\MonoBehaviours\Gui\MainMenu\MainMenuMultiplayerPanel.cs	59	Active
> Error	CS0246	The type or namespace name 'TranslationLiveUpdate' could not be found (are you missing a using directive or an assembly reference?)	NitroxClient	C:\Users\Matteo\Documents\Nitrox\NitroxClient\MonoBehaviours\Gui\MainMenu\MainMenuMultiplayerPanel.cs	72	Active

Getting these 3 errors in the first compiling, i'm not an expert, but i can use Visual Studio and i've never encountered this error and i really want to play the mod

**Comment by FahadAhmad2001** [comment]
Make sure that you're using the latest version of Subnautica

**Comment by overspin99** [comment]
Ok i updated the game and the error got away... But still in the final window i see "9 successful, 0 failed, 0 up-to-date, 1 skipped" i gave no importance to the 1 skipped, but when compiling with dnSpy later i get these 2 errors 

> Severity	Code	Description	File	Line
> Error	CS0592	Attribute 'global::System.Diagnostics.DebuggerBrowsable' is not valid on this declaration type. It is only valid on 'property, indexer, field' declarations.	main.g.cs	12
> Error	CS0592	Attribute 'global::System.Diagnostics.DebuggerBrowsable' is not valid on this declaration type. It is only valid on 'property, indexer, field' declarations.	main.g.cs	18

I dunno if they're linked to that 1 skipped in Visual Studio, i just want to get this over with :(

**Comment by Measurity** [comment]
If you double click on the error in dnSpy you can comment those attributes out in the code. Then it will compile fine. See #211 and the wiki here for setting up a dev environment.
