### ISSUE TITLE
[request] server wine support. please depreciate presentationFramework

### ISSUE THREAD

**Issue by Aaronstar-McClure** [SubnauticaNitrox/Nitrox#320]
i have tested to see if nitroxServer could work on Linux mono or wine. unfortunately it seems presentationFramework(windows presentation foundation) is not supported by wine or mono. would it be possible to move from this to an alternative?

![untitled](https://user-images.githubusercontent.com/24755349/49098575-2d325400-f23d-11e8-828b-325519411048.png)

**Comment by Measurity** [comment]
Yes, the WPF codepath is in the process of being moved to its own project.

**Comment by Aaronstar-McClure** [comment]
Found it, thankyou!
