### ISSUE TITLE
Issue with custom Subnautica installation folder

### ISSUE THREAD

**Issue by PredatorVII** [SubnauticaNitrox/Nitrox#323]
I'm trying to build using VS 2017, and have adjusted the DevVars.targets file to specify my Subnautica install folder:

    

But I am running into the following error:
Error		Your Subnautica installation folder has not been found at the path defined in DevVars.targets. Please set it correctly.		

I've tried a bunch of different formatting options, to no avail. What am I doing wrong?

**Comment by M3dicCookie** [comment]
Have tried adding the end / but if you can't get it I have it built with the files you need to change your game to multiplayer.

**Comment by re-polm** [comment]
You're putting the path into the comment, not in the right place.

```
  <PropertyGroup>
    <!--Enter the location of your Subnautica installation here:-->
    <SubnauticaDir>E:/SteamLibrary/steamapps/common/Subnautica</SubnauticaDir>
  </PropertyGroup>
```

But the mod is intended for developers at the moment, I'd wait for the release.

**Comment by quimnuss** [comment]
You're putting the path into the comment, not in the right place.

  <PropertyGroup>
    
    <SubnauticaDir>E:/SteamLibrary/steamapps/common/Subnautica</SubnauticaDir>
  </PropertyGroup>

But the mod is intended for developers at the moment, I'd wait for the
release.

**Comment by quimnuss** [comment]
You're putting the path into the comment, not in the right place.

<PropertyGroup>
    
    <SubnauticaDir>E:/SteamLibrary/steamapps/common/Subnautica</SubnauticaDir>
</PropertyGroup>

But the mod is intended for developers at the moment, I'd wait for the
release.

**Comment by quimnuss** [comment]
You're putting the path into the comment, not in the right place.

```
    <PropertyGroup>
        <!--Enter the location of your Subnautica installation here:-->
        <SubnauticaDir>E:/SteamLibrary/steamapps/common/Subnautica</SubnauticaDir>
    </PropertyGroup>
```
But the mod is intended for developers at the moment, I'd wait for the
release.

**Comment by PredatorVII** [comment]
> You're putting the path into the comment, not in the right place.
> 
> ```
>     <PropertyGroup>
>         
>         <SubnauticaDir>E:/SteamLibrary/steamapps/common/Subnautica</SubnauticaDir>
>     </PropertyGroup>
> ```
> But the mod is intended for developers at the moment, I'd wait for the
> release.

Wow, how did I miss that one,. I guess I was pretty tired when I tried doing this. Thanks for the help! Got some missing assembly errors now (Lidgren) but I should be able to deal with that.

I didn't find any information about estimated release, so I figured I'd try my hand at it so me and my brother can play. 

Thanks for the help! Sorry to bother you for such a silly fix.

**Comment by quimnuss** [comment]
For the lidgren, don't forget to _also_ clone the nitrox repository's
submodules.

**Comment by aamhm** [comment]
hello , i got same error but the game is in the correct location ,here is the screenshots
![subnautica dev issue](https://user-images.githubusercontent.com/39556627/120642305-03dd8900-c475-11eb-8689-ed5a8c979923.jpg)

**Comment by Coding-Hen** [comment]
You need to change the path in the devvars.target found in your nitrox source code folder and restart visual studio then it should work and the error will be resolved

**Comment by Measurity** [comment]
Apparently it created the "DevVars.targets" file for you so the condition does not pass (it won't use the default path). Just apply fix that Hen suggested.

**Comment by aamhm** [comment]
i even change the location to c:\G\Subnautica ,still same error
![image](https://user-images.githubusercontent.com/39556627/120649568-325f6200-c47d-11eb-885f-861928b76052.png)

**Comment by Measurity** [comment]
Because you didn't change the `DevVars.targets` file IN Nitrox folder.
