### ISSUE TITLE
"Multiplayer Client Loaded..." and "Unable to connect to the remote server at..."

### ISSUE THREAD

**Issue by CoryJS** [SubnauticaNitrox/Nitrox#324]
When attempting to play with my friend, I keep getting the messages mentioned in the title of this issue. However, I've port forwarded as TCP/UDP on the ports 11000, to 11000 and made exceptions to both UDP and TCP in my Firewall with 11000 as the ports. The messages vary on whether I have the :11000 on the end of the IP, when I don't the "Unable to connect..." message appears and with it on the end, the other message.

Please - if anyone can help me it would be highly appreciated as my friend and I would really like to try this mod out and play together.

**Comment by M3dicCookie** [comment]
Are you adding the port to the IP part of subnauica. If your having trouble I have it built and can send you the package.

**Comment by crankineer** [comment]
When you port forward on your router, and you add a server in the multiplayer part, do not put ":11000" at the end. Let me know if that fixed it. Also, when you port forwarded, make sure you took note of the correct IP address you are connecting to.
