### ISSUE TITLE
Visual studio doesn't make a nitrox pacher.dll in subnautica + nitroxserver.exe isn't generated

### ISSUE THREAD

**Issue by mikekmp** [SubnauticaNitrox/Nitrox#330]
![screenshot_1](https://user-images.githubusercontent.com/45897741/50043531-7cbab180-007e-11e9-839c-bf0fde6b56d5.png)

also nitroxserver.exe isn't generated

I don't know what to do

**Comment by MypowerHD** [comment]
First of all read this two wiki entrys..
https://github.com/SubnauticaNitrox/Nitrox/wiki/Software-Used-for-Development-&-Installation
and
https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox

**Comment by mikekmp** [comment]
ok wait

**Comment by mikekmp** [comment]
so

**Comment by mikekmp** [comment]
xD

**Comment by mikekmp** [comment]
what do i type in it i thing i did it wrong
