### ISSUE TITLE
SUBNAUTICA below zero Nitrox

### ISSUE THREAD

**Issue by Kexite123** [SubnauticaNitrox/Nitrox#331]
Hello, I am very interested in the question, whether to wait for the same nitrox multiplayer mod for subnautica below zero? Please answer, just like the game very much and I want to see multiplayer for a new subnautica

**Comment by xl3lackout** [comment]
Considering its standalone it probably sports a fresh coat of paint as far as programming is concerned. This mod would need either a complete overhaul or an extensive patch job. Whether they want to go that far is up to their discretion, but i'm assuming it would be a tall order
