### ISSUE TITLE
Fauna not spawning

### ISSUE THREAD

**Issue by TheNimDude** [SubnauticaNitrox/Nitrox#332]
There are a few issues already about this but nothing seems to work and the issues are from months ago.
Basically everything works until I get into the server, there are just no fish or limestone etcetc. It's annoying. Any fixes? (I did the code change suggested by DanX100 but it didn't work)

**Comment by onyxius** [comment]
I am using the Epic Launcher version and so far so good on loading myself and a friend in, but we too cannot see any spawns and I did what DanX100 suggested as well.

**Comment by onyxius** [comment]
closed with no resolution / suggestion?

**Comment by alexanderheuts** [comment]
There are a bunch of changes w.r.t. spawning since the original report. If problems persist, join Discord.

**Comment by onyxius** [comment]
Thank you, ill have to get the newer version and try it again.
On 1/14/2019 8:10:48 AM, alexanderheuts <notifications@github.com> wrote:
There are a bunch of changes w.r.t. spawning since the original report. If problems persist, join Discord.
