### ISSUE TITLE
World doesn't save

### ISSUE THREAD

**Issue by AntteS** [SubnauticaNitrox/Nitrox#337]
So whenever we restart the server, all of our stuff inside the storage container inside the escape pod is emptied. The lockers have also vanished. Fix plox.

**Comment by TahMahn** [comment]
This happens to us as well. Also happens when we all log out, and someone logs back in again without the server being restarted.

**Comment by LuukUnger** [comment]
I'v got this too. idk why, no error what so ever. What is the save file/folder?

**Comment by TahMahn** [comment]
I think it's the "save.nitrox" file located in the Debug_WPF folder (path "C:\Users\"USERNAME"\Documents\Nitrox\NitroxServer\bin\Debug_WPF")

**Comment by RobinKuiper** [comment]
Our escape pods gets reset everytime to. Repairs (secondary systems) are undone, and the storage container is reset to the 2 flares, 2 waters, 2 food thingies.

Also, my radiation suite always misses parts (sometimes the gloves, sometimes the helmet, sometimes both)
