### ISSUE TITLE
Some eeror text in server console

### ISSUE THREAD

**Issue by trjflash** [SubnauticaNitrox/Nitrox#338]
Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18

Steam and Epic based servers

**Comment by xl3lackout** [comment]
Yeah i have the same issue, I'm assuming its a batch points error dealing with loading in entities, as it only occurs when i move into a new chunk, my console is spammed with it along with the occasional "loaded 0 entity spawn points for batch 13,16,7" Though im unsure if these problems are related or not. Theres already several issue links here about the batch problem specifically, and many of it was caused by following an incorrect youtube guide on where you inject NitroxPatcher.Main.Execute(); . Ive only seen one thread about where exactly to put it, and it said to place immediately after awake, being the next executed line. Im unaware as to if that is a viable location or not, as i am left with the same problem

**Comment by xl3lackout** [comment]
I checked my logs and i do not have a IndexOutOfRangeExceptionError, which is commonplace for that kind of batch error, which is kinda peculiar tbh. Im assuming that the Path error was possibly an oversight on the epic games patch? But im more interested in if its a standalone issue or if it coincides with other issues

**Comment by monoxacc** [comment]
Had the same problem...i set the game path in path.txt file
It seems the server expect some file which doesn't exist anymore or were moved/renamed by patches of the vendor. Problem is located in NitroxServer.Serialization.BatchCellsParser Method ParseBatchData() and ParseFile().
I added more output information in my server code..Here a list of game files the server expected to be available but they does not exist in current game release state:
\SNUnmanagedData\Build18\batch-cells-9-16-13-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-16-13-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-13-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-16-13-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-13-other.bin
\SNUnmanagedData\Build18\batch-cells-9-16-14-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-16-14-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-14-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-16-14-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-14-other.bin
\SNUnmanagedData\Build18\batch-cells-9-16-8-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-16-8-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-8-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-16-8-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-8-other.bin
\SNUnmanagedData\Build18\batch-cells-9-16-9-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-16-9-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-9-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-16-9-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-16-9-other.bin
\SNUnmanagedData\Build18\batch-cells-9-17-14-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-17-14-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-17-14-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-17-14-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-17-14-other.bin
\SNUnmanagedData\Build18\batch-cells-9-17-8-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-17-8-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-17-8-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-17-8-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-18-14-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-18-14-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-18-8-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-18-8-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-18-8-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-18-8-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-18-9-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-18-9-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-19-14-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-19-14-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-19-14-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-19-14-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-19-14-other.bin
\SNUnmanagedData\Build18\batch-cells-9-19-8-creatures.bin
\SNUnmanagedData\Build18\batch-cells-9-19-8-creature-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-19-8-loot.bin
\SNUnmanagedData\Build18\batch-cells-9-19-8-loot-slots.bin
\SNUnmanagedData\Build18\batch-cells-9-19-8-other.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-16-13-slots.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-16-14-slots.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-16-8-slots.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-16-9-slots.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-17-14-slots.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-19-14-slots.bin
\SNUnmanagedData\Build18\Generated\batch-cells-9-19-8-slots.bin

For example entry 1 (\SNUnmanagedData\Build18\batch-cells-9-16-13-creatures.bin) following files containing "9-16-13" exist in current game release state:
\SNUnmanagedData\Build18\CompiledOctreesCache\compiled-batch-9-16-13.optoctrees
\SNUnmanagedData\Build18\batch-9-16-13.octrees

Hope this helps to fix the issue in any way.
