### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by MasterPizza** [SubnauticaNitrox/Nitrox#340]
Every time I try to connect to a server (no matter what IP I try) I get this error message:

"Multiplayer client loaded...
Unable to connect to remote server at: 127.0.0.1:11000"

(example IP above)

**Comment by crankineer** [comment]
That is the default server when you load up multiplayer. You need to delete that server, and then add a new server using the correct IP address. Are you trying to connect to your own server(need to port forward), or someone else's?

**Comment by MasterPizza** [comment]
I am using my own server. I also know basically nothing about modding, so this is basically a foreign language to me.
