### ISSUE TITLE
Feature: Add Epic Games' launcher support.

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#341]
Common registry key for Win7 and Win10 for Epic Games' launcher (credits to [GSF] Neimoh on Discord):

[GSF] Neimoh says:

this is common entry in both win7 and win 10 BUT win10 adds the .FriendlyAppName tag to the key where win7 does not
https://media.discordapp.net/attachments/325084661011316737/523641873898668032/unknown.png

**Comment by Measurity** [comment]
True it's not perfect but we need a solution for detecting the install directory automatically when using Epic Games' launcher. Setting path in a .txt file will still be the last fallback plan if all other tries fail.

**Comment by crankineer** [comment]
This should be put in pull requests, not issues.

**Comment by Measurity** [comment]
Github issues are used for feature requests as well. I'll close this in a PR whenever I got some code that fixes this issue.
