### ISSUE TITLE
Server files were not created

### ISSUE THREAD

**Issue by UltraVaporizer** [SubnauticaNitrox/Nitrox#342]
Hello. I was able to download and install Nitrox client side just fine. But both me and a friend didn't have the server the Nitrox\NitroxServer\bin folder. I was wondering if there was a place were I could download the server files without jumping through any hoops. Thanks for any and all help.

**Comment by Zatshot** [comment]
Did you do the visual studio part and the dns part too ?

**Comment by UltraVaporizer** [comment]
I was able to use Dnspy just fine. When I start visual studio up it prompts me with 3 options (attached below) I used the first option and it seems to work fine apart from not generating the server files.
![github](https://user-images.githubusercontent.com/34201426/50049069-d4224700-00a9-11e9-88ff-2bd4e3fe7002.PNG)

**Comment by crankineer** [comment]
Most videos on YouTube don't tell you to install the .NET addon to Visual Studio, as well as the WixToolset program. You need those to properly install Nitrox.

**Comment by Zatshot** [comment]
What about this ? 
![image](https://user-images.githubusercontent.com/45905961/50050270-618b8880-00f6-11e9-8448-8e504074be5d.png)

**Comment by Zatshot** [comment]
And yes you need to install Wixtoolset and .net if you don't have it.
For visual studio i used this video and found the rest by myself 
https://www.youtube.com/watch?v=3o-ej4YpYw0
