### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by xkaczors** [SubnauticaNitrox/Nitrox#343]
[Nitrox] D: Batch 14,19,13 not parsed yet; parsing...
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] D: Loaded 0 entity-spawn-points for batch 14,19,13

(EpicGames server..)

btw: they do not spawn fish and creatures

**Comment by crankineer** [comment]
I've had problems with the Epic Games version of Subnautica too. Rather than using the Epic Games version, you should switch to the Steam version as it has less problems installing Nitrox.

**Comment by xkaczors** [comment]
unfortunately I do not have a steam version, does anyone have an idea?
