### ISSUE TITLE
Easy Downloader?

### ISSUE THREAD

**Issue by Sunkerino** [SubnauticaNitrox/Nitrox#344]
Okay so I myself and many others would love if we could fix an easy downloader. At this point I think that we all dont even care so much if the mod is a bit buggy. The only thing that matters is that we can get it out. I've been a hugh beliver in this and would play it nomather the state of the mod. And one last thing, please give out an update video about how far the project has gotten. This is not any form of hate, just a very hyped player.

**Comment by crankineer** [comment]
I myself am not a developer of Nitrox, but I think I can safely say that the devs do NOT have priorities in the public release yet. The mod is still super buggy, and many things need to be fixed or added. At this point, the safest and easiest way to install Nitrox is to purchase the Steam version and use this video: https://youtu.be/3o-ej4YpYw0

**Comment by Measurity** [comment]
There already is a video out showing the latest state of the mod. With the last frame saying "release in December" but that's up to the maintainer to decide. Releasing the installer will only attract a bad rep and a lot of questions & bug reports for Nitrox. All of which we know about but haven't gotten the time to fix yet.

If you are a dev and want to help this mod please head over to the Discord server "Subnautica Modding" and join the discussion. Also, have a look at https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox for building Nitrox.

**Comment by Sunkerino** [comment]
Okay, well im not an dev but is there any way of me joinging and just taking a part in the discusions?

**Comment by Measurity** [comment]
Sure, just join the Discord. https://discord.gg/9MfKs2s

**Comment by Sunkerino** [comment]
Thanks!

**Comment by crankineer** [comment]
> There already is a video out showing the latest state of the mod. With the last frame saying "release in December" but that's up to the maintainer to decide. Releasing the installer will only attract a bad rep and a lot of questions & bug reports for Nitrox. All of which we know about but haven't gotten the time to fix yet.
> 
> If you are a dev and want to help this mod please head over to the Discord server "Subnautica Modding" and join the discussion. Also, have a look at https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox for building Nitrox.
> 
> Edit:
> Btw, the video posted above isn't entirely correct on how to install this mod (the dnSpy injection part).

Oh, I didn't notice. Is there a video with the correct dnSpy injection?

**Comment by MypowerHD** [comment]
@crankineer iam sitting on fixing some syncro stuff since 5 houres... there are massy stuff that is not implemented yet. Server is dont save the PlayerInventory, Changes you made etc.
Many Syncro stuff todo :D
