### ISSUE TITLE
Got everything working w/ friend connected - No fish spawn?

### ISSUE THREAD

**Issue by conman127** [SubnauticaNitrox/Nitrox#347]
Hey if anyone could help with this issue that would be awesome. 

No fish or resources spawn on the server. The map/skybox/pod all load fine but no fish.
I tried redirecting the available files to the epic games installation but no luck.

In the server console i first get the No peepers error and then later on it says something along the lines of 
Loading Batch #/#/# - failed no entity's spawned

**Comment by crankineer** [comment]
This is commonly found in the Epic Games version.

**Comment by Maryanna98** [comment]
Open File explorer and in the top right search for " resources.assets"
Look for the path underneath the big name. It should contain something 
like: Steam or Epic (depending on where you have the game from) / 
Subnautica ...
Right-click the file, copy it and go into the this folder (probably this path): 
C:\Users\Boss\Documents\Nitrox\NitroxServer\bin\Debug_WPF
Paste it in there and then run the server.
OT but, how did your friend joined you? Are you using Hamachi or something else? I create the server and I can join it but my boyfriend can't lol

**Comment by conman127** [comment]
Nope that didnt work maryanna98. 

Also the specific error is Fallback and steam path failed Please move SNUmanagedData/build18 to \SNUnmanagedData\Build18

**Comment by crankineer** [comment]
I was able to run a server for a little bit with a friend, and resources spawned. However, after about 10 minutes I got that same error.

> Nope that didnt work maryanna98.
> 
> Also the specific error is Fallback and steam path failed Please move SNUmanagedData/build18 to \SNUnmanagedData\Build18
