### ISSUE TITLE
Clean up logging and exceptions

### ISSUE THREAD

**Issue by MarijnS95** [SubnauticaNitrox/Nitrox#35]
@SunnyBat worked on a logging framework, but most of the code is still using `Console.WriteLine`.
### Logging TODO:
- [ ] Make sure the logging framework has enough utility functions, like `Console.WriteLine`.
- [ ] Use tags or classnames (through `StackFrame`) to indicate the origin of the message.
- [ ] If applicable, print the name of the current player, or make it an option. (to distinguish clients when running multiple instances on a single machine, all dumping to the same log file).
- [ ] Convert existing code to use the logging framework.
- [ ] Disable certain logging functions with `[Conditional("DEBUG")]`.
- [ ] Enforce new code to use this framework.

In some places (such as `Optional` and `Validate`), we throw system exceptions (and our own exceptions.) This should be generalized as these are helpers and the exception is usually dependent on the context (for instance something is an `ArgumentException` for `Validate`, but that's not really descriptive when in the context that called this).

### Exceptions TODO:
- [ ] Come up with some descriptive exceptions to replace our current ones.
- [ ] Replace existing exceptions.
#### Also:
- [ ] Should `Optional` have an `.AssertPresent`, or should this be in `Validate`?

### Both:
Because attaching a debugger to the Unity game doesn't work that well, see if more information about the code path, such as line numbers (and variables) can be printed to the console (`StackFrame` can do this based on debugging symbols).

**Comment by Sunrunner37** [comment]
1) I'll perform a Console.WriteLine() to ClientLogger refactor in the headless branch.
2) Stackframe might be very expensive to use for logging unless we only do it on errors
3) The ClientLogger supports Info() and Debug() logging levels so we only need the conditional debug in one place
4) Would prefer Validate.IsPresent(optional) to be consistent.

**Comment by MarijnS95** [comment]
1. :+1:, I'll do the refactor on my branches once I rebase them.
2. Only for errors, of course.
3. That `Conditional` attribute applies to methods and prevents the function and function calls from ending up in the library when `DEBUG` is not set. We don't have to write any logic.
4. My preference as well, and to keep it the same naming as the rest: `Validate.NotEmpty`.

**Comment by Sunrunner37** [comment]
I am mixed on NotEmpty as that seems to imply comparing a collection of items.  Also, isPresent makes optional clear and  is consistent with isTrue and isFalse.

**Comment by MarijnS95** [comment]
We can have both I guess: `IsPresent` besides `IsTrue` and `IsFalse`, and `NotEmpty` besides `NotNull` (or we can make an overload for `NotNull` like `public static void NotNull<T>(Optional<T> op)`.
