### ISSUE TITLE
No Fish, Minerals

### ISSUE THREAD

**Issue by Legired** [SubnauticaNitrox/Nitrox#350]
Hello guys, i got a problem with the lastest version,

i can't see fish or scrap metal, i have no error in the consol, for the serveur, everything is ok

When i check my subnautica log, i got this 

> `[Nitrox] E: Expected to simulate an unknown entity: 191ec100-3674-416c-981a-97615e5cfe40
> 
> [Nitrox] E: Expected to simulate an unknown entity: cb585976-7e21-42ba-9da1-3899dee4f6ee
> 
> [Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: 362ede52-ec2b-4fbf-a433-e096d1195fab AcidMushroom 99cdec62-302b-4999-ba49-f50c73575a4d
> 
> [Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: 0d260a6c-8bfe-4945-b211-81996999407a AcidMushroom 99cdec62-302b-4999-ba49-f50c73575a4d
> 
> [Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: ca0af673-6188-4137-9bd6-eb6fb6a5c372 AcidMushroom 99cdec62-302b-4999-ba49-f50c73575a4d
> 
> [Nitrox] E: Entity was already spawned but not found(is it in another chunk?) guid: 476d720b-a92e-4f41-847f-f90d1025cc85 AcidMushroom 99cdec62-302b-4999-ba49-f50c73575a4d
> 

I turn the server on the same computer, my subnautica is update too.

thx in advance.

**Comment by Sajgoniarz** [comment]
Its the part of https://github.com/SubnauticaNitrox/Nitrox/issues/188 i had same logs, but after fetching new commits, i have only errors in server log.
