### ISSUE TITLE
Nothing spawns

### ISSUE THREAD

**Issue by Xryzo11** [SubnauticaNitrox/Nitrox#351]
I tried to play Subnatica with my friends, but I realised that nothing spawns in the world. (no fish, materials). It's not something about the server, because it even happens in single player. I have Subnautica on Epic Games if it's important. Also the server on start is giving some errors:

[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] D: Event Triggerer started!
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Nitrox Server Started

Sometimes it gives a lot more errors.

**Comment by Xryzo11** [comment]
Yes, I do. I downloaded Subnautica and Nitrox yesterday.

**Comment by Measurity** [comment]
Dunno when your yesterday ended but 2 hours ago doesn't sound like yesterday's time ;). Please come join us in Discord for easier troubleshooting.

**Comment by xl3lackout** [comment]
> Dunno when your yesterday ended but 2 hours ago doesn't sound like yesterday's time ;). Please come join us in Discord for easier troubleshooting.

Ive reinstalled the new patches. I just replaced the folders that had changed, i assumed that i wouldnt need to reinject the mod into my subnautica. Ive rerouted all 5 path.txt but im still in the same situation

**Comment by trjflash** [comment]
All have this problem. But there are people who have everything exactly the opposite.  And don't want to share )))

**Comment by xl3lackout** [comment]
I got it to work, but i did so many things at once i dont have a clue as to what exactly fixed it. Try copying everything from your build18 folder into the folder that contains your server exe. Youll still get the error, but thats because it searches for files that dont exist, but it doesnt effect the game in any way. Also after you make a change to your files, you should always rebuild the Nitrox.sln.

**Comment by Sajgoniarz** [comment]
I think we can move all those issues, into https://github.com/SubnauticaNitrox/Nitrox/issues/188 since they are caused by missing files.
