### ISSUE TITLE
Error after I past resources.assets in server 's folder

### ISSUE THREAD

**Issue by longstl** [SubnauticaNitrox/Nitrox#357]
I have some issue with Nitrox server file. I used Epic Game Client.

My Error after I past resources.assets in server 's folder:
> [Nitrox] I: Could not load world: System.IO.InvalidDataException: Persisted state is not valid
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() in C:\Users\hoang\Documents\Nitrox\NitroxServer\Serialization\World\WorldPersistence.cs:line 68 creating a new one.

code in NitroxServer\Serialization\World\WorldPersistence.cs:line 68
`World world = CreateWorld(persistedData.ServerStartTime,
                                          persistedData.EntityData, 
                                          persistedData.BaseData,
                                          persistedData.VehicleData,
                                          persistedData.InventoryData,
                                          persistedData.PlayerData,
                                          persistedData.GameData,
                                          persistedData.ParsedBatchCells);`

Please help me.
Thanks for helping

**Comment by Felino41** [comment]
Why was this closed without a comment? I have the exact same Problem, is there a fix?

**Comment by petethacker** [comment]
i'm getting this on the latest version of Nitrox  `Alpha 1.1.0.1-159-alpha-1.1.0.101554587988` and the latest version of subnautica.

everything runs fine, i can create a new world, save it etc but when it comes to reload it i get the error.
