### ISSUE TITLE
New problem

### ISSUE THREAD

**Issue by xkaczors** [SubnauticaNitrox/Nitrox#358]
I have another problem after multiplayer installation where there were no mobs, and now there is nothing in the singleplayer

**Comment by xl3lackout** [comment]
A lot of people are having the same problem rn. Not to be rude, but you should really have picked a better title for this issue. Look around for a lot of the recent issues and youll find a lot of different ways people are getting problems. Hopefully one works for you, but so far most people havent gotten it fixed
