### ISSUE TITLE
Server and Connection Issues

### ISSUE THREAD

**Issue by getsmor** [SubnauticaNitrox/Nitrox#359]
I can't seem to get my server up and running properly, I can get into the game but none of my friends can join it. I have tried to Port Forward but I dont know if I did it correctly. (Asus routers are so unclear with settings)

**Comment by Frutipro** [comment]
Upload a picture of your port forwarding and im pretty sure subnautica have to have firewall permissions.

**Comment by getsmor** [comment]
![image](https://user-images.githubusercontent.com/43723030/50057047-76ebcb80-0165-11e9-94d1-545538815a5d.png)

**Comment by Damply** [comment]
Same here, I have port forwarded correctly and firewall is disabled. Cant connect to external IP but works fine for internal IP or localhost

**Comment by getsmor** [comment]
yh, i gave up. Ill wait for beta update
