### ISSUE TITLE
Mob don't spawn, steam path failed!

### ISSUE THREAD

**Issue by gitnever** [SubnauticaNitrox/Nitrox#362]
`[Nitrox] D: Using default packet processor for: NitroxModel.Packets.SubRootChanged and player 1
[Nitrox] D: Batch 11,19,13 not parsed yet; parsing...
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18
[Nitrox] I: Fallback path and Steam path failed! Please move SNUnmanagedData/Build18 to \SNUnmanagedData\Build18`

I got this error, my game is on the Epic Games Launcher, path of game is : J:/Program Files/Subnautica
Please help me.

**Comment by gitnever** [comment]
### EDIT
I just find how to resolve the problem, except that the fish doesn't spawn...
I just change the path in this file `C:\Users\JustNever\Documents\Nitrox\NitroxServer\Serialization\BatchCellsParser.cs`
No error in the debug/logs.. Except that the fish, items, entitys doesn't spawn ...

**Comment by Sajgoniarz** [comment]
You can move to https://github.com/SubnauticaNitrox/Nitrox/issues/188
Its same issue, but now you should have 0 spawn points loaded
