### ISSUE TITLE
Nitrox Server Batch Error

### ISSUE THREAD

**Issue by Margoovian** [SubnauticaNitrox/Nitrox#367]
I have gotten the Nitrox server to run and spawn entities but every time i or a friend makes a lootable object this error comes up in the log: 
Unable to find batch cells file 'D:\games\subnautica\SNUnmanagedData/Build18\batch-cells-5-16-13-other.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Delta\Desktop\Games\Software\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.
-----------
and when the error comes up a bunch of reasources stop spawning.
plus i have moved the file into the server DIR.
any help??

**Comment by Margoovian** [comment]
Nitrox] I: Unable to find batch cells file 'D:\games\subnautica\SNUnmanagedData/Build18\batch-cells-6-17-13-loot-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Delta\Desktop\Games\Software\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\games\subnautica\SNUnmanagedData/Build18\batch-cells-6-17-13-creature-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Delta\Desktop\Games\Software\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\games\subnautica\SNUnmanagedData/Build18\batch-cells-6-17-13-loot.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Delta\Desktop\Games\Software\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\games\subnautica\SNUnmanagedData/Build18\batch-cells-6-17-13-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Delta\Desktop\Games\Software\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\games\subnautica\SNUnmanagedData/Build18\batch-cells-6-17-13-other.bin'! Please move SNUnmanagedData\Build18 to C:\Users\Delta\Desktop\Games\Software\Nitrox\NitroxServer\bin\Debug_WPF\SNUnmanagedData\Build18.

**Comment by trjflash** [comment]
Dude, how did u get spawns??? ))) All want to know it )

**Comment by Margoovian** [comment]
i followed this tut https://www.youtube.com/watch?v=bzF9C4gR9C0

**Comment by Sajgoniarz** [comment]
Its pretty much same issue as https://github.com/SubnauticaNitrox/Nitrox/issues/188

**Comment by Margoovian** [comment]
Its a different issue, its not a problem with the path i found it is a problem with the files needed no being there

**Comment by Margoovian** [comment]
another bug, when i restarted the server i found that the water proof containers had disapeared

**Comment by Sunrunner37** [comment]
Please update to 1.0.0.5, start a new server(delete nitrox.save), swim
around for a bit, and post server logs here.  The more the better.

(You can write server logs to a file by starting it in a command window.
Navigate to the directory and  run the command "nitroxserver.exe > log")
