### ISSUE TITLE
Epicgames

### ISSUE THREAD

**Issue by Stefan2ND** [SubnauticaNitrox/Nitrox#368]
I was wonderig if it works on epicgames? because i really want to play with my friend :D

**Comment by Hacksawfred3232** [comment]
It should work. Are both of you using the Epic games launcher?

**Comment by huhenU** [comment]
I can confirm it working on EpicGames. At least I got it installed. Will reply again when I can say that crossplay with steam works.

**Comment by Sajgoniarz** [comment]
Yes, it was added yesterday in https://github.com/SubnauticaNitrox/Nitrox/commit/8c75bcc5e6caaee9562f23d1c5325bd86275a7c2

**Comment by Hacksawfred3232** [comment]
Cross-platform should work due to it relying on the client, not steam.

**Comment by gitnever** [comment]
https://www.youtube.com/watch?v=bzF9C4gR9C0
