### ISSUE TITLE
Non-Game Breaking Bugs and suggestions

### ISSUE THREAD

**Issue by AusKarlos** [SubnauticaNitrox/Nitrox#369]
Thanks for all your work so far, fantastic mod. 
I've stumbled upon a few minor issues (Will add a detailed list to the same thread and any reproduction steps as time goes on.)

- The initial O2 tank upgrade will give you infinite O2 unless you remove it from your suit slot and place it back.
- Quitting while in a Hab (After a server save) and rejoining will desync your characters state from the server, causes you to be able to swim inside the Hab and lose O2. Simply interacting with the external hatch will make you re-enter.
- Power levels in the Hab reset when restarting the server

- Players with an unstable connection (on their end) can lock fabricators in a loop, If a different player interacts with the Fab during this loop they will lose all crafting ingredients and the item they crafted
(Player with the unstable connection need to reconnect) 

- Wreck door sync issues. If player 1 opens a door to a wreck when player 2 isn't in the loaded cell the door for player 2 is still closed.

- Crashfish nests don't open for Connected players when the fish is triggered (With LocalHost connected player Crashfish work as intended)

- If unstable connected player enters a unloaded cell first other players are unable to scan items until the unstable client disconnects

Temp fixes
-  For users with Compile issues copying Subnautica to its default location of C:/Program Files (x86)/Steam/Steamapps/Common (Remove the target file in the compile directory) and run VS 2017 as Admin..
Fixes the follow error in VS
```
Using "ResolvePackageFileConflicts" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\\tools\net46\Microsoft.NET.Build.Extensions.Tasks.dll".
  Task "ResolvePackageFileConflicts"
```
Its attempting to look in an invalid directory  ```\\tools``` instead of ```\tools```

- Missing assets/fish/loot , copying the folders Subnautica_data and SNUmanagedData to the Root directory of the server exe and running the server as Admin seems to of fixed a lot of those spawn issues.

Suggestions

- Print out Sever World save on screen please
- Allow a "Localhost" connected player to initiate a World Save via console command

**Comment by Sunrunner37** [comment]
Thanks for the bug reports and suggestions.

> Quitting while in a Hab (After a server save) and rejoining will desync your characters state from the server, causes you to be able to swim inside the Hab and lose O2. Simply interacting with the external hatch will make you re-enter.

Have you tried with the latest commit?  Players were not be appropriately assigned to the building when spawned.  Let me know if this persists.

> Allow a "Localhost" connected player to initiate a World Save via console command
You can initiate a world save with the "mpsave" console command

**Comment by AusKarlos** [comment]
Another bug.
Server is attempting to parse files that have been incorrectly named.
Example.
``` [Nitrox] I: Unable to find batch cells file 'd:/program files (x86)/steam\steamapps\common\Subnautica\SNUnmanagedData/Build18\batch-cells-11-18-8-creatures.bin'! ```

The file in question is actually called ``` batch-cells-11-18-8-creatures-slots.bin ```

**Comment by Measurity** [comment]
Since this is a list-issue and old I'm going to close it. Please create 1 GitHub issue per bug so that we can easily verify if it's fixed or not.
