### ISSUE TITLE
Unable to load SNUnmanagedData

### ISSUE THREAD

**Issue by deynon** [SubnauticaNitrox/Nitrox#371]
Hello,
I tried the latest build in order to get entity back, everything went right but, their is still no creature, and i have an error asking me to move SNUnmanagedData/Build18 in my Debug_WPF folder, even when its already in that directory:

![image](https://user-images.githubusercontent.com/18290225/50088079-4dcd4880-0202-11e9-8abf-7f1fdc931707.png)

As you can see, i'm still having the error, and Build18 is in the right directory. What sould i do?
Thanks for help.

Finally, it's looking in my steam directory despite that i have an Epic Games installation.
(Btw no entity in solo save either).

**Comment by trjflash** [comment]
Yep. I have this problem to. Try move folder to server folder. Modify permissions to folders, but this doesn't work. Help someone ))))

**Comment by trjflash** [comment]
Problems on steam and epic versions

**Comment by trjflash** [comment]
No #188 not help. This isnt normaal...

[Nitrox] I: Unable to find batch cells file 'D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18\batch-cells-9-16-13-loot-slots.bin'! Please move SNUnmanagedData\Build18 to D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18\batch-cells-9-16-13-creature-slots.bin'! Please move SNUnmanagedData\Build18 to D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18\Generated\batch-cells-9-16-13-slots.bin'! Please move SNUnmanagedData\Build18 to D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18\batch-cells-9-16-13-loot.bin'! Please move SNUnmanagedData\Build18 to D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18\batch-cells-9-16-13-creatures.bin'! Please move SNUnmanagedData\Build18 to D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18\batch-cells-9-16-13-other.bin'! Please move SNUnmanagedData\Build18 to D:\SteamLibrary\steamapps\common\Subnautica\SNUnmanagedData\Build18.
