### ISSUE TITLE
RDP problems

### ISSUE THREAD

**Issue by trjflash** [SubnauticaNitrox/Nitrox#372]
Hi! I have problems witch RDP connection to host witch nitrox server. When i connect to server RDP connection is fall. When i disconnect from nitrox RDP become to normal... Just for info for developers

**Comment by trjflash** [comment]
Need to fix it.... I can't administraite and play at one time.

**Comment by FahadAhmad2001** [comment]
The RDP might be using the same port as nitrox (port 11000), try changing the port of either nitrox or RDP.

**Comment by trjflash** [comment]
RDP by default using port 3389

**Comment by FahadAhmad2001** [comment]
Do you get any error when the rdp disconnects after connecting to nitrox?

**Comment by trjflash** [comment]
No, just attemts counter to restart connection
