### ISSUE TITLE
Store Containers  Disappear and Itens Inside Too

### ISSUE THREAD

**Issue by XBlack007** [SubnauticaNitrox/Nitrox#373]
I was playing on multiplayer mode for 3 hours with my friend, after we decided to save and leave the game, in the following day all of our's itens and storages were deleted, the only things that remain were our itens in inventory.

**Comment by CSaratakij** [comment]
@XBlack007  Same here, seems like a world is reset..

**Comment by Hacksawfred3232** [comment]
What errors are you getting on the console (If any?)

**Comment by M3dicCookie** [comment]
might be not running the server as admin because its in the C: drive it might not be able to make a save file

**Comment by CrushedPixl** [comment]
Same here, only items in the inventory is saved for me.

**Comment by Exeden** [comment]
> might be not running the server as admin because its in the C: drive it might not be able to make a save file

Is this true?

**Comment by Measurity** [comment]
This issue is being tracked here: #1003
