### ISSUE TITLE
FAST. WHAT PROBLEM?

### ISSUE THREAD

**Issue by ErrorMyLife** [SubnauticaNitrox/Nitrox#377]
On compilling stage, visual studio view this error: 

Error	CS0246	The type or namespace name 'Lidgren' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\vipza\Desktop\Nitrox-master\NitroxModel\Packets\Movement.cs	3	Active
Error	CS0246	The type or namespace name 'Lidgren' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\vipza\Desktop\Nitrox-master\NitroxModel\Packets\Packet.cs	11	Active
Error	CS0246	The type or namespace name 'NetDeliveryMethod' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\vipza\Desktop\Nitrox-master\NitroxModel\Packets\Packet.cs	50	Active
Error	CS0246	The type or namespace name 'Lidgren' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\vipza\Desktop\Nitrox-master\NitroxModel\Packets\PlayerStats.cs	1	Active
Error	CS0246	The type or namespace name 'Lidgren' could not be found (are you missing a using directive or an assembly reference?)	NitroxModel	C:\Users\vipza\Desktop\Nitrox-master\NitroxModel\Packets\VehicleMovement.cs	3	Active

**Comment by MypowerHD** [comment]
git submodule init
git submodule update
that solves your problem

**Comment by ErrorMyLife** [comment]
No. This not solves my problem

**Comment by ErrorMyLife** [comment]
![image](https://user-images.githubusercontent.com/43316438/50093730-8ed55500-0222-11e9-8d25-b5b7a148af55.png)

**Comment by MypowerHD** [comment]
close the ide than run git bash the Solution dir and ran the git commands...

> 
> 
> git submodule init
> git submodule update
> that solves your problem

**Comment by ErrorMyLife** [comment]
don't work

**Comment by ErrorMyLife** [comment]
![image](https://user-images.githubusercontent.com/43316438/50094179-9cd7a580-0223-11e9-9602-ab276d19d29a.png)

**Comment by MypowerHD** [comment]
Pls deinstall Visualstudio and play Singleplayer.. -.-

**Comment by ErrorMyLife** [comment]
:(

**Comment by Sajgoniarz** [comment]
You are not fetching repository using recursive option, so you wont have libraries in local repo.

**Comment by ErrorMyLife** [comment]
> You are not fetching repository using recursive option, so you wont have libraries in local repo.

Thanks for you help. I do this
