### ISSUE TITLE
Subnautica is crashing once friend presses on ip to join

### ISSUE THREAD

**Issue by Sorxa** [SubnauticaNitrox/Nitrox#379]
So we wanted to play lan but that didnt work so i decided to portforward once we did i could join and everything and once he presses on the link it says on the top right he is joining but when im looking at the server cmd thing i see his ip then the whole thing crashes i hope i could get a fix fast :/

**Comment by CrushedPixl** [comment]
Please provide server log if possible, there is too little information in the issue.
