### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by CrushedPixl** [SubnauticaNitrox/Nitrox#380]
It works fine on my PC but when I try to run it on my server it crashes. I've tried a clean install and directly copying the exact same files from my PC. I'm guessing it has with the installation of Nitrox to do. Here's the log ("Värde får inte vara null" = "Value can't be null":

[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] D: Event Triggerer started!
[Nitrox] I: Could not load world: System.ArgumentNullException: Värde får inte vara null.
Parameternamn: path1
   vid System.IO.Path.Combine(String path1, String path2)
   vid NitroxModel.Discovery.InstallationFinders.SteamGameRegistryFinder.FindGame(List`1 errors)
   vid NitroxModel.Discovery.GameInstallationFinder.FindGame(List`1 errors)
   vid NitroxServer.Serialization.ResourceAssetsParser.FindPath()
   vid NitroxServer.Serialization.ResourceAssetsParser.Parse()
   vid NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, BaseData baseData, VehicleData vehicleData, InventoryData inventoryData, PlayerData playerData, GameData gameData, List`1 ParsedBatchCells)
   vid NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] E: System.ArgumentNullException: Värde får inte vara null.
Parameternamn: path1
   vid System.IO.Path.Combine(String path1, String path2)
   vid NitroxModel.Discovery.InstallationFinders.SteamGameRegistryFinder.FindGame(List`1 errors)
   vid NitroxModel.Discovery.GameInstallationFinder.FindGame(List`1 errors)
   vid NitroxServer.Serialization.ResourceAssetsParser.FindPath()
   vid NitroxServer.Serialization.ResourceAssetsParser.Parse()
   vid NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, BaseData baseData, VehicleData vehicleData, InventoryData inventoryData, PlayerData playerData, GameData gameData, List`1 ParsedBatchCells)
   vid NitroxServer.Serialization.World.WorldPersistence.CreateFreshWorld()
   vid NitroxServer.Server..ctor(ServerConfigReader configReader)
   vid NitroxServer.Program.Main(String[] args)

**Comment by AusKarlos** [comment]
The Server executable requires files from Substantial to work, it will initially search the Windows Registry for the Steam version installation, failing that it will fallback to a text file in the Servers root directory called path.txt

A possible work around is to copy the ``` SNUnmanagedData ``` and ``` Subnautica_Data ``` folders to the servers directory and launching the server again.

**Comment by Sajgoniarz** [comment]
@AusKarlos its outdated solutiion, now everything should work by putting Subnautica path inside path.txt inside server directory

**Comment by AusKarlos** [comment]
@Sajgoniarz He's running it on a different machine. Quote : ``` works fine on my PC but when I try to run it on my server it crashes. ```
If he didn't copy the game across to the server he'll run into these issues.

**Comment by CrushedPixl** [comment]
@AusKarlos I have copied the game over as well as running it.

**Comment by CrushedPixl** [comment]
@Sajgoniarz The path.txt in SubServer is "C:\Program Files\Epic Games\Subnautica\", the SubServer folder is directly inside that.

**Comment by CrushedPixl** [comment]
@AusKarlos I tried both installing the game through Epic Games and running the installer and copying the files directly from the PC where it worked.

**Comment by AusKarlos** [comment]
@CrushedPixl Did you manually copy Subnautica over to the server or did you install Steam on it and restore a backup of the game or download it again?
The Nitrox Server is coded to search your registry for Steam as steam records game installs and location into the registry.
Failing to find the steam copy it will then use the ``` path.txt ``` file located in the server directory. Edit that file to reflect the location of the manually copied Subnautica game folder.

Another few tips are, Run the server with Admin permissions, and install the latest .NET Framework

**Comment by CrushedPixl** [comment]
@AusKarlos I got it to work by installing Steam, apparently Nitrox needs that even when using the Epic store. Should I open a new issue about this and close the current one or should I rename this one?
