### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by MasterPizza** [SubnauticaNitrox/Nitrox#388]
On the alpha version, I get the error "Unable to connect to remote server at:" Can anyone help me with this? Tried multiple IPs and could not get it to work. Thanks!

**Comment by CrushedPixl** [comment]
@MasterPizza Are the client and server on the same network? What IPs have you tried? Have you opened up the firewall for the computer that runs the server? Can you connect from the same PC that is running the server? Does anything appear in the server log? If the client is on another network, have you portforwarded 11000 in your router?
