### ISSUE TITLE
[Feedback] Require protocol TCP

### ISSUE THREAD

**Issue by dexter74** [SubnauticaNitrox/Nitrox#393]
[ENG] Google TRADUCTION.
Hello,
could you replace the server's UDP protocol with TCP.

The UDP protocol does not allow the verification of transmitted packets if they are well received, while the TCP protocol can transmit and verify the correct destination / reception of the packet.

Which translates in the game to no loss of connection or desynchronization.

[FR] Ma langue maternelle

Bonjour,
pourriez-vous remplacer le protocole UDP du serveur par le protocole TCP.

Le protocole UDP ne permet pas la vérification des paquets transmis si ceux ci sont bien réceptionner, alors que le protocole TCP permet de transmettre et de vérifier la bonne destination / reception du paquet.

Ce qui se traduit dans le jeu à aucune perte de connexion ou de désynchronisation.

**Comment by The-Great-Sephiroth** [comment]
TCP is normally not used for gaming. It is much slower, adding latency. Since the dawn of IP games, UDP/IP has been used with great success. I would recommend you do a little research as to why UDP is chosen for gaming and TCP is used for things like streaming or secure connections.
