### ISSUE TITLE
[Bug] Path File Build18

### ISSUE THREAD

**Issue by dexter74** [SubnauticaNitrox/Nitrox#395]
Hello,
Can you look path & fix path.

[Nitrox] I: Unable to find batch cells file 'F:\Jeux\Steam\steamapps/common\Subnautica\SNUnmanagedData/Build18\batch-cells-13-19-12-creature-slots.bin'! Please move SNUnmanagedData\Build18 to D:\Documents\Bureau\Nitrox\NitroxServer\bin\Release\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'F:\Jeux\Steam\steamapps/common\Subnautica\SNUnmanagedData/Build18\Generated\batch-cells-13-19-12-slots.bin'! Please move SNUnmanagedData\Build18 to D:\Documents\Bureau\Nitrox\NitroxServer\bin\Release\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'F:\Jeux\Steam\steamapps/common\Subnautica\SNUnmanagedData/Build18\batch-cells-13-19-12-loot.bin'! Please move SNUnmanagedData\Build18 to D:\Documents\Bureau\Nitrox\NitroxServer\bin\Release\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'F:\Jeux\Steam\steamapps/common\Subnautica\SNUnmanagedData/Build18\batch-cells-13-19-12-creatures.bin'! Please move SNUnmanagedData\Build18 to D:\Documents\Bureau\Nitrox\NitroxServer\bin\Release\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'F:\Jeux\Steam\steamapps/common\Subnautica\SNUnmanagedData/Build18\batch-cells-13-19-12-other.bin'! Please move SNUnmanagedData\Build18 to D:\Documents\Bureau\Nitrox\NitroxServer\bin\Release\SNUnmanagedData\Build18.

**Comment by dexter74** [comment]
My path : F:\Jeux\Steam\steamapps/common/Subnautica/

It's good ?

**Comment by dexter74** [comment]
File not exist:


Generated\batch-cells-11-19-12-slots.bin
Generated\batch-cells-12-19-12-slots.bin
Generated\batch-cells-13-19-12-slots.bin


batch-cells-11-18-12-creatures.bin

batch-cells-11-19-12-creatures.bin
batch-cells-11-19-12-creature-slots.bin
batch-cells-11-19-12-loot.bin
batch-cells-11-19-12-loot-slots.bin
batch-cells-11-19-12-other.bin

batch-cells-12-18-12-creatures.bin
batch-cells-12-19-12-creature-slots.bin
batch-cells-12-19-12-creatures.bin
batch-cells-12-19-12-other.bin
batch-cells-12-19-12-loot.bin

batch-cells-13-17-12-loot.bin
batch-cells-13-17-12-creatures.bin
batch-cells-13-17-12-other.bin
batch-cells-13-18-12-creatures.bin

batch-cells-13-19-12-creature-slots.bin
batch-cells-13-19-12-loot.bin
batch-cells-13-19-12-loot-slots.bin
batch-cells-13-19-12-creatures.bin
batch-cells-13-19-12-other.bin

**Comment by killzoms** [comment]
oh @dexter74 you got an older version wait for an update shortly(probably)

**Comment by dexter74** [comment]
I take last version Steam.

**Comment by dexter74** [comment]
Good evening,
The list of files to load does not match the existing file.

I own the latest stable version of subnautica via steam.

**Comment by Sajgoniarz** [comment]
@dexter74  If you don't have mobs etc, you found the root cause of #188.
