### ISSUE TITLE
World not save!

### ISSUE THREAD

**Issue by hussaniza2** [SubnauticaNitrox/Nitrox#399]
inventory it save!. Character position save!. but World not Save!

**Comment by hussaniza2** [comment]
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: No previous save file found - creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Nitrox Server Started
[Nitrox] I: Networking: Socket bound to 0.0.0.0:11000: True
[Nitrox] I: Networking: Network thread started
[Nitrox] I: Identifier -6996800357551627738 RespondedConnect: Remotely requested connect
[Nitrox] I: Identifier -6996800357551627738 Connected: Connected to 2622CF3B255FE69E
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.ColorSurrogate for type UnityEngine.Color
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.Int3Surrogate for type Int3
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.QuaternionSurrogate for type UnityEngine.Quaternion
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.TechTypeSurrogate for type TechType
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.Vector3Surrogate for type UnityEngine.Vector3
[Nitrox] I: Providing session policies...
[Nitrox] I: Networking: Initiated average roundtrip time to 10.73 ms Remote time is: 271.426384407813
[Nitrox] I: Processing reservation request...
[Nitrox] I: Reservation processed successfully: ReservationState: Reserved - ReservationKey: 80525042-65e2-44c4-8ed4-eed484dda5b6...
[Nitrox] D: Batch 12,19,10 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-10-loot-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-10-creature-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\Generated\batch-cells-12-19-10-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-10-loot.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-10-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-10-other.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 0 entity-spawn-points for batch 12,19,10
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional<System.String>.Empty()]
[Nitrox] D: Batch 12,19,11 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-11-loot-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-11-creature-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\Generated\batch-cells-12-19-11-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-11-loot.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-11-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-19-11-other.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 0 entity-spawn-points for batch 12,19,11
[Nitrox] D: Batch 11,19,10 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-10-loot-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-10-creature-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\Generated\batch-cells-11-19-10-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-10-loot.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-10-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-10-other.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 0 entity-spawn-points for batch 11,19,10
[Nitrox] D: Batch 11,19,11 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-11-loot-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-11-creature-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\Generated\batch-cells-11-19-11-slots.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Saving world state.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-11-loot.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-11-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-19-11-other.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 0 entity-spawn-points for batch 11,19,11
[Nitrox] D: Batch 11,18,10 not parsed yet; parsing...
[Nitrox] I: World state saved.
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-18-10-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 2126 entity-spawn-points for batch 11,18,10
[Nitrox] D: Batch 11,18,11 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-11-18-11-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 2286 entity-spawn-points for batch 11,18,11
[Nitrox] D: Batch 12,18,10 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-18-10-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 2881 entity-spawn-points for batch 12,18,10
[Nitrox] D: Batch 12,18,11 not parsed yet; parsing...
[Nitrox] I: Unable to find batch cells file 'C:\Program Files\Epic Games\Subnautica\SNUnmanagedData/Build18\batch-cells-12-18-11-creatures.bin'! Please move SNUnmanagedData\Build18 to C:\Program Files\Epic Games\Subnautica\SubServer\bin\Debug_WPF\SNUnmanagedData\Build18.
[Nitrox] D: Loaded 3034 entity-spawn-points for batch 12,18,11

**Comment by Coding-Hen** [comment]
I believe that this has now been fixed and can be closed.
