### ISSUE TITLE
Lost Connection to Game Server GENERAL SERVER/CLIENT ISSUE

### ISSUE THREAD

**Issue by ghost** [SubnauticaNitrox/Nitrox#402]
**Hello everybody!**
I would like to thank the developers of this mod for doing an outstanding job on the alpha version. Everything is functioning well. To the developers: I know there are many issues people are asking help for and I acknowledge that. Please help if possible, but great job, and I hope you can release a fully operational version soon.

**THE ISSUE:** My friends and I keep receiving this recurring error "Lost connection to game server" when connected to each others servers, and happens very quickly, everytime.

**WHAT WE HAVE TRIED:**
- reinstalling the game and nitrox.
- using hamachi (used that from the start).
-  we originally installed the nitrox mod through the very tedious and messy way of editing code etc and had the same problem (though the actual installation process was fine using the method before the installer.)
- installing nitrox through the newly released installer.

**WHAT WE HAVEN'T TRIED:**
- port forwarding.

**FINALLY:** 
If anyone could help, developers, knowledgeable coders, programmers that would be fantastic. 
Sorry for the long writing, I needed to make this professional. Please post at this Issue. 
If anyone needs server logs etc, please leave a message here. I will check this regularly. Thanks.

**Comment by kiyoshi-kurosaki** [comment]
Hello @pepe-ga 

Have you forwarded the port 11000 on UDP and not TCP?

Regards

**Comment by Phreak1202** [comment]
Hi, i didnt want to open a new Post.
Me and my friends have the same problem.
we join the server and 30sec later we get "disconnected: Connection timed out"

We even deactivated the modem firewall and computer firewall but it didnt change anything
