### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by Gortaf** [SubnauticaNitrox/Nitrox#403]
So, I've forwarded  port 11000 to my local ip, i've got no error in the NitroxServer console, I've opened port 11000 in the firewall, yet my friends can't join. We've tried with my pulblic ip and local ip. Anyone got any idea of what we're doing wrong ? Do my friends have to run NitroxServer aswell ?
Anyway, thanks in advance.

**Comment by kiyoshi-kurosaki** [comment]
Hello @Gortaf 

Have you forwarded the port 11000 on UDP and NOT TCP so i think that will solve the problem

Regards

**Comment by Gortaf** [comment]
Hi ! It worked ! Many thanks ! Altough fishes seems to not spawn correctly, but that's probably the mod having some troubles. Thanks again !
