### ISSUE TITLE
Installer does't work

### ISSUE THREAD

**Issue by TheShadowTV** [SubnauticaNitrox/Nitrox#404]
Installer does't work :/
https://imgur.com/kHfRCuE

**Comment by OmniTitan** [comment]
Hi,

You need to make the install directory the same as the Subnautica folder,

ie Program Files/Steam/steamapps/Subnautica

It wont work otherwise.

**Comment by TheShadowTV** [comment]
I did it but still bad

**Comment by OmniTitan** [comment]
Can you post a screenshot of the install directory page on the installer?

**Comment by crankineer** [comment]
I'd suggest you install it manually. It isn't very hard, and if you search on YouTube there is even a tutorial on how to install for Epic Games now.
