### ISSUE TITLE
Client Side Minerals and Fish

### ISSUE THREAD

**Issue by ghost** [SubnauticaNitrox/Nitrox#405]
Hi, another issue that has been brought to my attention is that everything from fish to minerals is client side at the moment. Please notify me when the mod becomes server side e.g sharing items in storage containers and fish/minerals.
Thanks in advance.

**Comment by OmniTitan** [comment]
In the previous version building storage (ie lockers) was shared. Has that stopped now too?

**Comment by JustinHoeky** [comment]
> In the previous version building storage (ie lockers) was shared. Has that stopped now too?

In my server it's not shared sadly enough. Latest build as far as i can see

**Comment by crankineer** [comment]
In my server, the inital storage in your lifepod isn't shared, but storage inside built lockers and other things IS shared. (using latest version)

**Comment by pepe-ga** [comment]
Just to clear some stuff up, 
The deposits and fish are not server side. So if my friend and I are playing together, my friend will not see a hostile fish that is attacking me. I know the mod is still developing and this is a lot to ask for, however its vital to having fun in the game - it makes it hard to communicate or play properly. 
Another issue is fish and minerals not spawning (only happening to my friend), if you have any idea or fix, please let me know. 

Regards,
Pepega

**Comment by pepe-ga** [comment]
1 more thing, 
Server side meaning the server does not generate the mineral/deposit locations and the fish, that is done by your computer (clientside). If there is any way to make it server side please let me know, or if a version of the Nitrox mod comes out that has serverside minerals and fish.

Regards, 
Pepega.
