### ISSUE TITLE
[Bug] Deconstruction not synced or saved, game breaking bug.

### ISSUE THREAD

**Issue by OmniTitan** [SubnauticaNitrox/Nitrox#406]
So construction seems to work fine.

But on attempting to deconstruct any buildings only the player deconstructing can see it, everyone else (including the server) does not have that building deconstructed at all. If the player who deconstructed relogs then the building will reappear where it originally was as if it had never been deconstructed.

Unfortunately this means bases will suddenly be incredibly unstable after a relog due to all deconstructed pieces reappearing. Also other players will build additions onto parts one player assumes are deconstructed as they cannot see them.

Urgently needs a fix, this is the one bug so far that has actually caused us to be unable to play.

**Comment by stanneman99** [comment]
Yeah, this is one of the main reasons we quit playing for now. And seeing as certain names for lockers and stuff dont save correctly is also quite irritating

**Comment by VHohenheim** [comment]
Same for me and my friend. I like to mess around with bases, but because what I delete doesn't actually delete its now just some mechanical monstrosity that we cant get rid of.

**Comment by Christopher117** [comment]
Yes, I have exactly the same problem.
If a developer sees this, I think it's really something to fix in the next update if it's possible for you.

Thank you for this great Mod !

**Comment by Measurity** [comment]
This issue is being tracked here: #951
