### ISSUE TITLE
Despawning Acid Mushroom and Table Coral after server restart

### ISSUE THREAD

**Issue by IngvarSchoenmaker** [SubnauticaNitrox/Nitrox#407]
After making a character and then restarting the server, the Acid Mushroom and the Table Coral on the ocean ground aren't there anymore. But after making a new character the Acid Mushroom and the Table Coral are there again.

**Comment by IngvarSchoenmaker** [comment]
I edit my previous statement after 10 minutes after making a character Acid Mushroom and the Table Coral already despawn around the places you have visited.

**Comment by sherpaxd** [comment]
do you also have way to much fish and debris spawning?
if so, my guess would be that there is some sort of entity limit and these are just the first things to despawn, to make place for new entities.

**Comment by IngvarSchoenmaker** [comment]
Now you say it there is a little more fish than usual. And the fish are also spawning in our base (maybe coincidence?).

**Comment by stanneman99** [comment]
Acid mushrooms are also getting despawned whenever they are put into a Wall Locker. So maybe it doesn't have anything to do with entitylimits?

**Comment by Agent77326** [comment]
#545

**Comment by DagrMine** [comment]
I don't think it requires the server to restart for this to happen. For me it was despawning whenever I got too far from the mushrooms/coral and didn't respawn when I came closer. It unloaded and didn't reload. TBH i'd rather have infinite of the two than none at all.
