### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by C9Tom** [SubnauticaNitrox/Nitrox#409]
So everything is doing good but It says I didn't select the Subnautica folder, which I did as you can see.
Hope I get a fast answer

Tom

Video: https://www.youtube.com/watch?v=471nbdn3N7I&feature=youtu.be

**Comment by sherpaxd** [comment]
it looks like you are launching the installer straight out of the archive, try unzipping/unpacking first.

**Comment by C9Tom** [comment]
I tried it but its still the same :c
