### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by Gravel789** [SubnauticaNitrox/Nitrox#41]
I tried leaving the zip that i unzipped and downloaded (i put the file from the zip) in almost everything data, resource, plugins, MacOs, e.g. however it did not work, i understand if you can't implement this feature, (mac compatibility is hard) but i would really really appreciate it if you could add mac support to this godsend of mod 

kind regards - Gravel

**Comment by MarijnS95** [comment]
This should work just fine on a mac, but that's not how you install this mod. It's not possible to install for playing yet, until we make a public release. You can however contribute, by following the guide on the wiki.

Until then, we advise against using this mod for playing. It's still in development and unstable. Besides, we are currently undergoing some major architectural changes, and all fixes and improvements will not be committed to master just yet.

**Comment by Gravel789** [comment]
my bad
