### ISSUE TITLE
How to change gamemode

### ISSUE THREAD

**Issue by emvo0** [SubnauticaNitrox/Nitrox#410]
can i do that ?

**Comment by stanneman99** [comment]
Type creative in console. To enable the console press F3 and click the button in the top left with disable console next to it. Then press the ~ button to type in the console.

**Comment by dgkepel** [comment]
The modes available are:
freedom
creative
survival
hardcore

**Comment by Sajgoniarz** [comment]
Will it affect state at world save?

**Comment by emvo0** [comment]
so i just need to type in "freedom"
to disable hunger yes ?

**Comment by papdehappy** [comment]
yes

**Comment by emvo0** [comment]
Thanks
