### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by tag166tt** [SubnauticaNitrox/Nitrox#416]
Hi,

I have a problem when connecting to the server. I can run the server normally, and anyone can join the server, but when I try and connect from the computer hosting the server, I get e message saying it was unable to connect to the server. Although I can choose a nickname and a color...

I tried connecting to a different server also running on the local network, but still getting the same message...

The server log are exactly the same for a successful connection, and the failed attempt from my computer.

Did anyone have the same problem? If so, how can you solve it?

Thanks for your help !

**Comment by crankineer** [comment]
That's weird. Could you send a screenshot or short video so that I can better understand this? Are you using the correct IP address on the host machine to connect?
