### ISSUE TITLE
Stuck on loading when using Nitrox 1.0.0.4 from Nexus

### ISSUE THREAD

**Issue by TKNNightKroz** [SubnauticaNitrox/Nitrox#418]
Before when a friend and I played alone it was fine and it worked the next day. After we invited a third friend, once we all left no one else was able to connect to the server. NitroxServer was open and so was Hamachi. 

I tried to find a solution but everyone else's problems were different.

**Comment by AurelienS** [comment]
Same issue with Alpha 1.0.0.5-159-1-0-0-5-1545298073.

**Comment by TKNNightKroz** [comment]
I got it to work now. However it is a pain that I have to restart everything.
