### ISSUE TITLE
Extended setting up env manual

### ISSUE THREAD

**Issue by kafeg** [SubnauticaNitrox/Nitrox#42]
Hi!

Can you expand wiki page about setting up project on local machine?

I am C++ developer and not quickly understand howto inject NitroxPatcher to Subnautica Assebly-CSharp.cs

When i try to inject `NitroxPatcher Main.Execute()` to GameInput.Awake (bottom of original code) by 'dnSpy -> change method' i get compilation errors:
'The type or namespace name ... could not be found ...'

Nitrox project successfully compiled and patcher and cliend DLL's auto copied to Subnautica folder.

PS: Sorry for 'bugged question', my cat hit 'Enter' when i open question editor =)

**Comment by MarijnS95** [comment]
@kafeg What is the question/issue?

**Comment by kafeg** [comment]
Hi, i will update question at top.

**Comment by MarijnS95** [comment]
The wiki is now updated with a little more detail on the injection step.

**Comment by kafeg** [comment]
Cool, it's working! Amazing! =)
