### ISSUE TITLE
[Bug] Acid mushrooms cannot be placed in lockers, will disappear

### ISSUE THREAD

**Issue by OmniTitan** [SubnauticaNitrox/Nitrox#423]
When trying to place acid mushrooms in a locker they will just disappear completely. They do show up for the briefest moment in the locker and then disappear as if going back into the players inventory, but they don't.

**Comment by Agent77326** [comment]
#545

**Comment by Sunrunner37** [comment]
Fixed in https://github.com/SubnauticaNitrox/Nitrox/commit/15709470c9280045910cc08adbfb978f4e663201
