### ISSUE TITLE
When I am trying to open the server i get this.

### ISSUE THREAD

**Issue by highDT01** [SubnauticaNitrox/Nitrox#424]
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: No previous save file found - creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] I: It appears you don't have Subnautica installed anywhere. The game files are needed to run the server.
[Nitrox] E: System.IO.FileNotFoundException: Make sure resources.assets is in current or parent directory and readable.
   σε NitroxServer.Serialization.ResourceAssetsParser.FindPath() στο C:\Users\user\Documents\Nitro\NitroxServer\Serialization\ResourceAssetsParser.cs:γραμμή 95
   σε NitroxServer.Serialization.ResourceAssetsParser.Parse() στο C:\Users\user\Documents\Nitro\NitroxServer\Serialization\ResourceAssetsParser.cs:γραμμή 18
   σε NitroxServer.Serialization.World.WorldPersistence.CreateWorld(DateTime serverStartTime, EntityData entityData, BaseData baseData, VehicleData vehicleData, InventoryData inventoryData, PlayerData playerData, GameData gameData, List`1 ParsedBatchCells) στο C:\Users\user\Documents\Nitro\NitroxServer\Serialization\World\WorldPersistence.cs:γραμμή 132
   σε NitroxServer.Serialization.World.WorldPersistence.CreateFreshWorld() στο C:\Users\user\Documents\Nitro\NitroxServer\Serialization\World\WorldPersistence.cs:γραμμή 105
   σε NitroxServer.Serialization.World.WorldPersistence.Load() στο C:\Users\user\Documents\Nitro\NitroxServer\Serialization\World\WorldPersistence.cs:γραμμή 100
   σε NitroxServer.Server..ctor() στο C:\Users\user\Documents\Nitro\NitroxServer\Server.cs:γραμμή 28
   σε NitroxServer.MainWindow.Window_Loaded(Object sender, RoutedEventArgs e) στο C:\Users\user\Documents\Nitro\NitroxServer\MainWindow.xaml.cs:γραμμή 44

**Comment by kiyoshi-kurosaki** [comment]
Hello @highDT01 

You need to install the Game on the same PC or Server youre running the Nitrox Server if not, you will get the error above, the Server need to read the Subnautica_Data folder from the game to spawn all entities and resources.

Regards

**Comment by highDT01** [comment]
Yeah its on the same PC thats why i dont know why there is such a problem

**Comment by kiyoshi-kurosaki** [comment]
Have you tried to delete and re-clone the repo?

Command: git clone --recurse-submodules https://github.com/SubnauticaNitrox/Nitrox.git

Normaly it will work, so for me it works, and im playing with the game from Epic Games.

**Comment by papdehappy** [comment]
On the folder the NItroxServer.exe is there is a file named path
Open that and enter the directory to your game

**Comment by highDT01** [comment]
there is no file "path" in that folder
