### ISSUE TITLE
I Can't Install The Version 1.0.0.5

### ISSUE THREAD

**Issue by kostantinos04** [SubnauticaNitrox/Nitrox#425]
Hello i can't install the new version.i have the correct setup and i can't install it for some reason
![image](https://user-images.githubusercontent.com/46007036/50287737-63de4180-046c-11e9-9cfe-9974c2748ebf.png)

**Comment by kiyoshi-kurosaki** [comment]
Hello @kostantinos04 

Have you cloned the repo with this command:

git clone --recurse-submodules https://github.com/SubnauticaNitrox/Nitrox.git

If not, this might be resolve the problem.

You need the git bash for this.

Regards

**Comment by pepe-ga** [comment]
Hello,

I want to ask what is the difference between 1.0.0.4 and 1.0.0.5 and is it worth playing?

Pepega

**Comment by kostantinos04** [comment]
ok thank you
