### ISSUE TITLE
Update without losing progress?

### ISSUE THREAD

**Issue by Thaisen69** [SubnauticaNitrox/Nitrox#427]
A question about the follow title. Is there any way that you can update to the latests push from you awesome guys without losing the progress in your multiplayer game?

Something i noticed is that.

- Fish can swim through buildings
- Desync between players maybe caused by the console spaming some "BATCH-CELLS" errors. (You properly already know this)
- Can confirm that the Acid Mushroom is bugged and sometimes you can't see them and you can't store them.

Thats all for now i think

**Comment by JetBr33ze** [comment]
You can try moving the Save.nitrox to another folder and symlinking it to the server folder. Then, anytime you have to rebuild/pull changes, you can just redo the symlink.
[Windows](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/), [Unix](https://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux)

**Comment by Thaisen69** [comment]
I have my save.nitrox in another folder. Don't know what symlinking means though

**Comment by JetBr33ze** [comment]
Symlinking is basically making a link to a file/folder that programs recognize as a regular file/folder, and update the original when they are changed. This way if the link is deleted, the original stays intact. I put some links of how to make symlinks for different operating systems in my first comment. Good luck!

**Comment by Thaisen69** [comment]
Yeah but that does not work. It seems to be more than the save.nitrox that saves it.

**Comment by Agent77326** [comment]
#442
