### ISSUE TITLE
Small gameplay bugs

### ISSUE THREAD

**Issue by werickson24** [SubnauticaNitrox/Nitrox#428]
Just a list of bugs from attempting a “normal play through” of this mod. I apologize if any of these are repeats

- Our lifepod’s broken wiring has no sparks
- Crashfish get stuck in their... flowers?
- and that’s all for now as of version 1.0.0.4

**Comment by Coding-Hen** [comment]
I believe that the broken wiring is fixed and the crashfish is fixed for the next release 2ccd92605c6269a97c245ebafc15617a80abe0e9.

**Comment by Coding-Hen** [comment]
@Measurity this can probably be closed now
