### ISSUE TITLE
[Bug] Seamoth other player creates on mobile vehicle bay cannot be seen

### ISSUE THREAD

**Issue by OmniTitan** [SubnauticaNitrox/Nitrox#431]
If one player makes a seamoth on a mobile vehicle bay that the other player cannot see then the seamoth will not be visible or exist at all for the player that cannot see the mobile vehicle bay.

May be fixed when the bug about deployables not saving is fixed, as this is the only way the mobile vehicle bay is not visible by one player.

**Comment by RylenWolf** [comment]
I had the same problem, until I restarted my server. Still got the seamoth, and now they are synced for other players to.
