### ISSUE TITLE
I can't open subnautica

### ISSUE THREAD

**Issue by kostantinos04** [SubnauticaNitrox/Nitrox#432]
Hello when i did the new update version 1.0.0.5 i can't open subnautica.what can i do to fix it?

**Comment by Sunrunner37** [comment]
Please post your Subnautica\Subnautica_Data\output_log.txt

**Comment by kostantinos04** [comment]
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2700078/output_log.txt)

**Comment by Sunrunner37** [comment]
Did you previously try to install manually?  I think you should remove Subnautica\Subnautica_Data\managed, run verify on the epic games launcher, then re-install using the 1.0.0.5 installer on the nexus mods website.

**Comment by kostantinos04** [comment]
I did it 5 times

**Comment by sherpaxd** [comment]
Reinstalling Nitrox and starting over the Launcher worked for me. (on epic)

**Comment by kostantinos04** [comment]
i have reinstall the nitrox 5 times

**Comment by SebiAi** [comment]
Have this issue with 1.0.0.5 too. Only a start via the empic games launcher works

**Comment by JetBr33ze** [comment]
Worked perfectly after reinstall+launch via epic games launcher. I used the msi installer

**Comment by kostantinos04** [comment]
What is msi installer?

**Comment by kostantinos04** [comment]
ok thank you

**Comment by papdehappy** [comment]
Did it work?

**Comment by kostantinos04** [comment]
yes

**Comment by kostantinos04** [comment]
but i ahev another  problem i acn;t connet to my friend's server it says "loading multiplayer" for ever.do you know how i can fix it?

**Comment by papdehappy** [comment]
do you get to the loading screen if yes thats a bug in this version

**Comment by kostantinos04** [comment]
all the fiels load but in the end it stuck to loading "multplayer"

**Comment by papdehappy** [comment]
its a bug in this version unfortunately

**Comment by papdehappy** [comment]
are you connected together via hamachi?

**Comment by papdehappy** [comment]
also you better create another issue for this

**Comment by kostantinos04** [comment]
i have already did it.
https://github.com/SubnauticaNitrox/Nitrox/issues/449
