### ISSUE TITLE
Fragments not spawning

### ISSUE THREAD

**Issue by SADXfan01** [SubnauticaNitrox/Nitrox#434]
Most entities seem to spawn correctly, wildlife, resources, and metal scrap all seem to function perfectly. Fragments, however, don't seem to spawn at all. Certain things, like trash cans, chairs and such do spawn, but the fragments for actual tech are nowhere to be found.

[log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2700024/log.txt)

**Comment by SADXfan01** [comment]
It seems that an alternate executable provided moments ago for issue #352 has resolved this, will continue monitoring.

https://github.com/SubnauticaNitrox/Nitrox/issues/352#issuecomment-449094900

**Comment by SADXfan01** [comment]
Not sure if this is the right place to ask, but are fragment scans shared between players? Or does it at least leave the fragments behind for others to scan?

**Comment by CodyHayzett** [comment]
> Not sure if this is the right place to ask, but are fragment scans shared between players? Or does it at least leave the fragments behind for others to scan?

Scans are shared between players, AND it saves the fragments for them. Can easily be cheesed. I avoided cheesing it by only having me go for fragments while my friend built our base and such.
