### ISSUE TITLE
Nitrox Server error Loading Multiplayer infinity

### ISSUE THREAD

**Issue by tpgamer** [SubnauticaNitrox/Nitrox#435]
Before this issue happen i can play normally but after i shutdown my computer and open it again
this issue is happen
-------------------------------------------------------------------------
[Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] D: Event Triggerer started!
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Nitrox Server Started
-------------------------------------------------------------------------

**Comment by tpgamer** [comment]
![image](https://user-images.githubusercontent.com/46032244/50305147-9a47ab00-04c4-11e9-9849-219a4c64b32d.png)

**Comment by killzoms** [comment]
question:
can you send client logs? (Subnautica folder)\Subanutica_Data\output_log.txt
did you happen to build a Nuclear Reactor or Bioreactor?

**Comment by tpgamer** [comment]
> question:
> can you send client logs? (Subnautica folder)\Subanutica_Data\output_log.txt
> did you happen to build a Nuclear Reactor or Bioreactor?

i'm just build foundation and tube before i'm quit the game
https://we.tl/t-qX2qdlwI4H < this is output_log

**Comment by tpgamer** [comment]
Help me please.

**Comment by kostantinos04** [comment]
me too.ples help me.
#511

**Comment by tpgamer** [comment]
why close ???

**Comment by alexanderheuts** [comment]
Because the ticket is old and we're on version 1.0.2.2 already. If the problem persists, join Discord
