### ISSUE TITLE
Singleplayer not working

### ISSUE THREAD

**Issue by Daywalkr1990** [SubnauticaNitrox/Nitrox#436]
After instal of the Multiplayer the Singleplayer keeps loading infinite.

**Comment by SebiAi** [comment]
Not a problem for me...

**Comment by SebiAi** [comment]
For me too...

**Comment by Daywalkr1990** [comment]
Tested it and it worked in 1.0.0.4 but not in the latest release

**Comment by Ovyerus** [comment]
Confirmed in 1.0.0.5 as well.

**Comment by GrapsZ** [comment]
Same problem

**Comment by M3dicCookie** [comment]
same problem 
so its something with 1.0.05

**Comment by silvervirus** [comment]
http://www.mediafire.com/file/pe01vr87th4zvw4/Codenamed_Two_nerds_one_zip.zip/file  don't mind the name this just new dll files from the mod if you all would test these in your managed folder thanks . (not a mod , or admin or dev)

**Comment by Sajgoniarz** [comment]
Yep, and everone will just trust you. Until you are not a long term contributor please share scan logs.

**Comment by Ovyerus** [comment]
Seems to be working on the recent updates. Works fine now in the 1.0.0.8 installer from Nexus.
