### ISSUE TITLE
Installer isn't working

### ISSUE THREAD

**Issue by SkidFlashys** [SubnauticaNitrox/Nitrox#437]
It wants me to get a package that has the installer.msi in it. I selected it and it still didn't work.
Img: https://imgur.com/a/ee4g5l0
Fix: I needed to select the .msi from the installer I had previously installed the mod with.

**Comment by SebiAi** [comment]
Try to fully extract the installer first!

**Comment by SkidFlashys** [comment]
I did, and it still didn't work

**Comment by SebiAi** [comment]
Ok... Worked for me.

**Comment by SkidFlashys** [comment]
Once I read the message, I instantly thought on that. But it didn't work
