### ISSUE TITLE
[1.0.0.5]Multiple issues [Metal Scraps,Fish,Fragments for Blueprints,Enemies,Oxygen Bug,Item dissapearing,Hunger and Water]

### ISSUE THREAD

**Issue by SebiAi** [SubnauticaNitrox/Nitrox#439]
*Works as expected in single player*

Subnautica Version: Dez. 2018 - 61951
Nitrox Version ([Download from NexusMods](https://www.nexusmods.com/subnautica/mods/159?tab=files)): Alpha 1.0.0.5

On Windows 64 Bit

Downloaded the installer from NexusMods and installed in "C:\ProgramData\EpicGames\Subnautica", where I installed Subnautica (downloaded it via Epic Games Launcher)

- Metal Scraps:
No metal scraps are spawning (see picture below)
Acid Mushrooms and Tubes are spawning correct.

- Fish:
Only the Bladderfish and the Holefish are spawning in the start area.
![desktop screenshot 2018 12 20 - 22 26 39 31](https://user-images.githubusercontent.com/41116921/50312330-45963700-04a8-11e9-802e-e3dd160e3825.png)

- Fragments:
No Fragments are spawning except tables and chairs etc.

- Enemies:
No enemies except the Crashfish.

- Oxygen Bug:
If you craft a Standard O2 Tank and equip it while not in the water you get unlimited O2. It is not going down. Only if equipped under water it works correctly.

- Item disappearing
If you put items in the storage of the rescue capsule, leave and rejoin the game the items are replaced with the default one.

- Hunger and Water:
The water and hunger "bar" resets to "standard", when rejoining (see picture above).

Log from the command line (If you wonder why there is no ip: I censored it):
[log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2700688/log.txt)

Really would like to see a good and working multiplayer xD. Thanks for your hard work!

**Comment by JulsOSpel** [comment]
Yes, I have a similar issue with disappearing objects, in particular, the acid mushrooms and other objects near them. But the way I found out to temporarily fix it is to go to the main menu and rejoin the server.
Before:
<img width="640" alt="before" src="https://user-images.githubusercontent.com/21327687/50326800-17612900-04a1-11e9-8a0b-6f1dff5a6065.png">
After:
<img width="640" alt="befor" src="https://user-images.githubusercontent.com/21327687/50326835-47103100-04a1-11e9-9c68-a6d4e6686d5e.png">

**Comment by SebiAi** [comment]
As crazy as it might seem acid mushrooms and tubes are spawning correct.

**Comment by JulsOSpel** [comment]
Yeah like for the first two hours it was spawning correctly, but then it just stops working correctly, and now I think I have a new issue with the seamoth randomly exploding even though the durability is 100%

**Comment by ambid17** [comment]
I am having the same issues with acid shroom and coral tube spawns, disappearing after a bit. (1.0.0.8)

**Comment by Agent77326** [comment]
#545

**Comment by GW-GhostWolf** [comment]
Oxygen bug mentioned is issue #290. Please see that thread for updates
