### ISSUE TITLE
[Minor] Discord on readme outdated

### ISSUE THREAD

**Issue by DukeVenator** [SubnauticaNitrox/Nitrox#441]
Your discord link on the readmemd is expired recommend updating.

**Comment by AriaanBruinsma** [comment]
I just noticed this too, I thought I'd join in, since some friends and me are actively testing the mod.

**Comment by Coding-Hen** [comment]
I think that this can now be closed as the link has been updated as per [commit](https://github.com/SubnauticaNitrox/Nitrox/commit/d5d373aaf10c05e64d0638a977599ebed3dcd9b8#diff-04c6e90faac2675aa89e2176d2eec7d8)
