### ISSUE TITLE
[1.0.0.8] Current list of bugs 

### ISSUE THREAD

**Issue by DukeVenator** [SubnauticaNitrox/Nitrox#442]
Current list of bugs over a 4 hour play session with regular half a hour rejoins as a precaution.

* INFINITE LOADING bug is caused by placing nuclear reactor or bio mass reactor! (DO NOT PLACE)!
* Exploding fish have a 80%ish percent chance of being stuck in their pods while the other 20% go after you and kill you just fine (terrifying) 
* Sometimes Habitat storage will duplicate and have two in the same space 
* Deconstruction appears not to save properly or sync between restarts (Tinnnnnny bit annoying)
* Seamoths Damage values need tobe sent to other clients along with if a client has done repairs on the seamoth
* Wearables sometimes disappear on relog (Currently using debug to spawn shit back in)
* 40% chance of the mobile vehicle bay despawning (unknown what triggers this) 
* Storage in the life pod is not synced and resets itself every relog
* Deployable storage pods are not synced (minor) 
* Sometimes the other players are a  meter off the ground in the habitats (can be fixed by everyone relogging) 
* The devs are doing a good job (not a bug it is a feature!)
* Infinite o2 bug (Fixed by reequiping tanks)
* Nuclear reactors break everything (Really annoying but thats why we backup)
* Bio reactors ^ (major problem)
* Scanner rooms are not synced and upgrades reset on restart of server (To be expected)
* Using grav gun on players can cause issues.... (funny issues)
* Prawn suit has same issue as sea moth with repairs not being sent to other players (you might need a sync event for this) 
* Player animations do what you do (minor as all hell fix this last)
* Fish go inside habitats and become stuck on the floor ( free fish to eat really don't mind)
_* FIsh spawn numbers are over the top and appear to have no limit or are dupping (Might need to have a limit in place)_ NOTE: APPEARS TO BE FIXED AS OF 1.0.0.8
*stalker teeth do not drop (For now you will just have to enable the console and type "item stalkertooth") 

Edit added to much fish spawning and stalker teeth bugs along with fix
Edit2: Fish bug appears to resolved!
Will update if I find more and what causes it.

You guys are doing excellent work! keep the good work rolling. No seriously apart from the bugs above its been mostly smooth sailing!

**Comment by trjflash** [comment]
All this problems are have about four months...

**Comment by trjflash** [comment]
Sorry for grammar. These problems last at least 4 months

**Comment by Sunrunner37** [comment]
Thanks for the great list.

**Comment by JozekStiha** [comment]
Yea and i m having this issue with too much mobs spawning in one place or mobs spawn on wrong places..

**Comment by DukeVenator** [comment]
Most excellent!

**Comment by DukeVenator** [comment]
Updated with two new bugs

**Comment by Sunrunner37** [comment]
if you experience a lot of fish go here, follow my steps, and paste your server log: https://github.com/SubnauticaNitrox/Nitrox/issues/352#issuecomment-449476606

**Comment by Asorley** [comment]
[Nitrox] I: ShaleChunk 7
[Nitrox] I: SpadefishEgg 9
[Nitrox] I: Rockgrub 20
[Nitrox] I: CrashHome 31
[Nitrox] I: Crash 31
[Nitrox] I: CrashPowder 31
[Nitrox] I: Spadefish 68
[Nitrox] I: Jumper 105
[Nitrox] I: HoleFish 118
[Nitrox] I: Bladderfish 132
[Nitrox] I: LimestoneChunk 157
[Nitrox] I: SandstoneChunk 168
[Nitrox] I: Biter 224
[Nitrox] I: Oculus 294
[Nitrox] I: Quartz 304
[Nitrox] I: Reginald 380
[Nitrox] I: Eyeye 1166

This is me guys so dont be mad 💃

**Comment by PorroKamui** [comment]
I Can't find any Mushroom
