### ISSUE TITLE
How can I generate .exe from lastest version here?

### ISSUE THREAD

**Issue by bleiz0n** [SubnauticaNitrox/Nitrox#443]
You are doing a great job developing this feature, but I would like to generate the .exe to be able to install the latest version uploaded here on Github. If someone could help me, I would be very grateful.

When I try to open the project with Visual Studio I can't find the file 'Nitrox-master\NitroxReloader\ReloaderSettings.cs'

**Comment by DukeVenator** [comment]
Please goto the wiki on the github for more information!

**Comment by Measurity** [comment]
Go to the Nitrox discord server to get help on everything related to this project: https://discord.gg/E8B4X9s
