### ISSUE TITLE
[BUG] Stalker teeths

### ISSUE THREAD

**Issue by ZeTioZ** [SubnauticaNitrox/Nitrox#444]
Hello, I was looking for stalker teeths, so I tried to do it like in solo, but it doesn't work, after at least 20min trying to get some teeths the stalkers don't drop any theeth. It's a game breaking bug because so we can't build a lot of thing like Cyclop or Pawn Suit...

Thanks in advance.

**Comment by quimnuss** [comment]
The DefaultEntitySpawner spawns the GameObjects like this:
        
        GameObject prefabForTechType = CraftData.GetPrefabForTechType(entity.TechType, false);
        [...]
        GameObject gameObject = global::Utils.SpawnFromPrefab(prefabForTechType, null);

on DefaultEntitySpawner:24. Those TechType = ScrapMetal prefabs already have no HardnessMixin component as they should, as well as fish and other munchable entities.
