### ISSUE TITLE
Need help with server

### ISSUE THREAD

**Issue by Tododas** [SubnauticaNitrox/Nitrox#455]
Me and my friend are trying to play subnuatica together but we just cant figure out how this stuff works could really use some help thanks

**Comment by pepe-ga** [comment]
Download the mod of nexus mods, and then run the installation. Make sure you install it **in the subnautica file location**. Set up a hamachi, get your friend to join it and then go to your **subnautica game folder** and **run nitrox server**.

**Comment by Sajgoniarz** [comment]
There is official release at Nexus, also Wiki contains instruction for compiling on your own.
