### ISSUE TITLE
Multiplayer client loaded and nothing happens

### ISSUE THREAD

**Issue by TheNimDude** [SubnauticaNitrox/Nitrox#456]
It's been asked before but no answers so hey....

**Comment by TheNimDude** [comment]
Basically everything worked until the small patch today, now when he tries to join my server it just says "multiplayer client loaded" and nothing happens

**Comment by igeorges1** [comment]
I know it's weird but if he double clicks it won't load in. I had the same. Just click one time and wait.

**Comment by Sajgoniarz** [comment]
I had same issue when used precompiled installer, when i compile server by myself connecting works fine.

**Comment by TheNimDude** [comment]
> I had same issue when used precompiled installer, when i compile server by myself connecting works fine.

What do you mean precompiled installer? The exe file as opposed to the injection with gitbash and stuff like that?

**Comment by Sajgoniarz** [comment]
Version from Nexus :)
