### ISSUE TITLE
[Urgent 1.0.0.5 & 1.0.0.4 Nexus] Infinite Loading Glitch

### ISSUE THREAD

**Issue by LiamBogur** [SubnauticaNitrox/Nitrox#458]
A few other people and I have noticed that after a while of playing other people will not be able to join, I have seen my logs it constantly saving, this glitch is on 1.0.0.5 and 1.0.0.4, I think it is only in the Nexus installer version but I might be wrong.

EDIT: I am using the epic games launcher version of subnautica

Links:
https://github.com/SubnauticaNitrox/Nitrox/issues/435
https://github.com/SubnauticaNitrox/Nitrox/issues/449
https://github.com/SubnauticaNitrox/Nitrox/issues/412
![image](https://user-images.githubusercontent.com/38594963/50371493-04209b80-0610-11e9-9a9e-35d731f22040.png)

**Comment by JulsOSpel** [comment]
Did you port forward or use Hamachi and do you have Windows Firewall disabled?

**Comment by LiamBogur** [comment]
as I have said we could join for a few days until suddenly it wouldn't let us, it would just keep on loading even though it said connection successful

**Comment by JulsOSpel** [comment]
Well, have you tried what I said in the previous message with disabling Windows firewall? Also, are you both using different versions of the mod?

**Comment by IngvarSchoenmaker** [comment]
I had the same. I fixed it to verify Subnautica, then uninstall multiplayer, then reinstall multiplayer.

**Comment by IngvarSchoenmaker** [comment]
Ok. I retried it and reinstalling the mod fixed it also for me. (in the NitroxInstaller-1.0.0.5.msi is also a uninstall function.)

**Comment by grepString** [comment]
Just ran into this issue. Using Hamachi, latest version of the mod (1.0.0.5), and the Epic version of Subnautica.

Ran great for hours, then after trying to reconnect some time later, this "infinite" screen happened. Seems like I'm loaded into the game, just suck with this screen.

**Comment by LiamBogur** [comment]
we did load in because sometimes I could see the UI elements flicker in and the console said we were connected.

**Comment by LiamBogur** [comment]
ok just installed 1.0.0.8 i will let you know if the problem appears again

**Comment by LiamBogur** [comment]
i think the problem has been fixed, we have been playing for a few hours and it hasn't happened

**Comment by kostantinos04** [comment]
hello i have the lastest version and i have the same issue.i had this issue for version 1.0.0.4 and.1.0.0.5 and 1.0.0.8.Please if you can help me do it.

**Comment by kostantinos04** [comment]
hello i have the lastest version and i have the same issue.i had this issue for version 1.0.0.4 and.1.0.0.5 and 1.0.0.8.Please if you can help me do it.
