### ISSUE TITLE
Version 1.0.0.6 Connection problem.

### ISSUE THREAD

**Issue by Tibnan** [SubnauticaNitrox/Nitrox#460]
I've updated to the newest version of Nitrox, and when I installed it and tried to connect to my own game I got "Multiplayer client loaded..." and it stopped doing it's job there. Not even got to connecting to the game. Tried with local IP, Hamachi IP, even Port forwarding (which resulted in a "Can't contact the remote server at..."). 
[log(1.0.0.6).txt](https://github.com/SubnauticaNitrox/Nitrox/files/2705180/log.1.0.0.6.txt)

**Comment by Sunrunner37** [comment]
1.0.0.7 is uploading to nexus - try that one

**Comment by Tibnan** [comment]
I'm going to try that later today, and write back if it's working or not.

**Comment by Jannify** [comment]
@Tibnan Can you please send me the "server" file from your subnautica folder? I have to know the IP you are trying to connect to. :/
