### ISSUE TITLE
Version 1.0.0.6 C'ant connect to server

### ISSUE THREAD

**Issue by MrBretze** [SubnauticaNitrox/Nitrox#461]
Hello i have installed the last version of your GREAT mod :)
But its impossible to connect on the server :(
I only view "Multiplayer Client Loaded..."

log (edit: more log): https://pastebin.com/ENg2ARdc

**Comment by Sunrunner37** [comment]
1.0.0.7 is uploading to nexus - try that one

**Comment by MrBretze** [comment]
Hello, thanks for your speed.
It does not work either with the version 1.0.07 :/
log: https://pastebin.com/48G1KVz7

**Comment by Jannify** [comment]
@MrBretze Can you please send me the "server" file from your subnautica folder? I have to know the IP your are trying to connect to. :/

**Comment by MrBretze** [comment]
Hello, i tried to connect in local for the moment
The server file is here: https://www.dropbox.com/s/j69lwiqnvt93ele/SubServer.zip?dl=0

**Comment by Jannify** [comment]
@MrBretze No :D, I need your "server" file
![grafik](https://user-images.githubusercontent.com/23176718/50375164-4ab6cb80-05f9-11e9-89ca-10f9a1ac30ac.png)

**Comment by Jannify** [comment]
And (as an tip) pls delete your dropbox files because the Assembly-CSharp is property of UWE.

**Comment by MrBretze** [comment]
Ho okay, sorry
servers file: https://www.dropbox.com/s/q81kiaqmu7pvw7e/servers.zip?dl=0

**Comment by MrBretze** [comment]
Problème fixed in 1.0.0.8

**Comment by Jannify** [comment]
Not really, just the reason for the error (special case in new domain resolving) was deleted.  I have fixed it now, so thanks for the file!
