### ISSUE TITLE
Version 1.0.0.7 Cant launch on Windows Server

### ISSUE THREAD

**Issue by MrBretze** [SubnauticaNitrox/Nitrox#462]
Subnautica is installed on server by SteamCMD

https://imgur.com/a/HkXTPeS

**Comment by Sunrunner37** [comment]
May want to try compiling the latest code to see if that works.  Code commit that will probably fix this:
https://github.com/SubnauticaNitrox/Nitrox/commit/2e0714ec62d76b746a2da6e1c88e662d139d9b86

**Comment by MrBretze** [comment]
https://pastebin.com/1kL0h24X English log

**Comment by Sunrunner37** [comment]
Can you try the latest version? (1.0.0.8)

**Comment by MrBretze** [comment]
@Sunrunner37 Its works, but if i restart the nitrox server, my game say, "Requesting session policy information..."

I opened the port 11000 UDP and TCP on my windows server, another port need to open ?

And no ore and fish appeared 

Log (after restart): https://imgur.com/a/D0LBTvR
