### ISSUE TITLE
Version 1.0.0.8 still has issue with spawning entities.

### ISSUE THREAD

**Issue by Tibnan** [SubnauticaNitrox/Nitrox#466]
Dear modders!

I've updated to version 1.0.0.8 and noticed that nothing changed at all. I still lack like 80% of fish, and no fragments or scraps at all. (Issue #188 is not solving it so please don't say that this is a dupe of that.)
[log(1.0.0.8).txt](https://github.com/SubnauticaNitrox/Nitrox/files/2705476/log.1.0.0.8.txt)
![image](https://user-images.githubusercontent.com/45972570/50377912-448b1400-0626-11e9-85e3-82837f289275.png)
![image](https://user-images.githubusercontent.com/45972570/50377923-83b96500-0626-11e9-9aba-e5121ab32345.png)
![image](https://user-images.githubusercontent.com/45972570/50377925-90d65400-0626-11e9-9671-a8c0bdbb95a0.png)

**Comment by DukeVenator** [comment]
Have you tried reconnecting ?> I have noticed that solves the issue most of the time

**Comment by raffi00** [comment]
Same here,
1.0.0.8 version from Epic store,
No scrap metal, almost no fishes.
I tried mod version from nexus mod, and and also compiled one,
There are lines in output log that have a strange path, c:/Subnautica
When both DevVars.targets, and path.txt has a different value

[Nitrox] I: Behaviours applied.
FMOD Studio: Creating runtime system instance
(Filename: C:/Subnautica/plastic_workspace_unity/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
