### ISSUE TITLE
Game won't save sea bases. (patch 1.0.0.8)

### ISSUE THREAD

**Issue by Goyoong** [SubnauticaNitrox/Nitrox#468]
I was able to make sea bases on patch 1.0.0.5. But since the new patch, making bases won't save after coming back to the server.

**Comment by DukeVenator** [comment]
Odd my servers are working fine? 
Does the server have write permissions and did you follow these steps in updating
https://nitrox.fandom.com/wiki/Updating_Nitrox

**Comment by Goyoong** [comment]
I did follow steps. I had a work around it. I just downgraded to 1.0.0.5 version.

**Comment by Aocxiez** [comment]
Same here, Sea base are saved but after re-joined, Sea base back to old state. We tried de-contructed some unwanted base. Deconstruction act are not synchronized. After many restart, Base keep loaded back to the first state. 

-De-Construction not syncing
-Base not properly saved

**Comment by RylenWolf** [comment]
@Aocxiez @Goyoong Seems that restarting the server fixes the problem. You can update to 1.0.0.8 and as long as you restart the server it should fix your sea base.

**Comment by Aocxiez** [comment]
@goyoong Thank for your hardwork.
Base and window de-construct still not sync. Only interrior are sync (Construct and Deconstuct)

**Comment by Goyoong** [comment]
@Aocxiez  Indeed de-construction does not sync. 1.0.0.8 does save building for me now, tho I had it built first at 1.0.0.5 and just built more on the latest patch. I also noticed some few bugs regarding interior pieces.

>Placed wall mounted interiors (wall lockers, radio, chargers, & medkit frabricator) on top of reinforcements does no get saved.
>Bioreactors are hella buggy so I don't use it.
>Scanner room upgrades disappear if not removed before quitting. (I built a wall locker beside the fabricator to keep it)

And in general when building, best not to make a mistake since deconstructing does not fully save everything. Also seamoth upgrades don't get saved.
