### ISSUE TITLE
Setup Wizard ended prematurely because of an error.

### ISSUE THREAD

**Issue by Poolitzer** [SubnauticaNitrox/Nitrox#469]
The installer fails with the error above. I use an Windows 10 PC, I don't change the install folder.

I enabled logging, as explained [here](https://support.microsoft.com/en-us/help/223300/how-to-enable-windows-installer-logging).

[MSI1e1d7.LOG](https://github.com/SubnauticaNitrox/Nitrox/files/2705577/MSI1e1d7.LOG)

(Pasted here as well, I didn't upload a virus :) https://pastebin.com/wuT0AhcL)
Probably related to #447

**Comment by horrorkevin** [comment]
You have to install it into the Subnautica Folder.

**Comment by Poolitzer** [comment]
Thank you, sounded good, still get the same error though.

It is installed on my second drive, D:\Spiele\Subnautica. May this cause a problem?

[MSI4bddc.LOG](https://github.com/SubnauticaNitrox/Nitrox/files/2705597/MSI4bddc.LOG)

**Comment by Aphermion** [comment]
`MSI (c) (D0:90) [23:53:59:695]: PROPERTY CHANGE: Modifying SubServer property. Its current value is 'C:\Program Files\Nitrox Installer\SubServer\'. Its new value: 'D:\Spiele\Subnautica\Subnautica_Data\SubServer\'.`

 and

`MSI (s) (18:80) [23:54:03:134]: PROPERTY CHANGE: Adding INSTALLFOLDER property. Its value is 'D:\Spiele\Subnautica\Subnautica_Data\'.`

That can't work. Still the wrong folder. Has to be in the Subnautica root folder, not in Subnautica_Data.

**Comment by RylenWolf** [comment]
You have to double click D:\, double click Spiele, and double click Subnautica and then choose the Select Folder button.

**Comment by Poolitzer** [comment]
@Aphermion newest one from nexusmod, so NitroxInstaller-1.0.0.8

**Comment by Poolitzer** [comment]
![image](https://user-images.githubusercontent.com/25934244/50459004-b71e2b80-0967-11e9-927e-8985f6218112.png)
@RylenWolf Im quite sure my double click are correect, it still fails though.

happy to assist further :)

**Comment by alexanderheuts** [comment]
Fixed with PR #522
