### ISSUE TITLE
A few Bugs i found.

### ISSUE THREAD

**Issue by horrorkevin** [SubnauticaNitrox/Nitrox#470]
(sorry for bad english im a german guy. )
1. Too many Fish and Fragment Spawns.
2. Acid Mushrooms are buggy. You cant store them(same for Batterys). And after rejoining the Server, every Acid Mushrooms is gone from the Inventory.
3. Crashfish=Stuck 
4. Every Rejoin=Reset Settings...
5. After leaving the Seabase and Server rejoin i am walking underwater.

**Comment by DukeVenator** [comment]
#442 
Noted but 1.0.0.8 appears to have fixed the spawn issue as long ass its a new world!

**Comment by DukeVenator** [comment]
Hmmm Seems to vary from person to person ATM

**Comment by Measurity** [comment]
We're closing list-issues because they often contain duplicate bugs that are already reported and make it hard for us to lock down on 1 issue at a time. Please create only 1 GitHub issue per bug and provide info on how/when the bug occurs, preferably with screenshots.
