### ISSUE TITLE
Loading music keeps playing after loading is done

### ISSUE THREAD

**Issue by ImTheSquid** [SubnauticaNitrox/Nitrox#472]
When joining a game, the loading/joining music keeps playing for a while after joining, sometimes having the in-game music overlap.

**Comment by AManNamedGaurav** [comment]
I'm having the exact same issue.

**Comment by Viceroyalty** [comment]
Having the same issue here as well

**Comment by LaikaIwanowa** [comment]
Visit another biom than the one you are in. That should fix it.
