### ISSUE TITLE
[1.0.0.8] Lifepod doesn't save state

### ISSUE THREAD

**Issue by KillerOfPie** [SubnauticaNitrox/Nitrox#473]
The interior of the life pod does not seem to save its state. After emptying the contents of it storage(or placing things into it) as soon as I log out and log back in its in the state it was when the server started. including the fire extinguisher on the ground, the Med Kit Fab, and any fish that found there was inside.

**Comment by KillerOfPie** [comment]
Looks like base sections do the same thing as well, except you can make them but deconstructing them does not take effect after play disconnect/server restart.  

Also, you do actually receive the materials even though the structure/items are reset.

**Comment by RylenWolf** [comment]
Disconnecting and reconnecting seems to cause some problems.
For your second comment, currently I found that disconnecting (causing server to save) and then restarting the server seems to catch things up. Except the life pod.

**Comment by KillerOfPie** [comment]
@RylenWolf Unfortunately, that does not seem to do anything

**Comment by KillerOfPie** [comment]
Also second note i just remembered. When I were to deconstruct a base piece my brother-in-law would not see it deconstructed and would be able to do so separately.
