### ISSUE TITLE
Too many entities

### ISSUE THREAD

**Issue by PurpleKief** [SubnauticaNitrox/Nitrox#474]
Not sure if anyone else is experiencing this issue but there are way too many entities spawned.
The ground is filled with metal fragments, scannable objects and worst of all the world is absolutely filled with enemies and fish alike.

Going into the enemies that spawn out of nowhere territory is insane, about 50 of them will spawn in at the same time, at one point I had about 50 - 100 different entities on my screen that were hostile, I dropped down to 1 - 5 FPS and died. 

Nitrox version 1.0.0.7

**Comment by ZeTioZ** [comment]
Same here. I was swimming and suddently at 120m of deepth there was like 100 warpers... That scared me at the first time and it also lagged my game as well.
