### ISSUE TITLE
Friends can't connect to server

### ISSUE THREAD

**Issue by xTGXP** [SubnauticaNitrox/Nitrox#476]
I believe I have port forwarded properly and when my friends attempt to join they get the can't connect error. Am I doing something wrong?

**Comment by Aphermion** [comment]
So port 11000 in the router config, if it still doesn't work, you could restart the router, add a firewall exception for the same port and restart the computer. 
It could also be the case that something occupies that port, though I would have to wonder what it would be. Seems like some games use it, though I doubt you are running Phantasy Star Universe or Everquest Online Adventures at the same time as the Server. 
I think you can use _netstat -a -b_ in the Windows command line to look at which ports are being listened to.

**Comment by xTGXP** [comment]
Yeah i'm not running any of those games
I've port forwarded things in the past like Minecraft to get a server running but I seem to have the most trouble with this Mod.

**Comment by xTGXP** [comment]
C:\Users\Tygam\Documents\Lightshot\Screenshot_386.png

**Comment by xTGXP** [comment]
![screenshot_386](https://user-images.githubusercontent.com/46080256/50381453-a6af3d80-0655-11e9-8665-9f6341604950.png)

**Comment by Aphermion** [comment]
Yes that should be correct.  
You can try to run the server and do a port test.
https://www.yougetsignal.com/tools/open-ports/

So just enter your IP and the 11000 there, should tell you if it's open or not.

**Comment by RylenWolf** [comment]
Hello, when I had this problem I tried the server WPF version, and it worked for me.

**Comment by DukeVenator** [comment]
If issue is fixed @xTGXP please close it
