### ISSUE TITLE
Question about Nitrox

### ISSUE THREAD

**Issue by xkaczors** [SubnauticaNitrox/Nitrox#477]
Does anyone still have a problem with creatures that they still do not appear?

**Comment by tonydhx** [comment]
Do you mean an specific creature, or u mean all?

**Comment by xkaczors** [comment]
All except the Bladder

**Comment by tonydhx** [comment]
I used the latest version of subnautica yesterday with 2 friends and all creatures that i see spawn like in single player but in more amount, it may be a result of a corrupt installation or modified parameter on server settings, try reinstalling the game and mod, if u haven´t done it already.

**Comment by xkaczors** [comment]
I understand, I only have a problem with the Automatic instal, I get a type error
Setup wizard ended prematurely because of an error your system has not been modified

**Comment by Measurity** [comment]
A lot of changes have been made in the mean time.

I'll close this due to its age. Open a new issue referencing this one if it's not resolved yet and/or join our Nitrox Discord server.
