### ISSUE TITLE
MoonPool Un-Docking not sync.

### ISSUE THREAD

**Issue by Aocxiez** [SubnauticaNitrox/Nitrox#485]
When we docked our ship all players are seeing it(sync) But problem started when un-docking the ship. Only pilot seen it un-docked but another player not synchronized and saw the ship still docked in MoonPool. 

Thank you in advance. We’re really enjoying coop. We will buy this coop if it come out as expansion. Please keep up a good work.

**Comment by JelmarG** [comment]
Yes, very buggy for now. Have all other players also undock the ship, that seems to re-sync it eventually.

**Comment by Agent77326** [comment]
#118
