### ISSUE TITLE
Infinity multiplayer loading

### ISSUE THREAD

**Issue by kostantinos04** [SubnauticaNitrox/Nitrox#486]
Hello i have an issue.When i am trying to join to my frien's server it says "Loading multiplayer".i just left it for 1 hour and nothing.And i had this issue with all the versions and i don't know how to solve it.Can you help me?

**Comment by DukeVenator** [comment]
#442 please consuult this list
Did you construct a nuclear reactor or bio mass reactor?
What version?/

**Comment by kostantinos04** [comment]
I have tried to play with version 1.0.0.4 and 1.0.0.5 and 1.0.0.8 and i can't connect to the server.it says "loading multiplayer" forever and i don't know how to solve it.if you know please help me.

**Comment by kostantinos04** [comment]
And we haven't place any of this.tge server is new

**Comment by Charismara** [comment]
Are you using hamachi?
