### ISSUE TITLE
update cause world break(FIXED)

### ISSUE THREAD

**Issue by Tododas** [SubnauticaNitrox/Nitrox#488]
me and my friend were just playing and then we decided to update the game and the this happend,how can i fix this i cant get rid of the rooms or windows (Also if you could help with wiping a world or something that would be every help full 
![image](https://user-images.githubusercontent.com/46060698/50384927-4a224180-069a-11e9-8e1d-c33a2c968e52.png)

**Comment by xeon321** [comment]
nuclear and bioreactor are game breaking, don't use them

**Comment by Tododas** [comment]
but how do i get rid of that

**Comment by xeon321** [comment]
well.. you can't deconstruct anything as its not sync'ed atm. And in my case, after the server restart, the world file will be corrupted, so yeah... 

if you want to play on a new world, simply delete the save.nitrox (thats the world file) located in the directory where the NitroxServer.exe is located

**Comment by Tododas** [comment]
Thanks for the help

**Comment by xeon321** [comment]
welcome

**Comment by killzoms** [comment]
@Tododas If your issue is fixed please close this issue
