### ISSUE TITLE
Seamoth upgrades and customization disappear on server restart

### ISSUE THREAD

**Issue by JelmarG** [SubnauticaNitrox/Nitrox#489]
When a player upgrades or customizes their Seamoth, i.e. change the color, it seems to reset after server restart. Some upgrades seem to usually stay (depth module), other upgrades always disappear (like the storage upgrade). Color and name always disappear. This is probably related to other syncing issues, like #118 #422 and #485

I assume it is probably the same for the other vehicles, although I didn't test this.

**Comment by ASimpson87** [comment]
Fixed in #634
