### ISSUE TITLE
[1.0.0.8] The problem that is occurring

### ISSUE THREAD

**Issue by xkaczors** [SubnauticaNitrox/Nitrox#492]
There are still no schemes and monsters.

**Comment by DukeVenator** [comment]
Rejoiniing will fix this?

**Comment by kiyoshi-kurosaki** [comment]
Hello @xkaczors you can try to create SinglePlayer session, save and exit, then try to connect the multiplayer.

I hope that will fix it, otherwise, the server files cannot read properly.

Regards

**Comment by xtosutosu** [comment]
Same problem, did as you told @DukeVenator, no dice here.

**Comment by xkaczors** [comment]
I checked everything, the problem is still there
Any idea?

**Comment by alexanderheuts** [comment]
Temporary workaround: Join https://discord.gg/E8B4X9s (Fan community discord to help sort Nitrox issues). There's a pinned item containing a world-save with content.
