### ISSUE TITLE
Unable to remove or repair Nitrox

### ISSUE THREAD

**Issue by NikoZ121** [SubnauticaNitrox/Nitrox#493]
I cannot remove or repair Nitrox which is not even installed. After uninstalling subnautica to install it in another disk Nitrox installer shows that Nitrox is installed but when I try to remove Nitrox using installer to install it again on different disk I get same thing, Nitrox still is installed and repair does nothing too. Simply Nitrox installer doesnt work as it should.

**Comment by crazyfrog151** [comment]
same here, really would like to know how to fix this

**Comment by leginhee** [comment]
try to remove the SubServer folder in subnautica directory

**Comment by crazyfrog151** [comment]
didnt work

**Comment by leginhee** [comment]
Go to your Programms (Apps and Features in search) and Install nitrox.

**Comment by crazyfrog151** [comment]
this way doesn't work either

**Comment by crazyfrog151** [comment]
i can not think of anything else to do, to remove this so i may reinstall it into the correct folder, I've tried deleting everything i know to be related to nitrox, and still every time i try and use the install i get the, please repair or remove, and witch both do nothing what so ever,

**Comment by UpcraftLP** [comment]
might be some registry entry telling it that it has been installed already? 🤔

**Comment by Krum3L** [comment]
> I was able to get this off my computer using iobit uninstalled here https://www.iobit.com/en/index.php?from=mobile for some reason windows can’t remove it by itself.

I was able to uninstall it like this, but the Nitrox launcher still says that i can only repair/uninstall it.

**Comment by Ghostgamer17** [comment]
to everyone stuggling with the same issue i did use this https://www.revouninstaller.com/revo_uninstaller_free_download.html
 download the trial of the pro version then uninstall nitrox 1.0.0.8 and reboot the pc before trying the latest installer once more
it worked for me and should work for you as well

**Comment by 0lm** [comment]
cant uninstall it either. revo uninstaller cant uninstall it either. any other tips anyone`?

**Comment by Ghostgamer17** [comment]
> revo uninstaller worked for me now.
> i found out the problem though. if you uninstall subnautica or delete the subnautica game folder (for example if you made a 2nd copy of it to test nitrox, and dont want it anymore and delete that 2nd copy) without uninstalling nitrox before, the uninstalling wll not work because the game folder where it was installed is missing now.
> yeah thats bad made in the installer, if you ask me. revo uninstaller tracks all remaining nitrox stuff, for example registry entries. and you can choose to delete it. that way nitrox will be completely wiped from your computer as if it was never installed.

that is how i finally got it off my pc
