### ISSUE TITLE
¿is possible to run a server-only subnautica server?

### ISSUE THREAD

**Issue by rlunaro** [SubnauticaNitrox/Nitrox#495]
I was wondering if it is possible to run a internet hosted server to hold a subnautica server. 

Do you have some sort of software to install in a server and to have a public subnautica server?

**Comment by ZeTioZ** [comment]
You actually can do that. You just need to open your ports in your modem and then give to all your public ip so they will be able to connect to your server from anywhere.

**Comment by JelmarG** [comment]
Yes, but the game does have to be installed (maybe it can be done differently, but it seems the server needs to have access to the game's assets).

**Comment by rlunaro** [comment]
No, this is  not exactly what I mean. I meant to use a third computer as the server.
Enviado desde la cafetera 
 
  El lun., dic. 24, 2018 a 13:03, ZeTioZ<notifications@github.com> escribió:   
You actually can do that. You just need to open your ports in your modem and then give to all your public ip so they will be able to connect to your server from anywhere.

**Comment by Measurity** [comment]
If the third computer has Subnautica you can host the server. Nitrox Server is not stand alone at the moment.

**Comment by rlunaro** [comment]
Ok, I will try it this way.

**Comment by DKingCN** [comment]
@rlunaro 
https://nitrox.fandom.com/wiki/Nitrox_on_Linux

I made a [video](https://www.youtube.com/watch?v=gvTYUUGdxPg&t=43s) about it

**Comment by rlunaro** [comment]
thanks!!!

    El miércoles, 30 de enero de 2019 11:21:00 a. m. GMT+1, DKing <notifications@github.com> escribió:  
 
 
@rlunaro
https://nitrox.fandom.com/wiki/Nitrox_on_Linux

I made a video about it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
   
 
|  | Libre de virus. www.avast.com  |
