### ISSUE TITLE
ipv6 support 

### ISSUE THREAD

**Issue by baayal** [SubnauticaNitrox/Nitrox#496]
its not possible to connect to the server via ipv6. Not even talking about a public connection, because local connection doesnt work either via ipv6. Would be very nice if ipv6 were possible because many people have fully working ipv6 connections

**Comment by Agent77326** [comment]
Nitrox is using lidgreen to handle to connection stuff, but there should be a ipv6 Support build in which is working already since almost 3 years... I believe your problem is lying somewhere else, I could not reproduce your problem with my ipv6 adress.
