### ISSUE TITLE
Aurora keeps exploding

### ISSUE THREAD

**Issue by RylenWolf** [SubnauticaNitrox/Nitrox#499]
Version 1.0.0.8 Nexusmods

The first time I played, we fixed the aurora (after explosion) and saved the game. On restart, it eventually explodes again at random.

Even if I repair the aurora with the console command, it keeps exploding once every restart (I'm fairly certain it's the same timer that it usually goes on for a new game.. every two hours?)

I have not tried manually repairing before the explosion since the first time (Which was done after the initial explosion) so there is room to test to see if an immediate teleport and manual repair with the tool will stop this behaviour, but it should have just saved the manual repairs from the first save, so I figured I would report this here anyways.

I will test another time if teleport+manual repair before explosion stops this and update with a comment.

**Comment by Agent77326** [comment]
Even so, can reproduce multiple Aurora expolsions when server is restarted.

**Comment by Coding-Hen** [comment]
@Measurity This can be closed
