### ISSUE TITLE
Inventories dont save 1.0.0.8

### ISSUE THREAD

**Issue by GitHubGui845** [SubnauticaNitrox/Nitrox#500]
Player inventories get saved, but everything else in world is being reset upon rejoining.
Also, dropping things in the world will not make the other person see it.
World Inventories arent being synced to the server either, and seem to be clientside
Version 1.0.0.8

**Comment by RylenWolf** [comment]
Have you tried base building storage?

There is currently a problem with only Lifepod 5 and Deployable Storage resetting every time that devs already know about.

**Comment by hagwart2** [comment]
havent gotten to it yet

**Comment by hagwart2** [comment]
Base storage is working perfectly, but there are upgrades for scanners that will not save, and the locker names wont save either

**Comment by Measurity** [comment]
This issue is too broad and doesn't contain reproducable steps. Inventory sync issues are being tracked here: #1003

We know of these issues already and are working on improving the client-server sync of item containers.
