### ISSUE TITLE
How to reset save?

### ISSUE THREAD

**Issue by beansrreal** [SubnauticaNitrox/Nitrox#502]

**Comment by zheka-100500** [comment]
Delete the file in the server folder save.nitrox

**Comment by beansrreal** [comment]
> Delete the file in the server folder save.nitrox

Thanks

**Comment by Daxter09042010** [comment]
> Delete the file in the server folder save.nitrox

where is the save.nitrox forlder like where do I get it

**Comment by RivalsRebels** [comment]
The Nitrox folder where nitroxlauncher.exe is. Also, keep in mind to not use issues for support. Please use the Discord Server from now on.

**Comment by Daxter09042010** [comment]
ok ty
