### ISSUE TITLE
I can't share items with my friend

### ISSUE THREAD

**Issue by Kutiyka** [SubnauticaNitrox/Nitrox#505]
I dont know how to share items with my friend.I tried to drop them,place in the base locker,i placed waterproof locker but my friend cant see any of my items.

**Comment by Dealymaniac** [comment]
I see, that happens to me too, but did you build an underwater base yet? those locker that you can make with habitat builder are able to share item, i share item with my friends from there

**Comment by Kutiyka** [comment]
> 
> 
> I see, that happens to me too, but did you build an underwater base yet? those locker that you can make with habitat builder are able to share item, i share item with my friends from there

No,i will try with builded chest,thanks.
