### ISSUE TITLE
Everything is still spawning like 10x

### ISSUE THREAD

**Issue by Krum3L** [SubnauticaNitrox/Nitrox#506]
Hello,
I still have the issue that there are like 10x the amout of fish, gaspods, leviathans etc. still not fixed?
I also always get the same spawn with like 40 time capsules below the base.
Any fix for that?

**Comment by Rauca** [comment]
> This savegame should help everyone with this problem!
> 
> [save.zip](https://github.com/SubnauticaNitrox/Nitrox/files/2708743/save.zip)

Savefile (ZIP) is broken.

**Comment by Agent77326** [comment]
Already duplicate in #352
