### ISSUE TITLE
FAST PLZ! 

### ISSUE THREAD

**Issue by ErrorMyLife** [SubnauticaNitrox/Nitrox#508]
Why resources not spawning? Help plz?

**Comment by leginhee** [comment]
try to reinstall

**Comment by ErrorMyLife** [comment]
this not fixed my problem

**Comment by kuzkuv** [comment]
i have same problem 
how to fix this?

**Comment by ErrorMyLife** [comment]
i don't know :(

**Comment by alexanderheuts** [comment]
Spawning is still not perfect. Delete your world in the server folder. It's a file called save.nitrox. Shut down your server prior to deleting the file.

**Comment by ErrorMyLife** [comment]
i don't have this file i the server folder
