### ISSUE TITLE
Nitrox Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by KILLERMANTV** [SubnauticaNitrox/Nitrox#513]
Hello,
3 days ago i tried to install nitrox into steam installation of subnautica, it didn't work, today i tried to install nitrox into epic games clean installation of subnautica, that didn't work too..

Here's the log: https://pastebin.com/LuVj4CYM

**Comment by TmPatrick** [comment]
same

**Comment by TmPatrick** [comment]
found something that worked for me try extracting it then install worked for me

**Comment by KILLERMANTV** [comment]
Nope, still same error

**Comment by Poolitzer** [comment]
may I point you to #469?

**Comment by KILLERMANTV** [comment]
> may I point you to #469?

I already saw this

**Comment by Poolitzer** [comment]
nope. you have the same problem. On GitHub, you don't open a new issue for the same problem :)

**Comment by KILLERMANTV** [comment]
> nope. you have the same problem. On GitHub, you don't open a new issue for the same problem :)

Did they solve the problem? No. Is anyone caring about the crucial part of this mod about installer? No.

**Comment by alexanderheuts** [comment]
There is a possible fix available using branch in pull request #522

**Comment by Poolitzer** [comment]
Oh man. Just gonna close my issue then if you even made a PR to this one, pfff.

I'd have to built it for myself though...

**Comment by alexanderheuts** [comment]
We have a build for it on https://discord.gg/E8B4X9s
