### ISSUE TITLE
Unable to contact remote server

### ISSUE THREAD

**Issue by sneakyfox94** [SubnauticaNitrox/Nitrox#514]
Hi I have installed the latest version to date of this mod however i keep getting the message above, every time i try to connect to the local server, i have hamachi, my firewall has allowed access, i have tried turning off my firewall and anti virus but still nothing. I am grateful for any help

**Comment by zheka-100500** [comment]
Check if you have a Hamachi network in your network connections. If do not, disable digital driver signature verification on your system, uninstall hamachi and download an old version. This is provided that you have the firewall turned off.

**Comment by xeon321** [comment]
shouldn't have to do this but sometimes I find adding the port number 11000 behind the IP helps
(eg: 192.168.1.123:11000)

**Comment by sneakyfox94** [comment]
I have tried both of those ideas and neither work

**Comment by Phsiic** [comment]
I also have this issue as well. I have Xfinity but I doubt this is the issue.
