### ISSUE TITLE
Missing ores/resources & dropped items

### ISSUE THREAD

**Issue by MrLetsplay2003** [SubnauticaNitrox/Nitrox#515]
So we set up a server with the newest build (from 3 days ago) today, but while playing we noticed that
- for one of us (not me, the host, in this case) the ores (like sandstone/limestone etc.) don't spawn (but mushrooms/corals do). They seem to spawn/be loaded when joining the server though (at least in the spawn chunks)
- when one of us (my friend, connected remotely, in this case) drops an item it doesn't appear for me.
- my friend's items always disappear (but only the hotbar and equipped items for some reason)
(I'm hosting the server locally and my friend is connecting via Hamachi)

**Comment by Agent77326** [comment]
#280 #528

**Comment by Measurity** [comment]
We're closing list-issues because they often contain duplicate issues that make it hard for us to track one bug at a time. Please make new issues if you found bugs that haven't been reported yet.
