### ISSUE TITLE
Base Sync Error

### ISSUE THREAD

**Issue by BeamPoints** [SubnauticaNitrox/Nitrox#516]
if the base gets bigger and there are 2 players on it, the base can not be synced anymore.

i tryed to fix it with a bigger buffer but it dosent work. 
:( 

> [Nitrox] Log level set to ConsoleInfo, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] D: Event Triggerer started!
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: If playing on LAN, use this IP: 192.168.178.85
[Nitrox] I: Nitrox Server Started
[Nitrox] I: If using port forwarding, use this IP:
[Nitrox] I: Networking: Socket bound to 0.0.0.0:11000: True
[Nitrox] I: Networking: Network thread started
[Nitrox] I: Identifier 8783587628938579450 RespondedConnect: Remotely requested connect
[Nitrox] I: Identifier 8783587628938579450 Connected: Connected to FA4D663C6992E579
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.ColorSurrogate for type UnityEngine.Color
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.Int3Surrogate for type Int3
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.QuaternionSurrogate for type UnityEngine.Quaternion
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.TechTypeSurrogate for type TechType
[Nitrox] D: Added surrogate NitroxModel.DataStructures.Surrogates.Vector3Surrogate for type UnityEngine.Vector3
[Nitrox] I: Providing session policies...
[Nitrox] I: Networking: Initiated average roundtrip time to 27,39 ms Remote time is: 0,22443838849685
[Nitrox] I: Processing reservation request...
[Nitrox] I: Reservation processed successfully: ReservationState: Reserved - ReservationKey: 220ad25c-74e1-4117-9b58-6ec6a20aa6d9...
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] D: Using default packet processor for: [Pickup Item - ItemPosition: (0,0, 0,0, 0,0) Guid: 6a7cadb6-60b0-4b87-8aed-34ad5d668bcb TechType: Titanium] and player 1
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional<System.String>.Empty()]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional<System.String>.Empty()]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional<System.String>.Empty()]
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional<System.String>.Empty()]
[Nitrox] D: Using default packet processor for: [DroppedItem - guid: 32a8c0dd-fe6b-44e1-921a-d788d80d193c WaterParkGuid: Optional<System.String>.Empty() techType: Titanium itemPosition: (-269,7, -59,7, -381,8)] and player 1
[Nitrox] I: [SubRootChanged - PlayerId: 1 SubRootGuid: Optional[69e54224-d333-47b9-8409-cec2001e37a1]]
[Nitrox] I: Saving world state.
[Nitrox] D: Using default packet processor for: [Pickup Item - ItemPosition: (0,0, 0,0, 0,0) Guid: e93cfc2b-0c2c-44d7-841c-33433a126924 TechType: Titanium] and player 1
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Identifier -1589821189277849844 RespondedConnect: Remotely requested connect
[Nitrox] I: Identifier -1589821189277849844 Connected: Connected to 0C67B4340DD2EFE9
[Nitrox] I: Providing session policies...
[Nitrox] I: Networking: Initiated average roundtrip time to 31,89 ms Remote time is: 0,175774655004375
[Nitrox] I: Processing reservation request...
[Nitrox] I: Reservation processed successfully: ReservationState: Reserved - ReservationKey: 6d922fea-fe17-4af4-b7ba-d33edf347637...
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Networking: Socket threw exception; would block - send buffer full? Increase in NetPeerConfiguration
[Nitrox] I: Identifier 8783587628938579450 Disconnected:
[Nitrox] I: Player Fally can take over 55e8849d-b847-4cbd-83ef-c12787e0f0a3
[Nitrox] I: World state saved.

**Comment by xeon321** [comment]
for me, having 1 player do all the constructions and no deconstructions (for base pieces) helps, if other players still cannot see the constructions, try restarting the server.

**Comment by BeamPoints** [comment]
this is not the problem. The Problem is the sync while 2 or more player in game the network sendbuffer is full. And does not Sync the bases.
