### ISSUE TITLE
items disappearing

### ISSUE THREAD

**Issue by toguno** [SubnauticaNitrox/Nitrox#518]
on my server my friends inventory keeps on wiping randomly as he is swimming. He is not dying, nor doing anything specific to trigger this. He said it only effected crafted items, not raw resource. He said this has occured multiple times. anything he should do to fix this? He restarted his game once in attempt to resolve the issue.

**Comment by Agent77326** [comment]
#280 #528

**Comment by Measurity** [comment]
This issue is being tracked here: #1003
