### ISSUE TITLE
lagg with more than 3 people

### ISSUE THREAD

**Issue by toguno** [SubnauticaNitrox/Nitrox#526]
The game becomes unplayable with more than 3 people due to extreme desync. The Operating System on the host computer only reports 50% cpu usage and 30% ram usage at the time of the lagg.

The most notable effect of the lagg was that players were unable to enter sea moths, and were in complete desync with other players. We experimented and one players actions were performed over one minute earlier than telegraphed/transmitted to other players.

**Comment by Xavernus2nd** [comment]
Same here. Even with just 3 players the amount of desync is hugely appearant.
