### ISSUE TITLE
resources disappearing

### ISSUE THREAD

**Issue by DocPineapple33** [SubnauticaNitrox/Nitrox#532]
after logging in our resources from teh day before have disappeared from our inventory and chests. fix?

**Comment by Agent77326** [comment]
Use the locker in your base to store items. You have to consider that this mod is still in the early alpha and has a a lot of bugs, so expect some to be there for a longer while.

**Comment by Kurgol** [comment]
I just put the contents of my inventory into the storage locker in the starting escape pod and then relogged and it only has the default biscuits, water and flares in it now.

**Comment by Measurity** [comment]
This issue is tracked here: #1003
