### ISSUE TITLE
Beacon bug?

### ISSUE THREAD

**Issue by Vallith** [SubnauticaNitrox/Nitrox#533]
Yesterday me and my friend started playing and all was good. Today we opened the server up and all of our mission beacons (lifepods) are just... gone.

**Comment by Agent77326** [comment]
It‘s a known issue that the story-play itself is conpletly a mess (progress won‘t be saved either), every time you start there is the Tipp to destroy the rock etc.

**Comment by danieltan** [comment]
Great work with this mod! My wife and I are playing it (after I finished the game single player) and we really love it. 

This beacon bug is a big one! Firstly when ever you quit you loose the mission beacons. In addition, any label you put for beacons or boxes get lost. 

Tips to destroy rocks I can live with. Its not like you've lost your blueprints or anything. But loosing critical mission locations is a showstopper for us.

**Comment by 0verdark** [comment]
@Vallith The issue has been resolved. You can download the latest **Nitrox Launcher** version which is: **v1.2.2.0** from the **Official Website** or from **Nexus Mods.** You're Welcome!
