### ISSUE TITLE
Game crashes on start

### ISSUE THREAD

**Issue by ragzda** [SubnauticaNitrox/Nitrox#535]
Bought the game months ago, played it a bit got bored, deleted for space.
Now heard of Nitrox and wanted to do multiplayer with my friends.
Installed Nitrox and dropped it in files before launching...
Now here is the output and error log. 
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2714356/output_log.txt)
[error.log](https://github.com/SubnauticaNitrox/Nitrox/files/2714357/error.log)

If someone could identify the issue and show me a way to fix it I would appreciate it.

~ Landon

**Comment by alexanderheuts** [comment]
@ragzda does this still exist with the latest version?
