### ISSUE TITLE
Spawning in double of landmarks

### ISSUE THREAD

**Issue by WonkaOh** [SubnauticaNitrox/Nitrox#536]
Major lag around island, aurora, alien bases, and lost river. We have found that the Aurora is spawned in twice when two players are connected, so are the alien bases and islands. Parts of the lost river are as well like the big skeletons and this causes major lag spikes for the players.

**Comment by stanneman99** [comment]
Can confirm, i also got major lag spikes when entering the Aurora. Also couldnt open some keypads as they were also spawned in twice.

**Comment by Agent77326** [comment]
#503
