### ISSUE TITLE
Vehicles exploding randomly, solved why

### ISSUE THREAD

**Issue by WonkaOh** [SubnauticaNitrox/Nitrox#537]
The vehicle is rendered in 2 times, one for the owner and one for the other player. The vehicle you are driving is also delayed for the non-owner of the vehicle and since that is, he sees the vehicle hitting unnecessary debris and it causes damage to his render of that vehicle. If he doesn't repair his render of YOUR vehicle, your vehicle will explode when it runs out of health on his render.

**Comment by Agent77326** [comment]
No it‘s not synched, at the moment it‘s like two independent simulations of the vehicle.

**Comment by Agent77326** [comment]
Dunno if this belongs really there, but: #118
