### ISSUE TITLE
Save Server.

### ISSUE THREAD

**Issue by ChicoPanda1999** [SubnauticaNitrox/Nitrox#540]
Can you save objects and structures in nitrox server?
How do I store the server?

**Comment by ChicoPanda1999** [comment]
Structures, ticket office and others

**Comment by flippo007** [comment]
I think **that's normal**.

**Comment by Agent77326** [comment]
Well.... they actually should be stored. (state of Aurora excepted, is currently messy)

**Comment by cher123** [comment]
Your computer will blow up, dude!

**Comment by flippo007** [comment]
> Your computer will blow up, dude!

xDD

**Comment by Coding-Hen** [comment]
@Measurity this can probably be closed
