### ISSUE TITLE
Acid Mushroom GUID Lookup Exception

### ISSUE THREAD

**Issue by Foltik** [SubnauticaNitrox/Nitrox#545]
### Description
When a single client is connected to the server, acid mushrooms can be added and removed from lockers properly. When a second client joins, however, all acid mushrooms are removed from all storage, and adding an acid mushroom to a storage results in it disappearing.

### Steps to Reproduce
1. Start a server
2. Have Player 1 join the server and create a habitat with a locker inside
3. Have Player 1 insert an acid mushroom into the locker
4. Have Player 2 join

The acid mushroom will disappear from the locker, and any mushrooms that are added after will also disappear.

### Reason for Removal from Storage
I added some logging in `NitroxServer/ItemContainer{Add,Remove}PacketProcessor.cs`, and get the following when acid mushrooms disappear:
```
[Nitrox] I: REMOVE PACKET: 0dcc1705-04ea-4f01-b8f3-9718bf6778e5 FROM: Gray
[Nitrox] I: ADD PACKET: [ItemData ContainerGuid: 5ddfbec7-4fa0-4dd5-9fd0-f6ce86d8f3ea Guid: 0dcc1705-04ea-4f01-b8f3-9718bf6778e5] FROM: Gray
[Nitrox] I: REMOVE PACKET: 0dcc1705-04ea-4f01-b8f3-9718bf6778e5 FROM: Jack
```
The first player, Gray, removes the acid mushroom from his inventory and adds it to a locker. Immediately after, the second player, Jack, sends the server a remove packet. This happens without input from the player.

### Cause
When the second client receives the add packet, the following exception is triggered:
```
Error: GetTransformById could not find '8ddb83df-7684-446c-b612-27d7ecf2a719' among 1836 ids

UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception, Object)
UWE.Utils:LogReport(String, Object)
UWE.Utils:LogReportFormat(Object, String, Object[])
UWE.Utils:LogReportFormat(String, Object[])
ProtobufSerializer:GetTransformById(String)
ProtobufSerializer:DeserializeIntoGameObject_Patch1(Object, Stream, GameObjectData, UniqueIdentifier, Boolean, Boolean, Transform, Int32)
<DeserializeObjectsAsync>c__Iterator3:MoveNext()
CoroutineTask`1:MoveNext()
SystemExtensions:SafeMoveNext(IEnumerator)
UWE.CoroutineUtils:PumpCoroutine(IEnumerator)
ProtobufSerializerExtensions:DeserializeObjectTree(ProtobufSerializer, Stream, Int32)
NitroxClient.GameLogic.Helper.SerializationHelper:GetGameObject(Byte[])
NitroxClient.GameLogic.ItemContainers:AddItem(ItemData)
NitroxClient.Communication.Packets.Processors.ItemContainerAddProcessor:Process(ItemContainerAdd)
NitroxClient.Communication.Packets.Processors.Abstract.ClientPacketProcessor`1:ProcessPacket(Packet, IProcessorContext)
NitroxClient.MonoBehaviours.Multiplayer:ProcessPackets()
NitroxClient.MonoBehaviours.Multiplayer:Update()
```
Note that the GUID that reportedly could not be found is not the same as the item GUID in the add packet. I believe this is what causes the remove packet to be sent to the server.

**Comment by Agent77326** [comment]
#442

**Comment by bannmann** [comment]
@PurpleTentacle81 and I can reproduce the vanishing mushrooms (actually, it's even easier than @Foltik describes) and want to share some information that may prove useful.

---

### Scenario 1 - Steps to Reproduce

1. Start a blank server (no `save.nitrox`)
2. Have Player 1 join the server and perform the following actions:
    1. swim to a group of mushrooms
    2. swim away far enough so that these mushrooms are no longer in sight
    3. swim back

Result: all mushrooms that were on screen during steps 1-3 are gone. Mushrooms elsewhere are still present until you swim away from them.

Note that any mushrooms you plucked remain in your inventory in any case (i.e. regardless of Player 2 joining, vanishing mushrooms on seafloor, putting any mushrooms in escape pod storage).

We reproduced this with 1.0.0.9 and with 9a9c0afb4b2bcede3d50539ab143d5c6197d5e64 from PR #561, so it should be reproducible on any recent `master` build.

---

### Scenario 2 - Steps to Reproduce

Note: this scenario requires 9a9c0afb4b2bcede3d50539ab143d5c6197d5e64 from PR #561.

1. Start a blank server (no `save.nitrox`)
2. Have Player 1 join the server and perform the following actions:
    1. pluck several mushrooms
    2. put one of them into the escape pod storage
3. Have Player 2 join the server
4. Have both players open the escape pod storage. The mushroom is gone.
5. Have Player 1 put another mushroom into escape pod storage. For a split second, it appears there, then vanishes.

**Comment by quimnuss** [comment]
I can confirm bannmann's Scenario 1 and that it spits `Entity was already spawned but not found(is it in another chunk?)` error on output_log.txt
