### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by NACH0CHEE5E** [SubnauticaNitrox/Nitrox#547]
i started up the server made the local thing with the local ip that my pc has, i then connected loading in fine i then found that i could not break open a limestone chunk thing, i then picked up two acid mushrooms and didnt get the prompt that they went in my inventory. i then pressed tab for the pda and is was a blank screen and then when i clossed it and went into the life boat through the bottom i got stuck under neith it and didnt eneter but my o2 refilled

also what ports must be forwarded to make teh multiplay work :)

**Comment by NACH0CHEE5E** [comment]
well i did launch the server using the file in SubServer but after portforwding and trying the other nitrox server (the WPF) one it worked so i dunno, also how you save and quit the server?

**Comment by Fchen48** [comment]
WPF doesn't support command input, use instead NitroxServer.exe, with `save` you can perform a manual save and with `exit` you can exit the server the secure way.

**Comment by NACH0CHEE5E** [comment]
ah ok, one last thing is it a known issue that contaners do not get synced up or not, also sometimes i get infinite oxygen

**Comment by Agent77326** [comment]
Already known, see #290, for containers: use the lockers in the base, they are the most bugfree currently.

**Comment by NACH0CHEE5E** [comment]
ok thank you
