### ISSUE TITLE
Player spinning wot?

### ISSUE THREAD

**Issue by JackBank** [SubnauticaNitrox/Nitrox#548]
So I have no idea what creates this issue, but basically my friend and I connects just fine to a server - we load in and can see eachother, but the issue is that we can see eachother spin around and basically just fly away or swim away and really cant start playing.

**Comment by Measurity** [comment]
Gonna close this as changes are still being made to the synchronization of clients and server. When this issue crops up we'll be sure to notice it and fix it asap.
