### ISSUE TITLE
No creatures, still doesnt work

### ISSUE THREAD

**Issue by perpas11** [SubnauticaNitrox/Nitrox#549]
After downloading save.nitrox from pinned comment on discord still doesn't work. I tried reinstall multiplayer. For my friend Bread it works.

**Comment by perpas11** [comment]
Working only for host

**Comment by Tibnan** [comment]
We had everything, even the starting fragments (seaglide, mobile vehicle bay) but we missed those that were in the grassy plateaus (battery charger, bio reactor, seamoth fragments etc.) We had to cheat them :(
Still waiting for a fixed version!
