### ISSUE TITLE
Cant start a server 

### ISSUE THREAD

**Issue by GentiG69** [SubnauticaNitrox/Nitrox#550]
I cant start a server because it crashes my subnautica when it arrives at 3rd second of "Starting multiplayer". Can anyone help?

**Comment by flippo007** [comment]
Are you launching it as an **administrator** ? Otherwise check **your firewall**.

**Comment by GentiG69** [comment]
> Are you launching it as an **administrator** ? Otherwise check **your firewall**.

What should i check?

**Comment by flippo007** [comment]
**You need to check if your firewall is not blocking the program**
