### ISSUE TITLE
Problem with the installation of the mod/Problème concernant l'installation du mod (Nitrox Setup Wizard ended prematurely)

### ISSUE THREAD

**Issue by DrustinBelmont** [SubnauticaNitrox/Nitrox#551]
**=English=**

Hi, I have a problem with the installation of the mod on the easy version of Nitrox. I'll give you a short list of the actions already done

- Installation of the model on 29/12/18 ;
> The mod works correctly
> I host a game with a friend
> No errors found

- Evening of 29/12/18: I decide to uninstall the mod while waiting for future updates and uninstalling Subnautica for a perfect purge.

- Evening of 29/12/18: Reinstallation of Subnautica

- Day of 30/12/18: I finally decide to reinstall the mod by performing the installation as usual in the Subnautica file.

And the boom! 

![capture d ecran 57](https://user-images.githubusercontent.com/46268930/50551092-471be800-0c7c-11e9-8a21-accda2c4bce6.png)

Any ideas?
Thank you in advance :)

**=French=**

J'ai un problème avec l'installation du mod sur la version facile de Nitrox. Je vais vous donner une courte liste des actions déjà réalisées

Installation du modèle le 29/12/18 ;
Le mod fonctionne correctement
J'organise une partie avec un ami
Aucune erreur trouvée

Soirée du 29/12/18 : Je décide de désinstaller le mod en attendant les futures mises à jour et de désinstaller Subnautica pour une purge parfaite.

Soirée du 29/12/18 : Réinstallation de Subnautica

Jour du 30/12/18 : Je décide enfin de réinstaller le mod en effectuant l'installation comme d'habitude dans le fichier Subnautica.

Et le boum !

![capture d ecran 57](https://user-images.githubusercontent.com/46268930/50551129-ab3eac00-0c7c-11e9-9b6c-1e3007cdf03c.png)

Des idées ?
Merci d'avance :)

**Comment by flippo007** [comment]
**Coucou ! No more seriously.... I think you're not the only one with this problem....  Did you check your register? Because in my opinion this program is in the Windows registry :) !**

**Comment by Sunrunner37** [comment]
Have you tried the latest version (1.0.0.9)?  That should fix this error.

**Comment by alexanderheuts** [comment]
This is most likely a historical issue from using various versions of the installer, please join the Nitrox Discord (https://discord.gg/E8B4X9s) and ask for help. The issue itself is resolved, but you may be experiencing evolutionary issues.
