### ISSUE TITLE
Aggressive creatures are passive

### ISSUE THREAD

**Issue by Agent77326** [SubnauticaNitrox/Nitrox#554]
I haven't been able to find an issue so far, but many aggressive creatures do not attack or recognize the players at all. I can definetly confirm this for the [Warpers](http://subnautica.wikia.com/wiki/Warper) (I am infected, or not? is it synched? believe not) and [Cave Crawlers](http://subnautica.wikia.com/wiki/Cave_Crawler). I also get the feeling that the normal peacful small fishes do not swim away from you like they do normaly, but may be just my feeling.
This may be related to the known bug of #442 with:

> Exploding fish have a 80%ish percent chance of being stuck in their pods while the other 20% go after you and kill you just fine (terrifying)

So those exploding fishes do not see an player and keep in their nests.

I am going to be busy the next time, so can someone verify this and create a list of animals which do not seem to correctly recognize the player (or react)?

Possible reason for this and a lot of other related bugs is that the fauna is not synched between the players and as a result the animals are unable to look up the current position of the player(s) and react properly, while some events like with the [River Prowler](http://subnautica.wikia.com/wiki/River_Prowler) and [Gasopod](http://subnautica.wikia.com/wiki/Gasopod) (=the sea cow) are automatically triggered and do not require a tracking of the player (my suggestion).

**Comment by GuzioMG** [comment]
Wait... You should be happy of that. Nothing is attacking you. You can easily catch fish, because they aren't escaping. Just be happy!

**Comment by capSAR273** [comment]
But this isn't how the game is intended to act, which is why it is an issue.

**Comment by GuzioMG** [comment]
I know, but it was something like "quick way to deal with it until devs repair it". Imagine, that you can go next to reaper and don't get killed.
