### ISSUE TITLE
Version 1.0.1.0 Major desync issue.

### ISSUE THREAD

**Issue by Tibnan** [SubnauticaNitrox/Nitrox#568]
After we installed the newest version, (1.0.1.0) we noticed that the host has fish and everything spawning correctly, but when somebody joins the server, he don't get the fish data and because of that he sees a blank world. Also, the players (both of them) are spinning and on top of that, after a ~2 min play the client gets disconnected. (We use hamachi with the latest version.) (PS.: The life pod's supplies don't spawn at the start.) I wonder if this is because my friend has Nitrox incorrectly installed? (He had it installed before and when we wanted to uninstall it to install the newest, we noticed that it isn't visible as installed.)
[nitroxlog 2019-01-04(Host).txt](https://github.com/SubnauticaNitrox/Nitrox/files/2727098/nitroxlog.2019-01-04.Host.txt)
[nitroxlog_2019-01-04_2(Client).txt](https://github.com/SubnauticaNitrox/Nitrox/files/2727100/nitroxlog_2019-01-04_2.Client.txt)

EDIT: We further investigated the issue, and over LAN it works properly (except spinning). So it's hamachi's fault. Any info on how to fix it? Or an alternative can fix it? (Like Tunngle.)

EDIT #2: Because of the spinning bug, my brother's character model stuck in front of the fabricator and took the oxygen tank that I was crafting, BUT, he wasn't there meaning that he didn't pick it up. (Meaning that it lost forever.) Also, the character positions will stop syncing after like 2 mins of play. Making the game unplayable in multiplayer.

**Comment by GentiG69** [comment]
are u getting disconnected, did u fix that ?

**Comment by Tibnan** [comment]
> are u getting disconnected, did u fix that ?

What do you mean by it?
I get disconnected only when we play on Hamachi. Is it a server problem with Hamachi? Also on LAN I don't get disconnected but I have serious desync problems. (On LAN and on Hamachi too)

**Comment by GentiG69** [comment]
Well that was the question that i was asking, because i'm having same problem playing with a friend with Hamachi. He gets disconnected after like 2-3 minutes of playing ...

**Comment by Tibnan** [comment]
Well, I tried again playing on LAN (not on hamachi) and we played withouth any problems! Haven't tried on hamachi yet.

**Comment by Tibnan** [comment]
We tried again on hamachi after a PC restart, the bug still exists.

**Comment by alexanderheuts** [comment]
> Well, I tried again playing on LAN (not on hamachi) and we played withouth any problems! Haven't tried on hamachi yet. EDIT: I forgot to mention, that we did a PC restart both.

Considering it works when playing locally it is not a technical bug. Please join the Nitrox Discord (https://discord.gg/E8B4X9s)  and ask for help regarding setup there.
