### ISSUE TITLE
Infinity Multiplayer Loading

### ISSUE THREAD

**Issue by kostantinos04** [SubnauticaNitrox/Nitrox#576]
Hello i have tried to play with this mod for many version but all the time when i am trying to connect it says "Loading Multiplayer" forever.Can anyone help me?

**Comment by Sunrunner37** [comment]
Please paste your `Subnautica\Subnautica_Data\output_log.txt` and check your firewall settings

**Comment by kostantinos04** [comment]
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2729533/output_log.txt)
i have turn off my firewall

**Comment by iFrez** [comment]
kostantinos04, got same error. It may caused by server/client version mismatch. If you run server from separate folder make sure it also update to latest build.

**Comment by Charismara** [comment]
We have the same problem 😢
[ServerLog](https://pastebin.com/1HvsFgs3)
[Player2 (external) Log](https://pastebin.com/R98Z1jsS)
We use NetOverNet to join the Server.

**Comment by alexanderheuts** [comment]
@Charismara @kostantinos04 Please try the latest version (1.0.2.2). Ask for help on the Nitrox Discord (https://discord.gg/E8B4X9s). Your currently posted logs have no indication of technical problems. May be networking issues.

**Comment by ShadowSZ72** [comment]
I have a problem too "Loading Multiplayer" forever.

**Comment by Fx73** [comment]
I have the same problem
