### ISSUE TITLE
All scrapmetal uses model4 instead of using model1-4 (minor)

### ISSUE THREAD

**Issue by quimnuss** [SubnauticaNitrox/Nitrox#583]
Scrap metal has 4 models: http://subnautica.wikia.com/wiki/Metal_Salvage

Only one (model4) seems to be used in spawning. This probably extends to all entities were several models are available.

**Comment by Coding-Hen** [comment]
From checking with the single player this is the default behaviour of the spawn command when spawning scrap metal.
