### ISSUE TITLE
Server not accepting outside connections

### ISSUE THREAD

**Issue by gibarel1** [SubnauticaNitrox/Nitrox#584]
The server is not accepting connections through the port forwarded ip. ive checked the port forwarding from a minecraft server running in the same port and it works fine. but when i try it with nitrox it doesnt see the server. im using the latest version(Alpha-1.0.1.0-159) from nexusmod with the intaller, i have the steam version of the game, but also tried with tthe epic store version and got the same problem and im using www.canyouseeme.org to test the port. if anything else is needed please ask and i will provide.

Edit: Tried using hamachi wih a friend and also does not work.

**Comment by Chewbaka69** [comment]
Have you add ad execption to allow Subnautica in the firewall of Windows?
I already have the problem like this with some friend on hamachi, and it's the firewall of windows that block the connection, so we have disable the firewall xD

**Comment by garsia0** [comment]
Remeber you need nat udp port not tcp

**Comment by gibarel1** [comment]
> Remeber you need nat udp port not tcp

ive checked, the port was forwarded on both in the router, but only tcp on my firewall, i opened it on my firewall using udp i tried againg but no luck. still http://www.canyouseeme.org/ cant see me

some more info on what appears in the cmd prompt (IP address censored):

[Nitrox] Log level set to ConsoleInfo, FileLog, ConsoleDebug
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: Could not load world: System.IO.InvalidDataException: Persisted state is not valid
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] W: Couldn't load serializable attribute for Peeper version
[Nitrox] I: If playing on LAN, use this IP: 192.168.0.13
[Nitrox] I: Nitrox Server Started
[Nitrox] I: If using port forwarding, use this IP: xxx.xx.xxx.xxx
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.

**Comment by alexanderheuts** [comment]
As this is a usability issue, not a mod technical issue, please join the Nitrox discord (https://discord.gg/E8B4X9s) and ask for help.
