### ISSUE TITLE
Base does bot properly sync

### ISSUE THREAD

**Issue by Mrassassin** [SubnauticaNitrox/Nitrox#588]
After building a base (in the first picture), when I leave and rejoin some parts of the old base are put back into place (the second picture). It doesn't matter if I save in-game or through the server (not sure if there is a difference lol), if I re-log or completely restart the server, the base always ends up like the second picture. 
Also when I remove everything, I can still add new parts to the base and it will save those. Just doesn't remove those parts
![20190105234843_1](https://user-images.githubusercontent.com/3239947/50732331-feb26d80-1146-11e9-8dbf-e10ab2141082.jpg)
![20190105235147_1](https://user-images.githubusercontent.com/3239947/50732332-feb26d80-1146-11e9-9d62-1cb5d1c41501.jpg)

**Comment by silvervirus** [comment]
base deconstructing is bugged wait for the next update

**Comment by TheClockTwister** [comment]
At the current master state, deconstruction is always saved, if your base is build using [this ](https://github.com/SubnauticaNitrox/Nitrox/issues/1000#issuecomment-605371622) guide. This also avoids pieces only being partially constructed (except for hatches and windows, and the bio reactor)
