### ISSUE TITLE
Chat won't open (latest build as of 10/01/2019)

### ISSUE THREAD

**Issue by lewis2470** [SubnauticaNitrox/Nitrox#604]
The chat key still appears in the Keyboard section of the settings when opened, however when the chat key is pressed in-game nothing happens except your held item being changed to another item in the inventory.

This is with the steampowered version on Windows 10

**Comment by M3dicCookie** [comment]
If you dnspy wrong adding the nitroxpatcher.dll after  Awake will do this , you have to add it before Awake () .
