### ISSUE TITLE
Found some pretty annoying syncing problems

### ISSUE THREAD

**Issue by TheWarTank** [SubnauticaNitrox/Nitrox#609]
Me, and my friend found some pretty annoying bugs:
1. I can't see my friend's vehicle, neither my friend can see my vehicle, when i go in my vehicle, or my friend goes in hes vehicule we just see ourselves inmobile, nocliping and with no vehicle at all.
2. I would like to know how to save a world and not loose it every time there's an update or a patch.
3. The majority of the time, my game or my friend's game are not syncing properly; Mobile vehicle bay not syncing and players vehicle's not appearing and some other stuff.

Please fix this as soon as possible, these bugs are practically breaking the game!

**Comment by alexanderheuts** [comment]
We are aware of vehicle syncing issues related to docking/undocking. This is being investigated.

> I would like to know how to save a world and not loose it every time there's an update or a patch.

As this mod is still in early stages, breaking changes are expected. We try to minimize them, but they can't be avoided.

**Comment by Reaping666** [comment]
> As this mod is still in early stages, breaking changes are expected. We try to minimize them, but they can't be avoided.

I just checked out the source and removed the version check for the save game (we had a version 4 save). This loaded this save in save game version 5. For now I can see no problem at all.
So is there a specific reason why you increased the version number, but did not even try to load the old one? None of the null checks afterwards fails and in-game, everything looks normal to us.

**Comment by alexanderheuts** [comment]
Feel free to join us on Discord (https://discord.gg/E8B4X9s) to see if you can contribute. It allows for more of a discussion than here.

**Comment by TheWarTank** [comment]
> We are aware of vehicle syncing issues related to docking/undocking. This is being investigated.
I did not even dock/undock a vehicle and i still can not see my friend's vehicle, (neither him).

**Comment by alexanderheuts** [comment]
@TheWarTank Did you build the vehicle or spawn it?

**Comment by TheWarTank** [comment]
> @TheWarTank Did you build the vehicle or spawn it?

Tried to build it, in another game spawned it, yet, still the same.

**Comment by Reaping666** [comment]
> 
> 
> Feel free to join us on Discord (https://discord.gg/E8B4X9s) to see if you can contribute. It allows for more of a discussion than here.

I did. I'm Drommedhar on there. Feel free to write me somewhere

**Comment by TheWarTank** [comment]
Wait; if i had a previous version of Nitrox installed in Subnautica's folder, and installing the newest version in Subnautica's folder including the old Nitrox, breaks it?
