### ISSUE TITLE
Version 1.0.2.0 issues.

### ISSUE THREAD

**Issue by Tibnan** [SubnauticaNitrox/Nitrox#613]
After installing V. 1.0.2.0 clients still don't receive like any data (We are using hamachi) and players spinning (host too) horizontally and vertically in the same time, then gets disconnected. (the time the client can be on the server is like 2 minutes.)
Host log:
[nitroxlog 2019-01-12.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2752424/nitroxlog.2019-01-12.txt)
Client log:
[nitroxlog_2019-01-12.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2752425/nitroxlog_2019-01-12.txt)

**Comment by Felps9494** [comment]
The mushrooms continue to disappear from the scene after a few minutes playing.

**Comment by alexanderheuts** [comment]
@Tibnan your log is full of network exceptions. This means your Hamachi is not properly configured or just not working properly. Please join the Nitrox Discord (https://discord.gg/E8B4X9s) to ask for help on this.
