### ISSUE TITLE
Bio and nuclear reactor wont sync!

### ISSUE THREAD

**Issue by Cynical8701** [SubnauticaNitrox/Nitrox#619]
Me and a mate got stuck on power because none of the reactors sync with each other so we had to resort to solar power but when its night we cant do anything!

**Comment by Furuchiru** [comment]
https://nitrox.fandom.com/wiki/Features
"Warning
Do NOT store acid mushrooms in lockers of any kind, they break the game
Do NOT use Bio-Reactors or Nuclear Reactors, they break the game
ONLY use external power Solar/Thermal"

**Comment by Swiff4** [comment]
Is there currently any solution for the syncing e.g. of bio reactor? We are facing the same problem.

**Comment by Coding-Hen** [comment]
This is covered by #691
