### ISSUE TITLE
Server-spawned models at wrong size

### ISSUE THREAD

**Issue by quimnuss** [SubnauticaNitrox/Nitrox#621]
Just documenting for future reference.
Some of the hand-placed models are of the wrong size.

I've launched the singleplayer vs the multiplayer with client-spawning de-authorized (= blacklist everything) and done some screenshots. (Also very useful for the seeing the duplication bug)

![image](https://user-images.githubusercontent.com/4179721/51090910-7f92ea00-1783-11e9-8dd4-9d95a9c86cd4.png)

This is also very patent in the CargoBoxes that are supposed to block your way like:

![image](https://user-images.githubusercontent.com/4179721/51091035-157b4480-1785-11e9-88ed-9dbff133a962.png)

The best one to see the difference is the piece of fuselage is in the way at 988.1 10.0 -38.0

**Comment by anoviel** [comment]
same with plants on floating island, and giant floaters under this island

**Comment by anoviel** [comment]
same with plants on floating island, and giant floaters under this island
