### ISSUE TITLE
[Player] Clipping through objects like Bases, Terrain and Aurora on joining

### ISSUE THREAD

**Issue by ScriptedAnar** [SubnauticaNitrox/Nitrox#624]
![capture](https://user-images.githubusercontent.com/46358553/51205240-1b506180-190e-11e9-8bff-17dace6e69ea.PNG)
![capture2](https://user-images.githubusercontent.com/46358553/51205247-1f7c7f00-190e-11e9-90ef-0a8703602572.PNG)
When i leave the game in a precursor base and rejoin the player spawns before world loads and i spawn below the base/ground like the screenshots. Also when you rejoin if you have unlocked the doors they do not save like the screenshots.

**Comment by alexanderheuts** [comment]
Not yet implemented

**Comment by disseminate** [comment]
Not just precursor bases for me but I had this below-the-floor issue with the Aurora. A solution might be blocking movement until the world's loaded but that's just a shot in the dark

**Comment by NitroxPower** [comment]
Yes pretty much anything that doesnt have to do with terrain
