### ISSUE TITLE
[Vehicles] Saves

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#628]
Seamoth ExoSuit Cyclops Colors and Upgrade modules do not get saved when you rejoin the game(Upgrade Modules must be in the Vehicles in order to happen).

**Comment by alexanderheuts** [comment]
Colors are not implemented. (Enhancement)
Upgrade modules apparently are bugged.

**Comment by ASimpson87** [comment]
Fixed in #634

**Comment by NitroxPower** [comment]
The Color/Name now work properly.The only thing that remains is the Upgrade Modules to get Saved when they are in the vehicle so i can close this bug.

**Comment by NitroxPower** [comment]
I would also want to refer to this issue cause its actually true and its also really important #537

**Comment by alexanderheuts** [comment]
@NitroxPower I appreciate you mentioning it's fixed. Do keep in mind that we haven't released a new version yet, so it's _fixed_ code-wise only. :)

**Comment by NitroxPower** [comment]
When i color my Seamoth all players have to rejoin in order to see the color change but its fine this has been fixed and i can close this issue
