### ISSUE TITLE
Blueprints Progress Doesnt Get Saved

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#639]
This is hard to explain.When you find all the blueprints for something when you rejoin it gets saved. When you find some blueprints like the cyclops Hull which needs 3 parts to be scanned in order to get unlocked  if you find just 2 of them and you rejoin the game it doest save that. Last time i tested this it was version 1.0.1.0 but i havent seen in github to get fixed so not 100% sure if it still a bug.

**Comment by NitroxPower** [comment]
Yeap its still a bug and its annoying...

**Comment by Coding-Hen** [comment]
This bug is related to protobuf not supporting dictonarys with custom objects #832 I think we need to rethink how we approach these if we are to fix these issues.
`partiallyUnlockedByTechType = new Dictionary<TechTypeModel, PDAEntry>();`

**Comment by Coding-Hen** [comment]
Fixed #1023 @Measurity this can be closed
