### ISSUE TITLE
Trying to build the binaires dont work :(

### ISSUE THREAD

**Issue by snayzix** [SubnauticaNitrox/Nitrox#64]
After the gen Failed For 4 things 4 errors appear 
" Impossible d'utiliser le type 'NitroxModel.Packets.Packet' comme paramètre de type 'T' dans le type ou la méthode générique 'PriorityQueue<T>'. Il n'y a pas de conversion de référence implicite de 'NitroxModel.Packets.Packet' en 'IPriorityQueueItem'.	NitroxClient	C:\Users\snayzix\Desktop\Nitrox-master\NitroxClient\Communication\DeferringPacketReceiver.cs	16
"
and 

"Aucune surcharge pour la méthode 'Enqueue' n'accepte les arguments 2	NitroxClient	C:\Users\snayzix\Desktop\Nitrox-master\NitroxClient\Communication\DeferringPacketReceiver.cs	30	Actif
"

Both of theses error are in french :D 
See ya

**Comment by Mathboy19** [comment]
I'm having the same issue as well. It seems as though the class `PriorityQueue` (Defined in `Assembly-CSharp-firstpass.dll`) has changed. This breaks using `NitroxModel.Packets.Packet` as a parameter and also breaks the `Enqueue` method. It's possible we are using the wrong `firstpass.dll`

**Comment by Alberto247** [comment]
Just replace every PriorityQueue with NitroxModel.DataStructures.PriorityQueue

**Comment by snayzix** [comment]
Trying thanks for the reply guys

**Comment by snayzix** [comment]
@Alberto247 Broooo , changing PriorityQueue with nitroxmodel resolv the errors bbut after gen 119 errors XD
Bbut im pretty sure what @Mathboy19 said is true the problem comme from the assembly csharp cuz im using a Cracked version so it can be outdated

**Comment by snayzix** [comment]
Something More weired No errors but 2 things fail to gen .... Why he dont just put the bins ...

**Comment by Alberto247** [comment]
Just download everything through the github app and harmony will get downloaded too

**Comment by Alberto247** [comment]
He can't put the bins because they are copied directly inside your subnautica folder

**Comment by Alberto247** [comment]
And the mod is still in an early stage

**Comment by Sunrunner37** [comment]
Fixed issues. Resolving.
