### ISSUE TITLE
Game Pause

### ISSUE THREAD

**Issue by Fekacsaby** [SubnauticaNitrox/Nitrox#650]
Game Pause. When all players enter the menu, pause the gameplay. Or, you can pause the menu by pressing a button.

**Comment by alexanderheuts** [comment]
We have no intention of _ever_ adding a pause function to Nitrox. This inherently brings with itself so many complexities that the effort needed to implement it far outweighs the benefit. Of course, it's already questionable whether or not a multiplayer game needs a pause function.
