### ISSUE TITLE
Mobs Issues

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#651]
There are 2 mobs that are currently bug.

1. Warpers are broken they can spawn but they dont move or do anything.

2. The Worms( the mobs that spawn at the purple mushrooms biome) Dont spawn.

**Comment by killzoms** [comment]
check ghost leviathans as well

**Comment by ahoboninja** [comment]
Also the red crabs on the island.  Blue crabs move and attack but the red crabs just spawn and sit there

**Comment by NitroxPower** [comment]
i havent seen red crabs before and i think blue crabs cant die from the last time i fought them i was knifing them but nothing

**Comment by ahoboninja** [comment]
I will hop on when I get home and see if I can get a screenshot of it.  I will say I have been able to kill blue crabs but you have to be super close and hit them 4 or 5 times.  basically lose half your health to kill one.

**Comment by EinLuigi** [comment]
no all big fishes are buggy and do not move
