### ISSUE TITLE
Plants disappear after sowing after a short time

### ISSUE THREAD

**Issue by ThoronadNg** [SubnauticaNitrox/Nitrox#653]
sown plants disappear after a short time
indoor and outdoor beet

**Comment by breaup** [comment]
we had the same issue too looks to be client side when I disconnect and reconnect they come back and other player have to do the same too or we all see different things

**Comment by Swiff4** [comment]
Is this bug related to the issue that plants restart growing from Zero after a server restart?

**Comment by Jannify** [comment]
Probably fixed with #1341
