### ISSUE TITLE
Major problems.

### ISSUE THREAD

**Issue by reaperguy101** [SubnauticaNitrox/Nitrox#655]
So from what I have experienced in the mod so far was a mix of major and minor glitches. From what I can tell is the biggest glitch that needs to be fixed before any other is the duplicate entities. This effects every entity that I have come across. An example would be the giant island floaters. Because it spawns in double the floaters it makes it hard to get on the island. When you are on the island because there are double the plants it makes it harder to get around. The next major problem is the disappearance of entities. Every few minutes all entities in the game world will disappear for both players and the game has to be restarted to continue playing. The story also needs to be synced between players. The next issue is not as bad as the others but should still be addressed. Syncing the player movement would be a nice thing to have.

**Comment by killzoms** [comment]
@reaperguy101 have you updated to the latest version?

**Comment by reaperguy101** [comment]
I believe I am on the latest version.

**Comment by alexanderheuts** [comment]
Pretty much everything that you mentioned is already known. Quite a few fixes address issues that you mention and will be rolled out the next version. I would recommend waiting a little while until the next release. Should you still have issues you want to address, please create individual tickets to discuss these topics. For now I'm closing the ticket as it's to broad and to vague to use as an issue to track items.
