### ISSUE TITLE
Discovered blueprints sync

### ISSUE THREAD

**Issue by Alberto247** [SubnauticaNitrox/Nitrox#66]
I tried the mod and realised that discovered blueprints are not synced between players. Is this an expected behaviour or an issue? Do you have plans to add this feature in future? Because it's really annoying while playing co-op to be unable to build the same things your friends can.
Thank you.

**Comment by Sunrunner37** [comment]
This is currently undefined behavior.  I may be incorrect, but I believe the game will give you access to a pattern if you are nearby a player that builds it. (unintended side-effect of another thing in game)
