### ISSUE TITLE
Loading Saved World doesn`t work

### ISSUE THREAD

**Issue by Felino41** [SubnauticaNitrox/Nitrox#660]
So the Server starts fine and I can connect without Problems, the logs say its saving after every couple of minutes, but when I close down the server and open it again using either Nitrox Server or Nitrox Server WPF there is the following output: 

Could not load world: System.IO.InvalidDataException: Persisted state is not valid
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() creating a new one

So it starts a new world even though there is a saved world. Is there a fix?

This is a short log showing how it opens a new world, saves and shut down work properly:

`[Nitrox] Log level set to ConsoleInfo, FileLog, ConsoleDebug
[Nitrox] I: Could not load world: System.IO.InvalidDataException: Persisted state is not valid
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() creating a new one.
[Nitrox] D: Event Triggerer started!
[Nitrox] I: If playing on LAN, use this IP: 192.168.178.42
[Nitrox] I: Nitrox Server Started
[Nitrox] I: If using port forwarding, use this IP: XX
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Nitrox Server Stopping...
[Nitrox] I: Saving world state.
[Nitrox] I: World state saved.
[Nitrox] I: Networking: Socket bound to 0.0.0.0:11000: True
[Nitrox] I: Networking: Network thread started
[Nitrox] I: Networking: Shutdown requested
[Nitrox] I: Networking: Shutting down...
[Nitrox] I: Nitrox Server Stopped`

**Comment by ASimpson87** [comment]
Try deleting the save file. If that doesn't work re install nitrox
