### ISSUE TITLE
No multiplayer button

### ISSUE THREAD

**Issue by Ziolo99** [SubnauticaNitrox/Nitrox#663]
there's no multiplayer button in main menu. I'm sure that everything was installed fine.

**Comment by NitroxPower** [comment]
This just means you dint installed the mod correctly have you installed that mod before @Ziolo99 ?

**Comment by NitroxPower** [comment]
Dont forget to close This Issue @Ziolo99

**Comment by alexanderheuts** [comment]
Join the Nitrox Discord for support. Closing the issue as it's non-technical.
