### ISSUE TITLE
Make saves useable in Single Player

### ISSUE THREAD

**Issue by tocram1** [SubnauticaNitrox/Nitrox#666]
It would be nice to have a save folder for Nitrox that would be the same as a save folder for a single player map, which would make single player maps loadable on the server, and vice-versa.

**Comment by NitroxPower** [comment]
I dont think thats possible.....it probably will be really hard to do something like thats why i think the developers of subnautica never made multiplayer cause look at this mod how much work they have done to get this far and its far away from perfect.The point is that there isnt really a reason to do that why somebody would want to load the singleplayer to multiplayer??? how ever you can save the multiplayer to singleplayer.

**Comment by kylinator25** [comment]
That _would_ require a lot of work to translate the format nitrox saves in to the format the base game saves in. I think the number one option right now would be to just try re-creating any bases you had in singleplayer in nitrox

**Comment by NitroxPower** [comment]
well you can use cheats in multiplayer and make your survival world
