### ISSUE TITLE
Some issues: Mob, Game, Map

### ISSUE THREAD

**Issue by lucafont2** [SubnauticaNitrox/Nitrox#670]
I want to report you some issues.
I'm very happy to see a multiplayer mod for this game, because it is the only think it miss.

- Mobs are not moving/attacking, fish are herded in group of 6/7 (without mooving)
- Some inventory items disapear after reacces
- There are very few fragments. In single player i had sea glaider in less an hour.
- I can not enter in seamoth and cyclope (not tested prawn)
- Other player are not in real time, they refresh position every 5 minutes.

**Comment by lucafont2** [comment]
I think that i have an old version. How can i ceck it?

**Comment by NitroxPower** [comment]
you probably do have old version @lucafont2 you should have the latest version which is the mod description called nexusmods also the mod isnt finished so all new updates/fixes will be posted there too and keep in mind this mod is in very early stages of development its not reccomended for casual play yet...

**Comment by alexanderheuts** [comment]
All these items have been resolved in previous versions. Should they persist in the latest version for you, please join our Discord to discuss before reporting here.
