### ISSUE TITLE
Server cant save game

### ISSUE THREAD

**Issue by chummiefummie** [SubnauticaNitrox/Nitrox#673]
Whenever the server tries to automatically save the game, the error code "Could not save world: System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Subnautia\SubServer\save.nitrox is denied." appears. Any clue on how to fix this?

**Comment by JustinHoeky** [comment]
Did you try to run the server as Admin? And did you install 1.0.3.1?
