### ISSUE TITLE
Wrecks broken

### ISSUE THREAD

**Issue by Avalonzo** [SubnauticaNitrox/Nitrox#676]
server running latest version 1.0.3.1.

All wrecks have no doors or any objects/scannables.

https://steamcommunity.com/sharedfiles/filedetails/?id=1637746862

Edit: after a server restart the doors, objects and scannables comeback but soon disappear again seems to coincide with the reefback spawning problem.

**Comment by duck24** [comment]
I've had the same issue, wrecks just refuse to spawn

**Comment by WarcraftAcc** [comment]
same here, whenever someone joins me all doors and items in wrecks just dissapear
