### ISSUE TITLE
Teleporter missing

### ISSUE THREAD

**Issue by Avalonzo** [SubnauticaNitrox/Nitrox#677]
Server running latest version 1.0.3.1.

The teleporter located inside the mountain behind the cannon is now located outside of the cannon's underwater dock.

https://steamcommunity.com/sharedfiles/filedetails/?id=1637799557

https://steamcommunity.com/sharedfiles/filedetails/?id=1637799596

**Comment by NitroxPower** [comment]
@Avalonzo  the teleporter in the mountain is a bug and its missing the other teleporter in the docks it was there anyways its not a bug you havent found how to use it yet....
