### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by bloodyfishhammock** [SubnauticaNitrox/Nitrox#68]
`[Failure] Could not find file '(directory)\ReloaderSettings.cs'.`
that message appears before compiling, when compiling this error occurs:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0311	The type 'NitroxModel.Packets.Packet' cannot be used as type parameter 'T' in the generic type or method 'PriorityQueue<T>'. There is no implicit reference conversion from 'NitroxModel.Packets.Packet' to 'IPriorityQueueItem'.	NitroxClient	(directory)\Nitrox\NitroxClient\Communication\DeferringPacketReceiver.cs	16	Active
```

**Comment by nesrak1** [comment]
Currently being fixed in my branch, Subnautica has a new `PriorityQueue` class so you can replace `PriorityQueue` with `NitroxModel.DataStructures.PriorityQueue`, however there will also be an error due to a variable removed from an animation class which I am also fixing now.

**Comment by bloodyfishhammock** [comment]
Thanks!

**Comment by nesrak1** [comment]
I've just uploaded the changes [here](https://github.com/nesrak1/Nitrox/tree/player-anims)
