### ISSUE TITLE
[Base] Fabricator, Radio and possibly growbeds and lockers disconnected after relog

### ISSUE THREAD

**Issue by sparhawk765** [SubnauticaNitrox/Nitrox#685]
Version 1.0.3.1, clean world.

After logout and login again it seems the fabricator and radio gets "disconnected" from my base (multipurpose-rooms) and ends up unpowered and shaded like they are in water. Same with lockers and growbeds but these seem to work anyway since they don't req. power.

Not tried chargers yet but guessing they suffer from the same problem.

**Comment by RylenWolf** [comment]
I have incurred the same problem with fabricator.

**Comment by acidscorch** [comment]
under investigation

**Comment by Wicloz** [comment]
As far as investigation goes, here are my observations:
As @sparhawk765 noticed, it would seem all furniture ends up 'disconnecting' from the base. As in, they act like they are just in the water, and with no base to draw power from, only lockers will keep working.
Additionally, anything constructed in the Cyclops will no longer be connected to the Cyclops after a rejoin, and will not move when the Cyclops moves.

**Comment by Jannify** [comment]
Moved to https://github.com/SubnauticaNitrox/Nitrox/issues/1160
