### ISSUE TITLE
Loading save faillure (dedicated server)

### ISSUE THREAD

**Issue by Khran** [SubnauticaNitrox/Nitrox#687]
Hi,
Nitrox run on dedicated server.
I test him and wait a stable release before opening to public.
But, when my server is restarted, The world and all items, accounts, isn't saved.

The error in logs below:

> [20:24:15 INFO]: Could not load world: ProtoBufNet.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354
>    at ProtoBufNet.ProtoReader.StartSubItem(ProtoReader reader)
>    at ProtoBufNet.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)
>    at ProtoBufNet.ProtoReader.ReadObject(Object value, Int32 key, ProtoReader reader)
>    at ProtoBufNet.Serializers.SubItemSerializer.ProtoBufNet.Serializers.IProtoSerializer.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.TagDecorator.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.PropertyDecorator.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.TypeSerializer.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Meta.RuntimeTypeModel.Deserialize(Int32 key, Object value, ProtoReader source)
>    at ProtoBufNet.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)
>    at ProtoBufNet.ProtoReader.ReadObject(Object value, Int32 key, ProtoReader reader)
>    at ProtoBufNet.Serializers.SubItemSerializer.ProtoBufNet.Serializers.IProtoSerializer.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.TagDecorator.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.MapDecorator`3.Read(Object untyped, ProtoReader source)
>    at ProtoBufNet.Serializers.PropertyDecorator.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.TypeSerializer.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Meta.RuntimeTypeModel.Deserialize(Int32 key, Object value, ProtoReader source)
>    at ProtoBufNet.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)
>    at ProtoBufNet.ProtoReader.ReadObject(Object value, Int32 key, ProtoReader reader)
>    at ProtoBufNet.Serializers.SubItemSerializer.ProtoBufNet.Serializers.IProtoSerializer.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.TagDecorator.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.PropertyDecorator.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Serializers.TypeSerializer.Read(Object value, ProtoReader source)
>    at ProtoBufNet.Meta.RuntimeTypeModel.Deserialize(Int32 key, Object value, ProtoReader source)
>    at ProtoBufNet.Meta.TypeModel.DeserializeWithLengthPrefix(Stream source, Object value, Type type, PrefixStyle style, Int32 expectedField, TypeResolver resolver, Int64& bytesRead, Boolean& haveObject, SerializationContext context)
>    at ProtoBufNet.Meta.TypeModel.DeserializeWithLengthPrefix(Stream source, Object value, Type type, PrefixStyle style, Int32 expectedField, TypeResolver resolver, Int64& bytesRead)
>    at ProtoBufNet.Meta.TypeModel.DeserializeWithLengthPrefix(Stream source, Object value, Type type, PrefixStyle style, Int32 fieldNumber)
>    at NitroxServer.Serialization.ServerProtobufSerializer.Deserialize[T](Stream stream)
>    at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() creating a new one.

**Comment by killzoms** [comment]
This is likely caused due to an update

**Comment by Khran** [comment]
not really, i make a fresh install for each version (game and nitrox) is released.

**Comment by Coding-Hen** [comment]
I think you will find that this is due to the save file being outdated from an older version. I believe that it is caused by trying to serialize the save file into the newly updated worldpersistance and because of the changes this can not happen and the error is thrown.
