### ISSUE TITLE
[Building]Vehicle Upgrade Console

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#688]
When you Rejoin the game the position of it its wrong and without it we cant progress further to the game this is critical bug here is a screenshot 
![capture 2](https://user-images.githubusercontent.com/46358553/52008377-2cd26580-24d9-11e9-93ff-6dde0e733b5a.PNG)

**Comment by ASimpson87** [comment]
Moonpools are very broken. However you can avoid it totally breaking by building the upgrade console in the middle at the end adjacent to the ladder.

**Comment by ASimpson87** [comment]
Yeah it depends on the rotation the moonpool/upgrade consoles are broken.

**Comment by NitroxPower** [comment]
Ok thanks for the advice this is the most weird thing i heard so it wont break
