### ISSUE TITLE
Flares Dont Despawn

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#689]
Its been there for ~4 Hours real life time
![image](https://user-images.githubusercontent.com/46358553/52008539-7c189600-24d9-11e9-88ee-4a256f38f3f0.png)

**Comment by brianpopow** [comment]
Is that maybe a bug from the main game and not nitrox? They do not go out in the single player mode for me either.

**Comment by Plazmaz** [comment]
Yeah this definitely seems to be the case in the game as well. You are able to pick them back up though.

**Comment by mcDandy** [comment]
Iritates me a little becouse Iaccidently shot one in escape pod, but its in model so waiting for it to disapper
