### ISSUE TITLE
Seamoths are called "Cyclops"

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#690]
For some Reason Seamoths names by default they have the name "Cyclops"

**Comment by ASimpson87** [comment]
Yep this is a bug with the persistence it will be fixed in the next
release. If you change the name/colour you wont see it as Cyclops anymore.

**Comment by NitroxPower** [comment]
Yes i have tryed that but my friend has to rejoin so he can see the changes also for some reason my seamoth was all the time black there must be an issue with the shading

**Comment by ASimpson87** [comment]
No it's just default name and colour. Once you change it updates and saves .

**Comment by ASimpson87** [comment]
Alright let me take a look at it. Easy fix if that's the case.

**Comment by NitroxPower** [comment]
Also my friend made a seamoth while i was far away and when i came to him the seamoth wasnt visible when i rejoined it fixed

**Comment by ASimpson87** [comment]
Fixed in #700

**Comment by NitroxPower** [comment]
Its not the moonpools it must be the upgrade console try make one and rejoin its totaly bugged out
