### ISSUE TITLE
Overall Aurora Sync

### ISSUE THREAD

**Issue by ScriptedAnar** [SubnauticaNitrox/Nitrox#693]
I went to the aurora with my friend and we explored it without commands but there are some stuff that arent Sync these are:

- [ ] 1.Fires

- [x] 2.Sealed Doors

- [x] 3.Boxes that we have to move with the propolution cannon

- [ ] 4.Aurora Nuclear reactors damage points(and i think if you rejoin it doest save so we cant reduce the Radiation levels) 

EDIT:Also all fires, boxes,Sealed Doors in aurora and in total game get reset when you rejoin

**Comment by Coding-Hen** [comment]
Sealed doors are synced as of: 728a405ee754ba52235643964c341d4311bc7a78

**Comment by dartasen** [comment]
Propulsion cannon are synced as of : [efde307](https://github.com/SubnauticaNitrox/Nitrox/commit/efde3078faff53ff904c9ae485c4d1c971594feb)

**Comment by Jannify** [comment]
Moved to https://github.com/SubnauticaNitrox/Nitrox/issues/1454
