### ISSUE TITLE
desync items

### ISSUE THREAD

**Issue by lordmzx** [SubnauticaNitrox/Nitrox#694]
i have last version of mod
I play with 1 friend it ok but when ~10 mins from start server goes , we ill get trouble with  sync items in the bag and mobs , and dropped items

**Comment by Mathew3000** [comment]
Same problem here, after a while all items I crafted disappearin his inventory and the items he crafted disappearin mine.

**Comment by arijan108** [comment]
Same problem here, exactly around 10 minutes from starting the server, the same issues occur with me and my friend too. 

[20:03:33 ERROR]: Error processing buildEvent in ThrottledBuilderSystem.NullReferenceException: Object reference not set to an instance of an object

**Comment by Mathew3000** [comment]
I can't see an error in the console... I tried to test vith vs-debugger, but my friends can't join that build. 
Generally it seems to be more frequent with the "complexity" of the save. The more items/structures the quicker it happens

**Comment by skourismanolis** [comment]
yeap same here, when we join on a new save, container syncing works as it should, but after a little while it's lost, tested on 1.0.2.2, 1.0.3.0 and 1.0.3.1 builds with the proper uninstall procedure and clean saves

**Comment by Mathew3000** [comment]
Just out of curiosity, were you guys using steam or epic version of the game?

**Comment by skourismanolis** [comment]
I used the latest Epic Games version

**Comment by Mathew3000** [comment]
We used that version too, maybe it has to do something with the epic version...

**Comment by Measurity** [comment]
Closing this in favor of #1003 where issues with items not staying in containers is tracked.
