### ISSUE TITLE
Upgrade Modules persistence Failure 

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#695]
Idk why it happened but it did we was 2 players in the server we already had depth mk modules 1 and never despawned then we made sonar and hull reinforcements for seamoth then i rejoined cause he frooze in my client and then his sonar hull reinforcement and my hull reinforcement dissapeared but the mk depth modules dint or my sonar.With all the respect Asimpsons idk why but it happened even it looks weird also the mk module we had it for avery long time and never dissapeared when we made the new when i rejoined(host) it happened...

**Comment by ASimpson87** [comment]
Can you get me your output_log from Nitrox Logs at that time ? Otherwise
hard to know what went wrong.

**Comment by NitroxPower** [comment]
[nitrox-2019-01-31.log](https://github.com/SubnauticaNitrox/Nitrox/files/2820217/nitrox-2019-01-31.log)

**Comment by NitroxPower** [comment]
Let me know how it turns out if you have any question ask me if i can help you find a solution...

**Comment by ASimpson87** [comment]
Can you add the client log.

**Comment by ASimpson87** [comment]
You can retrieve previous client log files from your Subnautica folder in
Nitrox Logs. Not the ones in Dub server

**Comment by NitroxPower** [comment]
Sorry i just found out this one here you go:
[nitrox-2019-01-31.log](https://github.com/SubnauticaNitrox/Nitrox/files/2824161/nitrox-2019-01-31.log)

**Comment by NitroxPower** [comment]
[nitrox-2019-01-31.log](https://github.com/SubnauticaNitrox/Nitrox/files/2824163/nitrox-2019-01-31.log)

**Comment by ASimpson87** [comment]
This looks like it's a problem with the moonpool module fabricator not syncing between clients correctly and the item guid not syncing. Please wait for a fix to moonpools.

**Comment by NitroxPower** [comment]
I have to be honest yes moonpool docking isnt fine sometimes his seamoth docking and it isnt and also i want to tell you that the upgrade console its full buged out ok thanks for that

**Comment by NitroxPower** [comment]
Wait so some of the modules disappeared cause i docked it in moonpool? if i make the modules and put them in the seamoth they wont disappear if i wont dock it?

**Comment by ASimpson87** [comment]
No it's to do with the upgrade console not syncing items properly when they are created.
