### ISSUE TITLE
Infinity Loading Returns

### ISSUE THREAD

**Issue by NitroxPower** [SubnauticaNitrox/Nitrox#698]
here is a peak:
![image](https://user-images.githubusercontent.com/46358553/52148057-31318680-2671-11e9-9f55-345ba47cff4c.png) 

So i left the game and i pressed immidiatly to join again thats what happened.I think now this is the end cause i cant join the game again i tryed restarting it and doest work and i close to finish the game with Multiplayer
[nitrox-2019-02-01.1.log](https://github.com/SubnauticaNitrox/Nitrox/files/2823256/nitrox-2019-02-01.1.log)

**Comment by ASimpson87** [comment]
Can you add the client logs.

**Comment by NitroxPower** [comment]
Hopefully you mean this
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2824146/output_log.txt)

**Comment by theonetoday** [comment]
My friend is also having this error. I can access the server and one of my other friends also can. [
[nitrox-2019-02-01.1.log](https://github.com/SubnauticaNitrox/Nitrox/files/2824153/nitrox-2019-02-01.1.log)
](url)

**Comment by ASimpson87** [comment]
Yes that was helpful did you by chance build a rocket base or spawn a
vehicle in? Looks like I need to add some null checks in for the vehicle
spawning. I'll make sure this is in the next release.

**Comment by NitroxPower** [comment]
No i dint spawn anything i just went to a wreck and the doors was broken so i rejoined and it happened

**Comment by NitroxPower** [comment]
@ASimpson87 o yes what i did is i upgraded my Depth Module MK 1 to MK 2 that may caused it but i dint make any new vehicle

**Comment by NitroxPower** [comment]
There is any way it can get fixed so it wont load infinity if we dont save?

**Comment by ASimpson87** [comment]
It shouldn't matter if you save or not. You will have to wait until the fix
is implemented to get that save back

**Comment by ASimpson87** [comment]
This is resolved with #700

**Comment by NitroxPower** [comment]
Good job Thanks a lot

**Comment by theonetoday** [comment]
My friend got the infinite loading screen before building any vehicles, besides the seaglide. Will this merge still fix that issue?

**Comment by ASimpson87** [comment]
No create a new issue and post logs from infinite loading screen

**Comment by Magic1000** [comment]
Anyone can help me? my game is in infinite loading 
[nitrox-2019-05-11 (1).log](https://github.com/SubnauticaNitrox/Nitrox/files/3243246/nitrox-2019-05-11.1.log)
[nitrox-2019-05-11.1 (1).log](https://github.com/SubnauticaNitrox/Nitrox/files/3243247/nitrox-2019-05-11.1.1.log)
[nitrox-2019-05-10 (1).log](https://github.com/SubnauticaNitrox/Nitrox/files/3243248/nitrox-2019-05-10.1.log)

**Comment by Coding-Hen** [comment]
This error seems to be within the PlayerPositionInitalSyncProcessor class Within the Process when checking the subroot root is null or doesnt have a base line 39. @Magic1000 Are you within a vehicle when the last save happend?

**Comment by Magic1000** [comment]
> This error seems to be within the PlayerPositionInitalSyncProcessor class Within the Process when checking the subroot root is null or doesnt have a base line 39. @Magic1000 Are you within a vehicle when the last save happend?


not that I remember, I had built a seamoth, and my friend built another seamoth, I remember that the server was a bit lame, we were relogging to restart the server and we could not do it anymore. Do you have other options for this to happen? and some solution if this is the problem? thks so much
