### ISSUE TITLE
spawning issue

### ISSUE THREAD

**Issue by newbfever** [SubnauticaNitrox/Nitrox#701]
Hey i just yesterday installed the mod and i gotta say i love it, but i found one very annoying bug and one kinda weird one.....

the weird one is that, after friend and i visited the alien base at the north island, the game thot we were in side the base after we left the area, aka footsteps sounded the same as inside, water actually didnt seem to exist as we just fell down  and ran at the bottom of the ocean  xD it was quite funny honestly,

but the thing what annoyed me the most is that the game spawned tons of reefbacks i mean like 20 of them at time at our location, and  server told me this 

[03:30:59 INFO]: Spawning 1502 entities from 1601 spawn points in batch 8,19,6
[03:30:59 INFO]: Spawning 697 entities from 933 spawn points in batch 8,18,6
[03:30:59 INFO]: Spawning 156 entities from 457 spawn points in batch 9,18,6
[03:30:59 INFO]: Spawning 1158 entities from 1171 spawn points in batch 7,19,6
[03:31:00 INFO]: Spawning 559 entities from 826 spawn points in batch 7,18,6
[03:31:00 INFO]: Spawning 126 entities from 645 spawn points in batch 7,18,7

we were in creative mode and had maxconnections valua at 100, like its as default, i changed the value to 10 after we stop playing  so it could be just the game spawning them for 100 people?  but i figured id ask about it since i didnt find any solution for this from here

thanks for your time!  ill be waiting for the reply

**Comment by newbfever** [comment]
glad to hear about the reefback bug fix! and ah, we didnt have water where it should of been  :D

**Comment by NitroxPower** [comment]
Using Commands can make issues like the water or no water doest happen in survival thow :+1:  close this issue

**Comment by newbfever** [comment]
commands such as?

**Comment by Jannify** [comment]
This issue (no water) is very common related to Subnautica and the reefbacks will be/is fixed. So no issue anymore, right?

**Comment by newbfever** [comment]
no exact issue, just questions :P so i guess i can close this
