### ISSUE TITLE
Stuck on loading multiplayer

### ISSUE THREAD

**Issue by maxibers** [SubnauticaNitrox/Nitrox#703]
Hello, me and my friend are using vers. 1.0.3.1. 
When my friend tries to join me (while i'm hosting the server) he is stuck on loading multiplayer. If i try to join him while he is hosting i can connect but i cannot see any entities (while he can).
We both have windows defender firewall totally disabled. We tried with both internet (port forwarding) and hamachi connections. We tried deleting the server save file. We also tried with an older version of the mod (same things happend)
Any help? 
Thanks

**Comment by NitroxPower** [comment]
Close your issue i reported this before and it has been fixed

**Comment by maxibers** [comment]
Is the fix gonna be released in the next update?
