### ISSUE TITLE
Multiplayer button isn't there

### ISSUE THREAD

**Issue by NoobKiller772** [SubnauticaNitrox/Nitrox#707]
I wanna do subnautica multiplayer with  an friend, we both downloaded the mod the same way, but mine doesn't work, i don't have the Multiplayer button so i can't play on it, i have hamachi already downloaded so that isn't the issue, could you please help me with this, i have tried installing it like 20 times on different way's.

**Comment by NitroxPower** [comment]
This isnt a bug you just havent installed the mod correctly please join the Discord Server so they can help you out

**Comment by NoobKiller772** [comment]
> 
> 
> This isnt a bug you just havent installed the mod correctly please join the Discord Server so they can help you out

i've tried to search the discord server, but the invite is unavalible

**Comment by NitroxPower** [comment]
here you go:https://discordapp.com/invite/E8B4X9s dont forget to close this issue
