### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by theonetoday** [SubnauticaNitrox/Nitrox#710]
I and another friend are able to connect to and play on the server. One other friend cannot. It gets stuck on the loading multiplayer screen. 
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/2825148/output_log.txt)
[nitrox-2019-02-01.1.log](https://github.com/SubnauticaNitrox/Nitrox/files/2825149/nitrox-2019-02-01.1.log)

**Comment by NitroxPower** [comment]
this issue has been resolved in #700 close this issue

**Comment by theonetoday** [comment]
> this issue has been resolved in #700 close this issue

I was told to make a new issue for mine in the same issue

**Comment by NitroxPower** [comment]
But i did report exacly the same issue and with Asimpson i gave him the output log and he fixed it

**Comment by theonetoday** [comment]
and he told me to make a new one

**Comment by NitroxPower** [comment]
Yes i see now there are more instances so that happens

**Comment by SFRacing** [comment]
A friend and i played together for 3 days. today we got infinite loading screens too.
Log file: 
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/3402791/output_log.txt)

I hope there is a fix for this ;(

**Comment by Coding-Hen** [comment]
Duplicate of #412
