### ISSUE TITLE
Inventory items being stolen

### ISSUE THREAD

**Issue by unlightednetting** [SubnauticaNitrox/Nitrox#711]
Version 1.0.3.1 from NexusMods. Fresh world, upgrade instructions of Uninstall Nitrox, Verify, and reinstall were taken.

This was originally going to be about items disappearing, but they are specifically being stolen.

Two player game, just started base building. The materials that are needed for any particular base piece are being taken from BOTH players' inventories.

As well, if the building player does not have every material needed but starts the building anyways, the materials that the builder is missing get taken from the other players' inventory, but the building does not actually finish, thereby sending the materials into the ether.

I have not tested if this is based on distance, and it does not seem to happen to happen to the lockers. As well ,this does not appear to happen reliably/every time for every material needed,, but testing does show it to be only when someone is building.

**Comment by docquantum** [comment]
This is a known bug that's being worked on.

Thanks for the report!

**Comment by 0verdark** [comment]
@Measurity The issue has been resolved. You can download the latest **Nitrox Launcher** version which is: **1.2.2.0** from the **Official Website** or from **Nexus Mods.** You're Welcome!
