### ISSUE TITLE
Client FPS dropping in "Freedom" mode

### ISSUE THREAD

**Issue by Nilsie** [SubnauticaNitrox/Nitrox#712]
When running a server in freedom mode. Client FPS drops to below 10 frames per second after a while.
This is fixed by reconnecting to the server.

I think this happens because food and water do keep counting somewhere and your framerate just drops when you run out and should technically die. 
This issue does not exist in survival mode.

(I've searched and didn't find this reported yet, sorry if it is a double post...)

**Comment by NitroxPower** [comment]
The fps is dropping by % not by frames for example if you get 100fps and you loose 10fps means there is a 10% performance decrease if you play with 20 fps and you loose 10 fps means there is a 50% performance decrease

**Comment by JustinHoeky** [comment]
@NitroxPower he isn't losing 10fps, it drops to 10fps.
@Nilsie Which version are you using? Mind joining the Discord #help-channel for this?

**Comment by NitroxPower** [comment]
@JustinHoeky  yes same if he was playing with 20 fps and went to 10 there is a ~50% performance decrease if he had 100 fps and got below 10 there is a ~90% performance decrease its just maths

**Comment by NitroxPower** [comment]
Cause telling how many fps he got at that point doest make us know what performance hit there is but saying how much % performance decrease we know the difference

**Comment by Nilsie** [comment]
I'm in the channel. PM/DM me @Lolzol#1680 whenever you need more information about this.

**Comment by Elvee1988** [comment]
A friend and I are encoutering the same issue. FPS are fine for some time and then starts to drop until its no more playable. Jas the issue been reproduced ? Thx

**Comment by Measurity** [comment]
Could anyone of you give us the `Player.log` file when this issue has happened and you close the game?
File can be found here: `%AppData%\..\LocalLow\Unknown Worlds\Subnautica\Player.log`
