### ISSUE TITLE
In-game screenshots (in PDA) do not get saved on reconnect

### ISSUE THREAD

**Issue by JulsOSpel** [SubnauticaNitrox/Nitrox#713]
Game Build: Alpha 1.0.3.1
Game Screenshots wipe every time you log off and on the server.
![20190203115407_1](https://user-images.githubusercontent.com/21327687/52181850-7fe33b80-27ab-11e9-94bd-518f9bb52d08.jpg)
![20190203115504_1](https://user-images.githubusercontent.com/21327687/52181854-85408600-27ab-11e9-9c30-497db1ab3bf5.jpg)

**Comment by Jannify** [comment]
That happens because the server world is a "virtual game save" which will be deleted after disconnect.
