### ISSUE TITLE
Player, not world, inventories aren't saving 1.0.3.1

### ISSUE THREAD

**Issue by UphillLobster** [SubnauticaNitrox/Nitrox#714]
So me and a group of friends, specifically a group of 5 players were playing using the nitrox multiplayer mod, we made sure to install the mod correctly with the right directly and get the server up, and have spent several hours on the game already. However whenever a player that isn't the host leaves the server or gets disconnected and rejoins their inventories are cleared including with all of their items. Not to mention the fact that whenever they rejoin they can't see any of the items inside any of the lockers until the host moves it into another one and then back into it. As well as sometimes one of the lockers in our base keeps glitching out and displaying a completely different inventory than the 4 lead that we put inside, although sometimes when we leave the base and re-enter our lead is back there. 

Please do help T-T

**Comment by UphillLobster** [comment]
Oh! I almost forgot, everytime someone rejoins we have to recreate our fabricator too because it says its out of power despite our base having full power

**Comment by NitroxPower** [comment]
M8 download always the latest version which is 1.0.3.1 you are playing in a really old version @UphillLobster  cause the most instances for that have been fixed

**Comment by NitroxPower** [comment]
the current newest version is a lot more stable than the version 1.0.0.8

**Comment by NitroxPower** [comment]
#691

**Comment by UphillLobster** [comment]
Thanks although I'm more concerned about our inventories disappearing

**Comment by ambid17** [comment]
This happens to me too. If you hit "save game" as a client, it bugs and and won't stop. If you try to rejoin, you inventory and all of the lockers are empty.. But if a friend puts something in the locker I can see it.

**Comment by Measurity** [comment]
Closing this in favor of issue #1003. Thanks for going into detail about what you did. It'll help us fix this bug faster.

Continue posting on the new issue if you have new information that might help to fix this bug.
