### ISSUE TITLE
Subnautica Nitrox download for Mac OSX

### ISSUE THREAD

**Issue by splattown** [SubnauticaNitrox/Nitrox#715]
I was wondering if anybody could link the download for the multiplayer mod of subnautica for Mac OS?

**Comment by Jannify** [comment]
Currently we have no Mac OS support :/

**Comment by tarsythetarsier** [comment]
> Currently we have no Mac OS support :/

Will there ever be Mac OS support?

**Comment by Measurity** [comment]
First step for this here: #995 (for Linux)

**Comment by PPetka** [comment]
It's been over a year since the last replay.
I see the First step is merged, what about other steps?
Can Nitrox be downloaded on MacOs right now?
Thanks
