### ISSUE TITLE
Game takes forever to load

### ISSUE THREAD

**Issue by LegnaKYT** [SubnauticaNitrox/Nitrox#717]
Making it a quick read, after my girlfriend and I hatched the Baby Leviathans, we took a break from our server, and upon trying to reconnect, it won't let us at all.

Any idea? It just loads forever after this issue.

**Comment by LegnaKYT** [comment]
[nitrox-2019-02-04.3.log](https://github.com/SubnauticaNitrox/Nitrox/files/2833491/nitrox-2019-02-04.3.log)

**Comment by Nilsie** [comment]
Not fixed upon trying multiple reconnects + run everything in administrator mode?

Looking at the logs the Identifier trying to connect has a negative value. Looking into my own server logs, my friend could never connect when his "Identifier" was negative. Retrying fixed it each time for him though. 

Fix -> Don't generate negative values for "Identifier"?

**Comment by Measurity** [comment]
The log file is incomplete. If you have to full, relevant, log file please upload it again. Gonna close this for now unless you post back.
