### ISSUE TITLE
console commands don't work

### ISSUE THREAD

**Issue by ambid17** [SubnauticaNitrox/Nitrox#722]
In the previous update i could use the day commands in the console as a client, now there is something about a password and I'm not sure how to use it

The command says "you do not have the required permission for this command"

**Comment by docquantum** [comment]
Please visit the Discord to get help (it's in the ReadMe/Homepage).

There is an administrator password set for the server in the server config file, this issue might be related to that. (SubServer/NitroxServer.exe.config)

**Comment by Coding-Hen** [comment]
@ambid17 are you still finding this issue with the latest release?

**Comment by Measurity** [comment]
This is related to command permissions which have been added to Nitrox. Gonna close this as a non-issue.
