### ISSUE TITLE
Deconstruction still not saved (1.0.3.1)

### ISSUE THREAD

**Issue by Christopher117** [SubnauticaNitrox/Nitrox#723]
The deconstruction is not saved, when we deconstruct something and we quit and return to the server the thing is still there.
This does not seem to happen for elements inside bases such as cabinets or fabricators, but only for structures.

**Comment by Fr33z3m4n** [comment]
We have the same problem.

Any Solution ?

**Comment by IzmoIzmi** [comment]
#733 
#691
#685
#588
#516
wait for the next update.

**Comment by CalebSargeant** [comment]
This is still an issue in the current version (Alpha 1.2.0.1-159-alpha-1-2-0-1-1583653383)

**Comment by Ryu-no-hub** [comment]
Same problem

**Comment by Measurity** [comment]
This issue is being tracked here: #951
