### ISSUE TITLE
Subnautica World Save

### ISSUE THREAD

**Issue by BearFreezing** [SubnauticaNitrox/Nitrox#724]
I know there are already people talking about this issue but it has not been answered. I want to find out how I can put an already existing world onto the subnautica multiplayer. I would really like to figure this out any help would be great!

**Comment by Sajgoniarz** [comment]
You cant, nitrox uses its own format.

**Comment by Measurity** [comment]
Don't make new issues for existing issues. Making MP save and SP save compatible is not planned right now.
