### ISSUE TITLE
Way too many reefbacks

### ISSUE THREAD

**Issue by Plazmaz** [SubnauticaNitrox/Nitrox#729]
This bug seems similar to #352, however I am not seeing overspawning of resources or other fish. Instead, I am only seeing hundreds and hundreds of reefbacks spawn:
![](https://i.imgur.com/Jxs2urE.jpg)
It is worth noting that I am running the latest nexus build(Alpha 1.0.3.1) vs compiling from source, but that fix happened before this build was released. Something else interesting about this is that some of the reefbacks are significantly smaller than others. I am unsure if this is just randomization or if this is actually a distinct entity of some sort.

**Comment by NitroxPower** [comment]
This issue was fixed a week ago but it hasnt been published yet. Dont forget to close this issue

**Comment by c-benoit** [comment]
ive the same problem please fix it

**Comment by f-ben** [comment]
Will there be a new build soon? This bug is killing the game for us. There spawn so many reefbacks that its impossible to navigate. Yesterday we had so many reefbacks that a core i7 with 1080 gtx dropped down to 15 fps.

**Comment by c-benoit** [comment]
same of f-ben, up pls

**Comment by vrbitm** [comment]
If this issue has been fixed can we please get a new release? The reefbacks cause lots of item/object spawning issues making wrecks and scan objects not appear.

**Comment by mcDandy** [comment]
fixed long time ago. Should be slosed.
