### ISSUE TITLE
No server file?

### ISSUE THREAD

**Issue by Xher0** [SubnauticaNitrox/Nitrox#730]
The Nitrox Installer didn't work so I tried using it through GitHub, It works and everything just fine but me and my friend cant find a NitroxServer.exe File so neither of us can start a server. Is there a different way you start a server on the GitHub version? I watched somebody else do it and they had one, is it because its a newer version then what they had and they is a different method now or did I install it wrong?

**Comment by Sajgoniarz** [comment]
What do you mean by "it works" when you dont know where you have exe file?

**Comment by Xher0** [comment]
I mean it installed correctly in that I can see the multiplayer button and join servers, but I can seem to find the exe file to start servers.

**Comment by Sajgoniarz** [comment]
So, at build it modified your Subnautica and you manually modified csharpassemby, so server should be at build directory

**Comment by Bamheadshotbk** [comment]
Did you ever resolve this?

**Comment by Measurity** [comment]
Nitrox now uses a launcher to start instead of an installer. Can you check if it works now? I'll close this issue but let me know if you still have issues installing Nitrox.
