### ISSUE TITLE
Nitrox unable to load gamesave

### ISSUE THREAD

**Issue by Sajgoniarz** [SubnauticaNitrox/Nitrox#731]
World save cannot be loaded after server restart :
`[21:42:22 INFO]: Could not load world: System.IO.InvalidDataException: Persisted state is not valid
   at NitroxServer.Serialization.World.WorldPersistence.LoadFromFile() creating a new one.
[21:42:22 DEBUG]: Event Triggerer started!`

Environment:
Windows 7 Home Basic x64 clean install with .NET 4 Client Profile
At Oracle Virtual Box 6.0
With Hardware VT-x/AMD-V virtualization (**Hyper-V disabled**, causing networking issue at Hyper-V machine)
2 Processors and 1000MB RAM assigned
Subnautica - Epic Store version

**Comment by docquantum** [comment]
It looks like the save file may have gotten corrupt. Are you able to reproduce this bug?

For safety, before shutting down the server, make sure to type in `save` to save the world and then `stop` to stop the server and have it shut itself down.

**Comment by Mathew3000** [comment]
Hey, 
I'm having the same problem, it is reproduceable, even when shutting the server down with "save" and "stop".
The persistedData is failing at IsValid because "EntityData.SerializableEntitiesById.Count" is 0
I'm not familiar with serializsation so I could not look deeper into it.
I hope this helps

**Comment by Measurity** [comment]
This error is no longer displayed and just says that a new save will be created. I talked with killzoms about this and having no `SerializableEntitiesById` likely means that the server was never connected to by anyone and so it won't have anything in its save file.
