### ISSUE TITLE
Building un-synched

### ISSUE THREAD

**Issue by Tinkertee** [SubnauticaNitrox/Nitrox#733]
My Husband went out exploring while I built a base for us, when he got back the base was all buggy, some features un-finished for him. Unable to access ladders no matter how many things I unbuilt and rebuilt infront of his eyes nothing changed.

**Comment by Tinkertee** [comment]
We restarted the server, saved before obviously. Restarted Subnautica, when I loaded back in everything was screwed up for me aswell.

**Comment by Christopher117** [comment]
Same for me !

**Comment by mrpenguinb** [comment]
Base building synchronization (more specifically the destruction part) is not implemented yet or working properly. I don't know all the details but it is definitely one of the main things that is stopping me and a friend of mine from playing Nitrox.

**Comment by Measurity** [comment]
This issue is being tracked here: #951
