### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by TheFurryCody** [SubnauticaNitrox/Nitrox#736]
During installation, I accidentally picked the wrong folder. I went into windows 10 settings and tried to remove nitrox through that. it didn't work, and now when i try to use the installer again, it says i can either repair or uninstall. both start to work, then give me the same error of "Nitrox Installer ended prematurely due to an error"
can i PLEASE get a response to this

**Comment by Sajgoniarz** [comment]
You can try to remove it forcefully with some 3rd party software. I know CCleaner had such funtion some time ago.

**Comment by TheFurryCody** [comment]
alright, I'll try that

**Comment by TheFurryCody** [comment]
Yeah, didn't work. I tried repairing it and uninstalling it. Didn't work. I can hit delete, as it cant delete the MSI installer

**Comment by Coding-Hen** [comment]
Can this issue now be closed as we have removed the installer?

**Comment by TheFurryCody** [comment]
I couldn't remove the installer though. 8t just softlocked at the "removing
program..." Window.

**Comment by Coding-Hen** [comment]
> 
> 
> During installation, I accidentally picked the wrong folder. I went into windows 10 settings and tried to remove nitrox through that. it didn't work, and now when i try to use the installer again, it says i can either repair or uninstall. both start to work, then give me the same error of "Nitrox Installer ended prematurely due to an error"
> can i PLEASE get a response to this

How did you manage to install it without pointing to the subnautica directory, it would have thrown an error? What version were you using?

**Comment by TheFurryCody** [comment]
It didnt finish, and now wheneber I use the built in remove function, it
gets confused as to where the files are and wont work.

**Comment by Measurity** [comment]
We no longer have the installer. If the issue still happens with the Nitrox Launcher then please create a new issue to let us know.
