### ISSUE TITLE
I have 14 errors on Build with Visual Studio

### ISSUE THREAD

**Issue by C0d0Type23** [SubnauticaNitrox/Nitrox#739]
I tried  to build several times and re launch Visual Stduio but the error is not gone
I'd modified the two files (DevVars.targets and SharedConfig.targets) for the Subnautica directory from epic games and here my errors

![capture](https://user-images.githubusercontent.com/36166761/53684914-99f83700-3ce1-11e9-88bd-a988f7b32c11.PNG)

**Comment by IzmoIzmi** [comment]
#741 was merged. fixed #748

**Comment by Coding-Hen** [comment]
@C0d0Type23 Can you close this issue now as it has been fixed?
