### ISSUE TITLE
Inject NitroxPatcher into Assembly-CSharp

### ISSUE THREAD

**Issue by Skyterix1991** [SubnauticaNitrox/Nitrox#74]
I would like to install this mod but I have a problem with the step: 5. Inject NitroxPatcher into Assembly-CSharp of Setting up a development environment for Nitrox
I don't really understand what to do, can someone help me ?

**Comment by Xenopsist** [comment]
Hey where can i find those instructions?

**Comment by ElMaxi** [comment]
https://github.com/SubnauticaNitrox/Nitrox/wiki/Setting-up-a-development-environment-for-Nitrox Here buuuut we still have this problem, may you help him? I can't seem to be so *witty*

**Comment by Za-Rii** [comment]
I have this issue too, the instructions are a bit vague for this part.
