### ISSUE TITLE
Nitrox Custom Launcher - design concept

### ISSUE THREAD

**Issue by andreaspalmer** [SubnauticaNitrox/Nitrox#740]
![preview](https://user-images.githubusercontent.com/16740257/53696693-0a7a8300-3dca-11e9-9d94-42c7eff799db.png)

### Custom Launcher Concept
With this concept I wanted to create a sleek looking, minimal launcher that is easy to use and helps gamers launch into Subnautica using Nitrox much faster. 🔥 

🎮 **Main screen**  
From the initial screen you're able to launch Subnautica in either singleplayer or multiplayer mode. You are also able to choose from the default game or the new Below Zero.

![launcherpreviewandreaspalmer](https://user-images.githubusercontent.com/16740257/53696730-79f07280-3dca-11e9-8922-f6d1f120d4bb.png)

💻  **Server tab**  
After doing some research and coming up with concepts with a moderator of the server, I tried to improve the server overview by adding simplicity and useful features.

- Add and your favourite servers
- Choose which game version you want to start a Nitrox server for
- Make it clear which version you are going to launch

![serversettingspreviewandreaspalmer](https://user-images.githubusercontent.com/16740257/53696834-34807500-3dcb-11e9-8417-ec1258ad9110.png)

⚙️ **Settings tab** 
This page is currently still very empty, as the only real setting you can modify is the game directory path. Yet, this page still allows easy further expansion as it is reusing all components of the launcher.

![settingspreviewandreaspalmer](https://user-images.githubusercontent.com/16740257/53696852-701b3f00-3dcb-11e9-837f-d26d9e28cba3.png)

I'd really like to hear some feedback and could also do a light/dark version of these concepts or design some smaller more specific features (only if there's even interest or the scope to add these).

🎨 Source files:
If you want to preview the designs you can take a look at the source here: [Figma: Nitrox Launcher](https://www.figma.com/file/DMdu6DJz8Jyh6uykFZaAlfmX/Nitrox-Launcher-by-Andreas-Palmer?node-id=0%3A1)

All designs were created using Figma and if you want to contribute please let me know so I can add you to the Figma project. :)

**Comment by Ghaarg** [comment]
Hey there,
i (and the project owner) want to use your concept and integrate it into the launcher.
Pleasy hit me up if you are still interested in contributing your launcher concept into the mod. :)

**Comment by Sunrunner37** [comment]
Hey @Ghaarg, we have sign-off to use these.  We have been in several conversations offline.

**Comment by Coding-Hen** [comment]
Shouldn't this be closed off now as its been implemented as per #765?
