### ISSUE TITLE
Fabricator desynchs players

### ISSUE THREAD

**Issue by Ghaarg** [SubnauticaNitrox/Nitrox#749]
After processing a craft (from another player) for a fabricator, many packages will not be synched anymore. That includes almost every cyclops synching.

Tried to fix this bug but so far the only thing that helped was not sending Craft and FabricatorPickup packets.
Packets seem to get passed to the server and the server pass them to other players but they never seem to get there. Maybe silent errors?

**Comment by brianpopow** [comment]
i think the logs need to be much more verbose. I think everything which does not meet the expectations needs to be logged alt least with Log.Debug or a warning. I have seen a lot of places in the source code, where something is attempted to be removed from a Dictionary, but fails without any log output.

Also structured logging could help alot to track such kind of issues.

**Comment by acidscorch** [comment]
There is a noticed generell issue with send/receive order of packages and packages loss. maybe this causes this issue.  
optimized packet synchronisation and stabilisation is in work at me. including additional log-output for typeof package and sequence number. give me just two more days to get this finalized. 

I cannot say if this fixes this issue, but you can see then which communication is done and which is forwarded to other players and which not.

**Comment by acidscorch** [comment]
please try PR#751

**Comment by Ghaarg** [comment]
> 
> 
> please try PR#751

So first tests show no difference. After i followed the conversation in your PR a bit, i suspect, that the ordered channel is not working properly after the CraftBegin packet and as you put it on top of Lidgren, these packets never get to your layer. As the error is easily reproduced, you could watch, what happens beneath? Maybe we find out why it is not working after the packet.

I will try to also dig a bit deeper later

**Comment by acidscorch** [comment]
I'm at work in the moment. Can you send a log on discord?

**Comment by Ghaarg** [comment]
Desync fixed with PR #704
