### ISSUE TITLE
Inventory Problems

### ISSUE THREAD

**Issue by Mys7eryMoose** [SubnauticaNitrox/Nitrox#750]
Me and a friend are playing, and we were building and noticed that materials are taken from one anothers inventories when building. I dont know if this is supposed to be like this or if it's something i need to change in my files. if someone could point me in the right direction id be very thankful :D 👍

**Comment by docquantum** [comment]
This is a known bug that is being worked on.

**Comment by Measurity** [comment]
This issue is being tracked here: #1003
