### ISSUE TITLE
[Vehicle] Docking/Undocking animation and sound issues

### ISSUE THREAD

**Issue by Ghaarg** [SubnauticaNitrox/Nitrox#753]
There are minor problems with docking (for cyclops):
- Docking into a cyclops will play the docking sounds for all player regardless of position. Super hard to find where the sounds come from
- Undocking will just release the vehicle after the animation are played for the person in the vehicle. Looks terrible but works just fine

Copied from PR [#748](https://github.com/SubnauticaNitrox/Nitrox/pull/748)

**Comment by acidscorch** [comment]
Hi @Ghaarg,

For the sounds, maybe this helps:

![image](https://user-images.githubusercontent.com/48223659/83644986-3595e880-a5b2-11ea-9641-f812fe070421.png)


And for the undocking i would suggest: 

![image](https://user-images.githubusercontent.com/48223659/83647821-a094ee80-a5b5-11ea-9c75-48a4bafe9238.png)

The exact values may need to be found by testing. This gives a smooth movement downwards. Maybe on the sending side the position updates should be suppressed as long as the cinematic is running. After the cinematic, the position on the remote client (evaluate how much speed is needed and how far away the position from the cyclops should be) needs to be very close to the position on the undocking client to avoid a reposition jump. 

Best regards

**Comment by Jannify** [comment]
With https://github.com/SubnauticaNitrox/Nitrox/pull/1291 a sound suppressor can be used in the docking processor.
