### ISSUE TITLE
Latest merge  caused nullref on ArmsController_Update_Patch..ctor 

### ISSUE THREAD

**Issue by Measuring** [SubnauticaNitrox/Nitrox#76]
https://github.com/SubnauticaNitrox/Nitrox/commit/1cd3d285438fa37e3790bb7de14a3b354be8e30f#diff-4a96142185effe1e33812b1ac29b195cR20

Proposal: Change `"armAiming"` to `"ArmAiming"`  on this line to resolve the issue. "Multiplayer" button appear again and the log no longer shows the NullReference.

**Comment by oliverslott** [comment]
I agree with this. 
![image](https://user-images.githubusercontent.com/1584195/35183463-1dbbdf3c-fde7-11e7-9476-c4abdda421c3.png)
It does indeed need to be named "ArmAiming". 
It looks like @urlordjames might have renamed it by accident while refactoring.

**Comment by Sunrunner37** [comment]
Thanks - fixed.  Next time feel free to open a PR and I'll approve.
