### ISSUE TITLE
Base piece rotations not synced

### ISSUE THREAD

**Issue by quimnuss** [SubnauticaNitrox/Nitrox#763]
Since the decoupling of NitroxModel from Assembly-CSharp at b0c4456, the rotation of Base Pieces (e.g. Corridors) fail to sync between clients.

The bug is with `Type.GetType` which does not work across assemblies as it is. One of the two [locations related](https://github.com/SubnauticaNitrox/Nitrox/blob/b0c4456bf19dde1ba6df35f6a4649177ee9d6a9b/NitroxModel/DataStructures/GameLogic/Buildings/Rotation/CorridorRotationMetadata.cs#L20) to rotation reads:

```
        public CorridorRotationMetadata(int rotation) : base (Type.GetType("BaseAddCorridorGhost"))
```
Type.GetType returns null and thus fails to create the base class.

Later, when the processor checks the type of the rotation but it doesn't match since one is null.

I've tried fixing it with the fully qualified assembly name but `Type.GetType` is new to me and I got `BaseAddCorridorGhost, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null` when called within Assembly-Csharp

**Comment by quimnuss** [comment]
Up to me, I'd block the next release until this regression is fixed.

**Comment by Sunrunner37** [comment]
Migrated to NitroxModel_Subnautica as part of https://github.com/SubnauticaNitrox/Nitrox/commit/50d9ce44ddf64d20a44da44c624772ac5edeece8
