### ISSUE TITLE
A Few Bugs

### ISSUE THREAD

**Issue by SamstarGaming1** [SubnauticaNitrox/Nitrox#770]
Here is a list of bugs my friends and I have experienced, I've added some gifs to help the developers.  (Sorry if any of these bugs have already been reported):

- Upon starting the server some habitat components deconstruct out of nowhere.
 https://media.giphy.com/media/5QMG8yIJmEqxgsOxUq/giphy.gif
- Bioreactors and nuclear reactors do the same as above although both have to be fully deconstructed before reconstructing it. All the fuel previously in the reactors disappear requiring them to be refueled.
https://giphy.com/gifs/878nV3H4m4c3bp0XT0
- Upwards of 20+ Reefbacks spawn in certain biomes, causing major lag spikes.
https://giphy.com/gifs/cXHyqlcnothvAC3gvo
- The Aurora detonates multiple times.
- Sometimes shipwrecks spawn without anything inside. Relogging is a temporary fix although only cosmetic models spawn inside. This has made it almost impossible to find any fragments as they don't spawn. Even after deleting and creating a new world twice, there are still no fragments inside any of the wrecks. (We had no other option but to use console commands to unlock all the blueprints.)
https://giphy.com/gifs/SSQ4ilRciwPbXkzR4d 
- When re-entering the server all fabricators and modification stations become unpowered despite there being enough power.
https://giphy.com/gifs/61XTidgqIk0Dn1c9mz
- Radio messages sometimes do not play.
https://giphy.com/gifs/ZNeht3iL77V7u0GSdG
- If the radio messages do play the waypoints are only given to the player that played the message.
- The amount of power in a base does not sync between clients, leading to a lot of issues. Fuel in the reactors doesn't sync either, requiring every player to get their own fuel for one base. 
- Time also doesn't sync. This ties in with the issue above since the time isn't the same for each client, solar panels produce different amounts of energy.
- Seamoths get stuck when trying to enter Cyclops
https://giphy.com/gifs/ZEYgrcQ4sTdCeKvlkU
- When connecting back to the server some habitat components act a bit glitchy.
https://giphy.com/gifs/1SG5qD4lVBr5gzWpUv 
- Items in planters don't sync.
- Water filtration machines just disappear.
- When relogging some previously deconstructed components reappear, essentially duplicating materials.

**Comment by docquantum** [comment]
Thanks for the detailed bug report!

In the future, be sure to search the open _and_ closed reports to make sure you don't post duplicates or bugs that have been patched. Many of the bugs you mention have been reported, and some have even been patched already.

Be sure to check out the Discord as well as many of the known bugs are also listed there.

**Comment by samstar2508** [comment]
Hi, the bugs on the list are from about 2 days ago (some are even from today) so I don't think they were patched. (I am running the latest version.)

Thanks for the advice, I'll make sure to search next time.

**Comment by docquantum** [comment]
By latest version, do you mean the current release or your own build from source? Some of the bugs have been patched, just not released yet officially, but you can see the changes if you build the code from source.

**Comment by samstar2508** [comment]
The latest one from NexuxMods (Alpha 1.0.3.1). So I'm guessing they've been patched in the source code?

**Comment by docquantum** [comment]
Yes, look through the pull requests, you'll see a lot has changed since the latest release. They're even working towards a proper launcher rather than an installed patch, which should make the install process much easier.

**Comment by Measurity** [comment]
Please do not create big issue lists in one GitHub issue because it makes it hard for us to track the progress and often times they have many duplicates (or people create duplicates because it's in a list somewhere like this issue).

If you have a unique issue, please create a new GitHub issue with detailed information on how to reproduce the issue so we can fix it.

**Comment by SamstarGaming1** [comment]
This was literally a year ago lmao

**Comment by Measurity** [comment]
That's one of the reasons why this is now closed.
