### ISSUE TITLE
Hadcoded path?

### ISSUE THREAD

**Issue by mcDandy** [SubnauticaNitrox/Nitrox#783]
The world path is probably hardcoded, but I don´t see the error nor the path existing now. Version Alpha 1.1.0.0
<Deleted image>
the path to Subnautica server is D:\Users\(myusername) \Desktop\Subnautica server

**Comment by Amcio** [comment]
It gave me the same error the first time i turned it on but it worked since then

**Comment by acidscorch** [comment]
Please edit and close this issue for personal data protection concerns. thanks

**Comment by mcDandy** [comment]
Removed any sources of potentially sensitive information
