### ISSUE TITLE
Doors not opening/some syncing issues

### ISSUE THREAD

**Issue by ProtoFG** [SubnauticaNitrox/Nitrox#784]
With the newest release(Alpha 1.1.0.1), the host and I went to the Aurora, but when we attempted to unlock any doors, the keypad would say that they were unlocked, however they did not open. We both entered the codes for the doors since it wasn't synced, but neither of us could open any doors. Also, the entrance to the aurora that is on the lowest level and requires the propulsion cannon(the other one you can jump over), wasn't synced either. I moved the blocks and desks out of the way and proceeded to enter the Aurora, but the host just laughed and said I stood there for a bit, and just walked through everything.

**Comment by plymoth45** [comment]
Can confirm same issues with doors. Also found similar issues with Gun platform force fields not lowering when tablets inserted and archways not activating when Ion cube was placed in activation platform. Was able to use opendoors cheat to lower force fields, but found it only worked on local force field. All other fields required the cheat on/off approach to lower when approached. Did not attempt on aurora doors.
