### ISSUE TITLE
Global Y-Coordinate missmatch between Clients - Help Wanted

### ISSUE THREAD

**Issue by acidscorch** [SubnauticaNitrox/Nitrox#794]
The Y-Coordinate (height level) isn't correctly between clients. Data transfers at packets for the value are correct. Maybe culture format related at client side. Noticed with players from different countrys. 

This causes remote player positioning half room-height below or above current player level and leads to misplaced Objects at building.

**Comment by NitroxPower** [comment]
Its not the reason that we from different country it was happening with my friends too when we was playing our survival (version 1.3.0.1).

**Comment by acidscorch** [comment]
It seems like, that someone else noticed the Y-mismatch a while ago at first time spawning the player in the escape pod and simply tried to solve it via moving the spawning player a little bit up. That's also the reason, why i'm falling a little, when connecting with a new player to the multiplayer game.

For me the values should be (0, -0.2f, 0) to result in the same coordinates after the local player has spawned and finished falling without performing any movement. I'm searching further, why the client-world-coordinates differ from client to client. 

![image](https://user-images.githubusercontent.com/48223659/56286332-bdeccc00-6119-11e9-9d39-eacf0c396c1b.png)
