### ISSUE TITLE
Activities lost between Initial-Sync and final game entry

### ISSUE THREAD

**Issue by acidscorch** [SubnauticaNitrox/Nitrox#795]
Activities that are performed by remote players between the moment of receiving the initial-sync packages after connect and the final game entry after finishing loading everything, aren't transfered  completely. 

This leads to e.g. the following:
- unfinished constructing/deconstructing (after rejoining again, everything is fine)
- fall off from moving cyclops

**Comment by acidscorch** [comment]
under investigation

**Comment by NitroxPower** [comment]
Cyclops moving issue is is weird cause a different person had tryed to fix that but even in singleplayer it seems that even the developers of Subnautica dint fix it. Basically if you go with the cyclops to max speed and you let the steering wheel you slide back when the cyclops moves so thats the reason in multiplayer the other person slides and doest go with the cyclops and causes many times to get flinged to space
