### ISSUE TITLE
Save game got corrupted due to server crash

### ISSUE THREAD

**Issue by JumperBoost** [SubnauticaNitrox/Nitrox#800]
Hello,

I playing in my world, when i was kick because the server crashed and that my friend have disconnected. For moment, it's ok, i reboot the server and i see when the server was already started according to a error message. So, i'm go to the task manager (windows) and i stopped the two tasks called "**NitroxServer-Subnautica.exe**". And, i start the server and when i'm connect to server, i spawn at first location of game. I search in the nitrox's files and my file (save) weighs about 57Mo, so i think that my file can be save. I search during 1 hour but i found nothing, i hope you have a solution.

Thanks for have read my post,
Sorry for my bad english, but i'm french ^^.

Sincerely, **JumperBoost**.

Edit: My File = https://www.mediafire.com/file/2kwnvthbfegir2d/save.nitrox/file

**Comment by Jannify** [comment]
Outdated and single user problem
