### ISSUE TITLE
Minor to Major Bugs

### ISSUE THREAD

**Issue by ImKoalafications** [SubnauticaNitrox/Nitrox#804]
Upon playing the mod today with multiple friends 5 in total we have found some minor issues and major ones the issues are as follows

Wrecks
-Upon loading into the world the aurora ship wrecks are completely open with boxes floating through the wrecks and all doors either outside of the wrecks or just not working properly or some wrecks just floating above where they should be leaving loot under the ocean floor (Can provide video evidence on multiple wrecks if needed)
Players
-Player models when in buildings or even in the life pod seem to glitch halfway into the floor where only upper torso arms and head are in the buildings (Happens with everyone)
Odd occurrences
-For whatever reason upon our 5th joining 2 people died a bit later and they completely disappeared from the game using the "list" command on the launcher showed their names but 2 players couldn't see them until game restart
Buildings(Major)
-Moonpools being only accessible by one person other people showing it not fully complete (Only seems to happen to certain people)
-Moonpools multiplying and turning upon server restart
-Some parts of buildings after deconstruction becoming glitched outside of base and not capable of being deconstructed. (Primarily Ladders and Bulkheads)
-Whole bases being client side where everyone else cant access any part of the base. (Re-logged in and couldn't even break down the base no deconstruct option)
Will comment any more that we find. Also can provide videos and pictures or bugs if needed.

**Comment by Coding-Hen** [comment]
Thanks for the bug reports. Would it be possible to cross reference these with the master building list #691 before adding to the list so we can avoid duplication. Thanks for reporting

**Comment by Measurity** [comment]
We're closing list-issues from GitHub so that we can more easily track bugs without having to open all the issues to see what's actually still broken.

If you have a unique bug, not previously reported, then please make a new GitHub issue explaining the steps you took that made the bug occur.
