### ISSUE TITLE
Aurora ship Keypad door not opening

### ISSUE THREAD

**Issue by five710** [SubnauticaNitrox/Nitrox#805]
Whenever I go and explore the aurora ship and come across the keypad door i'm unable to open it. The code is accepted and the sound animation comes on as the door opened but it doesn't and i'm unable to go any further

**Comment by rockythehamster** [comment]
use the unlockdoors command to open the door in the console opened with grave.
More here:
https://subnautica.fandom.com/wiki/Console_Commands

**Comment by silvermoonstar3** [comment]
Another option is going right up to it and typing "warpforward 2".  This also mostly works with forcefields that won't go down.

**Comment by EmuLegs** [comment]
My friend and I are having the same problem, we can both "unlock" the door but it wont open

**Comment by Coding-Hen** [comment]
Peolle have been looking at this for a while now but the current advice
that is given out is to

how do i open the doors that will not open ?
Use the command warpforward
or
Use the command unlockdoors

Give that a try and let us know

**Comment by EmuLegs** [comment]
That worked (unlockdoors)
would this be related to how the buildings spawn in a kind of offset way ?

**Comment by Jannify** [comment]
This will probably be fixed after this https://github.com/SubnauticaNitrox/Nitrox/pull/854 pull request.

**Comment by Coding-Hen** [comment]
Possibly fixed per 936a62118f966a6558b8deea69435e06a41167cb
