### ISSUE TITLE
Launcher crashes when i try to run sever

### ISSUE THREAD

**Issue by Nmaniac** [SubnauticaNitrox/Nitrox#807]
everything works fine but when I try to launch a server with the 1.1.0.1 launcher it just crashes.

**Comment by Coding-Hen** [comment]
Hi,

Do you get an error message? Can you provide the log files?

Thanks

**Comment by Nmaniac** [comment]
I don't see an error message when it crashes it just freezes and disappears. and here's
 all the logs
[Nitrox logs.zip](https://github.com/SubnauticaNitrox/Nitrox/files/3194825/Nitrox.logs.zip)

**Comment by Coding-Hen** [comment]
Within the log when removing the second patches its saying access denied. Do you have the other logs that are generated? They should be within the subnautica folder itself rather than the nitrox launcher folder.

**Comment by Nmaniac** [comment]
what folder do you want?
can upload all the folder inside of subnautica if you want

**Comment by Coding-Hen** [comment]
You should have a nitrox logs inside the main subnautica directory?

**Comment by Nmaniac** [comment]
yeah I got it
[ntirox logs.zip](https://github.com/SubnauticaNitrox/Nitrox/files/3197460/ntirox.logs.zip)

**Comment by Coding-Hen** [comment]
Great, can you also upload the output_log.txt under subnautica_data that
will give a full view to look at

**Comment by Nmaniac** [comment]
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/3201405/output_log.txt)

**Comment by Jannify** [comment]
Is this still an issue?

**Comment by Measurity** [comment]
Closed due to inactivity. Open a new issue referencing this one and/or join our Nitrox Discord server.
