### ISSUE TITLE
items disappering after death trom inventory

### ISSUE THREAD

**Issue by mcDandy** [SubnauticaNitrox/Nitrox#809]
When I get killed by fall or the jellyfish like creatures I lose all items in my inventory and at least flippers (do not know if I used wrong word here) on my feet (I had oxygen tank too). Normally all tools should be preserved and most of materials (which I do not know what dictates what will stay or vanish.)

Death from lack of oxygen, radiation, gasopod´s toxic weapon, reaper and sea dragon leviatan, Lava lizard, ... and under sea vulcanos works fine. Cannot test Crash fish, becouse it is stuck in its nest, does not attack when spawned.

**Comment by mcDandy** [comment]
Did not get killed by other creaturesd. Death from lack of oxygen works fine.

**Comment by Measurity** [comment]
Closing this in favor of a similar but more detailed issue: #1003
