### ISSUE TITLE
TypeLoadException 

### ISSUE THREAD

**Issue by blackmutzi** [SubnauticaNitrox/Nitrox#81]
NitroxPatcher ( all libs ) Compiled with dotnet 4.0 and worked, but see output_log.txt.
Assembly-CSharp.dll modified by GameInput.Awake() method and write at the end NitroxPatcher.Main.Execute()

How can I fix this, TypeLoadException?
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/1657542/output_log.txt)

--- output_log.txt ---
UnloadTime: 1.285892 ms
Platform assembly: F:\Steam\steamapps\common\Subnautica\Subnautica_Data\Managed\NitroxPatcher.dll (this message is harmless)
Platform assembly: F:\Steam\steamapps\common\Subnautica\Subnautica_Data\Managed\0Harmony.dll (this message is harmless)
Platform assembly: F:\Steam\steamapps\common\Subnautica\Subnautica_Data\Managed\NitroxModel.dll (this message is harmless)
TypeLoadException: A type load exception has occurred.
  at GameInput.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.Object:INTERNAL_CALL_Internal_InstantiateSingle(Object, Vector3&, Quaternion&)
UnityEngine.Object:Internal_InstantiateSingle(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
SystemsSpawner:Awake()

**Comment by Measuring** [comment]
The instructions in the wiki are purposely abstract. I think you added 'GameInput.Awake()' which is wrong, inside the GameInput.Awake() method. Getting it to work is an initiation test for this project because the mod is not stable enough for general use.

**Comment by MarijnS95** [comment]
Well, the log shows that it has only loaded `NitroxPatcher`, `0Harmony` and `NitroxModel`, right before the crash. Meaning that it's still missing `NitroxClient` and `NitroxReloader`. Can you check if these are in the same folder? If the wiki has been followed carefully, all these libraries should end up in that directory.

**Comment by blackmutzi** [comment]
NitroxClient.dll and NitroxReloader.dll are still in the same folder xD

**Comment by Alberto247** [comment]
Can you attach an image of your patch to GameInput.Awake()?

**Comment by blackmutzi** [comment]
![gameinput-patch](https://user-images.githubusercontent.com/3210662/35330819-334c02ac-0105-11e8-954d-fa2f9325cf5d.png)

**Comment by Measuring** [comment]
I don't have `NitroxModel` and `NitroxReloader` in references to Assembly-CSharp.dll. Did you also add those or was that automatic? Referencing `NitroxPatcher` is enough. Don't know if it will solve the issue though.

**Comment by blackmutzi** [comment]
okay, i have only NitroxPatcher too. It was a Test with NitroxModel and NitroxReloader.
i can´t fix the issue

**Comment by MarijnS95** [comment]
Just in case, try deleting all the Nitrox dll's in the game folder, and clean + build (rebuild) the solution.

**Comment by Measuring** [comment]
So you also tried removing those double instances of `System`, `System.Core` and `mscorlib`?

**Comment by blackmutzi** [comment]
I have that too now, only NitroxPatcher as Reference and only one System .... @Measuring

**Comment by Alberto247** [comment]
Click the file icon in the bottom left corner, select NitroxPatcher.dll, then add "using NitroxPatcher;" at the start of the code.

**Comment by blackmutzi** [comment]
hahah, i try it 
![nitrox01](https://user-images.githubusercontent.com/3210662/35345912-324a9c34-0131-11e8-93c4-7baecc6e6bd6.png)
after i compile, save and reload assembly, see result. switched automatic the line xD
![nitrox-assembly-reload01](https://user-images.githubusercontent.com/3210662/35346038-6cc9c5b0-0131-11e8-8335-393ab8aee467.png)
Sorry, issue is still there.

**Comment by blackmutzi** [comment]
I tried something new xD
[output_log.txt](https://github.com/SubnauticaNitrox/Nitrox/files/1661397/output_log.txt)

**Comment by MarijnS95** [comment]
It looks like `.NET Core` does not properly support `.NET V3.5`, which is what's needed for building this project. I assume you upgraded the project to 4.0, because I tried that and got the same error.

I can only advise to use Visual Studio 2017, or find a workaround.
