### ISSUE TITLE
Duping with Waterproof storage

### ISSUE THREAD

**Issue by greenking13** [SubnauticaNitrox/Nitrox#813]
Hello! First off, awesome work getting this single player game to be multiplayer. (There may be bugs, but god damn, it is multiplayer.)

Now onto the bug report.

So basically, I used a waterproof storage early into the game and then picked it up after I had finished using it. Since they were cluttering the space in my base, I had decided to toss them out and just pile them outside... except their inventory started duping without me putting anything in them. From what I can tell, each time you open the inventory, the amount in there increases. This can be even more easily seen by just hitting escape once, since the number will drastically increase from that alone. Screenshots below (Since I couldn't find the in-game screen shots, but those also didn't have the numbers in the top left.)

![Screenshot (5)](https://user-images.githubusercontent.com/9355993/58572167-c4825f00-8200-11e9-9582-b4759241ec96.png)
![Screenshot (6)](https://user-images.githubusercontent.com/9355993/58572168-c4825f00-8200-11e9-8adc-981ec32ba65d.png)
![Screenshot (7)](https://user-images.githubusercontent.com/9355993/58572169-c4825f00-8200-11e9-90a6-cfcc1e8b225d.png)
![Screenshot (8)](https://user-images.githubusercontent.com/9355993/58572170-c51af580-8200-11e9-9f3b-5b86251808e6.png)
![Screenshot (9)](https://user-images.githubusercontent.com/9355993/58572171-c51af580-8200-11e9-942a-914e93994f45.png)
![Screenshot (10)](https://user-images.githubusercontent.com/9355993/58572172-c51af580-8200-11e9-8004-02fa19b00921.png)
![Screenshot (11)](https://user-images.githubusercontent.com/9355993/58572173-c51af580-8200-11e9-8cff-a26dbe15638e.png)
![Screenshot (12)](https://user-images.githubusercontent.com/9355993/58572174-c51af580-8200-11e9-85e3-9d7bc07764ac.png)
![Screenshot (13)](https://user-images.githubusercontent.com/9355993/58572175-c5b38c00-8200-11e9-8cf4-c7fd4830ff0e.png)
![Screenshot (14)](https://user-images.githubusercontent.com/9355993/58572178-c5b38c00-8200-11e9-9fc7-23cb1babee8c.png)
![Screenshot (15)](https://user-images.githubusercontent.com/9355993/58572179-c5b38c00-8200-11e9-9fab-2c0515222a0f.png)

**Comment by Jannify** [comment]
https://github.com/SubnauticaNitrox/Nitrox/issues/1003
