### ISSUE TITLE
All of the bugs that me & my friends have encountered that are effecting game play majorly

### ISSUE THREAD

**Issue by ImStormzTV** [SubnauticaNitrox/Nitrox#814]
Me & 2 other friends are playing on a Multiplayer server & these are the biggest bugs that we've encountered:
-Aurora re-exploding randomly
-Base components disappearing
-Sandshark becoming bigger and smaller rapidly
-Items duping in storage
-Items disappearing from inventory
-Seamoth not moving at all
-Teleporting to moonpool when entering seamoth
-Fabricator deconstructing and reconstructing and then consistently replaying the sound of making an item
-Bodies of other players and beacons of players not correctly displaying
-Seamoth inching forward with no driver, then teleporting roughly 20 meters every few seconds
-Base being flooded for some people and not for others
If there are any solutions that you can think of that would help, please reply with them.

**Comment by Zaannaah** [comment]
i too have had  similar issues. 
-the aurora explosion  
-base components disappeareing (and reappearing. i'll deconstruct something and i'll exit load back in and it will have come back and i'll have to deconstruct again.) 
-issues with fabricators showing "not powered" and i have to deconstruct and reconstruct. 
-items disappearing. 
-a huge issue with other players disappearing so we cant see each other. (and sometimes their marker would just start moving in a random direction and keep going farther and farther away)
-got randomly teliported in a seamoth back to the moonpool and i couldnt get back out. i was stuck in the seamoth until i restarted the game. 
-seamoths would randomly explode 
-the classic keypad on the aurora issue. 
-one bug where i got in a seamoth and my body just trailed out behind me in an ever extending line. that one was quite hilarious looking. 
-base being flooded. 
-distorted wreckage. 
-was unable to cut through certain laser cuttable doors.

**Comment by Measurity** [comment]
Gonna close this as this issue is too broad and not specific enough for us to track and fix. Make new GitHub issues for unique issues, please.
