### ISSUE TITLE
Reshade.me injector triggers anti pirating protection 

### ISSUE THREAD

**Issue by ElCap1tan** [SubnauticaNitrox/Nitrox#816]
# Displayed behavior
When you try to start the game from the launcher with Reshade.me injector files in the game directory instead of launching the game a YouTube video (You are a pirate) is displayed in the launcher. Curiously enough the first time I started the game with Reshad enabled it did work as expected. 

# Expected behavior
I guess this is supposed to play when you try to start Nitrox with a pirated copy of the game which Reshade clearly isn't. The game should still start normaly.

**Comment by Coding-Hen** [comment]
Hi,

Nitrox does a check against the DLL file that runs the game. I'm assuming
that the Reshare.me modified the DLL hence the video showing.

Is this correct?

**Comment by SubSonix** [comment]
It adds it's own dll and directory.

It in no way modifies the game though.

**Comment by Wolle0rism** [comment]
So, why does it show the pirating video then when i have purchased the game on Steam years ago already. I used Re-Shade, but i already deinstalled everything. Still wondering what it causes

**Comment by Coding-Hen** [comment]
Okay, have you tried to verify the game files with steam? This usually
fixes the problem for most people.

**Comment by SubSonix** [comment]
Didn't solve the problem for me.

**Comment by FreelancePoliceman** [comment]
Chalk it up to yet another instance of "anti-piracy" features targeting legitimate users.

**Comment by Wolle0rism** [comment]
After re-installing the game end deleting everything remaind in the folder after uninstall, it works like a charm. I guess it was a problem with the Re-Shade

**Comment by M3dicCookie** [comment]
Just get rid of reshade nuff said.

**Comment by ElCap1tan** [comment]
@M3dicCookie Of course I already did this but this is nothing more then a workaround. If Reshad triggers pirating protection then this is a bug and deserves to be reported here because I bought a legit copy of subnautica. Just telling people to not use Reshade doesn't change this and adds nothing to the discussion.
