### ISSUE TITLE
Looks like Nitrox development is dead.

### ISSUE THREAD

**Issue by dborosev** [SubnauticaNitrox/Nitrox#818]
Doesn't look like any of the files have been touched in over 3 months.  Can you confirm this, and at least let people know what the status/plans are?

**Comment by JustinHoeky** [comment]
Looks like someone is not reading the active community on Discord.
They are completely rewriting the base code, which takes al lot of time.

**Comment by Measurity** [comment]
It's open-source, community driven. There is no concept of death, only inactivity. We'll see what happens. Gonna close this because it's not what GitHub issues are here for.
