### ISSUE TITLE
Subnautica Nitrox (Alpha 1.1.0.1) no fragments (moonpool, cyclops, modification station)

### ISSUE THREAD

**Issue by Stank132** [SubnauticaNitrox/Nitrox#822]
I usually go to the mushroom forest to the direct left of the aurora for moonpool, cyclops hull and bridge, modification station, power transmitter fragments and get all of them from there. When I play on nitrox with my friend and go there, I was only able to find 1 modification station fragment and literally no other fragments in that area where there are all of them. Please help, I really hope there is a quick fix to this. This is our 3rd world we created. First 2 didn't have fragments either.

**Comment by darthmat** [comment]
Yep, i must confirm i get same issue. I checked all areas with example moonpool fragments and found none of them, same with thermal power plant. Additionally seems that wrecks or degasi underwater base are not rendered correctly.

**Comment by EinLuigi** [comment]
restart the server than it is there or maybe you have bad internet

**Comment by Jannify** [comment]
Probably fixed with newest release
