### ISSUE TITLE
Keeps opening in VR

### ISSUE THREAD

**Issue by FTWGaming0** [SubnauticaNitrox/Nitrox#823]
The way I made subnautica open in the epic games launcher was to add "-vrmode none" to the additional command line arguments, but the launcher doesn't appear to give me that option... can anyone show me a way of doing this with it?

**Comment by Praevalens** [comment]
Bit late, but I've seen people fixing this issue by adding the game to steam as a non-steam game with the "-vrmode none" arguments which worked for them.

**Comment by HarveyBB** [comment]
I want to know how to play **with** VR tbh

**Comment by BlockArchitech** [comment]
Simply, Unplug your VR headset, or turn off your switch box. Worked for me!

HMD: Oculus Rift S

**Comment by FTWGaming0** [comment]
I don't want to have to crawl behind my computer and unplug my headset every time I want to play this game tho,

**Comment by Coding-Hen** [comment]
@FTWGaming0 @Praevalens Is this only a problem with the epic? Or is it steam and epic?

**Comment by Measurity** [comment]
Closing because of #972
