### ISSUE TITLE
Does not build on Linux 

### ISSUE THREAD

**Issue by FreelancePoliceman** [SubnauticaNitrox/Nitrox#824]
Relevant error message is
```
"/home/adam/dev/Nitrox/Nitrox.sln" (default target) (1) ->
"/home/adam/dev/Nitrox/NitroxClient/NitroxClient.csproj" (default target) (5) ->
(CoreResGen target) -> 
  RESGEN : error : Could not find a part of the path "/r:/opt/Subnautica/Subnautica_Data/Managed/Assembly-CSharp-firstpass.dll". [/home/adam/dev/Nitrox/NitroxClient/NitroxClient.csproj]


"/home/adam/dev/Nitrox/Nitrox.sln" (default target) (1) ->
"/home/adam/dev/Nitrox/NitroxServer-Subnautica/NitroxServer-Subnautica.csproj" (default target) (9) ->
(CoreCompile target) -> 
  GameLogic/Entities/Spawning/SlotsHelper.cs(7,66): error CS0012: The type `ICompileTimeCheckable' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [/home/adam/dev/Nitrox/NitroxServer-Subnautica/NitroxServer-Subnautica.csproj]
```
The latter problem seems to be fixed by adding a reference to Assembly-CSharp-firstpass.dll in Nitrox/NitroxServer-Subnautica/NitroxServer-Subnautica.csproj. I'm completely stumped as to the first problem though. I'm not familiar with C# or the Mono environment at all, but there appear to be two problems. 1., obviously the "r:/" shouldn't occur on Linux (and I have no idea where it's coming from; grep didn't seem to give anything useful, which leads me to:) 2., I'm guessing that Assembly-CSharp-firstpass.dll is somehow being used as a resource file when it ought not to be. I actually created the path /r:/opt/Subnautica/Subnautica_Data/Managed/Assembly-CSharp-firstpass.dll as a symlink to see if this would be accepted; this only changes the error to:
```
"/home/adam/dev/Nitrox/Nitrox.sln" (default target) (1) ->
"/home/adam/dev/Nitrox/NitroxClient/NitroxClient.csproj" (default target) (5) ->
(CoreResGen target) -> 
  RESGEN : error : Unknown format in file /r:/opt/Subnautica/Subnautica_Data/Managed/Assembly-CSharp-firstpass.dll [/home/adam/dev/Nitrox/NitroxClient/NitroxClient.csproj]
```

Any help would be graciously received.

**Comment by galaxy119** [comment]
The launcher won't build for Linux anyways because Mono doesn't (and never will, confirmed by devs) support PresentationFramework
