### ISSUE TITLE
Nearly Unplayable Building Issue

### ISSUE THREAD

**Issue by Inpranked** [SubnauticaNitrox/Nitrox#825]
All Power Sources Produce A Maximum Of 1 Power (The Display Shows 1/500 For Every Item Built. For Every Additional Bioreactor/Nuclear Reactor/Solar Panel, The Numerator Value Increases By 1). 

Consistent Oxygen Supply Present, But No Other Things To Note.

**Comment by Coding-Hen** [comment]
Are you able to retest this with the latest release?

**Comment by Measurity** [comment]
Gonna close this as base building is still buggy in general. After it's stable we'll pick up issues like this. See #951
