### ISSUE TITLE
subnautica lifepod 3 & dropping things problem

### ISSUE THREAD

**Issue by animating-dino** [SubnauticaNitrox/Nitrox#826]
when I was playing with my friend subnautca I tried to give my friend an item but he didnt see
it, and my friend cannot see lifepod 3 he just pass through it and when someone get a blueprint the other didnt get it

**Comment by Jannify** [comment]
The items/lifepods should be visible/synchronised, is it still an issue?
The not synchronised blueprints is a know issue, we will work on that.
