### ISSUE TITLE
Explosive fish isnt working, just stays in the plant, trying to leave

### ISSUE THREAD

**Issue by mechass13** [SubnauticaNitrox/Nitrox#829]

**Comment by juntaosh** [comment]
I have the same issue on some of the explosive fish. Others work just fine

**Comment by SavageJayGatsby** [comment]
Known bug in the current build. You can knife them to get the crash powder.

**Comment by Coding-Hen** [comment]
Fixed with 2ccd92605c6269a97c245ebafc15617a80abe0e9
