### ISSUE TITLE
Wrecks Broken Apart and/or Missing Pieces

### ISSUE THREAD

**Issue by DeepSeaHaberdasher** [SubnauticaNitrox/Nitrox#830]
![264710_20190826155741_1](https://user-images.githubusercontent.com/54558111/63726389-bd301900-c822-11e9-9780-42e5832ee966.png)

They're discombobulated rather thoroughly. Pieces are floating in random locations, doors are shifted out of their frames, and the electrical spark effects are having a merry time, disconnected from any wires. The wrecks I've found are still mostly navigable, even more easily navigable thanks to doors being out of place. The discombobulation is more severe at some wrecks than others. Some are mostly intact.

In addition, this coincides with missing fragments, such as the Prawn Suit upgrades I expected to find at this particular wreck, though I'm aware that that is an existing bug.

**Comment by Granonis** [comment]
I can verify that this is a bug. Tried to find the multipurpose room in the Deepshroom Caves to scan, but it's completely missing. Just floating utilities where the room is supposed to be.

**Comment by Addolgar** [comment]
Is there anyway to fix this bug?

**Comment by Jannify** [comment]
This is a know bug and should be fixed with https://github.com/SubnauticaNitrox/Nitrox/pull/854.

**Comment by Coding-Hen** [comment]
Can you retest with the latest release?
