### ISSUE TITLE
Nitrox mod no whant work on windows vista

### ISSUE THREAD

**Issue by Chocodu31** [SubnauticaNitrox/Nitrox#831]
Hey !!!!!!
I have a litlle problem , nitrox mod no whant work :sob: 
the new launcher no whant launch ( because i not have the .net framework and is not support vista)
and the old launcher no work too (he launch but ended without install the nitrox mod)
and if is possible to say/give to me the folder/files i have put on the folder of subnautica

edit : you can say to me what i do to nitrox mod work x)

**Comment by Coding-Hen** [comment]
Unfortunately the Vista is not supported as it uses v4.7 .net. A suggestion would be is to download the repository, open with visual studio and change the version to v4.6 latest supported vista .net and hope that it works.

**Comment by Chocodu31** [comment]
Hmm an alternative to VisualStudioCode ? x) or a link for download the version for windows vista :C

**Comment by Chocodu31** [comment]
and (because i am a noob x)) where is the repository i have to download ? (Sorry but i am a big noob x))

**Comment by killzoms** [comment]
check the wiki on this repo

**Comment by Chocodu31** [comment]
i can't have Github on my pc with visualstudiocode x)

**Comment by Chocodu31** [comment]
ho :D I finnaly find !
I can't have visualstudiocode so i have install SublimeText3 and I have open folder nitrox folder and i have change version .
thanks !

**Comment by Coding-Hen** [comment]
Nice, does everything work as expected? If so might be something we want to
add to the wiki for others

**Comment by Coding-Hen** [comment]
@Chocodu31 Do you still need this open?
