### ISSUE TITLE
Deserializing the PersistedWorldData doesn't reload EntityData

### ISSUE THREAD

**Issue by Coding-Hen** [SubnauticaNitrox/Nitrox#832]
When the savefile is deserialized it doesn't have the SerializableEntitiesById populated this means that it is not persistant data and resets the savefile each time the server is started.
![image](https://user-images.githubusercontent.com/8798074/64210431-2525d580-ce9b-11e9-8cb6-98ef666eeea2.png)

**Comment by killzoms** [comment]
now that i look... i dont think ProtoBuf actually supports dictionary serialization and if thats the case... a work-around would have to be implemented...

**Comment by killzoms** [comment]
i have one in mind but its just a theory at this point in time(i cant open computer to code atm because i gotta wake up for work at 3AM its 8PM now

**Comment by Coding-Hen** [comment]
Glad I wasn't the only one who found this. Yes I think a work around would
be easier bearing in mind how baked in it is.

**Comment by Coding-Hen** [comment]
@killzoms I have had a look and seems that when the NitorxId was introduced replacing the String GUID it caused this issue. commit cacf262d4d2a4c8718a90a3de97cf3ed39a53105
