### ISSUE TITLE
Nitrox update 

### ISSUE THREAD

**Issue by Kexite123** [SubnauticaNitrox/Nitrox#833]
hi, I wanted to ask the mod stopped being developed? Why are there no updates in the summer and when will the mod be released?  There is also information that there will be the same mod at below zero?

**Comment by Coding-Hen** [comment]
Several people are still looking into things and it is said that the devs are currently rewiting the code base

**Comment by SavageJayGatsby** [comment]
as for the Below Zero remark. Sunny and the other devs haven't stated anything about that. Below Zero is still being worked on so even if they were going to make this for BZ it would be at least a couple years.

**Comment by Coding-Hen** [comment]
@Kexite123 Can we close this?

**Comment by Measurity** [comment]
It's best to ask questions in the Discord server and Nitrox gameplay issues here.
