### ISSUE TITLE
Events and story mod seem to bug

### ISSUE THREAD

**Issue by paberthier15** [SubnauticaNitrox/Nitrox#834]
Since the beginning, we have to reach a place on the surface, 300m approximately from our survival capsule but when we arrive to, we have to come back and it starts again. On the surface, there are some floating trashes and one purple thing. Don't know what it means.
I don't know if the events and the story mod work correctly, the Aurora explode each time after launching the session. The radio works sometime but not often like in solo mod.

**Comment by HarveyBB** [comment]
That is not a story point it is just the server's 'player marker'
The 'floating trashes and one purple thing' is the servers player model so that it doesn't get in the way of gameplay.

If I were you I'd just recolour it in the ping tab so you know which mark is a story and which is the server

**Comment by Coding-Hen** [comment]
The aurora exploding each time and other events is currently something I am working on. It's due to the timers for events (Aurora being one of them) restarting everyone the server is loaded and not saved to file

**Comment by paberthier15** [comment]
Thank you Coding-Hen, I thought it was a timer problem but I wasn't sure.

**Comment by Coding-Hen** [comment]
@Measurity This can be closed
