### ISSUE TITLE
NitroxServer won't build

### ISSUE THREAD

**Issue by galaxy119** [SubnauticaNitrox/Nitrox#835]
"/opt/Nitrox/Nitrox.sln" (default target) (1) ->
"/opt/Nitrox/NitroxServer/NitroxServer.csproj" (default target) (2) ->
(CoreCompile target) -> 
  Serialization/ServerConfig.cs(89,31): error CS0103: The name 'ConfigurationManager' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(54,13): error CS0246: The type or namespace name 'Configuration' could not be found (are you missing a using directive or an assembly reference?) [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(54,36): error CS0103: The name 'ConfigurationManager' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(54,78): error CS0103: The name 'ConfigurationUserLevel' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(56,25): error CS0103: The name 'ConfigurationSaveMode' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(58,13): error CS0103: The name 'ConfigurationManager' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(65,13): error CS0246: The type or namespace name 'Configuration' could not be found (are you missing a using directive or an assembly reference?) [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(65,36): error CS0103: The name 'ConfigurationManager' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(65,78): error CS0103: The name 'ConfigurationUserLevel' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(67,25): error CS0103: The name 'ConfigurationSaveMode' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Serialization/ServerConfig.cs(69,13): error CS0103: The name 'ConfigurationManager' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]
  Server.cs(21,17): error CS0103: The name 'ConfigurationManager' does not exist in the current context [/opt/Nitrox/NitroxServer/NitroxServer.csproj]

**Comment by Coding-Hen** [comment]
Have you tried getting a fresh version of the latest repo then trying to
build again? Works perfectly for me

**Comment by galaxy119** [comment]
This was clones literally 2mins before attemping to build, with no changes made to anything.

**Comment by Coding-Hen** [comment]
@galaxy119 are you still getting this error with the latest build?

**Comment by galaxy119** [comment]
Will try it and let you know

**Comment by Measurity** [comment]
If you're using Resharper/Rider it might help to clear the cache and restart the IDE.

**Comment by Jannify** [comment]
Try to delete the .vs folder. Restart the IDE and use "Rebuild" instead of "Build".

**Comment by Measurity** [comment]
If you still have the issue with the version of Nitrox on master then come join us on the nitrox discord server.
