### ISSUE TITLE
i can't build and even see my friend's buildings (only thing i can see is a solar panel if it changes anything)

### ISSUE THREAD

**Issue by adelayboy** [SubnauticaNitrox/Nitrox#847]
Hello. 

I have an issue which makes a game unplayable.
I installed today a mod, and we played a few minutes and then when i wanted to build a base, i took a habitat builder and when i chose a x compartment or anything else, nothing appears.
I dropped a habitat builder to my friend and he could build but i couldn't see what he was building.
i tried to change some code lines in BaseDeconstructable_Constructor_Patch but nothing helped at all.

**Any suggestions?**

**Comment by Coding-Hen** [comment]
Did you try relogging could you see it then?

**Comment by Measurity** [comment]
All base syncing issues are tracked on this issue: #951

Closing this for now. Once that issue is fixed we'll pickup new base sync issues.
