### ISSUE TITLE
Lunch multiplayer error

### ISSUE THREAD

**Issue by WiZ3R** [SubnauticaNitrox/Nitrox#848]
Hello, i have an issue with the multiplayer nitrox mod.
When i try to lunch in multiplayer mod after lunching the server i got this error.
![image](https://user-images.githubusercontent.com/57489459/68390223-18588300-0165-11ea-9d44-99a1e9df82a6.png)

Can someone explain what can i do ?

**Comment by Coding-Hen** [comment]
Hi, have you unpacked the launcher from the zip file? Also is
subnautica/nitrox already running?

**Comment by WiZ3R** [comment]
I managed to solve the problem but now when i lauch the game i got no interface

**Comment by TRXMXD75** [comment]
iam get nothing when i launch the game i press in play multiplayer but nothing happen

**Comment by Andrewbandrew05** [comment]
An update for Subnautica was released a few days ago and it broke the mod. The dev team is working on it but there is no eta as of now.

**Comment by Andrewbandrew05** [comment]
If you still want to play multiplayer revert back to an older version of the game of syeam and rewrite the directory thingy for the launcher.

**Comment by dismypie** [comment]
@WiZ3R how did you fix? my friends have this problem. or failed to load mono error

**Comment by Cynical8701** [comment]
How do you revert back an update?

**Comment by diarm56** [comment]
@Cynical870 there is a support channel on the Nitrox discord.

Le mar. 12 nov. 2019 à 18:35, Cynical8701 <notifications@github.com> a
écrit :
