### ISSUE TITLE
Title screen bugged

### ISSUE THREAD

**Issue by KingTyl3r** [SubnauticaNitrox/Nitrox#851]
Hello i have recently been trying to install Nitrox to play Subnautica with my friend and when we would install the latest version it would say that 'discord-rpc.dll' was missing. So i removed the files in my Subnautica folders and tried a different version and the version 1.0.3.1(installer version) works but only partially when i open Subnautica it seems to be on some infinite loading screen I've tried to look it up and see if anyone else is having the issue i am having but i can only find things for join the server mine is once i load the game. My friend was having the same issue and i cant figure it out.
![issue](https://user-images.githubusercontent.com/17015281/68535215-d2d6ba00-030c-11ea-8be1-150a28d34bd1.PNG)
This is all the game does when i load it through the Epic Games launcher there is no sound or buttons the only way i can close the game is to alt-tab out and force close it or to alt-f4 to close it.

**Comment by Cha0sPudd1ng** [comment]
Same problem!

**Comment by diarm56** [comment]
The last update of Subnautica broke nitrox. Try too revert your subnautica
to an older version. For help regarding this go the support channel on the
discord of nitrox.

Le mer. 13 nov. 2019 à 11:31, Cha0sPudd1ng <notifications@github.com> a
écrit :

**Comment by Coding-Hen** [comment]
Can this be closed as fixed in commit #1759c5c770356b8adcbe72e0f85ea8bc9d230e3c
