### ISSUE TITLE
Issues after installation, cannot uninstall

### ISSUE THREAD

**Issue by mlpimsler** [SubnauticaNitrox/Nitrox#852]
OS: Windows 10
Subnautica: Steam

I followed the information to install the mod (https://nitrox.fandom.com/wiki/Nitrox) and set up the server. I did not get any error messages. I also checked in my Steam properties for my Subnautica installation and made sure that Nitrox was pointing to the correct location. 

Starting the server appeared to work without issues. However, when I went to make sure that I had properly set up port forwarding with my router, I was not permitted to set up port forwarding because the listed IP was not within my LAN.
![Capture](https://user-images.githubusercontent.com/14222778/68559010-101c7400-0401-11ea-982c-349051a45b53.PNG).

Next, when I went to play/run Subnautica in multiplayer, I got the following error messages:
![Capture2](https://user-images.githubusercontent.com/14222778/68558609-a18ae680-03ff-11ea-909c-5e9a30ffb713.PNG)

I thought maybe uninstalling and reinstalling would help (following: https://nitrox.fandom.com/wiki/Updating_Nitrox)- unfortunately, I was unable to find the app listed under "Apps & features". 
![Capture6](https://user-images.githubusercontent.com/14222778/68559071-48bc4d80-0401-11ea-9f2c-516a7b9925dc.PNG)

The folder cannot be deleted because "it's open in another program", though Subnautica isn't running right now.
![Capture4](https://user-images.githubusercontent.com/14222778/68558955-e1060280-0400-11ea-916f-93c63c6991cf.PNG)

Please help. I REALLY want to play Subnautica with my friends!

**Comment by Andrewbandrew05** [comment]
Subnautica updated recently breaking the mod. You can either revert back to an earlier version or wait for an update to be released for the mod. If you need help reverting go to the help channel on nitrox's discord server where people with much better qualifications than me can help with the installation process.

**Comment by Coding-Hen** [comment]
@Measurity this can probably be closed this is partly port forwarding issue and mono issue is covered by #855
