### ISSUE TITLE
Infinite loading multiplayer

### ISSUE THREAD

**Issue by Damply** [SubnauticaNitrox/Nitrox#858]
I've tried every other fix from other issues here, i've asked in discord and searched everywhere on google. The log does not show any serious errors from i can see. [Here is the log output](https://pastr.io/raw/RzJYLy)

**Comment by alepiumetti** [comment]
Same problem

**Comment by egor-png** [comment]
+

**Comment by egor-png** [comment]
+

**Comment by egor-png** [comment]
таже фигня

**Comment by Damply** [comment]
Anyone know a fix? Seems like no one has any clue whats causing it

**Comment by Andrewbandrew05** [comment]
This is a known problem which began around the begining of November. The dev teams working on it and hopefully will get it fixed soon

**Comment by killzoms** [comment]
@Damply what does the server log say?

**Comment by Kodi4444** [comment]
the only way I was able to fix it is reinstalling subnautica but after that nitrox stopped working,

**Comment by Coding-Hen** [comment]
Duplicate of #412
