### ISSUE TITLE
No MENU Epic Game Version

### ISSUE THREAD

**Issue by SCHUGRWS** [SubnauticaNitrox/Nitrox#859]
I dont know if there is any other issue like this, but when I try to start the multiplayer version of the game of Epic Game the game opens, but there is no Menu, I can do nothing.

Can someone give this issue any attention?

**Comment by killzoms** [comment]
@SCHUGRWS that issue should be fixed with https://github.com/SubnauticaNitrox/Nitrox/commit/1759c5c770356b8adcbe72e0f85ea8bc9d230e3c

**Comment by SCHUGRWS** [comment]
Hi @killzoms thanks for the answer.

Well, I tried with the last public version of Nitrox that's ready for download.
Can you tell me if that commit is already there?

**Comment by Coding-Hen** [comment]
The commit mentioned is in master but hasn't been build for a public
release yet.

**Comment by SCHUGRWS** [comment]
Oh, ok then, thank you,

So all I have to do now is wait, a very long wait e.e haha!

Could you tell if there is any prediction of releasing a new version to the public?

**Comment by ap3322** [comment]
I'm having this same issue as well. I hope patch will be released soon.

**Comment by athaun** [comment]
it has been 25 days, we would really appreciate it if you could build the fix into a new nitrox release, or make it easier for us to do it ourselves without having to setup a dev environment, I don't want to get into all of that.

**Comment by Coding-Hen** [comment]
@athaun Unfortuantly its not that simple although we could do another release there are still outstanding blockers that mean the build would not work at all as per the last Subnautica update so it will come but we are working on some other fixes that need to be fixed before a release can be put out

**Comment by athaun** [comment]
alright, that makes sense... keep up the good work!

**Comment by Kappamenhehe** [comment]
I really hope , you will make it soon :<

**Comment by Coding-Hen** [comment]
@Measurity This can also be closed its been fixed as mentioned by killzoms 1759c5c

**Comment by Measurity** [comment]
Gonna leave this one open until new release of Nitrox. Workaround is downloading old version of subnautica.

**Comment by brorsrs** [comment]
im sorry im kinda dumb but can we like do this manually?

**Comment by Measurity** [comment]
If you can't wait you can follow the dev setup on the wiki. But it requires a lot of tool downloads and we're still in the progress of bugfixing so it might be a worse experience than doing the downgrade (I personally don't know how well the public Nitrox release works).

**Comment by Measurity** [comment]
Gonna close this as this issue will be fixed once #856 is resolved (same bug).

**Comment by Sporeut** [comment]
This wasn't fixed as of 09/05/2020

**Comment by Amnesiac9** [comment]
Still having this issue, steam version. 9-16-20
