### ISSUE TITLE
Joining Server Issue

### ISSUE THREAD

**Issue by JohnTitor95** [SubnauticaNitrox/Nitrox#860]
i have been playing subnautica with nitrox with my friend for a while now. However, today i changed locations and thus networks, and when trying to play today, when i try to join my server, it says launching game in the upper left hand corner, but nothing happens. If i try again, it says that my name is already in use. My friend is able to connect normally without issue. Is there a way to fix this? I host the server on my machine and we use hamachi.

**Comment by Jannify** [comment]
What IP did you use for joining? What are the log/logs saying?

**Comment by Measurity** [comment]
Gonna close this because of inactivity. Please visit the Nitrox Discord server if you still have this issue.
