### ISSUE TITLE
When launching multiplayer, main menu is completely blank.

### ISSUE THREAD

**Issue by CSAJoe** [SubnauticaNitrox/Nitrox#865]
When I launch multiplayer through the Nitrox launcher the game launches but there is nothing on the main menu. I attached a screenshot below.

https://i.imgur.com/PoLPOvJ.jpg

**Comment by Coding-Hen** [comment]
Thanks for reporting but this has already been reported. If you are using steam then head to the discord server where you can find a pinned tab in the help channel for resolving this issue with a downgrade.
Duplicate of #859 
Fixed in commit 1759c5c

**Comment by Coding-Hen** [comment]
@Measurity This can also been closed fixed as mentioned above
