### ISSUE TITLE
Unable to open game with Launcher

### ISSUE THREAD

**Issue by JumperBoost** [SubnauticaNitrox/Nitrox#867]
Uhm... How say it...

I launch the multiplayer game with the launcher, but...
A Youtube Video launched... "Lazy Town | You Are A Pirate Music Video"
But... I'm not a pirate 😂
Little video: https://youtu.be/56kHjQC-3zs

PS: I'm French for information :)

Thanks ^^

**Comment by Coding-Hen** [comment]
Are you using any mods? And have you verified your game files?

**Comment by JumperBoost** [comment]
I haven't any mods and i have verified my game files with Epic Games (No corrupted files)

**Comment by Measurity** [comment]
You have any .ini files inside the subnautica directory? That triggered the pirate check. It's fixed on master if you know how to build from it (requires Visual Studio or at least a tool to build Nitrox).
