### ISSUE TITLE
Player is not returned to menu when kicked from the server and receives no message either

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#873]
**Getting started**
Start in DisconnectPlayer method on the KickCommand class and log information about what happens when this packet is received by the player. Most important is that the player at least knows it was kicked.

You can log with the `Log` class. The resulting logs will be in the "Nitrox Logs" directory: `[...]\steamapps\common\Subnautica\Nitrox Logs`

**Comment by ltthomas11** [comment]
Was this working previously?

**Comment by Measurity** [comment]
It seems to be implemented all the way so I think it worked previously. Just need to know why it broke down.

**Comment by killzoms** [comment]
The issue pertaining to this happens to deal with the player being able to click out of the pop up menu
we should disable this and force them to close the game_
