### ISSUE TITLE
Implement a rudimentary packet log in-game.

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#874]
There’s a stub for this already in Nitrox but it has no implementation. Ideally it should show how many packets of X have been sent/received.

**Getting started**
- `PacketReceiver` class for detecting what kind of packets are received.
- `MultiplayerSessionManager` class for detecting what kind of packets are send.
- `NetworkDebugger` class should be where a new gui is rendered displaying the types of packets sent/received.

**Nice-to-have**
- Being able to view what a packet contained.

**Comment by j657** [comment]
Cool

**Comment by iCleeem** [comment]
I'll check that

**Comment by Measurity** [comment]
@iCleeem If you are working on this please join our discord and post it on the jr-alterra channel as well. Tell the moderators you're interested in helping out if you aren't jr-alterra yet.
