### ISSUE TITLE
windows store version

### ISSUE THREAD

**Issue by kales12** [SubnauticaNitrox/Nitrox#878]
Is there a way to make it work with Windows store version of subnautica? I did access the folder containing game files by changing ownership of the WindowsApp folder, but NITROX Launcher still came up with error notification - System.IO.IOException: The media is write protected.

**Comment by Measurity** [comment]
Windows Store is a PITA to mod. It's unlikely to get support until at least after the mod is stable on Steam/Epic. That said, anyone is free to attempt it and make a pull request.
