### ISSUE TITLE
Compilation error "Access denied".

### ISSUE THREAD

**Issue by GuzioMG** [SubnauticaNitrox/Nitrox#90]
I was just first-time compiling and lunching (by using Visual Studio's "Run" button) the NitroxServer source code. I didn't use dnSpy or something like this, but I my Visual Studio returned this error:
![image](https://user-images.githubusercontent.com/35845447/35462916-798fd0f0-02ee-11e8-9c29-da029c4388f3.png)
(here should be scerrnshot)
Can somebody help me?
Polish translations (useful to read screenshot properly):
Rozpocznij-Run
Błąd podczas próby uruchomienia projektu-error while lunching a project
Nie można uruchomić projektu "(here is the filepath)"-Cannot run project "(here is the filepath)"
Plik-file
Edycja-edit
Widok-view
Odmowa dostępu-access denied
Dane wyjściowe-output
Kompilacja-compile
Zakończono powodzeniem-finished succesful
Zakończono niepowodzeniem-finished with error
zaktualizowano-updated
pominięto-skipped
Eksplarator rozwiązń -solution explorer

Other info:
-I'm on admin's profile
-VisualStudio 2017
-I'm from Poland, so I'm sorry, if i done any language mistakes
-I found a way to repair it on Google: re-open VS, but nothing happend. Alwas the same error.

**Comment by MarijnS95** [comment]
Shut down the server application before compiling; it's running in the background (check your taskbar), preventing it from being overwritten with the new version.

**Comment by GuzioMG** [comment]
No, there is another thing running on my taskbar. It is not connected with VS.

**Comment by MarijnS95** [comment]
Then *you* have to figure out which other program is using the executable. This issue is not specifically linked to this project.

**Comment by GuzioMG** [comment]
Yes, I have permissions to write in folder, but I didn't extracted ZIP, because I used _Git Repository (from "git clone" command), not a ZIP_. And I want to say thanks for your help
> Then _you_ have to figure out which other program is using the executable. This issue is not specifically linked to this project.

I'll check.

Ps. If you mind "console" by "executabe", I closed it, and the same error again. Exactly the same. But I'll check. I'll also check have I permissions to run `.EXE` file, but I propably have.

**Comment by GuzioMG** [comment]
Yes, I have.

**Comment by GuzioMG** [comment]
So I'll
>Figure out which other program is using the executable.

**Comment by MarijnS95** [comment]
Great, `git clone` is an even better way to do it :+1:

Perhaps try manually deleting the `bin` and `obj` folders, and rebuild the solution. At this point I have no idea what may prevent the exe from compiling. Did you compile the solution previously, and does the file even exist?

**Comment by GuzioMG** [comment]
Yes, it existed. And I'll delete bin and obj.

**Comment by GuzioMG** [comment]
Emmmm..... I deleted `bin` (there was `Debug\NitroxServer.EXE` file), but I didn't found `obj`. Now, I compiled this and `obj` don't exist egain, BUT there ISN'T na `NitroxServer.EXE` in `bin\Debug`!!!! AND the VisualStudio, says it IS!

![image](https://user-images.githubusercontent.com/35845447/35480038-365139fa-0406-11e8-8f33-489032d4914d.png)
(here shoud be screenshot with the same error, but without `NitroxServer.EXE` on the right side)
INFO:
If you think "Hey, but in windows explorer you're at Guzio MG user, but VisualStudio says Mateusz user..." Nope! It's the same user, but I signed in at Microsoft account leater and my profile name changed, but of my folder-no.

**Comment by MartinX3** [comment]
Maybe, you should remove everything and checkout the source code again from github. :)

**Comment by MarijnS95** [comment]
You *are* looking at the wrong folder. In explorer, you're looking at:

> Nitrox\bin\Debug

But Visual studio tells you it can't access the file in:

> Nitrox\\**NitroxServer**\bin\Debug

**Comment by GuzioMG** [comment]
Oh, yes, I didn't saw that :-).
