### ISSUE TITLE
Storage and inventory states are lost

### ISSUE THREAD

**Issue by LordDangerous** [SubnauticaNitrox/Nitrox#909]
Hello. I have a problem while playing your subnautica multiplayer mod. We start a game and when we close it the inventory / storage items are lost. Meanwhile, some parts are saved while others (like the lifepod) arent. Am I doing something wrong?
Thanks.

**Comment by PauMAVA** [comment]
Same issue here

**Comment by Measurity** [comment]
Closing this in favor of a similar and more detailed issue: #1003
