### ISSUE TITLE
Game starts up gives the main menu screen but its empty

### ISSUE THREAD

**Issue by GamerTamas** [SubnauticaNitrox/Nitrox#912]
It starts up normally but there are no sounds and no buttons only the water is waving
![image](https://user-images.githubusercontent.com/60712623/73874936-b0ddcc80-4854-11ea-82c5-3f66f725a209.png)
-reinstalling didnt work(2x)
-making it not run in vr mode still didnt change anything
-tried running it with admin priviliges

**Comment by Nanna11** [comment]
I encountered this issue as well and was able to fix it by reinstalling the game.

**Comment by BlockArchitech** [comment]
Same here. Using latest steam subnautica. Server doesn't work either.

**Comment by Measurity** [comment]
This has been fixed for the upcoming Nitrox release.
