### ISSUE TITLE
Replace current logging framework with a modern one

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#913]
Reasons for change from log4net:
 - Games have a tight performance budget so a faster logger is preferred.
 - Log4net configuration is confusing
 - No structured logging so logs are long, messy and hard to search through.

Features to look for:
 - High-performance: A lot of logs should not bog down the main thread the game runs on. It should be able to handle about 1000 logs-lines/second without noticably impacting FPS.
- Ability to mark some data as 'sensitive' so that it will be starred (***) out in the log files. Useful for passwords, file paths containing user name and IP addresses.
 - Structured logging: Make logs easier to search through by being consistent with the log format.
 - When building Nitrox in release mode it should not compile debug log methods to improve performance of those builds.

Frameworks that could be a good match:
 - [Serilog](https://serilog.net/)
 - [NLog](https://nlog-project.org/)

**Comment by 80cmdude** [comment]
I have limited experience with logging frameworks but i do know that serilog is probably a no go if you want performance. Is there any reliance on UI shown errors or are we just logging to a file/console here?

**Comment by Measurity** [comment]
Just logging to file and console. And high performance is definitely top priority.

**Comment by Jannify** [comment]
https://github.com/SubnauticaNitrox/Nitrox/pull/1121
