### ISSUE TITLE
 NitroxPatcher.dll 

### ISSUE THREAD

**Issue by Pantking** [SubnauticaNitrox/Nitrox#93]
Where to get

NitroxPatcher.dll

i can't find in my Subnautica installation folder

**Comment by Skyterix1991** [comment]
Did you compile entire solution or just Nitrox Server

**Comment by Pantking** [comment]
Nitrox server and Nitrox client

**Comment by Staudey** [comment]
You have to build the entire solution, as stated in the wiki guide.

**Comment by Pantking** [comment]
This guide gives 50% information and the rest you have to think for yourself

**Comment by Staudey** [comment]
Which is intentional as I understand it.

But anyway, this point is clearly stated in the guide. Build the entire
solution.

**Comment by Pantking** [comment]
3 and 4 of the points made
About 1 and 2 don't understand where to register or anything to work with

**Comment by Staudey** [comment]
Look, it really doesn't seem like you have the skills required to use this
project. Even if somebody helped you all the way, you're going to be
stranded again as soon as a new Subnautica version requires an update of
the mod. I suggest you wait for a more accessible version that will be
available when the mod is more mature.

**Comment by MattSowards** [comment]
Why does it matter if he doesn't have the skills, they should still make it easier for all users to get a hold of the mod. Regardless of its state.

**Comment by Sunrunner37** [comment]
This source code is only released for developers and not intended for consumption.  The mod is constantly in a broken, development state.  Wait for an official release.

**Comment by MattSowards** [comment]
Yes, That's understandable I should take a look at it myself rather than watching these youtube videos of the mods state, because from what i've seen it looks like its running in very playable condition.
