### ISSUE TITLE
Could not find a part of the path discord-rpc.dll

### ISSUE THREAD

**Issue by Tvde1** [SubnauticaNitrox/Nitrox#949]
Clicking "Play Multiplayer" on the launcher shows this pop-up:

![image](https://user-images.githubusercontent.com/11540531/76144322-4ef4ca80-607f-11ea-8ca4-f23a4ef8f397.png)

**Comment by Measurity** [comment]
You're on the previous release "ALPHA 1.1.0". We're on "ALPHA 1.2.0.0" right now. Could you try it again on the latest version of Nitrox?

**Comment by Tvde1** [comment]
It can be fixed by creating a folder called `Mono` inside `Satisfsctory_Data`
