### ISSUE TITLE
Add "ALPHA" text in main menu and during loading screen

### ISSUE THREAD

**Issue by Measurity** [SubnauticaNitrox/Nitrox#957]
We want to communicate to players that Nitrox is still in alpha and that they should expect bugs.

Add UI text to the existing canvas in game. Can use scene debugger to search for the canvas object in-game (press F7). Should be able to add atext element to it like so: https://docs.unity3d.com/ScriptReference/Canvas.html

**Comment by Jannify** [comment]
See https://github.com/SubnauticaNitrox/Nitrox/pull/969
