### ISSUE TITLE
Multiplayer Mod Installer

### ISSUE THREAD

**Issue by yungnibbawantsanswers** [SubnauticaNitrox/Nitrox#96]
multiplayer installer please gimme gimme (eta?) -yungnibbawantsanswers

**Comment by Skyterix** [comment]
Nope

**Comment by al-darwish** [comment]
still gotta b patient

**Comment by urlordjames** [comment]
No installer will be released anytime soon in order to keep out normies REEEEE GET OFF OUR MOD!

**Comment by Rsslone** [comment]
@urlordjames I think people are just excited and want to have easier access to the testing. I personally would like to play it casually even if its buggy as hell as long as the core idea is working.
