### ISSUE TITLE
Seamoth's explode within moments of each other constantly

### ISSUE THREAD

**Issue by getsmor** [SubnauticaNitrox/Nitrox#966]
I am playing with 2 other people for about 5 hours, but after installing depth module MK1 and exploring mushroom forest, all the seamoths starts to explode one after another and after another hour of rebuilding them, now it's every few minutes. My thoughts were that it was the depth module but am not sure atm.

**Comment by tomi1206** [comment]
it's not the depth module fault, we have the same issue and we're using standard seamoth

**Comment by Gh0stNappa** [comment]
I installed upgrades and was doing fine. I then docked the seamoth in the moonpool and changed the color. After taking it out it exploded within seconds. I did accidentally run into a leg of the moonpool but that shouldn't cause an INSTANT explosion. This happened twice within 30 minutes.

**Comment by Stormrage74** [comment]
I have the same problem, with 3 players, hours of palying, after 3 uses the seamoth explode in the middle of no where : no obstacles, no fish on the way can explain that.
For the moment we decide to not use it.

**Comment by dartasen** [comment]
Duplicate #1223
