### ISSUE TITLE
Path hardcoded in file

### ISSUE THREAD

**Issue by AlexALX** [SubnauticaNitrox/Nitrox#97]
https://github.com/SubnauticaNitrox/Nitrox/blob/7509e533b0d060eed3c765349dcb4557177b3b10/NitroxServer/Serialization/BatchCellsParser.cs#L84

Why is this hardcoded in file? Can you use path from config or so? I took me some time to understand why it not loading (and i have different path for subnautica).

**Comment by Measuring** [comment]
Thank you for posting an issue but this one is currently handled in a PR: #88.

**Comment by AlexALX** [comment]
Ok then, i'm glad that this is already fixed in PR, looking forward to have it in master branch!
