### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by dominikrathmer** [SubnauticaNitrox/Nitrox#981]
Servers as for example a Raspberry PI can't hold an Overbloated System like Windows. With adding official Linux support it would be possible for users to create dedicated Servers for other players.

**Comment by dartasen** [comment]
@dominikrathmer That's definitly something that we planned to

**Comment by dominikrathmer** [comment]
> @dominikrathmer That's definitly something that we planned to

Oh thats really awesome. Thank you. It would be possible for all of us to make dedicated servers that way. The problem is, that the code relies on Unity and other aspects that wine cant emulate
